// Generated by the nanoOCP generator from OCCT package BRepMeshData (toolkit TKMesh). Do not edit.
#include "nanoocp_common.h"
#include <BRepMeshData_Curve.hxx>
#include <BRepMeshData_Edge.hxx>
#include <BRepMeshData_Face.hxx>
#include <BRepMeshData_Model.hxx>
#include <BRepMeshData_PCurve.hxx>
#include <BRepMeshData_Wire.hxx>
#include <IMeshData_Edge.hxx>
#include <IMeshData_Face.hxx>
#include <IMeshData_Model.hxx>
#include <Standard_Type.hxx>
#include <TopoDS_Edge.hxx>
#include <TopoDS_Face.hxx>
#include <TopoDS_Shape.hxx>

void nanoocp_declare_BRepMeshData(nb::module_ &m) {
    { nb::class_<BRepMeshData_Model, IMeshData_Model> cls(m, "BRepMeshData_Model", R"nbdoc(Default implementation of model entity.)nbdoc");
    }
}

void nanoocp_templates_BRepMeshData(nb::module_ &m) {
}

void nanoocp_define_BRepMeshData(nb::module_ &m) {
    nb::borrow<nb::class_<BRepMeshData_Model>>(m.attr("BRepMeshData_Model"))
        .def(nb::new_([](const TopoDS_Shape & theShape) { return opencascade::handle<BRepMeshData_Model>(new BRepMeshData_Model(theShape)); }), nb::arg("theShape"), R"nbdoc(Constructor.
Initializes empty model.)nbdoc")
        .def("GetMaxSize", static_cast<double (BRepMeshData_Model::*)() const>(&BRepMeshData_Model::GetMaxSize), R"nbdoc(Returns maximum size of shape's bounding box.)nbdoc")
        .def("SetMaxSize", static_cast<void (BRepMeshData_Model::*)(const double)>(&BRepMeshData_Model::SetMaxSize), nb::arg("theValue"), R"nbdoc(Sets maximum size of shape's bounding box.)nbdoc")
        .def_static("get_type_name", static_cast<const char * (*)()>(&BRepMeshData_Model::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&BRepMeshData_Model::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (BRepMeshData_Model::*)() const>(&BRepMeshData_Model::DynamicType))
        .def("FacesNb", static_cast<int (BRepMeshData_Model::*)() const>(&BRepMeshData_Model::FacesNb), R"nbdoc(@name discrete faces
Returns number of faces in discrete model.)nbdoc")
        .def("AddFace", static_cast<const IMeshData::IFaceHandle & (BRepMeshData_Model::*)(const TopoDS_Face &)>(&BRepMeshData_Model::AddFace), nb::arg("theFace"), R"nbdoc(Adds new face to shape model.)nbdoc")
        .def("GetFace", static_cast<const IMeshData::IFaceHandle & (BRepMeshData_Model::*)(const int) const>(&BRepMeshData_Model::GetFace), nb::arg("theIndex"), R"nbdoc(Gets model's face with the given index.)nbdoc")
        .def("EdgesNb", static_cast<int (BRepMeshData_Model::*)() const>(&BRepMeshData_Model::EdgesNb), R"nbdoc(@name discrete edges
Returns number of edges in discrete model.)nbdoc")
        .def("AddEdge", static_cast<const IMeshData::IEdgeHandle & (BRepMeshData_Model::*)(const TopoDS_Edge &)>(&BRepMeshData_Model::AddEdge), nb::arg("theEdge"), R"nbdoc(Adds new edge to shape model.)nbdoc")
        .def("GetEdge", static_cast<const IMeshData::IEdgeHandle & (BRepMeshData_Model::*)(const int) const>(&BRepMeshData_Model::GetEdge), nb::arg("theIndex"), R"nbdoc(Gets model's edge with the given index.)nbdoc");
    nanoocp_implicit_copy_ctor<BRepMeshData_Model>(nb::borrow<nb::class_<BRepMeshData_Model>>(m.attr("BRepMeshData_Model")));
    nb::implicitly_convertible<std::decay_t<const TopoDS_Shape &>, BRepMeshData_Model>();
}

void nanoocp_conversions_BRepMeshData(nb::module_ &m) {
}
