// Generated by the nanoOCP generator from OCCT package Wasm (toolkit TKService). Do not edit.
#include "nanoocp_common.h"
#include <Wasm_Window.hxx>
#include <Aspect_DisplayConnection.hxx>
#include <Aspect_Drawable.hxx>
#include <Aspect_TypeOfResize.hxx>
#include <Aspect_VKey.hxx>
#include <Aspect_Window.hxx>
#include <NCollection_Vec2.hxx>
#include <Standard_Type.hxx>
#include <TCollection_AsciiString.hxx>

void nanoocp_declare_Wasm(nb::module_ &m) {
    { nb::class_<Wasm_Window, Aspect_Window> cls(m, "Wasm_Window", R"nbdoc(This class defines WebAssembly window (HTML5 canvas) intended for creation of OpenGL (WebGL)
context.

Note that canvas may define an independent dimensions for backing store (WebGL buffer to render)
and for CSS (logical units to present buffer onto screen).
These dimensions differ when browser is dragged into a high pixel density screen (HiDPI),
or when user scales page in the browser (in both cases window.devicePixelRatio JavaScript
property becomes not equal to 1.0).

By default, Wasm_Window::DoResize() will scale backing store of a canvas basing on
DevicePixelRatio() scale factor to ensure canvas content being rendered with the native
resolution and not stretched by browser. This, however, might have side effects:
- a slow GPU might experience performance issues on drawing into larger buffer (e.g. HiDPI);
- user interface displayed in 3D Viewer (e.g. AIS presentations) should be scaled proportionally
to be accessible,
which might require extra processing at application level.
Consider changing ToScaleBacking flag passed to Wasm_Window constructor in case of issues.)nbdoc");
    }
}

void nanoocp_templates_Wasm(nb::module_ &m) {
}

void nanoocp_define_Wasm(nb::module_ &m) {
    nb::borrow<nb::class_<Wasm_Window>>(m.attr("Wasm_Window"))
        .def(nb::new_([](const TCollection_AsciiString & theCanvasId, const bool theToScaleBacking) { return opencascade::handle<Wasm_Window>(new Wasm_Window(theCanvasId, theToScaleBacking)); }), nb::arg("theCanvasId"), nb::arg("theToScaleBacking") = static_cast<std::decay_t<const bool>>(true), R"nbdoc(Wraps existing HTML5 canvas into window.
@param[in] theCanvasId target HTML element id defined in a querySelector() syntax
@param[in] theToScaleBacking when TRUE, window will automatically scale backing store of
canvas
basing on DevicePixelRatio() scale factor within DoResize())nbdoc")
        .def_static("get_type_name", static_cast<const char * (*)()>(&Wasm_Window::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&Wasm_Window::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (Wasm_Window::*)() const>(&Wasm_Window::DynamicType))
        .def_static("MouseButtonsFromNative", static_cast<Aspect_VKeyMouse (*)(unsigned short)>(&Wasm_Window::MouseButtonsFromNative), nb::arg("theButtons"), R"nbdoc(Convert Emscripten mouse buttons into Aspect_VKeyMouse.)nbdoc")
        .def_static("VirtualKeyFromNative", static_cast<Aspect_VKey (*)(int)>(&Wasm_Window::VirtualKeyFromNative), nb::arg("theKey"), R"nbdoc(Convert DOM virtual key into Aspect_VKey.)nbdoc")
        .def("IsMapped", static_cast<bool (Wasm_Window::*)() const>(&Wasm_Window::IsMapped), R"nbdoc(Return true if window is not hidden.)nbdoc")
        .def("Map", static_cast<void (Wasm_Window::*)() const>(&Wasm_Window::Map), R"nbdoc(Change window mapped flag to TRUE.)nbdoc")
        .def("Unmap", static_cast<void (Wasm_Window::*)() const>(&Wasm_Window::Unmap), R"nbdoc(Change window mapped flag to FALSE.)nbdoc")
        .def("DoResize", static_cast<Aspect_TypeOfResize (Wasm_Window::*)()>(&Wasm_Window::DoResize), R"nbdoc(Resize window.
In case of ToScaleBacking flag, this method will resize the backing store of canvas
basing on DevicePixelRatio() scale factor and CSS canvas size.)nbdoc")
        .def("DoMapping", static_cast<bool (Wasm_Window::*)() const>(&Wasm_Window::DoMapping), R"nbdoc(Apply the mapping change to the window.)nbdoc")
        .def("Ratio", static_cast<double (Wasm_Window::*)() const>(&Wasm_Window::Ratio), R"nbdoc(Returns window ratio equal to the physical width/height dimensions.)nbdoc")
        .def("Position", [](const Wasm_Window &self) { int theX1{}; int theY1{}; int theX2{}; int theY2{}; self.Position(theX1, theY1, theX2, theY2); return std::make_tuple(theX1, theY1, theX2, theY2); }, R"nbdoc(Returns The Window POSITION in PIXEL)nbdoc")
        .def("Size", [](const Wasm_Window &self) { int theWidth{}; int theHeight{}; self.Size(theWidth, theHeight); return std::make_tuple(theWidth, theHeight); }, R"nbdoc(Return the window size in pixels.)nbdoc")
        .def("SetSizeLogical", static_cast<void (Wasm_Window::*)(const NCollection_Vec2<double> &)>(&Wasm_Window::SetSizeLogical), nb::arg("theSize"), R"nbdoc(Set new window size in logical (density-independent units).
Backing store will be resized basing on DevicePixelRatio().)nbdoc")
        .def("SetSizeBacking", static_cast<void (Wasm_Window::*)(const NCollection_Vec2<int> &)>(&Wasm_Window::SetSizeBacking), nb::arg("theSize"), R"nbdoc(Set new window size in pixels.
Logical size of the element will be resized basing on DevicePixelRatio().)nbdoc")
        .def("CanvasId", static_cast<const TCollection_AsciiString & (Wasm_Window::*)() const>(&Wasm_Window::CanvasId), R"nbdoc(Returns canvas id.)nbdoc")
        .def("NativeHandle", static_cast<Aspect_Drawable (Wasm_Window::*)() const>(&Wasm_Window::NativeHandle), R"nbdoc(Current EGL implementation in Emscripten accepts only 0 for native window id.)nbdoc")
        .def("NativeParentHandle", static_cast<Aspect_Drawable (Wasm_Window::*)() const>(&Wasm_Window::NativeParentHandle), R"nbdoc(Always returns 0 for this class.)nbdoc")
        .def("DevicePixelRatio", static_cast<double (Wasm_Window::*)() const>(&Wasm_Window::DevicePixelRatio), R"nbdoc(Return device pixel ratio (logical to backing store scale factor).)nbdoc")
        .def("SetDevicePixelRatio", static_cast<void (Wasm_Window::*)(double)>(&Wasm_Window::SetDevicePixelRatio), nb::arg("theDevicePixelRatio"), R"nbdoc(Sets device pixel ratio for a window with IsVirtual() flag.)nbdoc")
        .def("InvalidateContent", static_cast<void (Wasm_Window::*)(const occ::handle<Aspect_DisplayConnection> &)>(&Wasm_Window::InvalidateContent), nb::arg("theDisp").none(), R"nbdoc(Invalidate entire window content through generation of Expose event.)nbdoc");
    nanoocp_implicit_copy_ctor<Wasm_Window>(nb::borrow<nb::class_<Wasm_Window>>(m.attr("Wasm_Window")));
    nb::implicitly_convertible<std::decay_t<const TCollection_AsciiString &>, Wasm_Window>();
}

void nanoocp_conversions_Wasm(nb::module_ &m) {
}
