// Generated by the nanoOCP generator: extension module for OCCT toolkit TKDEGLTF. Do not edit.
#include "nanoocp_common.h"

void nanoocp_declare_RWGltf(nb::module_ &);
void nanoocp_templates_RWGltf(nb::module_ &);
void nanoocp_define_RWGltf(nb::module_ &);
void nanoocp_conversions_RWGltf(nb::module_ &);
void nanoocp_declare_DEGLTF(nb::module_ &);
void nanoocp_templates_DEGLTF(nb::module_ &);
void nanoocp_define_DEGLTF(nb::module_ &);
void nanoocp_conversions_DEGLTF(nb::module_ &);

NB_MODULE(_TKDEGLTF, m) {
    m.doc() = "OCCT toolkit TKDEGLTF";
    nb::object sys_modules = nb::module_::import_("sys").attr("modules");
    // toolkits this one links against must have registered their types first
    nb::module_::import_("nanoocp._TKernel");
    nb::module_::import_("nanoocp._TKMath");
    nb::module_::import_("nanoocp._TKMesh");
    nb::module_::import_("nanoocp._TKXCAF");
    nb::module_::import_("nanoocp._TKLCAF");
    nb::module_::import_("nanoocp._TKV3d");
    nb::module_::import_("nanoocp._TKBRep");
    nb::module_::import_("nanoocp._TKG3d");
    nb::module_::import_("nanoocp._TKDE");
    nb::module_::import_("nanoocp._TKService");
    nb::module_::import_("nanoocp._TKRWMesh");
    nb::module_ m_RWGltf = m.def_submodule("RWGltf", "OCCT package RWGltf (toolkit TKDEGLTF)");
    m_RWGltf.attr("__name__") = "nanoocp.RWGltf";
    sys_modules["nanoocp._TKDEGLTF.RWGltf"] = m_RWGltf;
    nb::module_ m_DEGLTF = m.def_submodule("DEGLTF", "OCCT package DEGLTF (toolkit TKDEGLTF)");
    m_DEGLTF.attr("__name__") = "nanoocp.DEGLTF";
    sys_modules["nanoocp._TKDEGLTF.DEGLTF"] = m_DEGLTF;
    // phase 1: all types (classes, enums) so that signatures/defaults can refer to them
    nanoocp_declare_RWGltf(m_RWGltf);
    nanoocp_declare_DEGLTF(m_DEGLTF);
    nanoocp_install_exception_translator(nullptr);
    // phase 2: NCollection template instances (need their element types)
    nanoocp_templates_RWGltf(m_RWGltf);
    nanoocp_templates_DEGLTF(m_DEGLTF);
    // phase 3: members
    nanoocp_define_RWGltf(m_RWGltf);
    nanoocp_define_DEGLTF(m_DEGLTF);
    // phase 4: constructors from conversion operators (every class has its own constructors by now)
    nanoocp_conversions_RWGltf(m_RWGltf);
    nanoocp_conversions_DEGLTF(m_DEGLTF);
}
