// Generated by the nanoOCP generator from OCCT package IGESConvGeom (toolkit TKDEIGES). Do not edit.
#include "nanoocp_common.h"
#include <IGESConvGeom.hxx>
#include <IGESConvGeom_GeomBuilder.hxx>
#include <Geom2d_BSplineCurve.hxx>
#include <Geom_BSplineCurve.hxx>
#include <Geom_BSplineSurface.hxx>
#include <IGESGeom_CopiousData.hxx>
#include <IGESGeom_SplineCurve.hxx>
#include <IGESGeom_SplineSurface.hxx>
#include <IGESGeom_TransformationMatrix.hxx>
#include <gp_Ax1.hxx>
#include <gp_Ax2.hxx>
#include <gp_Ax3.hxx>
#include <gp_Trsf.hxx>
#include <gp_XY.hxx>
#include <gp_XYZ.hxx>

void nanoocp_declare_IGESConvGeom(nb::module_ &m) {
    { nb::class_<IGESConvGeom> cls(m, "IGESConvGeom", R"nbdoc(This package is intended to gather geometric conversion which
are not immediate but can be used for several purposes :
mainly, standard conversion to and from CasCade geometric and
topologic data, and adaptations of IGES files as required
(as replacing Spline entities to BSpline equivalents).)nbdoc");
    }
    { nb::class_<IGESConvGeom_GeomBuilder> cls(m, "IGESConvGeom_GeomBuilder", R"nbdoc(This class provides some useful basic tools to build IGESGeom
curves, especially :
define a curve in a plane in 3D space (ex. Circular or Conic
arc, or Copious Data defined in 2D)
make a CopiousData from a list of points/vectors)nbdoc");
    }
}

void nanoocp_templates_IGESConvGeom(nb::module_ &m) {
}

void nanoocp_define_IGESConvGeom(nb::module_ &m) {
    nanoocp_implicit_default_ctor<IGESConvGeom>(nb::borrow<nb::class_<IGESConvGeom>>(m.attr("IGESConvGeom")));
    nb::borrow<nb::class_<IGESConvGeom>>(m.attr("IGESConvGeom"))
        .def_static("SplineCurveFromIGES", [](const occ::handle<IGESGeom_SplineCurve> & igesent, const double epscoef, const double epsgeom) { occ::handle<Geom_BSplineCurve> result{}; auto nanoocp_result = IGESConvGeom::SplineCurveFromIGES(igesent, epscoef, epsgeom, result); return std::make_tuple(nanoocp_result, result); }, nb::arg("igesent").none(), nb::arg("epscoef"), nb::arg("epsgeom"), R"nbdoc(basic tool to build curves from IGESGeom (arrays of points,
Transformations, evaluation of points in a datum)
Converts a SplineCurve from IGES to a BSplineCurve from CasCade
<epscoef> gives tolerance to consider coefficient to be nul
<epsgeom> gives tolerance to consider poles to be equal
The returned value is a status with these possible values :
- 0  OK, done
- 1  the result is not guaranteed to be C0 (with <epsgeom>)
- 2  SplineType not processed (allowed : max 3)
(no result produced)
- 3  error during creation of control points
(no result produced)
- 4  polynomial equation is not correct (no result produced)
- 5  less than one segment (no result produced))nbdoc")
        .def_static("IncreaseCurveContinuity", static_cast<int (*)(const occ::handle<Geom_BSplineCurve> &, const double, const int)>(&IGESConvGeom::IncreaseCurveContinuity), nb::arg("curve").none(), nb::arg("epsgeom"), nb::arg("continuity") = static_cast<std::decay_t<const int>>(2), R"nbdoc(Tries to increase curve continuity with tolerance <epsgeom>
<continuity> is the new desired continuity, can be 1 or 2
(more than 2 is considered as 2).
Returns the new maximum continuity obtained on all knots.
Remark that, for instance with <continuity> = 2, even if not
all the knots can be passed to C2, all knots which can be are.)nbdoc")
        .def_static("IncreaseCurveContinuity", static_cast<int (*)(const occ::handle<Geom2d_BSplineCurve> &, const double, const int)>(&IGESConvGeom::IncreaseCurveContinuity), nb::arg("curve").none(), nb::arg("epsgeom"), nb::arg("continuity") = static_cast<std::decay_t<const int>>(2))
        .def_static("SplineSurfaceFromIGES", [](const occ::handle<IGESGeom_SplineSurface> & igesent, const double epscoef, const double epsgeom) { occ::handle<Geom_BSplineSurface> result{}; auto nanoocp_result = IGESConvGeom::SplineSurfaceFromIGES(igesent, epscoef, epsgeom, result); return std::make_tuple(nanoocp_result, result); }, nb::arg("igesent").none(), nb::arg("epscoef"), nb::arg("epsgeom"), R"nbdoc(Converts a SplineSurface from IGES to a BSplineSurface from CasCade
<epscoef> gives tolerance to consider coefficient to be nul
<epsgeom> gives tolerance to consider poles to be equal
The returned value is a status with these possible values :
- 0  OK, done
- 1  the result is not guaranteed to be C0 (with <epsgeom>)
- 2  degree is not compatible with code boundary type
(warning) but C0 is OK
- 3  idem but C0 is not guaranteed (warning)
- 4  degree has been determined to be nul, either in U or V
(no result produced)
- 5  less than one segment in U or V (no result produced))nbdoc")
        .def_static("IncreaseSurfaceContinuity", static_cast<int (*)(const occ::handle<Geom_BSplineSurface> &, const double, const int)>(&IGESConvGeom::IncreaseSurfaceContinuity), nb::arg("surface").none(), nb::arg("epsgeom"), nb::arg("continuity") = static_cast<std::decay_t<const int>>(2), R"nbdoc(Tries to increase Surface continuity with tolerance <epsgeom>
<continuity> is the new desired continuity, can be 1 or 2
(more than 2 is considered as 2).
Returns the new maximum continuity obtained on all knots.
Remark that, for instance with <continuity> = 2, even if not
all the knots can be passed to C2, all knots which can be are.)nbdoc");
    nanoocp_implicit_copy_ctor<IGESConvGeom>(nb::borrow<nb::class_<IGESConvGeom>>(m.attr("IGESConvGeom")));
    nb::borrow<nb::class_<IGESConvGeom_GeomBuilder>>(m.attr("IGESConvGeom_GeomBuilder"))
        .def(nb::init<>(), R"nbdoc(Creates a GeomBuilder at initial state.)nbdoc")
        .def("Clear", static_cast<void (IGESConvGeom_GeomBuilder::*)()>(&IGESConvGeom_GeomBuilder::Clear), R"nbdoc(Clears list of Points/Vectors and data about Transformation)nbdoc")
        .def("AddXY", static_cast<void (IGESConvGeom_GeomBuilder::*)(const gp_XY &)>(&IGESConvGeom_GeomBuilder::AddXY), nb::arg("val"), R"nbdoc(Adds a XY (Z=0) to the list of points)nbdoc")
        .def("AddXYZ", static_cast<void (IGESConvGeom_GeomBuilder::*)(const gp_XYZ &)>(&IGESConvGeom_GeomBuilder::AddXYZ), nb::arg("val"), R"nbdoc(Adds a XYZ to the list of points)nbdoc")
        .def("AddVec", static_cast<void (IGESConvGeom_GeomBuilder::*)(const gp_XYZ &)>(&IGESConvGeom_GeomBuilder::AddVec), nb::arg("val"), R"nbdoc(Adds a Vector part to the list of points. It will be used
for CopiousData, datatype=3, only.
AddXY and AddXYZ consider a null vector part (0,0,0)
AddVec adds to the last added XY or XYZ)nbdoc")
        .def("NbPoints", static_cast<int (IGESConvGeom_GeomBuilder::*)() const>(&IGESConvGeom_GeomBuilder::NbPoints), R"nbdoc(Returns the count of already recorded points)nbdoc")
        .def("Point", static_cast<gp_XYZ (IGESConvGeom_GeomBuilder::*)(const int) const>(&IGESConvGeom_GeomBuilder::Point), nb::arg("num"), R"nbdoc(Returns a point given its rank (if added as XY, Z will be 0))nbdoc")
        .def("MakeCopiousData", static_cast<occ::handle<IGESGeom_CopiousData> (IGESConvGeom_GeomBuilder::*)(const int, const bool) const>(&IGESConvGeom_GeomBuilder::MakeCopiousData), nb::arg("datatype"), nb::arg("polyline") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Makes a CopiousData with the list of recorded Points/Vectors
according to <datatype>, which must be 1,2 or 3
If <polyline> is given True, the CopiousData is coded as a
Polyline, but <datatype> must not be 3
<datatype> = 1 : Common Z is computed as average of all Z
<datatype> = 1 or 2 : Vectors are ignored)nbdoc")
        .def("Position", static_cast<gp_Trsf (IGESConvGeom_GeomBuilder::*)() const>(&IGESConvGeom_GeomBuilder::Position), R"nbdoc(Returns the Position in which the method EvalXYZ will
evaluate a XYZ. It can be regarded as defining a local system.
It is initially set to Identity)nbdoc")
        .def("SetPosition", static_cast<void (IGESConvGeom_GeomBuilder::*)(const gp_Trsf &)>(&IGESConvGeom_GeomBuilder::SetPosition), nb::arg("pos"), R"nbdoc(Sets final position from an already defined Trsf)nbdoc")
        .def("SetPosition", static_cast<void (IGESConvGeom_GeomBuilder::*)(const gp_Ax3 &)>(&IGESConvGeom_GeomBuilder::SetPosition), nb::arg("pos"), R"nbdoc(Sets final position from an Ax3)nbdoc")
        .def("SetPosition", static_cast<void (IGESConvGeom_GeomBuilder::*)(const gp_Ax2 &)>(&IGESConvGeom_GeomBuilder::SetPosition), nb::arg("pos"), R"nbdoc(Sets final position from an Ax2)nbdoc")
        .def("SetPosition", static_cast<void (IGESConvGeom_GeomBuilder::*)(const gp_Ax1 &)>(&IGESConvGeom_GeomBuilder::SetPosition), nb::arg("pos"), R"nbdoc(Sets final position from an Ax1
(this means that origin point and Z-axis are defined, the
other axes are defined arbitrarily))nbdoc")
        .def("IsIdentity", static_cast<bool (IGESConvGeom_GeomBuilder::*)() const>(&IGESConvGeom_GeomBuilder::IsIdentity), R"nbdoc(Returns True if the Position is Identity)nbdoc")
        .def("IsTranslation", static_cast<bool (IGESConvGeom_GeomBuilder::*)() const>(&IGESConvGeom_GeomBuilder::IsTranslation), R"nbdoc(Returns True if the Position is a Translation only
Remark : Identity and ZOnly will answer True)nbdoc")
        .def("IsZOnly", static_cast<bool (IGESConvGeom_GeomBuilder::*)() const>(&IGESConvGeom_GeomBuilder::IsZOnly), R"nbdoc(Returns True if the Position corresponds to a Z-Displacement,
i.e. is a Translation only, and only on Z
Remark : Identity will answer True)nbdoc")
        .def("EvalXYZ", [](const IGESConvGeom_GeomBuilder &self, const gp_XYZ & val) { double X{}; double Y{}; double Z{}; self.EvalXYZ(val, X, Y, Z); return std::make_tuple(X, Y, Z); }, nb::arg("val"), R"nbdoc(Evaluates a XYZ value in the Position already defined.
Returns the transformed coordinates.
For a 2D definition, X,Y will then be used to define a XY and
Z will be regarded as a Z Displacement (can be ignored))nbdoc")
        .def("MakeTransformation", static_cast<occ::handle<IGESGeom_TransformationMatrix> (IGESConvGeom_GeomBuilder::*)(const double) const>(&IGESConvGeom_GeomBuilder::MakeTransformation), nb::arg("unit") = static_cast<std::decay_t<const double>>(1), R"nbdoc(Returns the IGES Transformation which corresponds to the
Position. Even if it is an Identity : IsIdentity should be
tested first.
<unit> is the unit value in which the model is created :
it is used to convert translation part)nbdoc");
    nanoocp_implicit_copy_ctor<IGESConvGeom_GeomBuilder>(nb::borrow<nb::class_<IGESConvGeom_GeomBuilder>>(m.attr("IGESConvGeom_GeomBuilder")));
}

void nanoocp_conversions_IGESConvGeom(nb::module_ &m) {
}
