// Generated by the nanoOCP generator from OCCT package IGESToBRep (toolkit TKDEIGES). Do not edit.
#include "nanoocp_common.h"
#include "nanoocp_ncollection.h"
#include <IGESToBRep.hxx>
#include <IGESToBRep_Actor.hxx>
#include <IGESToBRep_AlgoContainer.hxx>
#include <IGESToBRep_BasicCurve.hxx>
#include <IGESToBRep_BasicSurface.hxx>
#include <IGESToBRep_BRepEntity.hxx>
#include <IGESToBRep_CurveAndSurface.hxx>
#include <IGESToBRep_IGESBoundary.hxx>
#include <IGESToBRep_Reader.hxx>
#include <IGESToBRep_ToolContainer.hxx>
#include <IGESToBRep_TopoCurve.hxx>
#include <IGESToBRep_TopoSurface.hxx>
#include <DE_ShapeFixParameters.hxx>
#include <Geom2d_BSplineCurve.hxx>
#include <Geom2d_Curve.hxx>
#include <Geom_BSplineCurve.hxx>
#include <Geom_BSplineSurface.hxx>
#include <Geom_ConicalSurface.hxx>
#include <Geom_Curve.hxx>
#include <Geom_CylindricalSurface.hxx>
#include <Geom_Plane.hxx>
#include <Geom_SphericalSurface.hxx>
#include <Geom_Surface.hxx>
#include <Geom_ToroidalSurface.hxx>
#include <Geom_Transformation.hxx>
#include <IGESBasic_SingleParent.hxx>
#include <IGESData_IGESEntity.hxx>
#include <IGESData_IGESModel.hxx>
#include <IGESGeom_BSplineCurve.hxx>
#include <IGESGeom_BSplineSurface.hxx>
#include <IGESGeom_Boundary.hxx>
#include <IGESGeom_BoundedSurface.hxx>
#include <IGESGeom_CircularArc.hxx>
#include <IGESGeom_CompositeCurve.hxx>
#include <IGESGeom_ConicArc.hxx>
#include <IGESGeom_CopiousData.hxx>
#include <IGESGeom_CurveOnSurface.hxx>
#include <IGESGeom_Line.hxx>
#include <IGESGeom_OffsetCurve.hxx>
#include <IGESGeom_OffsetSurface.hxx>
#include <IGESGeom_Plane.hxx>
#include <IGESGeom_Point.hxx>
#include <IGESGeom_RuledSurface.hxx>
#include <IGESGeom_SplineCurve.hxx>
#include <IGESGeom_SplineSurface.hxx>
#include <IGESGeom_SurfaceOfRevolution.hxx>
#include <IGESGeom_TabulatedCylinder.hxx>
#include <IGESGeom_TransformationMatrix.hxx>
#include <IGESGeom_TrimmedSurface.hxx>
#include <IGESSolid_ConicalSurface.hxx>
#include <IGESSolid_CylindricalSurface.hxx>
#include <IGESSolid_EdgeList.hxx>
#include <IGESSolid_Face.hxx>
#include <IGESSolid_Loop.hxx>
#include <IGESSolid_ManifoldSolid.hxx>
#include <IGESSolid_PlaneSurface.hxx>
#include <IGESSolid_Shell.hxx>
#include <IGESSolid_SphericalSurface.hxx>
#include <IGESSolid_ToroidalSurface.hxx>
#include <IGESSolid_VertexList.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Message_Msg.hxx>
#include <Message_ProgressRange.hxx>
#include <NCollection_DataMap.hxx>
#include <NCollection_HArray1.hxx>
#include <NCollection_HSequence.hxx>
#include <ShapeExtend_WireData.hxx>
#include <Standard_Transient.hxx>
#include <Standard_Type.hxx>
#include <TCollection_AsciiString.hxx>
#include <TopoDS_Edge.hxx>
#include <TopoDS_Face.hxx>
#include <TopoDS_Shape.hxx>
#include <TopoDS_Vertex.hxx>
#include <Transfer_ActorOfTransientProcess.hxx>
#include <Transfer_Binder.hxx>
#include <Transfer_TransientProcess.hxx>
#include <gp_Trsf2d.hxx>

void nanoocp_declare_IGESToBRep(nb::module_ &m) {
    { nb::class_<IGESToBRep> cls(m, "IGESToBRep", R"nbdoc(Provides tools in order to transfer IGES entities
to CAS.CADE.)nbdoc");
    }
    { nb::class_<IGESToBRep_Actor, Transfer_ActorOfTransientProcess> cls(m, "IGESToBRep_Actor", R"nbdoc(This class performs the transfer of an Entity from
IGESToBRep

I.E. for each type of Entity, it invokes the appropriate Tool
then returns the Binder which contains the Result)nbdoc");
    }
    { nb::class_<IGESToBRep_AlgoContainer, Standard_Transient> cls(m, "IGESToBRep_AlgoContainer");
    }
    { nb::class_<IGESToBRep_CurveAndSurface> cls(m, "IGESToBRep_CurveAndSurface", R"nbdoc(Provides methods to transfer CurveAndSurface from IGES to CASCADE.)nbdoc");
    }
    { nb::class_<IGESToBRep_BasicCurve, IGESToBRep_CurveAndSurface> cls(m, "IGESToBRep_BasicCurve", R"nbdoc(Provides methods to transfer basic geometric curves entities
from IGES to CASCADE.
These can be:
* Circular arc
* Conic arc
* Spline curve
* BSpline curve
* Line
* Copious data
* Point
* Transformation matrix)nbdoc");
    }
    { nb::class_<IGESToBRep_BasicSurface, IGESToBRep_CurveAndSurface> cls(m, "IGESToBRep_BasicSurface", R"nbdoc(Provides methods to transfer basic geometric surface entities
from IGES to CASCADE.
These can be:
* Spline surface
* BSpline surface)nbdoc");
    }
    { nb::class_<IGESToBRep_BRepEntity, IGESToBRep_CurveAndSurface> cls(m, "IGESToBRep_BRepEntity", R"nbdoc(Provides methods to transfer BRep entities
( VertexList 502, EdgeList 504, Loop 508,
Face 510, Shell 514, ManifoldSolid 186)
from IGES to CASCADE.)nbdoc");
    }
    { nb::class_<IGESToBRep_IGESBoundary, Standard_Transient> cls(m, "IGESToBRep_IGESBoundary", R"nbdoc(This class is intended to translate IGES boundary entity
(142-CurveOnSurface, 141-Boundary or 508-Loop) into the wire.
Methods Transfer are virtual and are redefined in Advanced
Data Exchange to optimize the translation and take into
account advanced parameters.)nbdoc");
    }
    { nb::class_<IGESToBRep_Reader> cls(m, "IGESToBRep_Reader", R"nbdoc(A simple way to read geometric IGES data.
Encapsulates reading file and calling transfer tools)nbdoc");
    }
    { nb::class_<IGESToBRep_ToolContainer, Standard_Transient> cls(m, "IGESToBRep_ToolContainer");
    }
    { nb::class_<IGESToBRep_TopoCurve, IGESToBRep_CurveAndSurface> cls(m, "IGESToBRep_TopoCurve", R"nbdoc(Provides methods to transfer topologic curves entities
from IGES to CASCADE.)nbdoc");
    }
    { nb::class_<IGESToBRep_TopoSurface, IGESToBRep_CurveAndSurface> cls(m, "IGESToBRep_TopoSurface", R"nbdoc(Provides methods to transfer topologic surfaces entities
from IGES to CASCADE.)nbdoc");
    }
}

void nanoocp_templates_IGESToBRep(nb::module_ &m) {
    { nb::module_ home = nb::module_::import_("nanoocp._TKernel.NCollection"); nanoocp::bind_NCollection_Array1<opencascade::handle<IGESData_IGESEntity>>(home, "NCollection_Array1__Handle_IGESData_IGESEntity"); }
    { nb::module_ home = nb::module_::import_("nanoocp._TKernel.NCollection"); nanoocp::bind_NCollection_HArray1<opencascade::handle<IGESData_IGESEntity>>(home, "NCollection_HArray1__Handle_IGESData_IGESEntity"); }
}

void nanoocp_define_IGESToBRep(nb::module_ &m) {
    nanoocp_implicit_default_ctor<IGESToBRep>(nb::borrow<nb::class_<IGESToBRep>>(m.attr("IGESToBRep")));
    nb::borrow<nb::class_<IGESToBRep>>(m.attr("IGESToBRep"))
        .def_static("Init", static_cast<void (*)()>(&IGESToBRep::Init), R"nbdoc(Creates and initializes default AlgoContainer.)nbdoc")
        .def_static("SetAlgoContainer", static_cast<void (*)(const occ::handle<IGESToBRep_AlgoContainer> &)>(&IGESToBRep::SetAlgoContainer), nb::arg("aContainer").none(), R"nbdoc(Sets default AlgoContainer)nbdoc")
        .def_static("AlgoContainer", static_cast<occ::handle<IGESToBRep_AlgoContainer> (*)()>(&IGESToBRep::AlgoContainer), R"nbdoc(Returns default AlgoContainer)nbdoc")
        .def_static("IsCurveAndSurface", static_cast<bool (*)(const occ::handle<IGESData_IGESEntity> &)>(&IGESToBRep::IsCurveAndSurface), nb::arg("start").none(), R"nbdoc(Return True if the IGESEntity can be transferred by
TransferCurveAndSurface.
ex: All IGESEntity from IGESGeom)nbdoc")
        .def_static("IsBasicCurve", static_cast<bool (*)(const occ::handle<IGESData_IGESEntity> &)>(&IGESToBRep::IsBasicCurve), nb::arg("start").none(), R"nbdoc(Return True if the IGESEntity can be transferred by
TransferBasicCurve.
ex: CircularArc, ConicArc, Line, CopiousData,
BSplineCurve, SplineCurve... from IGESGeom :
104,110,112,126)nbdoc")
        .def_static("IsBasicSurface", static_cast<bool (*)(const occ::handle<IGESData_IGESEntity> &)>(&IGESToBRep::IsBasicSurface), nb::arg("start").none(), R"nbdoc(Return True if the IGESEntity can be transferred by
TransferBasicSurface.
ex: BSplineSurface, SplineSurface... from IGESGeom :
114,128)nbdoc")
        .def_static("IsTopoCurve", static_cast<bool (*)(const occ::handle<IGESData_IGESEntity> &)>(&IGESToBRep::IsTopoCurve), nb::arg("start").none(), R"nbdoc(Return True if the IGESEntity can be transferred by
TransferTopoCurve.
ex: all Curves from IGESGeom :
all basic curves,102,130,142,144)nbdoc")
        .def_static("IsTopoSurface", static_cast<bool (*)(const occ::handle<IGESData_IGESEntity> &)>(&IGESToBRep::IsTopoSurface), nb::arg("start").none(), R"nbdoc(Return True if the IGESEntity can be transferred by
TransferTopoSurface.
ex: All Surfaces from IGESGeom :
all basic surfaces,108,118,120,122,141,143)nbdoc")
        .def_static("IsBRepEntity", static_cast<bool (*)(const occ::handle<IGESData_IGESEntity> &)>(&IGESToBRep::IsBRepEntity), nb::arg("start").none(), R"nbdoc(Return True if the IGESEntity can be transferred by
TransferBRepEntity.
ex: VertexList, EdgeList, Loop, Face, Shell,
Manifold Solid BRep Object from IGESSolid :
502, 504, 508, 510, 514, 186.)nbdoc")
        .def_static("IGESCurveToSequenceOfIGESCurve", [](const occ::handle<IGESData_IGESEntity> & curve) { occ::handle<NCollection_HSequence<opencascade::handle<Standard_Transient>>> sequence{}; auto nanoocp_result = IGESToBRep::IGESCurveToSequenceOfIGESCurve(curve, sequence); return std::make_tuple(nanoocp_result, sequence); }, nb::arg("curve").none())
        .def_static("TransferPCurve", static_cast<bool (*)(const TopoDS_Edge &, const TopoDS_Edge &, const TopoDS_Face &)>(&IGESToBRep::TransferPCurve), nb::arg("fromedge"), nb::arg("toedge"), nb::arg("face"));
    nanoocp_implicit_copy_ctor<IGESToBRep>(nb::borrow<nb::class_<IGESToBRep>>(m.attr("IGESToBRep")));
    nb::borrow<nb::class_<IGESToBRep_Actor>>(m.attr("IGESToBRep_Actor"))
        .def(nb::new_([]() { return opencascade::handle<IGESToBRep_Actor>(new IGESToBRep_Actor()); }))
        .def("SetModel", static_cast<void (IGESToBRep_Actor::*)(const occ::handle<Interface_InterfaceModel> &)>(&IGESToBRep_Actor::SetModel), nb::arg("model").none())
        .def("SetContinuity", static_cast<void (IGESToBRep_Actor::*)(const int)>(&IGESToBRep_Actor::SetContinuity), nb::arg("continuity") = static_cast<std::decay_t<const int>>(0), R"nbdoc(---Purpose   By default continuity = 0
if continuity = 1 : try C1
if continuity = 2 : try C2)nbdoc")
        .def("GetContinuity", static_cast<int (IGESToBRep_Actor::*)() const>(&IGESToBRep_Actor::GetContinuity), R"nbdoc(Return "thecontinuity")nbdoc")
        .def("Recognize", static_cast<bool (IGESToBRep_Actor::*)(const occ::handle<Standard_Transient> &)>(&IGESToBRep_Actor::Recognize), nb::arg("start").none())
        .def("Transfer", static_cast<occ::handle<Transfer_Binder> (IGESToBRep_Actor::*)(const occ::handle<Standard_Transient> &, const occ::handle<Transfer_TransientProcess> &, const Message_ProgressRange &)>(&IGESToBRep_Actor::Transfer), nb::arg("start").none(), nb::arg("TP").none(), nb::arg("theProgress") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()))
        .def("UsedTolerance", static_cast<double (IGESToBRep_Actor::*)() const>(&IGESToBRep_Actor::UsedTolerance), R"nbdoc(Returns the tolerance which was actually used, either from
the file or from statics)nbdoc")
        .def_static("get_type_name", static_cast<const char * (*)()>(&IGESToBRep_Actor::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&IGESToBRep_Actor::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (IGESToBRep_Actor::*)() const>(&IGESToBRep_Actor::DynamicType));
    nanoocp_implicit_copy_ctor<IGESToBRep_Actor>(nb::borrow<nb::class_<IGESToBRep_Actor>>(m.attr("IGESToBRep_Actor")));
    nb::borrow<nb::class_<IGESToBRep_AlgoContainer>>(m.attr("IGESToBRep_AlgoContainer"))
        .def(nb::new_([]() { return opencascade::handle<IGESToBRep_AlgoContainer>(new IGESToBRep_AlgoContainer()); }), R"nbdoc(Empty constructor)nbdoc")
        .def("SetToolContainer", static_cast<void (IGESToBRep_AlgoContainer::*)(const occ::handle<IGESToBRep_ToolContainer> &)>(&IGESToBRep_AlgoContainer::SetToolContainer), nb::arg("TC").none(), R"nbdoc(Sets ToolContainer)nbdoc")
        .def("ToolContainer", static_cast<occ::handle<IGESToBRep_ToolContainer> (IGESToBRep_AlgoContainer::*)() const>(&IGESToBRep_AlgoContainer::ToolContainer), R"nbdoc(Returns ToolContainer)nbdoc")
        .def_static("get_type_name", static_cast<const char * (*)()>(&IGESToBRep_AlgoContainer::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&IGESToBRep_AlgoContainer::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (IGESToBRep_AlgoContainer::*)() const>(&IGESToBRep_AlgoContainer::DynamicType));
    nanoocp_implicit_copy_ctor<IGESToBRep_AlgoContainer>(nb::borrow<nb::class_<IGESToBRep_AlgoContainer>>(m.attr("IGESToBRep_AlgoContainer")));
    nb::borrow<nb::class_<IGESToBRep_CurveAndSurface>>(m.attr("IGESToBRep_CurveAndSurface"))
        .def(nb::init<>(), R"nbdoc(Creates a tool CurveAndSurface ready to run, with
epsilons set to 1.E-04, myModeTopo to True, the
optimization of the continuity to False.)nbdoc")
        .def(nb::init<const double, const double, const double, const bool, const bool, const bool>(), nb::arg("eps"), nb::arg("epsGeom"), nb::arg("epsCoeff"), nb::arg("mode"), nb::arg("modeapprox"), nb::arg("optimized"), R"nbdoc(Creates a tool CurveAndSurface ready to run.)nbdoc")
        .def("Init", static_cast<void (IGESToBRep_CurveAndSurface::*)()>(&IGESToBRep_CurveAndSurface::Init), R"nbdoc(Initializes the field of the tool CurveAndSurface with
default creating values.)nbdoc")
        .def("SetEpsilon", static_cast<void (IGESToBRep_CurveAndSurface::*)(const double)>(&IGESToBRep_CurveAndSurface::SetEpsilon), nb::arg("eps"), R"nbdoc(Changes the value of "myEps")nbdoc")
        .def("GetEpsilon", static_cast<double (IGESToBRep_CurveAndSurface::*)() const>(&IGESToBRep_CurveAndSurface::GetEpsilon), R"nbdoc(Returns the value of "myEps")nbdoc")
        .def("SetEpsCoeff", static_cast<void (IGESToBRep_CurveAndSurface::*)(const double)>(&IGESToBRep_CurveAndSurface::SetEpsCoeff), nb::arg("eps"), R"nbdoc(Changes the value of "myEpsCoeff")nbdoc")
        .def("GetEpsCoeff", static_cast<double (IGESToBRep_CurveAndSurface::*)() const>(&IGESToBRep_CurveAndSurface::GetEpsCoeff), R"nbdoc(Returns the value of "myEpsCoeff")nbdoc")
        .def("SetEpsGeom", static_cast<void (IGESToBRep_CurveAndSurface::*)(const double)>(&IGESToBRep_CurveAndSurface::SetEpsGeom), nb::arg("eps"), R"nbdoc(Changes the value of "myEpsGeom")nbdoc")
        .def("GetEpsGeom", static_cast<double (IGESToBRep_CurveAndSurface::*)() const>(&IGESToBRep_CurveAndSurface::GetEpsGeom), R"nbdoc(Returns the value of "myEpsGeom")nbdoc")
        .def("SetMinTol", static_cast<void (IGESToBRep_CurveAndSurface::*)(const double)>(&IGESToBRep_CurveAndSurface::SetMinTol), nb::arg("mintol"), R"nbdoc(Changes the value of "myMinTol")nbdoc")
        .def("SetMaxTol", static_cast<void (IGESToBRep_CurveAndSurface::*)(const double)>(&IGESToBRep_CurveAndSurface::SetMaxTol), nb::arg("maxtol"), R"nbdoc(Changes the value of "myMaxTol")nbdoc")
        .def("UpdateMinMaxTol", static_cast<void (IGESToBRep_CurveAndSurface::*)()>(&IGESToBRep_CurveAndSurface::UpdateMinMaxTol), R"nbdoc(Sets values of "myMinTol" and "myMaxTol" as follows
myMaxTol = Max ("read.maxprecision.val", myEpsGeom * myUnitFactor)
myMinTol = Precision::Confusion()
Remark: This method is automatically invoked each time the values
of "myEpsGeom" or "myUnitFactor" are changed)nbdoc")
        .def("GetMinTol", static_cast<double (IGESToBRep_CurveAndSurface::*)() const>(&IGESToBRep_CurveAndSurface::GetMinTol), R"nbdoc(Returns the value of "myMinTol")nbdoc")
        .def("GetMaxTol", static_cast<double (IGESToBRep_CurveAndSurface::*)() const>(&IGESToBRep_CurveAndSurface::GetMaxTol), R"nbdoc(Returns the value of "myMaxTol")nbdoc")
        .def("SetModeApprox", static_cast<void (IGESToBRep_CurveAndSurface::*)(const bool)>(&IGESToBRep_CurveAndSurface::SetModeApprox), nb::arg("mode"), R"nbdoc(Changes the value of "myModeApprox")nbdoc")
        .def("GetModeApprox", static_cast<bool (IGESToBRep_CurveAndSurface::*)() const>(&IGESToBRep_CurveAndSurface::GetModeApprox), R"nbdoc(Returns the value of "myModeApprox")nbdoc")
        .def("SetModeTransfer", static_cast<void (IGESToBRep_CurveAndSurface::*)(const bool)>(&IGESToBRep_CurveAndSurface::SetModeTransfer), nb::arg("mode"), R"nbdoc(Changes the value of "myModeIsTopo")nbdoc")
        .def("GetModeTransfer", static_cast<bool (IGESToBRep_CurveAndSurface::*)() const>(&IGESToBRep_CurveAndSurface::GetModeTransfer), R"nbdoc(Returns the value of "myModeIsTopo")nbdoc")
        .def("SetOptimized", static_cast<void (IGESToBRep_CurveAndSurface::*)(const bool)>(&IGESToBRep_CurveAndSurface::SetOptimized), nb::arg("optimized"), R"nbdoc(Changes the value of "myContIsOpti")nbdoc")
        .def("GetOptimized", static_cast<bool (IGESToBRep_CurveAndSurface::*)() const>(&IGESToBRep_CurveAndSurface::GetOptimized), R"nbdoc(Returns the value of "myContIsOpti")nbdoc")
        .def("GetUnitFactor", static_cast<double (IGESToBRep_CurveAndSurface::*)() const>(&IGESToBRep_CurveAndSurface::GetUnitFactor), R"nbdoc(Returns the value of " myUnitFactor")nbdoc")
        .def("SetSurfaceCurve", static_cast<void (IGESToBRep_CurveAndSurface::*)(const int)>(&IGESToBRep_CurveAndSurface::SetSurfaceCurve), nb::arg("ival"), R"nbdoc(Changes the value of "mySurfaceCurve")nbdoc")
        .def("GetSurfaceCurve", static_cast<int (IGESToBRep_CurveAndSurface::*)() const>(&IGESToBRep_CurveAndSurface::GetSurfaceCurve), R"nbdoc(Returns the value of "mySurfaceCurve" 0 = value in
file, 2 = keep 2d and compute 3d, 3 = keep 3d and
compute 2d)nbdoc")
        .def("SetModel", static_cast<void (IGESToBRep_CurveAndSurface::*)(const occ::handle<IGESData_IGESModel> &)>(&IGESToBRep_CurveAndSurface::SetModel), nb::arg("model").none(), R"nbdoc(Set the value of "myModel")nbdoc")
        .def("GetModel", static_cast<occ::handle<IGESData_IGESModel> (IGESToBRep_CurveAndSurface::*)() const>(&IGESToBRep_CurveAndSurface::GetModel), R"nbdoc(Returns the value of "myModel")nbdoc")
        .def("SetContinuity", static_cast<void (IGESToBRep_CurveAndSurface::*)(const int)>(&IGESToBRep_CurveAndSurface::SetContinuity), nb::arg("continuity"), R"nbdoc(Changes the value of "myContinuity"
if continuity = 0 do nothing else
if continuity = 1 try C1
if continuity = 2 try C2)nbdoc")
        .def("GetContinuity", static_cast<int (IGESToBRep_CurveAndSurface::*)() const>(&IGESToBRep_CurveAndSurface::GetContinuity), R"nbdoc(Returns the value of "myContinuity")nbdoc")
        .def("SetTransferProcess", static_cast<void (IGESToBRep_CurveAndSurface::*)(const occ::handle<Transfer_TransientProcess> &)>(&IGESToBRep_CurveAndSurface::SetTransferProcess), nb::arg("TP").none(), R"nbdoc(Set the value of "myMsgReg")nbdoc")
        .def("GetTransferProcess", static_cast<occ::handle<Transfer_TransientProcess> (IGESToBRep_CurveAndSurface::*)() const>(&IGESToBRep_CurveAndSurface::GetTransferProcess), R"nbdoc(Returns the value of "myMsgReg")nbdoc")
        .def("TransferCurveAndSurface", static_cast<TopoDS_Shape (IGESToBRep_CurveAndSurface::*)(const occ::handle<IGESData_IGESEntity> &, const Message_ProgressRange &)>(&IGESToBRep_CurveAndSurface::TransferCurveAndSurface), nb::arg("start").none(), nb::arg("theProgress") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()), R"nbdoc(Returns the result of the transfert of any IGES Curve
or Surface Entity. If the transfer has failed, this
member return a NullEntity.)nbdoc")
        .def("TransferGeometry", static_cast<TopoDS_Shape (IGESToBRep_CurveAndSurface::*)(const occ::handle<IGESData_IGESEntity> &, const Message_ProgressRange &)>(&IGESToBRep_CurveAndSurface::TransferGeometry), nb::arg("start").none(), nb::arg("theProgress") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()), R"nbdoc(Returns the result of the transfert the geometry of
any IGESEntity. If the transfer has failed, this
member return a NullEntity.)nbdoc")
        .def("SendFail", static_cast<void (IGESToBRep_CurveAndSurface::*)(const occ::handle<IGESData_IGESEntity> &, const Message_Msg &)>(&IGESToBRep_CurveAndSurface::SendFail), nb::arg("start").none(), nb::arg("amsg"), R"nbdoc(Records a new Fail message)nbdoc")
        .def("SendWarning", static_cast<void (IGESToBRep_CurveAndSurface::*)(const occ::handle<IGESData_IGESEntity> &, const Message_Msg &)>(&IGESToBRep_CurveAndSurface::SendWarning), nb::arg("start").none(), nb::arg("amsg"), R"nbdoc(Records a new Warning message)nbdoc")
        .def("SendMsg", static_cast<void (IGESToBRep_CurveAndSurface::*)(const occ::handle<IGESData_IGESEntity> &, const Message_Msg &)>(&IGESToBRep_CurveAndSurface::SendMsg), nb::arg("start").none(), nb::arg("amsg"), R"nbdoc(Records a new Information message from the definition
of a Msg (Original+Value))nbdoc")
        .def("HasShapeResult", static_cast<bool (IGESToBRep_CurveAndSurface::*)(const occ::handle<IGESData_IGESEntity> &) const>(&IGESToBRep_CurveAndSurface::HasShapeResult), nb::arg("start").none(), R"nbdoc(Returns True if start was already treated and has a result in "myMap"
else returns False.)nbdoc")
        .def("GetShapeResult", static_cast<TopoDS_Shape (IGESToBRep_CurveAndSurface::*)(const occ::handle<IGESData_IGESEntity> &) const>(&IGESToBRep_CurveAndSurface::GetShapeResult), nb::arg("start").none(), R"nbdoc(Returns the result of the transfer of the IGESEntity "start" contained
in "myMap" . (if HasShapeResult is True).)nbdoc")
        .def("SetShapeResult", static_cast<void (IGESToBRep_CurveAndSurface::*)(const occ::handle<IGESData_IGESEntity> &, const TopoDS_Shape &)>(&IGESToBRep_CurveAndSurface::SetShapeResult), nb::arg("start").none(), nb::arg("result"), R"nbdoc(set in "myMap" the result of the transfer of the IGESEntity "start".)nbdoc")
        .def("NbShapeResult", static_cast<int (IGESToBRep_CurveAndSurface::*)(const occ::handle<IGESData_IGESEntity> &) const>(&IGESToBRep_CurveAndSurface::NbShapeResult), nb::arg("start").none(), R"nbdoc(Returns the number of shapes results contained in "myMap" for the
IGESEntity start (type VertexList or EdgeList).)nbdoc")
        .def("GetShapeResult", static_cast<TopoDS_Shape (IGESToBRep_CurveAndSurface::*)(const occ::handle<IGESData_IGESEntity> &, const int) const>(&IGESToBRep_CurveAndSurface::GetShapeResult), nb::arg("start").none(), nb::arg("num"), R"nbdoc(Returns the numth result of the IGESEntity start (type VertexList or
EdgeList) in "myMap". (if NbShapeResult is not null).)nbdoc")
        .def("AddShapeResult", static_cast<void (IGESToBRep_CurveAndSurface::*)(const occ::handle<IGESData_IGESEntity> &, const TopoDS_Shape &)>(&IGESToBRep_CurveAndSurface::AddShapeResult), nb::arg("start").none(), nb::arg("result"), R"nbdoc(set in "myMap" the result of the transfer of the entity of the
IGESEntity start (type VertexList or EdgeList).)nbdoc")
        .def("SetSurface", static_cast<void (IGESToBRep_CurveAndSurface::*)(const occ::handle<Geom_Surface> &)>(&IGESToBRep_CurveAndSurface::SetSurface), nb::arg("theSurface").none())
        .def("Surface", static_cast<occ::handle<Geom_Surface> (IGESToBRep_CurveAndSurface::*)() const>(&IGESToBRep_CurveAndSurface::Surface))
        .def("GetUVResolution", static_cast<double (IGESToBRep_CurveAndSurface::*)()>(&IGESToBRep_CurveAndSurface::GetUVResolution));
    nanoocp_implicit_copy_ctor<IGESToBRep_CurveAndSurface>(nb::borrow<nb::class_<IGESToBRep_CurveAndSurface>>(m.attr("IGESToBRep_CurveAndSurface")));
    nb::borrow<nb::class_<IGESToBRep_BasicCurve>>(m.attr("IGESToBRep_BasicCurve"))
        .def(nb::init<>(), R"nbdoc(Creates a tool BasicCurve ready to run, with
epsilons set to 1.E-04, TheModeTopo to True, the
optimization of the continuity to False.)nbdoc")
        .def(nb::init<const IGESToBRep_CurveAndSurface &>(), nb::arg("CS"), R"nbdoc(Creates a tool BasicCurve ready to run and sets its
fields as CS's.)nbdoc")
        .def(nb::init<const double, const double, const double, const bool, const bool, const bool>(), nb::arg("eps"), nb::arg("epsGeom"), nb::arg("epsCoeff"), nb::arg("mode"), nb::arg("modeapprox"), nb::arg("optimized"), R"nbdoc(Creates a tool BasicCurve ready to run.)nbdoc")
        .def("TransferBasicCurve", static_cast<occ::handle<Geom_Curve> (IGESToBRep_BasicCurve::*)(const occ::handle<IGESData_IGESEntity> &)>(&IGESToBRep_BasicCurve::TransferBasicCurve), nb::arg("start").none(), R"nbdoc(Transfer a IGESEntity which answer True to the
member : IGESToBRep::IsBasicCurve(IGESEntity). If this
Entity could not be converted, this member returns a NullEntity.)nbdoc")
        .def("Transfer2dBasicCurve", static_cast<occ::handle<Geom2d_Curve> (IGESToBRep_BasicCurve::*)(const occ::handle<IGESData_IGESEntity> &)>(&IGESToBRep_BasicCurve::Transfer2dBasicCurve), nb::arg("start").none(), R"nbdoc(Transfert a IGESEntity which answer True to the
member : IGESToBRep::IsBasicCurve(IGESEntity).
The IGESEntity must be a curve UV and its associed TRSF must
be planar. If this Entity could not be converted, this member
returns a NullEntity.)nbdoc")
        .def("TransferBSplineCurve", static_cast<occ::handle<Geom_Curve> (IGESToBRep_BasicCurve::*)(const occ::handle<IGESGeom_BSplineCurve> &)>(&IGESToBRep_BasicCurve::TransferBSplineCurve), nb::arg("start").none())
        .def("Transfer2dBSplineCurve", static_cast<occ::handle<Geom2d_Curve> (IGESToBRep_BasicCurve::*)(const occ::handle<IGESGeom_BSplineCurve> &)>(&IGESToBRep_BasicCurve::Transfer2dBSplineCurve), nb::arg("start").none())
        .def("TransferCircularArc", static_cast<occ::handle<Geom_Curve> (IGESToBRep_BasicCurve::*)(const occ::handle<IGESGeom_CircularArc> &)>(&IGESToBRep_BasicCurve::TransferCircularArc), nb::arg("start").none())
        .def("Transfer2dCircularArc", static_cast<occ::handle<Geom2d_Curve> (IGESToBRep_BasicCurve::*)(const occ::handle<IGESGeom_CircularArc> &)>(&IGESToBRep_BasicCurve::Transfer2dCircularArc), nb::arg("start").none())
        .def("TransferConicArc", static_cast<occ::handle<Geom_Curve> (IGESToBRep_BasicCurve::*)(const occ::handle<IGESGeom_ConicArc> &)>(&IGESToBRep_BasicCurve::TransferConicArc), nb::arg("start").none())
        .def("Transfer2dConicArc", static_cast<occ::handle<Geom2d_Curve> (IGESToBRep_BasicCurve::*)(const occ::handle<IGESGeom_ConicArc> &)>(&IGESToBRep_BasicCurve::Transfer2dConicArc), nb::arg("start").none())
        .def("TransferCopiousData", static_cast<occ::handle<Geom_BSplineCurve> (IGESToBRep_BasicCurve::*)(const occ::handle<IGESGeom_CopiousData> &)>(&IGESToBRep_BasicCurve::TransferCopiousData), nb::arg("start").none())
        .def("Transfer2dCopiousData", static_cast<occ::handle<Geom2d_BSplineCurve> (IGESToBRep_BasicCurve::*)(const occ::handle<IGESGeom_CopiousData> &)>(&IGESToBRep_BasicCurve::Transfer2dCopiousData), nb::arg("start").none())
        .def("TransferLine", static_cast<occ::handle<Geom_Curve> (IGESToBRep_BasicCurve::*)(const occ::handle<IGESGeom_Line> &)>(&IGESToBRep_BasicCurve::TransferLine), nb::arg("start").none())
        .def("Transfer2dLine", static_cast<occ::handle<Geom2d_Curve> (IGESToBRep_BasicCurve::*)(const occ::handle<IGESGeom_Line> &)>(&IGESToBRep_BasicCurve::Transfer2dLine), nb::arg("start").none())
        .def("TransferSplineCurve", static_cast<occ::handle<Geom_BSplineCurve> (IGESToBRep_BasicCurve::*)(const occ::handle<IGESGeom_SplineCurve> &)>(&IGESToBRep_BasicCurve::TransferSplineCurve), nb::arg("start").none())
        .def("Transfer2dSplineCurve", static_cast<occ::handle<Geom2d_BSplineCurve> (IGESToBRep_BasicCurve::*)(const occ::handle<IGESGeom_SplineCurve> &)>(&IGESToBRep_BasicCurve::Transfer2dSplineCurve), nb::arg("start").none())
        .def("TransferTransformation", static_cast<occ::handle<Geom_Transformation> (IGESToBRep_BasicCurve::*)(const occ::handle<IGESGeom_TransformationMatrix> &)>(&IGESToBRep_BasicCurve::TransferTransformation), nb::arg("start").none());
    nanoocp_implicit_copy_ctor<IGESToBRep_BasicCurve>(nb::borrow<nb::class_<IGESToBRep_BasicCurve>>(m.attr("IGESToBRep_BasicCurve")));
    nb::implicitly_convertible<std::decay_t<const IGESToBRep_CurveAndSurface &>, IGESToBRep_BasicCurve>();
    nb::borrow<nb::class_<IGESToBRep_BasicSurface>>(m.attr("IGESToBRep_BasicSurface"))
        .def(nb::init<>(), R"nbdoc(Creates a tool BasicSurface ready to run, with
epsilons set to 1.E-04, TheModeTopo to True, the
optimization of the continuity to False.)nbdoc")
        .def(nb::init<const IGESToBRep_CurveAndSurface &>(), nb::arg("CS"), R"nbdoc(Creates a tool BasicSurface ready to run and sets its
fields as CS's.)nbdoc")
        .def(nb::init<const double, const double, const double, const bool, const bool, const bool>(), nb::arg("eps"), nb::arg("epsGeom"), nb::arg("epsCoeff"), nb::arg("mode"), nb::arg("modeapprox"), nb::arg("optimized"), R"nbdoc(Creates a tool BasicSurface ready to run.)nbdoc")
        .def("TransferBasicSurface", static_cast<occ::handle<Geom_Surface> (IGESToBRep_BasicSurface::*)(const occ::handle<IGESData_IGESEntity> &)>(&IGESToBRep_BasicSurface::TransferBasicSurface), nb::arg("start").none(), R"nbdoc(Returns Surface from Geom if the last transfer has succeeded.)nbdoc")
        .def("TransferPlaneSurface", static_cast<occ::handle<Geom_Plane> (IGESToBRep_BasicSurface::*)(const occ::handle<IGESSolid_PlaneSurface> &)>(&IGESToBRep_BasicSurface::TransferPlaneSurface), nb::arg("start").none(), R"nbdoc(Returns Plane from Geom if the transfer has succeeded.)nbdoc")
        .def("TransferRigthCylindricalSurface", static_cast<occ::handle<Geom_CylindricalSurface> (IGESToBRep_BasicSurface::*)(const occ::handle<IGESSolid_CylindricalSurface> &)>(&IGESToBRep_BasicSurface::TransferRigthCylindricalSurface), nb::arg("start").none(), R"nbdoc(Returns CylindricalSurface from Geom if the transfer has succeeded.)nbdoc")
        .def("TransferRigthConicalSurface", static_cast<occ::handle<Geom_ConicalSurface> (IGESToBRep_BasicSurface::*)(const occ::handle<IGESSolid_ConicalSurface> &)>(&IGESToBRep_BasicSurface::TransferRigthConicalSurface), nb::arg("start").none(), R"nbdoc(Returns ConicalSurface from Geom if the transfer has succeeded.)nbdoc")
        .def("TransferSphericalSurface", static_cast<occ::handle<Geom_SphericalSurface> (IGESToBRep_BasicSurface::*)(const occ::handle<IGESSolid_SphericalSurface> &)>(&IGESToBRep_BasicSurface::TransferSphericalSurface), nb::arg("start").none(), R"nbdoc(Returns SphericalSurface from Geom if the transfer has succeeded.)nbdoc")
        .def("TransferToroidalSurface", static_cast<occ::handle<Geom_ToroidalSurface> (IGESToBRep_BasicSurface::*)(const occ::handle<IGESSolid_ToroidalSurface> &)>(&IGESToBRep_BasicSurface::TransferToroidalSurface), nb::arg("start").none(), R"nbdoc(Returns SphericalSurface from Geom if the transfer has succeeded.)nbdoc")
        .def("TransferSplineSurface", static_cast<occ::handle<Geom_BSplineSurface> (IGESToBRep_BasicSurface::*)(const occ::handle<IGESGeom_SplineSurface> &)>(&IGESToBRep_BasicSurface::TransferSplineSurface), nb::arg("start").none(), R"nbdoc(Returns BSplineSurface from Geom if the transfer has succeeded.)nbdoc")
        .def("TransferBSplineSurface", static_cast<occ::handle<Geom_BSplineSurface> (IGESToBRep_BasicSurface::*)(const occ::handle<IGESGeom_BSplineSurface> &)>(&IGESToBRep_BasicSurface::TransferBSplineSurface), nb::arg("start").none(), R"nbdoc(Returns BSplineSurface from Geom if the transfer has succeeded.)nbdoc");
    nanoocp_implicit_copy_ctor<IGESToBRep_BasicSurface>(nb::borrow<nb::class_<IGESToBRep_BasicSurface>>(m.attr("IGESToBRep_BasicSurface")));
    nb::implicitly_convertible<std::decay_t<const IGESToBRep_CurveAndSurface &>, IGESToBRep_BasicSurface>();
    nb::borrow<nb::class_<IGESToBRep_BRepEntity>>(m.attr("IGESToBRep_BRepEntity"))
        .def(nb::init<>(), R"nbdoc(Creates a tool BRepEntity ready to run, with
epsilons set to 1.E-04, TheModeTopo to True, the
optimization of the continuity to False.)nbdoc")
        .def(nb::init<const IGESToBRep_CurveAndSurface &>(), nb::arg("CS"), R"nbdoc(Creates a tool BRepEntity ready to run and sets its
fields as CS's.)nbdoc")
        .def(nb::init<const double, const double, const double, const bool, const bool, const bool>(), nb::arg("eps"), nb::arg("epsGeom"), nb::arg("epsCoeff"), nb::arg("mode"), nb::arg("modeapprox"), nb::arg("optimized"), R"nbdoc(Creates a tool BRepEntity ready to run.)nbdoc")
        .def("TransferBRepEntity", static_cast<TopoDS_Shape (IGESToBRep_BRepEntity::*)(const occ::handle<IGESData_IGESEntity> &, const Message_ProgressRange &)>(&IGESToBRep_BRepEntity::TransferBRepEntity), nb::arg("start").none(), nb::arg("theProgress") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()), R"nbdoc(Transfer the BRepEntity" : Face, Shell or ManifoldSolid.)nbdoc")
        .def("TransferVertex", static_cast<TopoDS_Vertex (IGESToBRep_BRepEntity::*)(const occ::handle<IGESSolid_VertexList> &, const int)>(&IGESToBRep_BRepEntity::TransferVertex), nb::arg("start").none(), nb::arg("index"), R"nbdoc(Transfer the entity number "index" of the VertexList "start")nbdoc")
        .def("TransferEdge", static_cast<TopoDS_Shape (IGESToBRep_BRepEntity::*)(const occ::handle<IGESSolid_EdgeList> &, const int)>(&IGESToBRep_BRepEntity::TransferEdge), nb::arg("start").none(), nb::arg("index"), R"nbdoc(Transfer the entity number "index" of the EdgeList "start".)nbdoc")
        .def("TransferLoop", static_cast<TopoDS_Shape (IGESToBRep_BRepEntity::*)(const occ::handle<IGESSolid_Loop> &, const TopoDS_Face &, const gp_Trsf2d &, const double)>(&IGESToBRep_BRepEntity::TransferLoop), nb::arg("start").none(), nb::arg("Face"), nb::arg("trans"), nb::arg("uFact"), R"nbdoc(Transfer the Loop Entity)nbdoc")
        .def("TransferFace", static_cast<TopoDS_Shape (IGESToBRep_BRepEntity::*)(const occ::handle<IGESSolid_Face> &)>(&IGESToBRep_BRepEntity::TransferFace), nb::arg("start").none(), R"nbdoc(Transfer the Face Entity)nbdoc")
        .def("TransferShell", static_cast<TopoDS_Shape (IGESToBRep_BRepEntity::*)(const occ::handle<IGESSolid_Shell> &, const Message_ProgressRange &)>(&IGESToBRep_BRepEntity::TransferShell), nb::arg("start").none(), nb::arg("theProgress") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()), R"nbdoc(Transfer the Shell Entity)nbdoc")
        .def("TransferManifoldSolid", static_cast<TopoDS_Shape (IGESToBRep_BRepEntity::*)(const occ::handle<IGESSolid_ManifoldSolid> &, const Message_ProgressRange &)>(&IGESToBRep_BRepEntity::TransferManifoldSolid), nb::arg("start").none(), nb::arg("theProgress") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()), R"nbdoc(Transfer the ManifoldSolid Entity)nbdoc");
    nanoocp_implicit_copy_ctor<IGESToBRep_BRepEntity>(nb::borrow<nb::class_<IGESToBRep_BRepEntity>>(m.attr("IGESToBRep_BRepEntity")));
    nb::implicitly_convertible<std::decay_t<const IGESToBRep_CurveAndSurface &>, IGESToBRep_BRepEntity>();
    nb::borrow<nb::class_<IGESToBRep_IGESBoundary>>(m.attr("IGESToBRep_IGESBoundary"))
        .def(nb::new_([]() { return opencascade::handle<IGESToBRep_IGESBoundary>(new IGESToBRep_IGESBoundary()); }), R"nbdoc(Empty constructor)nbdoc")
        .def(nb::new_([](const IGESToBRep_CurveAndSurface & CS) { return opencascade::handle<IGESToBRep_IGESBoundary>(new IGESToBRep_IGESBoundary(CS)); }), nb::arg("CS"), R"nbdoc(Empty constructor)nbdoc")
        .def("Init", static_cast<void (IGESToBRep_IGESBoundary::*)(const IGESToBRep_CurveAndSurface &, const occ::handle<IGESData_IGESEntity> &, const TopoDS_Face &, const gp_Trsf2d &, const double, const int)>(&IGESToBRep_IGESBoundary::Init), nb::arg("CS"), nb::arg("entity").none(), nb::arg("face"), nb::arg("trans"), nb::arg("uFact"), nb::arg("filepreference"), R"nbdoc(Inits the object with parameters common for all
types of IGES boundaries.
<CS>: object to be used for retrieving translation parameters
and sending messages,
<entity>: boundary entity to be processed,
<face>, <trans>, <uFact>: as for IGESToBRep_TopoCurve
<filepreference>: preferred representation (2 or 3) given
in the IGES file)nbdoc")
        .def("WireData", static_cast<occ::handle<ShapeExtend_WireData> (IGESToBRep_IGESBoundary::*)() const>(&IGESToBRep_IGESBoundary::WireData), R"nbdoc(Returns the resulting wire)nbdoc")
        .def("WireData3d", static_cast<occ::handle<ShapeExtend_WireData> (IGESToBRep_IGESBoundary::*)() const>(&IGESToBRep_IGESBoundary::WireData3d), R"nbdoc(Returns the wire from 3D curves (edges contain 3D curves
and may contain pcurves))nbdoc")
        .def("WireData2d", static_cast<occ::handle<ShapeExtend_WireData> (IGESToBRep_IGESBoundary::*)() const>(&IGESToBRep_IGESBoundary::WireData2d), R"nbdoc(Returns the wire from 2D curves (edges contain pcurves
only))nbdoc")
        .def("Transfer", [](IGESToBRep_IGESBoundary &self, const occ::handle<IGESData_IGESEntity> & curve3d, const bool toreverse3d, const occ::handle<NCollection_HArray1<opencascade::handle<IGESData_IGESEntity>>> & curves2d, const int number) { bool okCurve{}; bool okCurve3d{}; bool okCurve2d{}; auto nanoocp_result = self.Transfer(okCurve, okCurve3d, okCurve2d, curve3d, toreverse3d, curves2d, number); return std::make_tuple(nanoocp_result, okCurve, okCurve3d, okCurve2d); }, nb::arg("curve3d").none(), nb::arg("toreverse3d"), nb::arg("curves2d").none(), nb::arg("number"), R"nbdoc(Translates 141 and 142 entities.
Returns True if the curve has been successfully translated,
otherwise returns False.
<okCurve..>: flags that indicate whether corresponding
representation has been successfully translated
(must be set to True before first call),
<curve3d>: model space curve for 142 and current model space
curve for 141,
<toreverse3d>: False for 142 and current orientation flag
for 141,
<curves2d>: 1 parameter space curve for 142 or list of
them for current model space curves for 141,
<number>: 1 for 142 and rank number of model space curve for 141.)nbdoc")
        .def("Transfer", [](IGESToBRep_IGESBoundary &self, const occ::handle<ShapeExtend_WireData> & curve3d, const occ::handle<NCollection_HArray1<opencascade::handle<IGESData_IGESEntity>>> & curves2d, const bool toreverse2d, const int number) { bool okCurve{}; bool okCurve3d{}; bool okCurve2d{}; occ::handle<ShapeExtend_WireData> lsewd{}; auto nanoocp_result = self.Transfer(okCurve, okCurve3d, okCurve2d, curve3d, curves2d, toreverse2d, number, lsewd); return std::make_tuple(nanoocp_result, okCurve, okCurve3d, okCurve2d, lsewd); }, nb::arg("curve3d").none(), nb::arg("curves2d").none(), nb::arg("toreverse2d"), nb::arg("number"), R"nbdoc(Translates 508 entity.
Returns True if the curve has been successfully translated,
otherwise returns False.
Input object IGESBoundary must be created and initialized
before.
<okCurve..>: flags that indicate whether corresponding
representation has been successfully translated
(must be set to True before first call),
<curve3d>: result of translation of current edge,
<curves2d>: list of parameter space curves for edge,
<toreverse2d>: orientation flag of current edge in respect
to its model space curve,
<number>: rank number of edge,
<lsewd>: returns the result of translation of current edge.)nbdoc")
        .def("Check", static_cast<void (IGESToBRep_IGESBoundary::*)(const bool, const bool, const bool, const bool)>(&IGESToBRep_IGESBoundary::Check), nb::arg("result"), nb::arg("checkclosure"), nb::arg("okCurve3d"), nb::arg("okCurve2d"), R"nbdoc(Checks result of translation of IGES boundary entities
(types 141, 142 or 508).
Checks consistency of 2D and 3D representations and keeps
only one if they are inconsistent.
<result>: result of translation (returned by Transfer),
<checkclosure>: False for 142 without parent 144 entity,
otherwise True,
<okCurve3d>, <okCurve2d>: those returned by Transfer.)nbdoc")
        .def_static("get_type_name", static_cast<const char * (*)()>(&IGESToBRep_IGESBoundary::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&IGESToBRep_IGESBoundary::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (IGESToBRep_IGESBoundary::*)() const>(&IGESToBRep_IGESBoundary::DynamicType));
    nanoocp_implicit_copy_ctor<IGESToBRep_IGESBoundary>(nb::borrow<nb::class_<IGESToBRep_IGESBoundary>>(m.attr("IGESToBRep_IGESBoundary")));
    nb::implicitly_convertible<std::decay_t<const IGESToBRep_CurveAndSurface &>, IGESToBRep_IGESBoundary>();
    nb::borrow<nb::class_<IGESToBRep_Reader>>(m.attr("IGESToBRep_Reader"))
        .def(nb::init<>(), R"nbdoc(Creates a Reader)nbdoc")
        .def("LoadFile", static_cast<int (IGESToBRep_Reader::*)(const char *const)>(&IGESToBRep_Reader::LoadFile), nb::arg("filename"), R"nbdoc(Loads a Model from a file.Returns 0 if success.
returns 1 if the file could not be opened,
returns -1 if an error occurred while the file was being loaded.)nbdoc")
        .def("SetModel", static_cast<void (IGESToBRep_Reader::*)(const occ::handle<IGESData_IGESModel> &)>(&IGESToBRep_Reader::SetModel), nb::arg("model").none(), R"nbdoc(Specifies a Model to work on
Also clears the result and Done status, sets TransientProcess)nbdoc")
        .def("Model", static_cast<occ::handle<IGESData_IGESModel> (IGESToBRep_Reader::*)() const>(&IGESToBRep_Reader::Model), R"nbdoc(Returns the Model to be worked on.)nbdoc")
        .def("SetTransientProcess", static_cast<void (IGESToBRep_Reader::*)(const occ::handle<Transfer_TransientProcess> &)>(&IGESToBRep_Reader::SetTransientProcess), nb::arg("TP").none(), R"nbdoc(Allows to set an already defined TransientProcess
(to be called after LoadFile or SetModel))nbdoc")
        .def("TransientProcess", static_cast<occ::handle<Transfer_TransientProcess> (IGESToBRep_Reader::*)() const>(&IGESToBRep_Reader::TransientProcess), R"nbdoc(Returns the TransientProcess)nbdoc")
        .def("Actor", static_cast<occ::handle<IGESToBRep_Actor> (IGESToBRep_Reader::*)() const>(&IGESToBRep_Reader::Actor), R"nbdoc(Returns "theActor")nbdoc")
        .def("Clear", static_cast<void (IGESToBRep_Reader::*)()>(&IGESToBRep_Reader::Clear), R"nbdoc(Clears the results between two translation operations.)nbdoc")
        .def("Check", static_cast<bool (IGESToBRep_Reader::*)(const bool) const>(&IGESToBRep_Reader::Check), nb::arg("withprint"), R"nbdoc(Checks the IGES file that was
loaded into memory. Displays error messages in the default
message file if withprint is true. Returns True if no fail
message was found and False if there was at least one fail message.)nbdoc")
        .def("TransferRoots", static_cast<void (IGESToBRep_Reader::*)(const bool, const Message_ProgressRange &)>(&IGESToBRep_Reader::TransferRoots), nb::arg("onlyvisible") = static_cast<std::decay_t<const bool>>(true), nb::arg("theProgress") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()), R"nbdoc(Translates root entities in an
IGES file. true is the default value and means that only
visible root entities are translated. false
translates all of the roots (visible and invisible).)nbdoc")
        .def("Transfer", static_cast<bool (IGESToBRep_Reader::*)(const int, const Message_ProgressRange &)>(&IGESToBRep_Reader::Transfer), nb::arg("num"), nb::arg("theProgress") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()), R"nbdoc(Transfers an Entity given its rank in the Model (Root or not)
Returns True if it is recognized as Geom-Topol.
(But it can have failed : see IsDone))nbdoc")
        .def("IsDone", static_cast<bool (IGESToBRep_Reader::*)() const>(&IGESToBRep_Reader::IsDone), R"nbdoc(Returns True if the LAST Transfer/TransferRoots was a success)nbdoc")
        .def("UsedTolerance", static_cast<double (IGESToBRep_Reader::*)() const>(&IGESToBRep_Reader::UsedTolerance), R"nbdoc(Returns the Tolerance which has been actually used, converted
in millimeters
(either that from File or that from Session, according the mode))nbdoc")
        .def("NbShapes", static_cast<int (IGESToBRep_Reader::*)() const>(&IGESToBRep_Reader::NbShapes), R"nbdoc(Returns the number of shapes produced by the translation.)nbdoc")
        .def("Shape", static_cast<TopoDS_Shape (IGESToBRep_Reader::*)(const int) const>(&IGESToBRep_Reader::Shape), nb::arg("num") = static_cast<std::decay_t<const int>>(1), R"nbdoc(Returns the num the resulting shape in a translation operation.)nbdoc")
        .def("OneShape", static_cast<TopoDS_Shape (IGESToBRep_Reader::*)() const>(&IGESToBRep_Reader::OneShape), R"nbdoc(Returns all of the results in a
single shape which is:
- a null shape if there are no results,
- a shape if there is one result,
- a compound containing the resulting shapes if there are several.)nbdoc")
        .def("SetShapeFixParameters", static_cast<void (IGESToBRep_Reader::*)(const NCollection_DataMap<TCollection_AsciiString, TCollection_AsciiString> &)>(&IGESToBRep_Reader::SetShapeFixParameters), nb::arg("theParameters"), R"nbdoc(Sets parameters for shape processing.
@param theParameters the parameters for shape processing.)nbdoc")
        .def("SetShapeFixParameters", static_cast<void (IGESToBRep_Reader::*)(const DE_ShapeFixParameters &, const NCollection_DataMap<TCollection_AsciiString, TCollection_AsciiString> &)>(&IGESToBRep_Reader::SetShapeFixParameters), nb::arg("theParameters"), nb::arg("theAdditionalParameters") = std::decay_t<const NCollection_DataMap<TCollection_AsciiString, TCollection_AsciiString> &>{ }, R"nbdoc(Sets parameters for shape processing.
Parameters from @p theParameters are copied to the internal map.
Parameters from @p theAdditionalParameters are copied to the internal map
if they are not present in @p theParameters.
@param theParameters the parameters for shape processing.
@param theAdditionalParameters the additional parameters for shape processing.)nbdoc")
        .def("GetShapeFixParameters", static_cast<const NCollection_DataMap<TCollection_AsciiString, TCollection_AsciiString> & (IGESToBRep_Reader::*)() const>(&IGESToBRep_Reader::GetShapeFixParameters), R"nbdoc(Returns parameters for shape processing that was set by SetParameters() method.
@return the parameters for shape processing. Empty map if no parameters were set.)nbdoc")
        .def("SetShapeProcessFlags", static_cast<void (IGESToBRep_Reader::*)(const std::bitset<18> &)>(&IGESToBRep_Reader::SetShapeProcessFlags), nb::arg("theFlags"), R"nbdoc(Sets flags defining operations to be performed on shapes.
@param theFlags The flags defining operations to be performed on shapes.)nbdoc")
        .def("GetShapeProcessFlags", static_cast<const std::bitset<18> & (IGESToBRep_Reader::*)() const>(&IGESToBRep_Reader::GetShapeProcessFlags), R"nbdoc(Returns flags defining operations to be performed on shapes.
@return The flags defining operations to be performed on shapes.)nbdoc");
    nanoocp_implicit_copy_ctor<IGESToBRep_Reader>(nb::borrow<nb::class_<IGESToBRep_Reader>>(m.attr("IGESToBRep_Reader")));
    nb::borrow<nb::class_<IGESToBRep_ToolContainer>>(m.attr("IGESToBRep_ToolContainer"))
        .def(nb::new_([]() { return opencascade::handle<IGESToBRep_ToolContainer>(new IGESToBRep_ToolContainer()); }), R"nbdoc(Empty constructor)nbdoc")
        .def("IGESBoundary", static_cast<occ::handle<IGESToBRep_IGESBoundary> (IGESToBRep_ToolContainer::*)() const>(&IGESToBRep_ToolContainer::IGESBoundary), R"nbdoc(Returns IGESToBRep_IGESBoundary)nbdoc")
        .def_static("get_type_name", static_cast<const char * (*)()>(&IGESToBRep_ToolContainer::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&IGESToBRep_ToolContainer::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (IGESToBRep_ToolContainer::*)() const>(&IGESToBRep_ToolContainer::DynamicType));
    nanoocp_implicit_copy_ctor<IGESToBRep_ToolContainer>(nb::borrow<nb::class_<IGESToBRep_ToolContainer>>(m.attr("IGESToBRep_ToolContainer")));
    nb::borrow<nb::class_<IGESToBRep_TopoCurve>>(m.attr("IGESToBRep_TopoCurve"))
        .def(nb::init<>(), R"nbdoc(Creates a tool TopoCurve ready to run, with
epsilons set to 1.E-04, TheModeTopo to True, the
optimization of the continuity to False.)nbdoc")
        .def(nb::init<const IGESToBRep_CurveAndSurface &>(), nb::arg("CS"), R"nbdoc(Creates a tool TopoCurve ready to run and sets its
fields as CS's.)nbdoc")
        .def(nb::init<const IGESToBRep_TopoCurve &>(), nb::arg("CS"), R"nbdoc(Creates a tool TopoCurve ready to run and sets its
fields as CS's.)nbdoc")
        .def(nb::init<const double, const double, const double, const bool, const bool, const bool>(), nb::arg("eps"), nb::arg("epsGeom"), nb::arg("epsCoeff"), nb::arg("mode"), nb::arg("modeapprox"), nb::arg("optimized"), R"nbdoc(Creates a tool TopoCurve ready to run.)nbdoc")
        .def("TransferTopoCurve", static_cast<TopoDS_Shape (IGESToBRep_TopoCurve::*)(const occ::handle<IGESData_IGESEntity> &)>(&IGESToBRep_TopoCurve::TransferTopoCurve), nb::arg("start").none())
        .def("Transfer2dTopoCurve", static_cast<TopoDS_Shape (IGESToBRep_TopoCurve::*)(const occ::handle<IGESData_IGESEntity> &, const TopoDS_Face &, const gp_Trsf2d &, const double)>(&IGESToBRep_TopoCurve::Transfer2dTopoCurve), nb::arg("start").none(), nb::arg("face"), nb::arg("trans"), nb::arg("uFact"))
        .def("TransferTopoBasicCurve", static_cast<TopoDS_Shape (IGESToBRep_TopoCurve::*)(const occ::handle<IGESData_IGESEntity> &)>(&IGESToBRep_TopoCurve::TransferTopoBasicCurve), nb::arg("start").none())
        .def("Transfer2dTopoBasicCurve", static_cast<TopoDS_Shape (IGESToBRep_TopoCurve::*)(const occ::handle<IGESData_IGESEntity> &, const TopoDS_Face &, const gp_Trsf2d &, const double)>(&IGESToBRep_TopoCurve::Transfer2dTopoBasicCurve), nb::arg("start").none(), nb::arg("face"), nb::arg("trans"), nb::arg("uFact"))
        .def("TransferPoint", static_cast<TopoDS_Vertex (IGESToBRep_TopoCurve::*)(const occ::handle<IGESGeom_Point> &)>(&IGESToBRep_TopoCurve::TransferPoint), nb::arg("start").none())
        .def("Transfer2dPoint", static_cast<TopoDS_Vertex (IGESToBRep_TopoCurve::*)(const occ::handle<IGESGeom_Point> &)>(&IGESToBRep_TopoCurve::Transfer2dPoint), nb::arg("start").none())
        .def("TransferCompositeCurve", static_cast<TopoDS_Shape (IGESToBRep_TopoCurve::*)(const occ::handle<IGESGeom_CompositeCurve> &)>(&IGESToBRep_TopoCurve::TransferCompositeCurve), nb::arg("start").none())
        .def("Transfer2dCompositeCurve", static_cast<TopoDS_Shape (IGESToBRep_TopoCurve::*)(const occ::handle<IGESGeom_CompositeCurve> &, const TopoDS_Face &, const gp_Trsf2d &, const double)>(&IGESToBRep_TopoCurve::Transfer2dCompositeCurve), nb::arg("start").none(), nb::arg("face"), nb::arg("trans"), nb::arg("uFact"))
        .def("TransferOffsetCurve", static_cast<TopoDS_Shape (IGESToBRep_TopoCurve::*)(const occ::handle<IGESGeom_OffsetCurve> &)>(&IGESToBRep_TopoCurve::TransferOffsetCurve), nb::arg("start").none())
        .def("Transfer2dOffsetCurve", static_cast<TopoDS_Shape (IGESToBRep_TopoCurve::*)(const occ::handle<IGESGeom_OffsetCurve> &, const TopoDS_Face &, const gp_Trsf2d &, const double)>(&IGESToBRep_TopoCurve::Transfer2dOffsetCurve), nb::arg("start").none(), nb::arg("face"), nb::arg("trans"), nb::arg("uFact"))
        .def("TransferCurveOnSurface", static_cast<TopoDS_Shape (IGESToBRep_TopoCurve::*)(const occ::handle<IGESGeom_CurveOnSurface> &)>(&IGESToBRep_TopoCurve::TransferCurveOnSurface), nb::arg("start").none())
        .def("TransferCurveOnFace", static_cast<TopoDS_Shape (IGESToBRep_TopoCurve::*)(TopoDS_Face &, const occ::handle<IGESGeom_CurveOnSurface> &, const gp_Trsf2d &, const double, const bool)>(&IGESToBRep_TopoCurve::TransferCurveOnFace), nb::arg("face"), nb::arg("start").none(), nb::arg("trans"), nb::arg("uFact"), nb::arg("IsCurv"), R"nbdoc(Transfers a CurveOnSurface directly on a face to trim it.
The CurveOnSurface have to be defined Outer or Inner.)nbdoc")
        .def("TransferBoundary", static_cast<TopoDS_Shape (IGESToBRep_TopoCurve::*)(const occ::handle<IGESGeom_Boundary> &)>(&IGESToBRep_TopoCurve::TransferBoundary), nb::arg("start").none())
        .def("TransferBoundaryOnFace", static_cast<TopoDS_Shape (IGESToBRep_TopoCurve::*)(TopoDS_Face &, const occ::handle<IGESGeom_Boundary> &, const gp_Trsf2d &, const double)>(&IGESToBRep_TopoCurve::TransferBoundaryOnFace), nb::arg("face"), nb::arg("start").none(), nb::arg("trans"), nb::arg("uFact"), R"nbdoc(Transfers a Boundary directly on a face to trim it.)nbdoc")
        .def("ApproxBSplineCurve", static_cast<void (IGESToBRep_TopoCurve::*)(const occ::handle<Geom_BSplineCurve> &)>(&IGESToBRep_TopoCurve::ApproxBSplineCurve), nb::arg("start").none())
        .def("NbCurves", static_cast<int (IGESToBRep_TopoCurve::*)() const>(&IGESToBRep_TopoCurve::NbCurves), R"nbdoc(Returns the count of Curves in "TheCurves")nbdoc")
        .def("Curve", static_cast<occ::handle<Geom_Curve> (IGESToBRep_TopoCurve::*)(const int) const>(&IGESToBRep_TopoCurve::Curve), nb::arg("num") = static_cast<std::decay_t<const int>>(1), R"nbdoc(Returns a Curve given its rank, by default the first one
(null Curvee if out of range) in "TheCurves")nbdoc")
        .def("Approx2dBSplineCurve", static_cast<void (IGESToBRep_TopoCurve::*)(const occ::handle<Geom2d_BSplineCurve> &)>(&IGESToBRep_TopoCurve::Approx2dBSplineCurve), nb::arg("start").none())
        .def("NbCurves2d", static_cast<int (IGESToBRep_TopoCurve::*)() const>(&IGESToBRep_TopoCurve::NbCurves2d), R"nbdoc(Returns the count of Curves in "TheCurves2d")nbdoc")
        .def("Curve2d", static_cast<occ::handle<Geom2d_Curve> (IGESToBRep_TopoCurve::*)(const int) const>(&IGESToBRep_TopoCurve::Curve2d), nb::arg("num") = static_cast<std::decay_t<const int>>(1), R"nbdoc(Returns a Curve given its rank, by default the first one
(null Curvee if out of range) in "TheCurves2d")nbdoc")
        .def("SetBadCase", static_cast<void (IGESToBRep_TopoCurve::*)(const bool)>(&IGESToBRep_TopoCurve::SetBadCase), nb::arg("value"), R"nbdoc(Sets TheBadCase flag)nbdoc")
        .def("BadCase", static_cast<bool (IGESToBRep_TopoCurve::*)() const>(&IGESToBRep_TopoCurve::BadCase), R"nbdoc(Returns TheBadCase flag)nbdoc");
    nb::implicitly_convertible<std::decay_t<const IGESToBRep_CurveAndSurface &>, IGESToBRep_TopoCurve>();
    nb::borrow<nb::class_<IGESToBRep_TopoSurface>>(m.attr("IGESToBRep_TopoSurface"))
        .def(nb::init<>(), R"nbdoc(Creates a tool TopoSurface ready to run, with
epsilons set to 1.E-04, TheModeTopo to True, the
optimization of the continuity to False.)nbdoc")
        .def(nb::init<const IGESToBRep_CurveAndSurface &>(), nb::arg("CS"), R"nbdoc(Creates a tool TopoSurface ready to run and sets its
fields as CS's.)nbdoc")
        .def(nb::init<const double, const double, const double, const bool, const bool, const bool>(), nb::arg("eps"), nb::arg("epsGeom"), nb::arg("epsCoeff"), nb::arg("mode"), nb::arg("modeapprox"), nb::arg("optimized"), R"nbdoc(Creates a tool TopoSurface ready to run.)nbdoc")
        .def("TransferTopoSurface", static_cast<TopoDS_Shape (IGESToBRep_TopoSurface::*)(const occ::handle<IGESData_IGESEntity> &)>(&IGESToBRep_TopoSurface::TransferTopoSurface), nb::arg("start").none())
        .def("TransferTopoBasicSurface", static_cast<TopoDS_Shape (IGESToBRep_TopoSurface::*)(const occ::handle<IGESData_IGESEntity> &)>(&IGESToBRep_TopoSurface::TransferTopoBasicSurface), nb::arg("start").none())
        .def("TransferRuledSurface", static_cast<TopoDS_Shape (IGESToBRep_TopoSurface::*)(const occ::handle<IGESGeom_RuledSurface> &)>(&IGESToBRep_TopoSurface::TransferRuledSurface), nb::arg("start").none())
        .def("TransferSurfaceOfRevolution", static_cast<TopoDS_Shape (IGESToBRep_TopoSurface::*)(const occ::handle<IGESGeom_SurfaceOfRevolution> &)>(&IGESToBRep_TopoSurface::TransferSurfaceOfRevolution), nb::arg("start").none())
        .def("TransferTabulatedCylinder", static_cast<TopoDS_Shape (IGESToBRep_TopoSurface::*)(const occ::handle<IGESGeom_TabulatedCylinder> &)>(&IGESToBRep_TopoSurface::TransferTabulatedCylinder), nb::arg("start").none())
        .def("TransferOffsetSurface", static_cast<TopoDS_Shape (IGESToBRep_TopoSurface::*)(const occ::handle<IGESGeom_OffsetSurface> &)>(&IGESToBRep_TopoSurface::TransferOffsetSurface), nb::arg("start").none())
        .def("TransferTrimmedSurface", static_cast<TopoDS_Shape (IGESToBRep_TopoSurface::*)(const occ::handle<IGESGeom_TrimmedSurface> &)>(&IGESToBRep_TopoSurface::TransferTrimmedSurface), nb::arg("start").none())
        .def("TransferBoundedSurface", static_cast<TopoDS_Shape (IGESToBRep_TopoSurface::*)(const occ::handle<IGESGeom_BoundedSurface> &)>(&IGESToBRep_TopoSurface::TransferBoundedSurface), nb::arg("start").none())
        .def("TransferPlane", static_cast<TopoDS_Shape (IGESToBRep_TopoSurface::*)(const occ::handle<IGESGeom_Plane> &)>(&IGESToBRep_TopoSurface::TransferPlane), nb::arg("start").none())
        .def("TransferPerforate", static_cast<TopoDS_Shape (IGESToBRep_TopoSurface::*)(const occ::handle<IGESBasic_SingleParent> &)>(&IGESToBRep_TopoSurface::TransferPerforate), nb::arg("start").none())
        .def("ParamSurface", [](IGESToBRep_TopoSurface &self, const occ::handle<IGESData_IGESEntity> & start, gp_Trsf2d & trans) { double uFact{}; auto nanoocp_result = self.ParamSurface(start, trans, uFact); return std::make_tuple(nanoocp_result, uFact); }, nb::arg("start").none(), nb::arg("trans"));
    nanoocp_implicit_copy_ctor<IGESToBRep_TopoSurface>(nb::borrow<nb::class_<IGESToBRep_TopoSurface>>(m.attr("IGESToBRep_TopoSurface")));
    nb::implicitly_convertible<std::decay_t<const IGESToBRep_CurveAndSurface &>, IGESToBRep_TopoSurface>();
}

void nanoocp_conversions_IGESToBRep(nb::module_ &m) {
}
