cmake_minimum_required(VERSION 3.20)
project(nanoocp_poc LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
find_package(Python 3.12 COMPONENTS Interpreter Development.Module Development.SABIModule REQUIRED)
execute_process(COMMAND ${Python_EXECUTABLE} -m nanobind --cmake_dir OUTPUT_STRIP_TRAILING_WHITESPACE OUTPUT_VARIABLE nanobind_ROOT)
find_package(nanobind CONFIG REQUIRED)
find_package(OpenCASCADE REQUIRED PATHS ${CMAKE_CURRENT_SOURCE_DIR}/../deps/occt-8.0.1/lib/cmake/opencascade NO_DEFAULT_PATH)
nanobind_add_module(nanoocp_poc STABLE_ABI NB_DOMAIN nanoocp poc.cpp)
target_link_libraries(nanoocp_poc PRIVATE TKernel TKMath TKG3d TKBRep TKPrim TKTopAlgo TKDESTEP TKXSBase TKService TKV3d)
