"""OCCT package AppBlend (toolkit TKGeomAlgo)"""

import nanoocp.NCollection
import nanoocp.gp


class AppBlend_Approx:
    """Bspline approximation of a surface."""

    def IsDone(self) -> bool: ...

    def SurfShape(self) -> tuple[int, int, int, int, int, int]: ...

    def Surface(self, TPoles: nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt], TWeights: nanoocp.NCollection.NCollection_Array2[float], TUKnots: nanoocp.NCollection.NCollection_Array1[float], TVKnots: nanoocp.NCollection.NCollection_Array1[float], TUMults: nanoocp.NCollection.NCollection_Array1[int], TVMults: nanoocp.NCollection.NCollection_Array1[int]) -> None: ...

    def UDegree(self) -> int: ...

    def VDegree(self) -> int: ...

    def SurfPoles(self) -> nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]: ...

    def SurfWeights(self) -> nanoocp.NCollection.NCollection_Array2[float]: ...

    def SurfUKnots(self) -> nanoocp.NCollection.NCollection_Array1[float]: ...

    def SurfVKnots(self) -> nanoocp.NCollection.NCollection_Array1[float]: ...

    def SurfUMults(self) -> nanoocp.NCollection.NCollection_Array1[int]: ...

    def SurfVMults(self) -> nanoocp.NCollection.NCollection_Array1[int]: ...

    def NbCurves2d(self) -> int: ...

    def Curves2dShape(self) -> tuple[int, int, int]: ...

    def Curve2d(self, Index: int, TPoles: nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d], TKnots: nanoocp.NCollection.NCollection_Array1[float], TMults: nanoocp.NCollection.NCollection_Array1[int]) -> None: ...

    def Curves2dDegree(self) -> int: ...

    def Curve2dPoles(self, Index: int) -> nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]: ...

    def Curves2dKnots(self) -> nanoocp.NCollection.NCollection_Array1[float]: ...

    def Curves2dMults(self) -> nanoocp.NCollection.NCollection_Array1[int]: ...

    def TolReached(self) -> tuple[float, float]: ...

    def TolCurveOnSurf(self, Index: int) -> float: ...
