"""OCCT package FSD (toolkit TKernel)"""

from typing import TextIO, overload

import nanoocp.NCollection
import nanoocp.Standard
import nanoocp.Storage
import nanoocp.TCollection


class FSD_Base64:
    """Tool for encoding/decoding base64 stream."""

    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, theOther: FSD_Base64) -> None: ...

    @staticmethod
    def Decode(theStr: str, theLen: int) -> nanoocp.NCollection.NCollection_Buffer:
        """
        Function decoding base64 string.
        @param[in] theStr the input encoded string
        @param[in] theLen the length of input encoded string
        @return null handle in case of out of memory condition
        """

class FSD_FileHeader:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, theOther: FSD_FileHeader) -> None: ...

    @property
    def testindian(self) -> int: ...

    @testindian.setter
    def testindian(self, arg: int, /) -> None: ...

    @property
    def binfo(self) -> int: ...

    @binfo.setter
    def binfo(self, arg: int, /) -> None: ...

    @property
    def einfo(self) -> int: ...

    @einfo.setter
    def einfo(self, arg: int, /) -> None: ...

    @property
    def bcomment(self) -> int: ...

    @bcomment.setter
    def bcomment(self, arg: int, /) -> None: ...

    @property
    def ecomment(self) -> int: ...

    @ecomment.setter
    def ecomment(self, arg: int, /) -> None: ...

    @property
    def btype(self) -> int: ...

    @btype.setter
    def btype(self, arg: int, /) -> None: ...

    @property
    def etype(self) -> int: ...

    @etype.setter
    def etype(self, arg: int, /) -> None: ...

    @property
    def broot(self) -> int: ...

    @broot.setter
    def broot(self, arg: int, /) -> None: ...

    @property
    def eroot(self) -> int: ...

    @eroot.setter
    def eroot(self, arg: int, /) -> None: ...

    @property
    def bref(self) -> int: ...

    @bref.setter
    def bref(self, arg: int, /) -> None: ...

    @property
    def eref(self) -> int: ...

    @eref.setter
    def eref(self, arg: int, /) -> None: ...

    @property
    def bdata(self) -> int: ...

    @bdata.setter
    def bdata(self, arg: int, /) -> None: ...

    @property
    def edata(self) -> int: ...

    @edata.setter
    def edata(self, arg: int, /) -> None: ...

class FSD_BinaryFile(nanoocp.Storage.Storage_BaseDriver):
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, theOther: FSD_BinaryFile) -> None: ...

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

    def Open(self, aName: nanoocp.TCollection.TCollection_AsciiString, aMode: nanoocp.Storage.Storage_OpenMode) -> nanoocp.Storage.Storage_Error: ...

    def IsEnd(self) -> bool: ...

    def Tell(self) -> int:
        """return position in the file. Return -1 upon error."""

    @staticmethod
    def IsGoodFileType(aName: nanoocp.TCollection.TCollection_AsciiString) -> nanoocp.Storage.Storage_Error: ...

    def BeginWriteInfoSection(self) -> nanoocp.Storage.Storage_Error: ...

    @staticmethod
    def WriteInfo_s(nbObj: int, dbVersion: nanoocp.TCollection.TCollection_AsciiString, date: nanoocp.TCollection.TCollection_AsciiString, schemaName: nanoocp.TCollection.TCollection_AsciiString, schemaVersion: nanoocp.TCollection.TCollection_AsciiString, appName: nanoocp.TCollection.TCollection_ExtendedString, appVersion: nanoocp.TCollection.TCollection_AsciiString, objectType: nanoocp.TCollection.TCollection_ExtendedString, userInfo: nanoocp.NCollection.NCollection_Sequence[nanoocp.TCollection.TCollection_AsciiString], theOnlyCount: bool = False) -> tuple[int, object]: ...

    def WriteInfo(self, nbObj: int, dbVersion: nanoocp.TCollection.TCollection_AsciiString, date: nanoocp.TCollection.TCollection_AsciiString, schemaName: nanoocp.TCollection.TCollection_AsciiString, schemaVersion: nanoocp.TCollection.TCollection_AsciiString, appName: nanoocp.TCollection.TCollection_ExtendedString, appVersion: nanoocp.TCollection.TCollection_AsciiString, objectType: nanoocp.TCollection.TCollection_ExtendedString, userInfo: nanoocp.NCollection.NCollection_Sequence[nanoocp.TCollection.TCollection_AsciiString]) -> None: ...

    def EndWriteInfoSection(self) -> nanoocp.Storage.Storage_Error: ...

    def EndWriteInfoSection__str(self) -> tuple[nanoocp.Storage.Storage_Error, object]:
        """
        EndWriteInfoSection__str: the C++ overload EndWriteInfoSection(Standard_OStream &); the suffix lists its returned out-parameters (nanoOCP R-COLLISION).
        """

    def BeginReadInfoSection(self) -> nanoocp.Storage.Storage_Error: ...

    def ReadInfo(self, dbVersion: nanoocp.TCollection.TCollection_AsciiString, date: nanoocp.TCollection.TCollection_AsciiString, schemaName: nanoocp.TCollection.TCollection_AsciiString, schemaVersion: nanoocp.TCollection.TCollection_AsciiString, appName: nanoocp.TCollection.TCollection_ExtendedString, appVersion: nanoocp.TCollection.TCollection_AsciiString, objectType: nanoocp.TCollection.TCollection_ExtendedString, userInfo: nanoocp.NCollection.NCollection_Sequence[nanoocp.TCollection.TCollection_AsciiString]) -> int: ...

    def ReadCompleteInfo(self, theIStream: TextIO, theData: nanoocp.Storage.Storage_Data | None) -> nanoocp.Storage.Storage_Data: ...

    def EndReadInfoSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginWriteCommentSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginWriteCommentSection__str(self) -> tuple[nanoocp.Storage.Storage_Error, object]:
        """
        BeginWriteCommentSection__str: the C++ overload BeginWriteCommentSection(Standard_OStream &); the suffix lists its returned out-parameters (nanoOCP R-COLLISION).
        """

    def WriteComment(self, userComments: nanoocp.NCollection.NCollection_Sequence[nanoocp.TCollection.TCollection_ExtendedString]) -> None: ...

    @staticmethod
    def WriteComment_s(theComments: nanoocp.NCollection.NCollection_Sequence[nanoocp.TCollection.TCollection_ExtendedString], theOnlyCount: bool = False) -> tuple[int, object]: ...

    def EndWriteCommentSection(self) -> nanoocp.Storage.Storage_Error: ...

    def EndWriteCommentSection__str(self) -> tuple[nanoocp.Storage.Storage_Error, object]:
        """
        EndWriteCommentSection__str: the C++ overload EndWriteCommentSection(Standard_OStream &); the suffix lists its returned out-parameters (nanoOCP R-COLLISION).
        """

    def BeginReadCommentSection(self) -> nanoocp.Storage.Storage_Error: ...

    def ReadComment(self, userComments: nanoocp.NCollection.NCollection_Sequence[nanoocp.TCollection.TCollection_ExtendedString]) -> None: ...

    @staticmethod
    def ReadComment_s(theIStream: TextIO, userComments: nanoocp.NCollection.NCollection_Sequence[nanoocp.TCollection.TCollection_ExtendedString]) -> None: ...

    def EndReadCommentSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginWriteTypeSection(self) -> nanoocp.Storage.Storage_Error: ...

    def SetTypeSectionSize(self, aSize: int) -> None: ...

    def WriteTypeInformations(self, typeNum: int, typeName: nanoocp.TCollection.TCollection_AsciiString) -> None: ...

    def EndWriteTypeSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginReadTypeSection(self) -> nanoocp.Storage.Storage_Error: ...

    def TypeSectionSize(self) -> int: ...

    @staticmethod
    def TypeSectionSize_s(theIStream: TextIO) -> int: ...

    def ReadTypeInformations(self, typeName: nanoocp.TCollection.TCollection_AsciiString) -> int: ...

    @staticmethod
    def ReadTypeInformations_s(theIStream: TextIO, typeName: nanoocp.TCollection.TCollection_AsciiString) -> int: ...

    def EndReadTypeSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginWriteRootSection(self) -> nanoocp.Storage.Storage_Error: ...

    def SetRootSectionSize(self, aSize: int) -> None: ...

    def WriteRoot(self, rootName: nanoocp.TCollection.TCollection_AsciiString, aRef: int, aType: nanoocp.TCollection.TCollection_AsciiString) -> None: ...

    def EndWriteRootSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginReadRootSection(self) -> nanoocp.Storage.Storage_Error: ...

    def RootSectionSize(self) -> int: ...

    @staticmethod
    def RootSectionSize_s(theIStream: TextIO) -> int: ...

    def ReadRoot(self, rootName: nanoocp.TCollection.TCollection_AsciiString, aType: nanoocp.TCollection.TCollection_AsciiString) -> int: ...

    @staticmethod
    def ReadRoot_s(theIStream: TextIO, rootName: nanoocp.TCollection.TCollection_AsciiString, aType: nanoocp.TCollection.TCollection_AsciiString) -> int: ...

    def EndReadRootSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginWriteRefSection(self) -> nanoocp.Storage.Storage_Error: ...

    def SetRefSectionSize(self, aSize: int) -> None: ...

    def WriteReferenceType(self, reference: int, typeNum: int) -> None: ...

    def EndWriteRefSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginReadRefSection(self) -> nanoocp.Storage.Storage_Error: ...

    def RefSectionSize(self) -> int: ...

    @staticmethod
    def RefSectionSize_s(theIStream: TextIO) -> int: ...

    def ReadReferenceType(self) -> tuple[int, int]: ...

    @staticmethod
    def ReadReferenceType_s(theIStream: TextIO) -> tuple[int, int]: ...

    def EndReadRefSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginWriteDataSection(self) -> nanoocp.Storage.Storage_Error: ...

    def WritePersistentObjectHeader(self, aRef: int, aType: int) -> None: ...

    def BeginWritePersistentObjectData(self) -> None: ...

    def BeginWriteObjectData(self) -> None: ...

    def EndWriteObjectData(self) -> None: ...

    def EndWritePersistentObjectData(self) -> None: ...

    def EndWriteDataSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginReadDataSection(self) -> nanoocp.Storage.Storage_Error: ...

    def ReadPersistentObjectHeader(self) -> tuple[int, int]: ...

    def BeginReadPersistentObjectData(self) -> None: ...

    def BeginReadObjectData(self) -> None: ...

    def EndReadObjectData(self) -> None: ...

    def EndReadPersistentObjectData(self) -> None: ...

    def EndReadDataSection(self) -> nanoocp.Storage.Storage_Error: ...

    def SkipObject(self) -> None: ...

    def PutReference(self, aValue: int) -> nanoocp.Storage.Storage_BaseDriver: ...

    def PutCharacter(self, aValue: str) -> nanoocp.Storage.Storage_BaseDriver: ...

    def PutExtCharacter(self, aValue: str) -> nanoocp.Storage.Storage_BaseDriver: ...

    @staticmethod
    def PutInteger_s(aValue: int, theOnlyCount: bool = False) -> tuple[int, object]: ...

    def PutInteger(self, aValue: int) -> nanoocp.Storage.Storage_BaseDriver: ...

    def PutBoolean(self, aValue: bool) -> nanoocp.Storage.Storage_BaseDriver: ...

    def PutReal(self, aValue: float) -> nanoocp.Storage.Storage_BaseDriver: ...

    def PutShortReal(self, aValue: float) -> nanoocp.Storage.Storage_BaseDriver: ...

    def GetReference(self) -> tuple[nanoocp.Storage.Storage_BaseDriver, int]: ...

    def GetCharacter(self) -> tuple[nanoocp.Storage.Storage_BaseDriver, str]: ...

    @staticmethod
    def GetReference_s(theIStream: TextIO) -> int: ...

    def GetExtCharacter(self) -> tuple[nanoocp.Storage.Storage_BaseDriver, str]: ...

    def GetInteger(self) -> tuple[nanoocp.Storage.Storage_BaseDriver, int]: ...

    @staticmethod
    def GetInteger_s(theIStream: TextIO) -> int: ...

    def GetBoolean(self) -> tuple[nanoocp.Storage.Storage_BaseDriver, bool]: ...

    def GetReal(self) -> tuple[nanoocp.Storage.Storage_BaseDriver, float]: ...

    def GetShortReal(self) -> tuple[nanoocp.Storage.Storage_BaseDriver, float]: ...

    def Close(self) -> nanoocp.Storage.Storage_Error: ...

    def Destroy(self) -> None: ...

    @staticmethod
    def InverseInt(theValue: int) -> int:
        """Inverse bytes in integer value"""

    @staticmethod
    def InverseExtChar(theValue: str) -> str:
        """Inverse bytes in extended character value"""

    @staticmethod
    def InverseReal(theValue: float) -> float:
        """Inverse bytes in real value"""

    @staticmethod
    def InverseShortReal(theValue: float) -> float:
        """Inverse bytes in short real value"""

    @staticmethod
    def InverseSize(theValue: int) -> int:
        """Inverse bytes in size value"""

    @staticmethod
    def InverseUint64(theValue: int) -> int:
        """Inverse bytes in 64bit unsigned int value"""

    @staticmethod
    def ReadHeader(theIStream: TextIO, theFileHeader: FSD_FileHeader) -> None: ...

    @staticmethod
    def ReadHeaderData(theIStream: TextIO, theHeaderData: nanoocp.Storage.Storage_HeaderData | None) -> None: ...

    @staticmethod
    def ReadString(theIStream: TextIO, buffer: nanoocp.TCollection.TCollection_AsciiString) -> None: ...

    @staticmethod
    def ReadExtendedString(theIStream: TextIO, buffer: nanoocp.TCollection.TCollection_ExtendedString) -> None: ...

    @staticmethod
    def WriteHeader(theHeader: FSD_FileHeader, theOnlyCount: bool = False) -> tuple[int, object]: ...

    @staticmethod
    def MagicNumber() -> str: ...

class FSD_File(nanoocp.Storage.Storage_BaseDriver):
    """
    A general driver which defines as a file, the
    physical container for data to be stored or retrieved.
    """

    def __init__(self) -> None:
        """
        Constructs a driver defining as a file, the physical
        container for data to be stored or retrieved.
        Use the function Open to give the name of the driven file.
        """

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

    def Open(self, aName: nanoocp.TCollection.TCollection_AsciiString, aMode: nanoocp.Storage.Storage_OpenMode) -> nanoocp.Storage.Storage_Error:
        """
        Assigns as aName the name of the file to be
        driven by this driver. aMode precises if the file is
        opened in read or write mode.
        The function returns Storage_VSOk if the file
        is opened correctly, or any other value of the
        Storage_Error enumeration which specifies the problem encountered.
        """

    def IsEnd(self) -> bool: ...

    def Tell(self) -> int:
        """return position in the file. Return -1 upon error."""

    @staticmethod
    def IsGoodFileType(aName: nanoocp.TCollection.TCollection_AsciiString) -> nanoocp.Storage.Storage_Error: ...

    def BeginWriteInfoSection(self) -> nanoocp.Storage.Storage_Error: ...

    def WriteInfo(self, nbObj: int, dbVersion: nanoocp.TCollection.TCollection_AsciiString, date: nanoocp.TCollection.TCollection_AsciiString, schemaName: nanoocp.TCollection.TCollection_AsciiString, schemaVersion: nanoocp.TCollection.TCollection_AsciiString, appName: nanoocp.TCollection.TCollection_ExtendedString, appVersion: nanoocp.TCollection.TCollection_AsciiString, objectType: nanoocp.TCollection.TCollection_ExtendedString, userInfo: nanoocp.NCollection.NCollection_Sequence[nanoocp.TCollection.TCollection_AsciiString]) -> None: ...

    def EndWriteInfoSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginReadInfoSection(self) -> nanoocp.Storage.Storage_Error: ...

    def ReadInfo(self, dbVersion: nanoocp.TCollection.TCollection_AsciiString, date: nanoocp.TCollection.TCollection_AsciiString, schemaName: nanoocp.TCollection.TCollection_AsciiString, schemaVersion: nanoocp.TCollection.TCollection_AsciiString, appName: nanoocp.TCollection.TCollection_ExtendedString, appVersion: nanoocp.TCollection.TCollection_AsciiString, objectType: nanoocp.TCollection.TCollection_ExtendedString, userInfo: nanoocp.NCollection.NCollection_Sequence[nanoocp.TCollection.TCollection_AsciiString]) -> int: ...

    def ReadCompleteInfo(self, theIStream: TextIO, theData: nanoocp.Storage.Storage_Data | None) -> nanoocp.Storage.Storage_Data: ...

    def EndReadInfoSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginWriteCommentSection(self) -> nanoocp.Storage.Storage_Error: ...

    def WriteComment(self, userComments: nanoocp.NCollection.NCollection_Sequence[nanoocp.TCollection.TCollection_ExtendedString]) -> None: ...

    def EndWriteCommentSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginReadCommentSection(self) -> nanoocp.Storage.Storage_Error: ...

    def ReadComment(self, userComments: nanoocp.NCollection.NCollection_Sequence[nanoocp.TCollection.TCollection_ExtendedString]) -> None: ...

    def EndReadCommentSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginWriteTypeSection(self) -> nanoocp.Storage.Storage_Error: ...

    def SetTypeSectionSize(self, aSize: int) -> None: ...

    def WriteTypeInformations(self, typeNum: int, typeName: nanoocp.TCollection.TCollection_AsciiString) -> None: ...

    def EndWriteTypeSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginReadTypeSection(self) -> nanoocp.Storage.Storage_Error: ...

    def TypeSectionSize(self) -> int: ...

    def ReadTypeInformations(self, typeName: nanoocp.TCollection.TCollection_AsciiString) -> int: ...

    def EndReadTypeSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginWriteRootSection(self) -> nanoocp.Storage.Storage_Error: ...

    def SetRootSectionSize(self, aSize: int) -> None: ...

    def WriteRoot(self, rootName: nanoocp.TCollection.TCollection_AsciiString, aRef: int, aType: nanoocp.TCollection.TCollection_AsciiString) -> None: ...

    def EndWriteRootSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginReadRootSection(self) -> nanoocp.Storage.Storage_Error: ...

    def RootSectionSize(self) -> int: ...

    def ReadRoot(self, rootName: nanoocp.TCollection.TCollection_AsciiString, aType: nanoocp.TCollection.TCollection_AsciiString) -> int: ...

    def EndReadRootSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginWriteRefSection(self) -> nanoocp.Storage.Storage_Error: ...

    def SetRefSectionSize(self, aSize: int) -> None: ...

    def WriteReferenceType(self, reference: int, typeNum: int) -> None: ...

    def EndWriteRefSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginReadRefSection(self) -> nanoocp.Storage.Storage_Error: ...

    def RefSectionSize(self) -> int: ...

    def ReadReferenceType(self) -> tuple[int, int]: ...

    def EndReadRefSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginWriteDataSection(self) -> nanoocp.Storage.Storage_Error: ...

    def WritePersistentObjectHeader(self, aRef: int, aType: int) -> None: ...

    def BeginWritePersistentObjectData(self) -> None: ...

    def BeginWriteObjectData(self) -> None: ...

    def EndWriteObjectData(self) -> None: ...

    def EndWritePersistentObjectData(self) -> None: ...

    def EndWriteDataSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginReadDataSection(self) -> nanoocp.Storage.Storage_Error: ...

    def ReadPersistentObjectHeader(self) -> tuple[int, int]: ...

    def BeginReadPersistentObjectData(self) -> None: ...

    def BeginReadObjectData(self) -> None: ...

    def EndReadObjectData(self) -> None: ...

    def EndReadPersistentObjectData(self) -> None: ...

    def EndReadDataSection(self) -> nanoocp.Storage.Storage_Error: ...

    def SkipObject(self) -> None: ...

    def PutReference(self, aValue: int) -> nanoocp.Storage.Storage_BaseDriver: ...

    def PutCharacter(self, aValue: str) -> nanoocp.Storage.Storage_BaseDriver: ...

    def PutExtCharacter(self, aValue: str) -> nanoocp.Storage.Storage_BaseDriver: ...

    def PutInteger(self, aValue: int) -> nanoocp.Storage.Storage_BaseDriver: ...

    def PutBoolean(self, aValue: bool) -> nanoocp.Storage.Storage_BaseDriver: ...

    def PutReal(self, aValue: float) -> nanoocp.Storage.Storage_BaseDriver: ...

    def PutShortReal(self, aValue: float) -> nanoocp.Storage.Storage_BaseDriver: ...

    def GetReference(self) -> tuple[nanoocp.Storage.Storage_BaseDriver, int]: ...

    def GetCharacter(self) -> tuple[nanoocp.Storage.Storage_BaseDriver, str]: ...

    def GetExtCharacter(self) -> tuple[nanoocp.Storage.Storage_BaseDriver, str]: ...

    def GetInteger(self) -> tuple[nanoocp.Storage.Storage_BaseDriver, int]: ...

    def GetBoolean(self) -> tuple[nanoocp.Storage.Storage_BaseDriver, bool]: ...

    def GetReal(self) -> tuple[nanoocp.Storage.Storage_BaseDriver, float]: ...

    def GetShortReal(self) -> tuple[nanoocp.Storage.Storage_BaseDriver, float]: ...

    def Close(self) -> nanoocp.Storage.Storage_Error:
        """
        Closes the file driven by this driver. This file was
        opened by the last call to the function Open.
        The function returns Storage_VSOk if the
        closure is correctly done, or any other value of
        the Storage_Error enumeration which specifies the problem encountered.
        """

    def Destroy(self) -> None: ...

    @staticmethod
    def MagicNumber() -> str: ...

class FSD_CmpFile(FSD_File):
    def __init__(self) -> None: ...

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

    def Open(self, aName: nanoocp.TCollection.TCollection_AsciiString, aMode: nanoocp.Storage.Storage_OpenMode) -> nanoocp.Storage.Storage_Error: ...

    @staticmethod
    def IsGoodFileType(aName: nanoocp.TCollection.TCollection_AsciiString) -> nanoocp.Storage.Storage_Error: ...

    def BeginWriteInfoSection(self) -> nanoocp.Storage.Storage_Error: ...

    def BeginReadInfoSection(self) -> nanoocp.Storage.Storage_Error: ...

    def WritePersistentObjectHeader(self, aRef: int, aType: int) -> None: ...

    def BeginWritePersistentObjectData(self) -> None: ...

    def BeginWriteObjectData(self) -> None: ...

    def EndWriteObjectData(self) -> None: ...

    def EndWritePersistentObjectData(self) -> None: ...

    def ReadPersistentObjectHeader(self) -> tuple[int, int]: ...

    def BeginReadPersistentObjectData(self) -> None: ...

    def BeginReadObjectData(self) -> None: ...

    def EndReadObjectData(self) -> None: ...

    def EndReadPersistentObjectData(self) -> None: ...

    def Destroy(self) -> None: ...

    @staticmethod
    def MagicNumber() -> str: ...
