"""OCCT package HeaderSection (toolkit TKDESTEP)"""

from typing import overload

import nanoocp.Interface
import nanoocp.NCollection
import nanoocp.Standard
import nanoocp.StepData
import nanoocp.TCollection


class HeaderSection:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, theOther: HeaderSection) -> None: ...

    @staticmethod
    def Protocol() -> HeaderSection_Protocol:
        """creates a Protocol"""

class HeaderSection_FileDescription(nanoocp.Standard.Standard_Transient):
    @overload
    def __init__(self) -> None:
        """Returns a FileDescription"""

    @overload
    def __init__(self, theOther: HeaderSection_FileDescription) -> None: ...

    def Init(self, aDescription: nanoocp.NCollection.NCollection_HArray1[nanoocp.TCollection.TCollection_HAsciiString] | None, aImplementationLevel: nanoocp.TCollection.TCollection_HAsciiString | None) -> None: ...

    def SetDescription(self, aDescription: nanoocp.NCollection.NCollection_HArray1[nanoocp.TCollection.TCollection_HAsciiString] | None) -> None: ...

    def Description(self) -> nanoocp.NCollection.NCollection_HArray1[nanoocp.TCollection.TCollection_HAsciiString]: ...

    def DescriptionValue(self, num: int) -> nanoocp.TCollection.TCollection_HAsciiString: ...

    def NbDescription(self) -> int: ...

    def SetImplementationLevel(self, aImplementationLevel: nanoocp.TCollection.TCollection_HAsciiString | None) -> None: ...

    def ImplementationLevel(self) -> nanoocp.TCollection.TCollection_HAsciiString: ...

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

class HeaderSection_FileName(nanoocp.Standard.Standard_Transient):
    @overload
    def __init__(self) -> None:
        """Returns a FileName"""

    @overload
    def __init__(self, theOther: HeaderSection_FileName) -> None: ...

    def Init(self, aName: nanoocp.TCollection.TCollection_HAsciiString | None, aTimeStamp: nanoocp.TCollection.TCollection_HAsciiString | None, aAuthor: nanoocp.NCollection.NCollection_HArray1[nanoocp.TCollection.TCollection_HAsciiString] | None, aOrganization: nanoocp.NCollection.NCollection_HArray1[nanoocp.TCollection.TCollection_HAsciiString] | None, aPreprocessorVersion: nanoocp.TCollection.TCollection_HAsciiString | None, aOriginatingSystem: nanoocp.TCollection.TCollection_HAsciiString | None, aAuthorisation: nanoocp.TCollection.TCollection_HAsciiString | None) -> None: ...

    def SetName(self, aName: nanoocp.TCollection.TCollection_HAsciiString | None) -> None: ...

    def Name(self) -> nanoocp.TCollection.TCollection_HAsciiString: ...

    def SetTimeStamp(self, aTimeStamp: nanoocp.TCollection.TCollection_HAsciiString | None) -> None: ...

    def TimeStamp(self) -> nanoocp.TCollection.TCollection_HAsciiString: ...

    def SetAuthor(self, aAuthor: nanoocp.NCollection.NCollection_HArray1[nanoocp.TCollection.TCollection_HAsciiString] | None) -> None: ...

    def Author(self) -> nanoocp.NCollection.NCollection_HArray1[nanoocp.TCollection.TCollection_HAsciiString]: ...

    def AuthorValue(self, num: int) -> nanoocp.TCollection.TCollection_HAsciiString: ...

    def NbAuthor(self) -> int: ...

    def SetOrganization(self, aOrganization: nanoocp.NCollection.NCollection_HArray1[nanoocp.TCollection.TCollection_HAsciiString] | None) -> None: ...

    def Organization(self) -> nanoocp.NCollection.NCollection_HArray1[nanoocp.TCollection.TCollection_HAsciiString]: ...

    def OrganizationValue(self, num: int) -> nanoocp.TCollection.TCollection_HAsciiString: ...

    def NbOrganization(self) -> int: ...

    def SetPreprocessorVersion(self, aPreprocessorVersion: nanoocp.TCollection.TCollection_HAsciiString | None) -> None: ...

    def PreprocessorVersion(self) -> nanoocp.TCollection.TCollection_HAsciiString: ...

    def SetOriginatingSystem(self, aOriginatingSystem: nanoocp.TCollection.TCollection_HAsciiString | None) -> None: ...

    def OriginatingSystem(self) -> nanoocp.TCollection.TCollection_HAsciiString: ...

    def SetAuthorisation(self, aAuthorisation: nanoocp.TCollection.TCollection_HAsciiString | None) -> None: ...

    def Authorisation(self) -> nanoocp.TCollection.TCollection_HAsciiString: ...

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

class HeaderSection_FileSchema(nanoocp.Standard.Standard_Transient):
    @overload
    def __init__(self) -> None:
        """Returns a FileSchema"""

    @overload
    def __init__(self, theOther: HeaderSection_FileSchema) -> None: ...

    def Init(self, aSchemaIdentifiers: nanoocp.NCollection.NCollection_HArray1[nanoocp.TCollection.TCollection_HAsciiString] | None) -> None: ...

    def SetSchemaIdentifiers(self, aSchemaIdentifiers: nanoocp.NCollection.NCollection_HArray1[nanoocp.TCollection.TCollection_HAsciiString] | None) -> None: ...

    def SchemaIdentifiers(self) -> nanoocp.NCollection.NCollection_HArray1[nanoocp.TCollection.TCollection_HAsciiString]: ...

    def SchemaIdentifiersValue(self, num: int) -> nanoocp.TCollection.TCollection_HAsciiString: ...

    def NbSchemaIdentifiers(self) -> int: ...

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

class HeaderSection_Protocol(nanoocp.StepData.StepData_Protocol):
    """
    Protocol for HeaderSection Entities
    It requires HeaderSection as a Resource
    """

    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, theOther: HeaderSection_Protocol) -> None: ...

    def TypeNumber(self, atype: nanoocp.Standard.Standard_Type | None) -> int:
        """Returns a Case Number for each of the HeaderSection Entities"""

    def SchemaName(self, arg0: nanoocp.Interface.Interface_InterfaceModel | None) -> str: ...

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...
