from typing import Generic, Self, TypeVar, overload
from collections.abc import Iterator
import nanoocp.Standard

_T = TypeVar('_T')
_K = TypeVar('_K')
_V = TypeVar('_V')

class _NCollection_Shared_members:
    """NCollection_Shared<T>: T made a Standard_Transient (handle-managed). The concrete instantiation
    derives from T's bound class, so T's API is available."""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theOther: object) -> None: ...
    def GetRefCount(self) -> int: ...
    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...
    def IsInstance(self, theTypeName: str) -> bool: ...
    def IsKind(self, theTypeName: str) -> bool: ...
    @staticmethod
    def get_type_name() -> str: ...
    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

class NCollection_Array1(Generic[_T]):
    """NCollection_Array1<T>: unidimensional array of fixed size with user-defined index range (OCCT).
    Instantiations are the concrete classes NCollection_Array1__<T>; NCollection_Array1[T] returns them."""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theLower: int, theUpper: int) -> None: ...
    @overload
    def __init__(self, theSize: int) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_Array1[_T]) -> None: ...
    def Init(self, theValue: _T) -> None: ...
    def Size(self) -> int: ...
    def Length(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Lower(self) -> int: ...
    def Upper(self) -> int: ...
    def IsDeletable(self) -> bool: ...
    def Assign(self, theOther: NCollection_Array1[_T]) -> Self: ...
    def CopyValues(self, theOther: NCollection_Array1[_T]) -> Self: ...
    def First(self) -> _T: ...
    def Last(self) -> _T: ...
    def Value(self, theIndex: int) -> _T: ...
    def At(self, theIndex: int) -> _T: ...
    def SetValue(self, theIndex: int, theItem: _T) -> None: ...
    def UpdateLowerBound(self, theLower: int) -> None: ...
    def UpdateUpperBound(self, theUpper: int) -> None: ...
    @overload
    def Resize(self, theLower: int, theUpper: int, theToCopyData: bool) -> None: ...
    @overload
    def Resize(self, theSize: int, theToCopyData: bool) -> None: ...
    def ChangeFirst(self) -> _T: ...
    def ChangeLast(self) -> _T: ...
    def ChangeValue(self, theIndex: int) -> _T: ...
    def ChangeAt(self, theIndex: int) -> _T: ...
    def __call__(self, theIndex: int) -> _T: ...
    def __getitem__(self, theIndex: int) -> _T: ...
    def __setitem__(self, theIndex: int, theItem: _T) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_T]: ...
class NCollection_Array2(NCollection_Array1[_T]):
    """NCollection_Array2<T>: 2D array with user-defined row/column ranges (OCCT); derives from NCollection_Array1."""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theRowLower: int, theRowUpper: int, theColLower: int, theColUpper: int) -> None: ...
    @overload
    def __init__(self, theNbRows: int, theNbCols: int) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_Array2[_T]) -> None: ...
    @staticmethod
    def BeginPosition(theRowLower: int, theRowUpper: int, theColLower: int, theColUpper: int) -> int: ...
    @staticmethod
    def LastPosition(theRowLower: int, theRowUpper: int, theColLower: int, theColUpper: int) -> int: ...
    def NbRows(self) -> int: ...
    def NbColumns(self) -> int: ...
    def RowLength(self) -> int: ...
    def ColLength(self) -> int: ...
    def LowerRow(self) -> int: ...
    def UpperRow(self) -> int: ...
    def LowerCol(self) -> int: ...
    def UpperCol(self) -> int: ...
    def UpdateLowerRow(self, theLowerRow: int) -> None: ...
    def UpdateLowerCol(self, theLowerCol: int) -> None: ...
    def UpdateUpperRow(self, theUpperRow: int) -> None: ...
    def UpdateUpperCol(self, theUpperCol: int) -> None: ...
    def Assign(self, theOther: NCollection_Array2[_T]) -> Self: ...  # type: ignore[override]
    def CopyValues(self, theOther: NCollection_Array2[_T]) -> Self: ...  # type: ignore[override]
    def Value(self, theRow: int, theCol: int) -> _T: ...  # type: ignore[override]
    def ChangeValue(self, theRow: int, theCol: int) -> _T: ...  # type: ignore[override]
    def SetValue(self, theRow: int, theCol: int, theItem: _T) -> None: ...  # type: ignore[override]
    def At(self, theRow: int, theCol: int) -> _T: ...  # type: ignore[override]
    def ChangeAt(self, theRow: int, theCol: int) -> _T: ...  # type: ignore[override]
    @overload
    def Resize(self, theRowLower: int, theRowUpper: int, theColLower: int, theColUpper: int, theToCopyData: bool) -> None: ...
    @overload
    def Resize(self, theNbRows: int, theNbCols: int, theToCopyData: bool) -> None: ...
    @overload
    def ResizeWithTrim(self, theRowLower: int, theRowUpper: int, theColLower: int, theColUpper: int, theToCopyData: bool) -> None: ...
    @overload
    def ResizeWithTrim(self, theNbRows: int, theNbCols: int, theToCopyData: bool) -> None: ...
    def __call__(self, theRow: int, theCol: int) -> _T: ...  # type: ignore[override]
    def __getitem__(self, theRowCol: tuple[int, int]) -> _T: ...  # type: ignore[override]
    def __setitem__(self, theRowCol: tuple[int, int], theItem: _T) -> None: ...  # type: ignore[override]
class NCollection_DataMap(Generic[_K, _V]):
    """NCollection_DataMap<Key, Item>: hashed map from keys to items (OCCT)."""
    class Iterator(Generic[_K, _V]):
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, theMap: NCollection_DataMap[_K, _V]) -> None: ...
        def Initialize(self, theMap: NCollection_DataMap[_K, _V]) -> None: ...
        def Reset(self) -> None: ...
        def More(self) -> bool: ...
        def Next(self) -> None: ...
        def Value(self) -> _V: ...
        def ChangeValue(self) -> _V: ...
        def Key(self) -> _K: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theNbBuckets: int, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None = None) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_DataMap[_K, _V]) -> None: ...
    def NbBuckets(self) -> int: ...
    def Extent(self) -> int: ...
    def Length(self) -> int: ...
    def Size(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Allocator(self) -> nanoocp.NCollection.NCollection_BaseAllocator: ...
    def Exchange(self, theOther: NCollection_DataMap[_K, _V]) -> None: ...
    def Assign(self, theOther: NCollection_DataMap[_K, _V]) -> Self: ...
    def ReSize(self, N: int) -> None: ...
    @overload
    def Clear(self, doReleaseMemory: bool = True) -> None: ...
    @overload
    def Clear(self, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None) -> None: ...
    def Bind(self, theKey: _K, theItem: _V) -> bool: ...
    def Bound(self, theKey: _K, theItem: _V) -> _V: ...
    def TryBind(self, theKey: _K, theItem: _V) -> bool: ...
    def TryBound(self, theKey: _K, theItem: _V) -> _V: ...
    def IsBound(self, theKey: _K) -> bool: ...
    def UnBind(self, theKey: _K) -> bool: ...
    def Seek(self, theKey: _K) -> _V | None: ...
    def ChangeSeek(self, theKey: _K) -> _V | None: ...
    @overload
    def Find(self, theKey: _K) -> _V: ...
    @overload
    def Find(self, theKey: _K, theValue: _V) -> bool: ...
    def ChangeFind(self, theKey: _K) -> _V: ...
    def __call__(self, theKey: _K) -> _V: ...
    def __contains__(self, theKey: _K) -> bool: ...
    def __getitem__(self, theKey: _K) -> _V: ...
    def __setitem__(self, theKey: _K, theItem: _V) -> None: ...
    def __delitem__(self, theKey: _K) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_K]: ...
    def items(self) -> list[tuple[_K, _V]]: ...
class NCollection_DoubleMap(Generic[_K, _V]):
    """NCollection_DoubleMap<Key1, Key2>: bidirectional hashed map (OCCT). _V stands for Key2."""
    class Iterator(Generic[_K, _V]):
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, theMap: NCollection_DoubleMap[_K, _V]) -> None: ...
        def Initialize(self, theMap: NCollection_DoubleMap[_K, _V]) -> None: ...
        def Reset(self) -> None: ...
        def More(self) -> bool: ...
        def Next(self) -> None: ...
        def Key1(self) -> _K: ...
        def Key2(self) -> _V: ...
        def Value(self) -> _V: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theNbBuckets: int, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None = None) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_DoubleMap[_K, _V]) -> None: ...
    def NbBuckets(self) -> int: ...
    def Extent(self) -> int: ...
    def Length(self) -> int: ...
    def Size(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Allocator(self) -> nanoocp.NCollection.NCollection_BaseAllocator: ...
    def Exchange(self, theOther: NCollection_DoubleMap[_K, _V]) -> None: ...
    def Assign(self, theOther: NCollection_DoubleMap[_K, _V]) -> Self: ...
    def ReSize(self, N: int) -> None: ...
    @overload
    def Clear(self, doReleaseMemory: bool = True) -> None: ...
    @overload
    def Clear(self, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None) -> None: ...
    def Bind(self, theKey1: _K, theKey2: _V) -> None: ...
    def TryBind(self, theKey1: _K, theKey2: _V) -> bool: ...
    def AreBound(self, theKey1: _K, theKey2: _V) -> bool: ...
    def IsBound1(self, theKey1: _K) -> bool: ...
    def IsBound2(self, theKey2: _V) -> bool: ...
    def UnBind1(self, theKey1: _K) -> bool: ...
    def UnBind2(self, theKey2: _V) -> bool: ...
    @overload
    def Find1(self, theKey1: _K) -> _V: ...
    @overload
    def Find1(self, theKey1: _K, theKey2: _V) -> bool: ...
    def Seek1(self, theKey1: _K) -> _V | None: ...
    @overload
    def Find2(self, theKey2: _V) -> _K: ...
    @overload
    def Find2(self, theKey2: _V, theKey1: _K) -> bool: ...
    def Seek2(self, theKey2: _V) -> _K | None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[tuple[_K, _V]]: ...
    def items(self) -> list[tuple[_K, _V]]: ...
class NCollection_DynamicArray(Generic[_T]):
    """NCollection_DynamicArray<T>: growable 0-based array (OCCT)."""
    @overload
    def __init__(self, theIncrement: int = 256) -> None: ...
    @overload
    def __init__(self, theIncrement: int, theAlloc: nanoocp.NCollection.NCollection_BaseAllocator | None) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_DynamicArray[_T]) -> None: ...
    def Size(self) -> int: ...
    def Length(self) -> int: ...
    def Lower(self) -> int: ...
    def Upper(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Assign(self, theOther: NCollection_DynamicArray[_T], theOwnAllocator: bool = True) -> Self: ...
    def Append(self, theValue: _T) -> _T: ...
    def InsertAfter(self, theIndex: int, theValue: _T) -> _T: ...
    def InsertBefore(self, theIndex: int, theValue: _T) -> _T: ...
    def EraseLast(self) -> None: ...
    def Appended(self) -> _T: ...
    def Value(self, theIndex: int) -> _T: ...
    def First(self) -> _T: ...
    def ChangeFirst(self) -> _T: ...
    def Last(self) -> _T: ...
    def ChangeLast(self) -> _T: ...
    def ChangeValue(self, theIndex: int) -> _T: ...
    def SetValue(self, theIndex: int, theValue: _T) -> _T: ...
    def Clear(self, theReleaseMemory: bool = False) -> None: ...
    def SetIncrement(self, theIncrement: int) -> None: ...
    def __call__(self, theIndex: int) -> _T: ...
    def __getitem__(self, theIndex: int) -> _T: ...
    def __setitem__(self, theIndex: int, theItem: _T) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_T]: ...
class NCollection_HArray1(NCollection_Array1[_T]):
    """NCollection_HArray1<T>: handle-managed (Standard_Transient) NCollection_Array1<T>. Bound with base
    NCollection_Array1 (offset-0 base); the Standard_Transient members are bound directly."""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theLower: int, theUpper: int) -> None: ...
    @overload
    def __init__(self, theLower: int, theUpper: int, theValue: _T) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_Array1[_T]) -> None: ...
    def Array1(self) -> NCollection_Array1[_T]: ...
    def ChangeArray1(self) -> Self: ...
    def GetRefCount(self) -> int: ...
    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...
    def IsInstance(self, theTypeName: str) -> bool: ...
    def IsKind(self, theTypeName: str) -> bool: ...
    @staticmethod
    def get_type_name() -> str: ...
    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...
class NCollection_HArray2(NCollection_Array2[_T]):
    """NCollection_HArray2<T>: handle-managed (Standard_Transient) NCollection_Array2<T>."""
    @overload
    def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
    @overload
    def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int, theValue: _T) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_Array2[_T]) -> None: ...
    def Array2(self) -> NCollection_Array2[_T]: ...
    def ChangeArray2(self) -> Self: ...
    def GetRefCount(self) -> int: ...
    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...
    def IsInstance(self, theTypeName: str) -> bool: ...
    def IsKind(self, theTypeName: str) -> bool: ...
    @staticmethod
    def get_type_name() -> str: ...
    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...
class NCollection_HSequence(NCollection_Sequence[_T]):
    """NCollection_HSequence<T>: handle-managed (Standard_Transient) NCollection_Sequence<T>."""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_Sequence[_T]) -> None: ...
    def Sequence(self) -> NCollection_Sequence[_T]: ...
    def ChangeSequence(self) -> Self: ...
    def GetRefCount(self) -> int: ...
    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...
    def IsInstance(self, theTypeName: str) -> bool: ...
    def IsKind(self, theTypeName: str) -> bool: ...
    @staticmethod
    def get_type_name() -> str: ...
    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...
class NCollection_IndexedDataMap(Generic[_K, _V]):
    """NCollection_IndexedDataMap<Key, Item>: hashed map with a stable 1-based index (OCCT)."""
    class Iterator(Generic[_K, _V]):
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, theMap: NCollection_IndexedDataMap[_K, _V]) -> None: ...
        def More(self) -> bool: ...
        def Next(self) -> None: ...
        def Value(self) -> _V: ...
        def ChangeValue(self) -> _V: ...
        def Key(self) -> _K: ...
        def Index(self) -> int: ...
        def IsEqual(self, theOther: NCollection_IndexedDataMap.Iterator[_K, _V]) -> bool: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theNbBuckets: int, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None = None) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_IndexedDataMap[_K, _V]) -> None: ...
    def NbBuckets(self) -> int: ...
    def Extent(self) -> int: ...
    def Length(self) -> int: ...
    def Size(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Allocator(self) -> nanoocp.NCollection.NCollection_BaseAllocator: ...
    def Exchange(self, theOther: NCollection_IndexedDataMap[_K, _V]) -> None: ...
    def Assign(self, theOther: NCollection_IndexedDataMap[_K, _V]) -> Self: ...
    def ReSize(self, N: int) -> None: ...
    @overload
    def Clear(self, doReleaseMemory: bool = True) -> None: ...
    @overload
    def Clear(self, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None) -> None: ...
    def Add(self, theKey: _K, theItem: _V) -> int: ...
    def TryBound(self, theKey: _K, theItem: _V) -> _V: ...
    def TryBind(self, theKey: _K, theItem: _V) -> bool: ...
    def Bind(self, theKey: _K, theItem: _V) -> bool: ...
    def Bound(self, theKey: _K, theItem: _V) -> _V: ...
    def Contains(self, theKey: _K) -> bool: ...
    def Substitute(self, theIndex: int, theKey: _K, theItem: _V) -> None: ...
    def Swap(self, theIndex1: int, theIndex2: int) -> None: ...
    def RemoveLast(self) -> None: ...
    def RemoveFromIndex(self, theIndex: int) -> None: ...
    def RemoveKey(self, theKey: _K) -> None: ...
    def FindKey(self, theIndex: int) -> _K: ...
    def FindFromIndex(self, theIndex: int) -> _V: ...
    def ChangeFromIndex(self, theIndex: int) -> _V: ...
    def FindIndex(self, theKey: _K) -> int: ...
    @overload
    def FindFromKey(self, theKey: _K) -> _V: ...
    @overload
    def FindFromKey(self, theKey: _K, theValue: _V) -> bool: ...
    def ChangeFromKey(self, theKey: _K) -> _V: ...
    def Seek(self, theKey: _K) -> _V | None: ...
    def ChangeSeek(self, theKey: _K) -> _V | None: ...
    def __call__(self, theIndex: int) -> _V: ...
    def __contains__(self, theKey: _K) -> bool: ...
    def __getitem__(self, theIndex: int) -> _V: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_K]: ...
    def items(self) -> list[tuple[_K, _V]]: ...
class NCollection_IndexedMap(Generic[_K]):
    """NCollection_IndexedMap<Key>: hashed set of keys with a stable 1-based index (OCCT)."""
    class Iterator(Generic[_K]):
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, theMap: NCollection_IndexedMap[_K]) -> None: ...
        def More(self) -> bool: ...
        def Next(self) -> None: ...
        def Value(self) -> _K: ...
        def Index(self) -> int: ...
        def IsEqual(self, theOther: NCollection_IndexedMap.Iterator[_K]) -> bool: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theNbBuckets: int, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None = None) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_IndexedMap[_K]) -> None: ...
    def NbBuckets(self) -> int: ...
    def Extent(self) -> int: ...
    def Length(self) -> int: ...
    def Size(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Allocator(self) -> nanoocp.NCollection.NCollection_BaseAllocator: ...
    def Exchange(self, theOther: NCollection_IndexedMap[_K]) -> None: ...
    def Assign(self, theOther: NCollection_IndexedMap[_K]) -> Self: ...
    def ReSize(self, N: int) -> None: ...
    @overload
    def Clear(self, doReleaseMemory: bool = True) -> None: ...
    @overload
    def Clear(self, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None) -> None: ...
    def Add(self, theKey: _K) -> int: ...
    def Added(self, theKey: _K) -> _K: ...
    def Contains(self, theKey: _K) -> bool: ...
    def Substitute(self, theIndex: int, theKey: _K) -> None: ...
    def Swap(self, theIndex1: int, theIndex2: int) -> None: ...
    def RemoveLast(self) -> None: ...
    def RemoveFromIndex(self, theIndex: int) -> None: ...
    def RemoveKey(self, theKey: _K) -> bool: ...
    def FindKey(self, theIndex: int) -> _K: ...
    def FindIndex(self, theKey: _K) -> int: ...
    def __call__(self, theIndex: int) -> _K: ...
    def __contains__(self, theKey: _K) -> bool: ...
    def __getitem__(self, theIndex: int) -> _K: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_K]: ...
class NCollection_List(Generic[_T]):
    """NCollection_List<T>: singly linked list (OCCT). NCollection_List[T] returns the bound instantiation."""
    class Iterator(Generic[_T]):
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, theList: NCollection_List[_T]) -> None: ...
        def Initialize(self, theList: NCollection_List[_T]) -> None: ...
        def More(self) -> bool: ...
        def Next(self) -> None: ...
        def Value(self) -> _T: ...
        def ChangeValue(self) -> _T: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_List[_T]) -> None: ...
    def Extent(self) -> int: ...
    def Length(self) -> int: ...
    def Size(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Allocator(self) -> nanoocp.NCollection.NCollection_BaseAllocator: ...
    def Assign(self, theOther: NCollection_List[_T]) -> Self: ...
    def Clear(self, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None = None) -> None: ...
    def First(self) -> _T: ...
    def Last(self) -> _T: ...
    @overload
    def Append(self, theItem: _T) -> _T: ...
    @overload
    def Append(self, theItem: _T, theIter: NCollection_List.Iterator[_T]) -> None: ...
    @overload
    def Append(self, theOther: NCollection_List[_T]) -> None: ...
    @overload
    def Prepend(self, theItem: _T) -> _T: ...
    @overload
    def Prepend(self, theOther: NCollection_List[_T]) -> None: ...
    def RemoveFirst(self) -> None: ...
    @overload
    def Remove(self, theIter: NCollection_List.Iterator[_T]) -> None: ...
    @overload
    def Remove(self, theObject: _T) -> bool: ...
    @overload
    def InsertBefore(self, theItem: _T, theIter: NCollection_List.Iterator[_T]) -> _T: ...
    @overload
    def InsertBefore(self, theOther: NCollection_List[_T], theIter: NCollection_List.Iterator[_T]) -> None: ...
    @overload
    def InsertAfter(self, theItem: _T, theIter: NCollection_List.Iterator[_T]) -> _T: ...
    @overload
    def InsertAfter(self, theOther: NCollection_List[_T], theIter: NCollection_List.Iterator[_T]) -> None: ...
    def Reverse(self) -> None: ...
    def Exchange(self, theOther: NCollection_List[_T]) -> None: ...
    def Contains(self, theObject: _T) -> bool: ...
    def __contains__(self, theObject: _T) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_T]: ...
class NCollection_Map(Generic[_K]):
    """NCollection_Map<Key>: hashed set of keys (OCCT)."""
    class Iterator(Generic[_K]):
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, theMap: NCollection_Map[_K]) -> None: ...
        def Initialize(self, theMap: NCollection_Map[_K]) -> None: ...
        def Reset(self) -> None: ...
        def More(self) -> bool: ...
        def Next(self) -> None: ...
        def Value(self) -> _K: ...
        def Key(self) -> _K: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theNbBuckets: int, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None = None) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_Map[_K]) -> None: ...
    def NbBuckets(self) -> int: ...
    def Extent(self) -> int: ...
    def Length(self) -> int: ...
    def Size(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Allocator(self) -> nanoocp.NCollection.NCollection_BaseAllocator: ...
    def Exchange(self, theOther: NCollection_Map[_K]) -> None: ...
    def Assign(self, theOther: NCollection_Map[_K]) -> Self: ...
    def ReSize(self, N: int) -> None: ...
    @overload
    def Clear(self, doReleaseMemory: bool = True) -> None: ...
    @overload
    def Clear(self, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None) -> None: ...
    def Add(self, theKey: _K) -> bool: ...
    def Added(self, theKey: _K) -> _K: ...
    @overload
    def Contains(self, theKey: _K) -> bool: ...
    @overload
    def Contains(self, theOther: NCollection_Map[_K]) -> bool: ...
    def Remove(self, theKey: _K) -> bool: ...
    def IsEqual(self, theOther: NCollection_Map[_K]) -> bool: ...
    def Union(self, theLeft: NCollection_Map[_K], theRight: NCollection_Map[_K]) -> None: ...
    def Unite(self, theOther: NCollection_Map[_K]) -> bool: ...
    def HasIntersection(self, theMap: NCollection_Map[_K]) -> bool: ...
    def Intersection(self, theLeft: NCollection_Map[_K], theRight: NCollection_Map[_K]) -> None: ...
    def Intersect(self, theOther: NCollection_Map[_K]) -> bool: ...
    def Subtraction(self, theLeft: NCollection_Map[_K], theRight: NCollection_Map[_K]) -> None: ...
    def Subtract(self, theOther: NCollection_Map[_K]) -> bool: ...
    def Difference(self, theLeft: NCollection_Map[_K], theRight: NCollection_Map[_K]) -> None: ...
    def Differ(self, theOther: NCollection_Map[_K]) -> bool: ...
    def __contains__(self, theKey: _K) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_K]: ...
class NCollection_Sequence(Generic[_T]):
    """NCollection_Sequence<T>: doubly linked, 1-based indexed sequence (OCCT)."""
    class Iterator(Generic[_T]):
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, theSeq: NCollection_Sequence[_T], isStart: bool = True) -> None: ...
        def More(self) -> bool: ...
        def Next(self) -> None: ...
        def Value(self) -> _T: ...
        def ChangeValue(self) -> _T: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_Sequence[_T]) -> None: ...
    def Length(self) -> int: ...
    def Size(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Lower(self) -> int: ...
    def Upper(self) -> int: ...
    def Allocator(self) -> nanoocp.NCollection.NCollection_BaseAllocator: ...
    def Reverse(self) -> None: ...
    def Exchange(self, I: int, J: int) -> None: ...
    def Clear(self, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None = None) -> None: ...
    def Assign(self, theOther: NCollection_Sequence[_T]) -> Self: ...
    @overload
    def Remove(self, thePosition: NCollection_Sequence.Iterator[_T]) -> None: ...
    @overload
    def Remove(self, theIndex: int) -> None: ...
    @overload
    def Remove(self, theFromIndex: int, theToIndex: int) -> None: ...
    @overload
    def Append(self, theItem: _T) -> None: ...
    @overload
    def Append(self, theSeq: NCollection_Sequence[_T]) -> None: ...
    @overload
    def Prepend(self, theItem: _T) -> None: ...
    @overload
    def Prepend(self, theSeq: NCollection_Sequence[_T]) -> None: ...
    @overload
    def InsertBefore(self, theIndex: int, theItem: _T) -> None: ...
    @overload
    def InsertBefore(self, theIndex: int, theSeq: NCollection_Sequence[_T]) -> None: ...
    @overload
    def InsertAfter(self, thePosition: NCollection_Sequence.Iterator[_T], theItem: _T) -> None: ...
    @overload
    def InsertAfter(self, theIndex: int, theSeq: NCollection_Sequence[_T]) -> None: ...
    @overload
    def InsertAfter(self, theIndex: int, theItem: _T) -> None: ...
    def Split(self, theIndex: int, theSeq: NCollection_Sequence[_T]) -> None: ...
    def First(self) -> _T: ...
    def Last(self) -> _T: ...
    def ChangeFirst(self) -> _T: ...
    def ChangeLast(self) -> _T: ...
    def Value(self, theIndex: int) -> _T: ...
    def ChangeValue(self, theIndex: int) -> _T: ...
    def SetValue(self, theIndex: int, theItem: _T) -> None: ...
    def At(self, theIndex: int) -> _T: ...
    def ChangeAt(self, theIndex: int) -> _T: ...
    def __call__(self, theIndex: int) -> _T: ...
    def __getitem__(self, theIndex: int) -> _T: ...
    def __setitem__(self, theIndex: int, theItem: _T) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_T]: ...
class _NCollection_Shared_template:
    """NCollection_Shared[T] -> the bound NCollection_Shared<T> class (derives from T)."""
    @overload
    def __getitem__(self, item: type[NCollection_Map[int]]) -> type[NCollection_Shared__NCollection_Map__int]: ...
    @overload
    def __getitem__(self, item: type) -> type: ...

NCollection_Shared: _NCollection_Shared_template


"""OCCT package NCollection (toolkit TKernel)"""

from collections.abc import Iterator
import enum
from typing import overload

import nanoocp.Bnd
import nanoocp.Message
import nanoocp.Poly
import nanoocp.Standard
import nanoocp.Storage
import nanoocp.TCollection
import nanoocp.Units
import nanoocp.gp


class NCollection_CellFilter_Action(enum.IntEnum):
    """Auxiliary enumeration serving as response from method Inspect"""

    CellFilter_Keep = 0

    CellFilter_Purge = 1

class NCollection_BaseAllocator(nanoocp.Standard.Standard_Transient):
    """
    Purpose:     Basic class for memory allocation wizards.
    Defines  the  interface  for devising  different  allocators
    firstly to be used  by collections of NCollection, though it
    it is not  deferred. It allocates/frees  the memory  through
    Standard procedures, thus it is  unnecessary (and  sometimes
    injurious) to have  more than one such  allocator.  To avoid
    creation  of multiple  objects the  constructors  were  maid
    inaccessible.  To  create the  BaseAllocator use  the method
    CommonBaseAllocator.
    Note that this object is managed by Handle.
    """

    @staticmethod
    def CommonBaseAllocator() -> NCollection_BaseAllocator:
        """
        CommonBaseAllocator
        This method is designed to have the only one BaseAllocator (to avoid
        useless copying of collections). However one can use operator new to
        create more BaseAllocators, but it is injurious.
        """

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

class NCollection_ListNode:
    """
    Purpose:     This class is used to  represent a node  in the BaseList and
    BaseMap.
    """

    def Next(self) -> NCollection_ListNode:
        """Next pointer const access"""

class NCollection_BaseMap:
    """
    Purpose:     This is a base class for all Maps:
    Map
    DataMap
    DoubleMap
    IndexedMap
    IndexedDataMap
    Provides utilitites for managing the buckets.
    """

    def NbBuckets(self) -> int:
        """NbBuckets"""

    def Extent(self) -> int:
        """Extent (number of elements, legacy int-returning API)."""

    def Length(self) -> int:
        """
        Length - number of elements (legacy int-returning API, synonym of Extent()).
        """

    def Size(self) -> int:
        """Size - number of elements."""

    def IsEmpty(self) -> bool:
        """IsEmpty"""

    def Allocator(self) -> NCollection_BaseAllocator:
        """Returns attached allocator"""

class NCollection_DefaultHasher__bool:
    """Explicit specialization for bool."""

    def __init__(self) -> None: ...

    @overload
    def __call__(self, theKey: bool) -> int: ...

    @overload
    def __call__(self, theK1: bool, theK2: bool) -> bool: ...

class NCollection_DefaultHasher__char:
    """Explicit specialization for char."""

    def __init__(self) -> None: ...

    @overload
    def __call__(self, theKey: str) -> int: ...

    @overload
    def __call__(self, theK1: str, theK2: str) -> bool: ...

class NCollection_DefaultHasher__signed_char:
    """Explicit specialization for signed char."""

    def __init__(self) -> None: ...

    @overload
    def __call__(self, theKey: int) -> int: ...

    @overload
    def __call__(self, theK1: int, theK2: int) -> bool: ...

class NCollection_DefaultHasher__unsigned_char:
    """Explicit specialization for unsigned char."""

    def __init__(self) -> None: ...

    @overload
    def __call__(self, theKey: int) -> int: ...

    @overload
    def __call__(self, theK1: int, theK2: int) -> bool: ...

class NCollection_DefaultHasher__wchar_t:
    """Explicit specialization for wchar_t."""

    def __init__(self) -> None: ...

    @overload
    def __call__(self, theKey: "wchar_t") -> int: ...

    @overload
    def __call__(self, theK1: "wchar_t", theK2: "wchar_t") -> bool: ...

class NCollection_DefaultHasher__char16_t:
    """Explicit specialization for char16_t."""

    def __init__(self) -> None: ...

    @overload
    def __call__(self, theKey: "char16_t") -> int: ...

    @overload
    def __call__(self, theK1: "char16_t", theK2: "char16_t") -> bool: ...

class NCollection_DefaultHasher__char32_t:
    """Explicit specialization for char32_t."""

    def __init__(self) -> None: ...

    @overload
    def __call__(self, theKey: "char32_t") -> int: ...

    @overload
    def __call__(self, theK1: "char32_t", theK2: "char32_t") -> bool: ...

class NCollection_DefaultHasher__short:
    """Explicit specialization for short."""

    def __init__(self) -> None: ...

    @overload
    def __call__(self, theKey: int) -> int: ...

    @overload
    def __call__(self, theK1: int, theK2: int) -> bool: ...

class NCollection_DefaultHasher__int:
    """Explicit specialization for int."""

    def __init__(self) -> None: ...

    @overload
    def __call__(self, theKey: int) -> int: ...

    @overload
    def __call__(self, theK1: int, theK2: int) -> bool: ...

class NCollection_DefaultHasher__long:
    """Explicit specialization for long."""

    def __init__(self) -> None: ...

    @overload
    def __call__(self, theKey: int) -> int: ...

    @overload
    def __call__(self, theK1: int, theK2: int) -> bool: ...

class NCollection_DefaultHasher__long_long:
    """Explicit specialization for long long."""

    def __init__(self) -> None: ...

    @overload
    def __call__(self, theKey: int) -> int: ...

    @overload
    def __call__(self, theK1: int, theK2: int) -> bool: ...

class NCollection_DefaultHasher__unsigned_short:
    """Explicit specialization for unsigned short."""

    def __init__(self) -> None: ...

    @overload
    def __call__(self, theKey: int) -> int: ...

    @overload
    def __call__(self, theK1: int, theK2: int) -> bool: ...

class NCollection_DefaultHasher__unsigned_int:
    """Explicit specialization for unsigned int."""

    def __init__(self) -> None: ...

    @overload
    def __call__(self, theKey: int) -> int: ...

    @overload
    def __call__(self, theK1: int, theK2: int) -> bool: ...

class NCollection_DefaultHasher__unsigned_long:
    """Explicit specialization for unsigned long."""

    def __init__(self) -> None: ...

    @overload
    def __call__(self, theKey: int) -> int: ...

    @overload
    def __call__(self, theK1: int, theK2: int) -> bool: ...

class NCollection_DefaultHasher__unsigned_long_long:
    """Explicit specialization for unsigned long long."""

    def __init__(self) -> None: ...

    @overload
    def __call__(self, theKey: int) -> int: ...

    @overload
    def __call__(self, theK1: int, theK2: int) -> bool: ...

class NCollection_SeqNode:
    def Next(self) -> NCollection_SeqNode: ...

    def Previous(self) -> NCollection_SeqNode: ...

    def SetNext(self, theNext: NCollection_SeqNode) -> None: ...

    def SetPrevious(self, thePrev: NCollection_SeqNode) -> None: ...

class NCollection_BaseSequence:
    """
    Purpose:     This  is  a base  class  for  the  Sequence.  It  deals with
    an indexed bidirectional list of NCollection_SeqNode's.
    """

    def IsEmpty(self) -> bool: ...

    def Length(self) -> int:
        """Number of items (legacy int-returning API)."""

    def Size(self) -> int:
        """Size - number of items."""

    def Allocator(self) -> NCollection_BaseAllocator:
        """Returns attached allocator"""

class NCollection_AccAllocator(NCollection_BaseAllocator):
    """
    Class NCollection_AccAllocator - accumulating memory allocator. This
    class allocates memory on request returning the pointer to the allocated
    space. The allocation units are grouped in blocks requested from the
    system as required. This memory is returned to the system when all
    allocations in a block are freed.

    By comparison with the standard new() and malloc() calls, this method is
    faster and consumes very small additional memory to maintain the heap.

    By comparison with NCollection_IncAllocator, this class requires some more
    additional memory and a little more time for allocation and deallocation.
    Memory overhead for NCollection_IncAllocator is 12 bytes per block;
    average memory overhead for NCollection_AccAllocator is 28 bytes per block.

    All pointers returned by Allocate() are aligned to 4 byte boundaries.
    To define the sizeof memory blocks requested from the OS, use the
    parameter of the constructor (measured in bytes).
    """

    def __init__(self, theBlockSize: int = 24600) -> None:
        """Constructor"""

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

class NCollection_AlignedAllocator(NCollection_BaseAllocator):
    """NCollection allocator with managed memory alignment capabilities."""

    def __init__(self, theAlignment: int) -> None:
        """
        Constructor. The alignment should be specified explicitly:
        16 bytes for SSE instructions
        32 bytes for AVX instructions
        """

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

class NCollection_BaseList:
    def Extent(self) -> int: ...

    def Length(self) -> int:
        """
        Length - number of nodes (legacy int-returning API, synonym of Extent()).
        """

    def Size(self) -> int:
        """Size - number of nodes."""

    def IsEmpty(self) -> bool: ...

    def Allocator(self) -> NCollection_BaseAllocator:
        """Returns attached allocator"""

class NCollection_Buffer(nanoocp.Standard.Standard_Transient):
    """Low-level buffer object."""

    def IsEmpty(self) -> bool:
        """@return true if buffer is not allocated"""

    def Size(self) -> int:
        """Return buffer length in bytes."""

    def Allocator(self) -> NCollection_BaseAllocator:
        """@return buffer allocator"""

    def SetAllocator(self, theAlloc: NCollection_BaseAllocator) -> None:
        """Assign new buffer allocator with de-allocation of buffer."""

    def Allocate(self, theSize: int) -> bool:
        """
        Allocate the buffer.
        @param theSize buffer length in bytes
        """

    def Free(self) -> None:
        """De-allocate buffer."""

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

class NCollection_IncAllocator(NCollection_BaseAllocator):
    """
    Class NCollection_IncAllocator - incremental memory  allocator. This class
    allocates  memory  on  request  returning  the  pointer  to  an  allocated
    block. This memory is never returned  to the system until the allocator is
    destroyed.

    By comparison with  the standard new() and malloc()  calls, this method is
    faster and consumes very small additional memory to maintain the heap.

    All pointers  returned by Allocate() are  aligned to the size  of the data
    type "aligned_t". To  modify the size of memory  blocks requested from the
    OS,  use the parameter  of the  constructor (measured  in bytes);  if this
    parameter is  smaller than  25 bytes on  32bit or  49 bytes on  64bit, the
    block size will be the default 12 kbytes.

    It is not recommended  to use memory blocks  larger than 16KB  on  Windows
    platform  for the repeated operations  because  Low Fragmentation Heap  is
    not going to be  used  for  these  allocations  which  may lead  to memory
    fragmentation and the general performance slow down.

    Note that this allocator is most suitable for single-threaded algorithms
    (consider creating dedicated allocators per working thread),
    and thread-safety of allocations is DISABLED by default (see SetThreadSafe()).
    """

    def __init__(self, theBlockSize: int = 12288) -> None:
        """
        Constructor.
        Note that this constructor does NOT setup mutex for using allocator concurrently from
        different threads, see SetThreadSafe() method.

        The default size of the memory blocks is 12KB.
        It is not recommended to use memory blocks larger than 16KB on Windows
        platform for the repeated operations (and thus multiple allocations)
        because Low Fragmentation Heap is not going to be used for these allocations,
        leading to memory fragmentation and eventual performance slow down.
        """

    class IBlockSizeLevel(enum.Enum):
        """Description ability to next growing size each 5-th new block"""

        Min = 0

        Small = 1

        Medium = 2

        Large = 3

        Max = 4

    def SetThreadSafe(self, theIsThreadSafe: bool = True) -> None:
        """
        Setup mutex for thread-safe allocations.
        @warning Must not be called concurrently with Allocate/AllocateOptimal/Reset/clean
        on the same allocator instance; toggling the mutex while another thread
        holds a shared_lock on the fast path is undefined behaviour.
        """

    def Reset(self, theReleaseMemory: bool = False) -> None:
        """
        Re-initialize the allocator so that the next Allocate call should
        start allocating in the very beginning as though the allocator is just
        constructed. Warning: make sure that all previously allocated data are
        no more used in your code!
        @param theReleaseMemory
        True - release all previously allocated memory, False - preserve it
        for future allocations.
        """

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

class NCollection_ForwardRangeSentinel:
    """Empty sentinel type used as the end marker for range-for loops."""

    def __init__(self) -> None: ...

class NCollection_HeapAllocator(NCollection_BaseAllocator):
    """Allocator that uses the global dynamic heap (malloc / free)."""

    @staticmethod
    def GlobalHeapAllocator() -> NCollection_HeapAllocator: ...

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

class NCollection_SparseArrayBase:
    """
    Base class for NCollection_SparseArray;
    provides non-template implementation of general mechanics
    of block allocation, items creation / deletion etc.

    Type-specific item operations (construction, destruction, copy)
    are provided by the derived template class via function pointers
    passed as arguments to the protected methods.
    """

    def Size(self) -> int:
        """Returns number of currently contained items"""

    def HasValue(self, theIndex: int) -> bool:
        """Check whether the value at given index is set"""

class NCollection_WinHeapAllocator(NCollection_BaseAllocator):
    """
    This memory allocator creates dedicated heap for allocations.
    This technics available only on Windows platform
    (no alternative on Unix systems).
    It may be used to take control over memory fragmentation
    because on destruction ALL allocated memory will be released
    to the system.

    This allocator can also be created per each working thread
    however its real multi-threading performance is dubious.

    Notice that this also means that existing pointers will be broken
    and you should control that allocator is alive along all objects
    allocated with him.
    """

    def __init__(self, theInitSizeBytes: int = 524288) -> None:
        """Main constructor"""

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

class NCollection_IndexedDataMap__TCollection_AsciiString__Standard_DumpValue(NCollection_IndexedDataMap[nanoocp.TCollection.TCollection_AsciiString, nanoocp.Standard.Standard_DumpValue]): ...
class NCollection_IndexedDataMap__TCollection_AsciiString__TCollection_AsciiString(NCollection_IndexedDataMap[nanoocp.TCollection.TCollection_AsciiString, nanoocp.TCollection.TCollection_AsciiString]): ...
class NCollection_List__int(NCollection_List[int]): ...
class NCollection_Array1__Handle_Standard_Persistent(NCollection_Array1[nanoocp.Standard.Standard_Persistent]): ...
class NCollection_HArray1__Handle_Standard_Persistent(NCollection_HArray1[nanoocp.Standard.Standard_Persistent]): ...
class NCollection_Sequence__TCollection_AsciiString(NCollection_Sequence[nanoocp.TCollection.TCollection_AsciiString]): ...
class NCollection_HSequence__TCollection_AsciiString(NCollection_HSequence[nanoocp.TCollection.TCollection_AsciiString]): ...
class NCollection_Sequence__Handle_Storage_Root(NCollection_Sequence[nanoocp.Storage.Storage_Root]): ...
class NCollection_HSequence__Handle_Storage_Root(NCollection_HSequence[nanoocp.Storage.Storage_Root]): ...
class NCollection_Sequence__TCollection_ExtendedString(NCollection_Sequence[nanoocp.TCollection.TCollection_ExtendedString]): ...
class NCollection_DataMap__TCollection_AsciiString__TCollection_AsciiString(NCollection_DataMap[nanoocp.TCollection.TCollection_AsciiString, nanoocp.TCollection.TCollection_AsciiString]): ...
class NCollection_Sequence__int(NCollection_Sequence[int]): ...
class NCollection_HSequence__int(NCollection_HSequence[int]): ...
class NCollection_Sequence__Handle_TCollection_HAsciiString(NCollection_Sequence[nanoocp.TCollection.TCollection_HAsciiString]): ...
class NCollection_HSequence__Handle_TCollection_HAsciiString(NCollection_HSequence[nanoocp.TCollection.TCollection_HAsciiString]): ...
class NCollection_Sequence__Handle_Units_Quantity(NCollection_Sequence[nanoocp.Units.Units_Quantity]): ...
class NCollection_HSequence__Handle_Units_Quantity(NCollection_HSequence[nanoocp.Units.Units_Quantity]): ...
class NCollection_Sequence__Handle_Units_Token(NCollection_Sequence[nanoocp.Units.Units_Token]): ...
class NCollection_HSequence__Handle_Units_Token(NCollection_HSequence[nanoocp.Units.Units_Token]): ...
class NCollection_Sequence__Handle_Units_Unit(NCollection_Sequence[nanoocp.Units.Units_Unit]): ...
class NCollection_HSequence__Handle_Units_Unit(NCollection_HSequence[nanoocp.Units.Units_Unit]): ...
class NCollection_Array1__double(NCollection_Array1[float]): ...
class NCollection_Array2__double(NCollection_Array2[float]): ...
class NCollection_DataMap__TCollection_AsciiString__int(NCollection_DataMap[nanoocp.TCollection.TCollection_AsciiString, int]): ...
class NCollection_DataMap__int__double(NCollection_DataMap[int, float]): ...
class NCollection_DoubleMap__int__TCollection_AsciiString(NCollection_DoubleMap[int, nanoocp.TCollection.TCollection_AsciiString]): ...
class NCollection_DynamicArray__int(NCollection_DynamicArray[int]): ...
class NCollection_HArray2__double(NCollection_HArray2[float]): ...
class NCollection_IndexedMap__TCollection_AsciiString(NCollection_IndexedMap[nanoocp.TCollection.TCollection_AsciiString]): ...
class NCollection_Map__int(NCollection_Map[int]): ...
class NCollection_Sequence__Handle_Standard_Transient(NCollection_Sequence[nanoocp.Standard.Standard_Transient]): ...
class NCollection_Shared__NCollection_Map__int(nanoocp.NCollection.NCollection_Map__int, _NCollection_Shared_members): ...
class NCollection_Sequence__Handle_TCollection_HExtendedString(NCollection_Sequence[nanoocp.TCollection.TCollection_HExtendedString]): ...
class NCollection_HSequence__Handle_TCollection_HExtendedString(NCollection_HSequence[nanoocp.TCollection.TCollection_HExtendedString]): ...
class NCollection_IndexedMap__Message_MetricType(NCollection_IndexedMap[nanoocp.Message.Message_MetricType]): ...
class NCollection_List__Handle_Message_Alert(NCollection_List[nanoocp.Message.Message_Alert]): ...
class NCollection_Sequence__Handle_Message_Printer(NCollection_Sequence[nanoocp.Message.Message_Printer]): ...
class NCollection_Array1__gp_Pnt2d(NCollection_Array1[nanoocp.gp.gp_Pnt2d]): ...
class NCollection_Array1__gp_Pnt(NCollection_Array1[nanoocp.gp.gp_Pnt]): ...
class NCollection_Array1__int(NCollection_Array1[int]): ...
class NCollection_HArray1__double(NCollection_HArray1[float]): ...
class NCollection_HArray1__int(NCollection_HArray1[int]): ...
class NCollection_Array2__gp_Pnt(NCollection_Array2[nanoocp.gp.gp_Pnt]): ...
class NCollection_Array1__NCollection_Vec3__float:
    """
    The class NCollection_Array1 represents unidimensional arrays of fixed size known at run time.
    The range of the index is user defined.
    An array1 can be constructed with a "C array".
    This functionality is useful to call methods expecting an Array1.
    It allows to carry the bounds inside the arrays.

    Examples:
    @code
    Item tab[100]; // an example with a C array
    NCollection_Array1<Item> ttab (tab[0], 1, 100);

    NCollection_Array1<Item> tttab (ttab(10), 10, 20); // a slice of ttab
    @endcode
    If you want to reindex an array from 1 to Length do:
    @code
    NCollection_Array1<Item> tab1 (tab (tab.Lower()), 1, tab.Length());
    @endcode
    Warning: Programs client of such a class must be independent of the range of the first element.
    Then, a C++ for loop must be written like this
    @code
    for (i = A.Lower(); i <= A.Upper(); i++)
    @endcode

    Zero-based (size_t) construction mode:
    Use NCollection_Array1(size_t theSize) or NCollection_Array1(pointer, size_t) to create
    a zero-based array (Lower()==0). In this mode At()/ChangeAt() and STL iterators are the
    preferred access path - they address elements directly without any offset subtraction.
    Buffer-reuse variants do NOT own the memory and will not free it on destruction.
    @code
    int aBuffer[100];
    NCollection_Array1<int> aZero(100);      // allocates, lower=0
    NCollection_Array1<int> aWrap(aBuffer, 100); // wraps aBuffer, lower=0, not owner
    for (size_t i = 0; i < aWrap.Size(); ++i)
    aWrap.At(i) = static_cast<int>(i);
    @endcode
    """

    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, theLower: int, theUpper: int) -> None: ...

    @overload
    def __init__(self, theSize: int) -> None: ...

    @overload
    def __init__(self, theOther: NCollection_Array1__NCollection_Vec3__float) -> None:
        """
        Zero-based constructor from first element reference.
        When theUseBuffer is true, wraps contiguous storage starting at theBegin.
        Otherwise allocates own storage of theSize elements.
        """

    def Init(self, theValue: "NCollection_Vec3<float>") -> None:
        """Initialise the items with theValue"""

    def Size(self) -> int:
        """Size query."""

    def Length(self) -> int:
        """Length query (legacy int-returning API)."""

    def IsEmpty(self) -> bool:
        """Return TRUE if array has zero length."""

    def Lower(self) -> int:
        """Lower bound"""

    def Upper(self) -> int:
        """Upper bound"""

    def IsDeletable(self) -> bool: ...

    def Assign(self, theOther: NCollection_Array1__NCollection_Vec3__float) -> NCollection_Array1__NCollection_Vec3__float:
        """
        Replaces this array by a copy of theOther array.
        Bounds and length are copied from theOther.
        When this array wraps an external (non-owned) buffer:
        - if theOther has the same length, values are copied in place into the
        external buffer and ownership is unchanged;
        - if theOther has a different length, this array detaches from the
        external buffer and allocates a fresh owned buffer.
        Use CopyValues() to preserve this array's bounds.
        """

    def CopyValues(self, theOther: NCollection_Array1__NCollection_Vec3__float) -> NCollection_Array1__NCollection_Vec3__float:
        """
        Copies values from theOther array without changing this array bounds.
        This array should be pre-allocated and have the same length as theOther;
        otherwise exception Standard_DimensionMismatch is thrown.
        """

    def First(self) -> "NCollection_Vec3<float>":
        """@return first element"""

    def Last(self) -> "NCollection_Vec3<float>":
        """@return last element"""

    def Value(self, theIndex: int) -> "NCollection_Vec3<float>":
        """Constant value access"""

    def At(self, theIndex: int) -> "NCollection_Vec3<float>":
        """
        0-based checked access independent of Lower()/Upper().
        @param[in] theIndex 0-based index in [0, Size()-1]
        """

    def SetValue(self, theIndex: int, theItem: "NCollection_Vec3<float>") -> None:
        """Set value"""

    def UpdateLowerBound(self, theLower: int) -> None:
        """Changes the lowest bound. Do not move data"""

    def UpdateUpperBound(self, theUpper: int) -> None:
        """Changes the upper bound. Do not move data"""

    @overload
    def Resize(self, theLower: int, theUpper: int, theToCopyData: bool) -> None: ...

    @overload
    def Resize(self, theSize: int, theToCopyData: bool) -> None:
        """
        Resizes the array to specified bounds.
        No re-allocation will be done if length of array does not change,
        but existing values will not be discarded if theToCopyData set to FALSE.
        @param theLower new lower bound of array
        @param theUpper new upper bound of array
        @param theToCopyData flag to copy existing data into new array
        """

    def __call__(self, theIndex: int) -> "NCollection_Vec3<float>":
        """operator() - alias to Value"""

    def __getitem__(self, theIndex: int) -> "NCollection_Vec3<float>":
        """operator[] - alias to Value"""

    def __setitem__(self, theIndex: int, theItem: "NCollection_Vec3<float>") -> None:
        """Python addition: alias to SetValue (OCCT index)."""

    def __len__(self) -> int:
        """Python addition: alias to Length."""

    def __iter__(self) -> Iterator["NCollection_Vec3<float>"]:
        """Python addition: iterates over the values from Lower() to Upper()."""

    def ChangeFirst(self) -> "NCollection_Vec3<float>":
        """@return first element"""

    def ChangeLast(self) -> "NCollection_Vec3<float>":
        """@return last element"""

    def ChangeValue(self, theIndex: int) -> "NCollection_Vec3<float>":
        """Variable value access"""

    def ChangeAt(self, theIndex: int) -> "NCollection_Vec3<float>":
        """
        0-based checked mutable access independent of Lower()/Upper().
        @param[in] theIndex 0-based index in [0, Size()-1]
        """

class NCollection_Array1__Poly_Triangle(NCollection_Array1[nanoocp.Poly.Poly_Triangle]): ...
class NCollection_HArray1__Poly_Triangle(NCollection_HArray1[nanoocp.Poly.Poly_Triangle]): ...
class NCollection_Array1__float:
    """
    The class NCollection_Array1 represents unidimensional arrays of fixed size known at run time.
    The range of the index is user defined.
    An array1 can be constructed with a "C array".
    This functionality is useful to call methods expecting an Array1.
    It allows to carry the bounds inside the arrays.

    Examples:
    @code
    Item tab[100]; // an example with a C array
    NCollection_Array1<Item> ttab (tab[0], 1, 100);

    NCollection_Array1<Item> tttab (ttab(10), 10, 20); // a slice of ttab
    @endcode
    If you want to reindex an array from 1 to Length do:
    @code
    NCollection_Array1<Item> tab1 (tab (tab.Lower()), 1, tab.Length());
    @endcode
    Warning: Programs client of such a class must be independent of the range of the first element.
    Then, a C++ for loop must be written like this
    @code
    for (i = A.Lower(); i <= A.Upper(); i++)
    @endcode

    Zero-based (size_t) construction mode:
    Use NCollection_Array1(size_t theSize) or NCollection_Array1(pointer, size_t) to create
    a zero-based array (Lower()==0). In this mode At()/ChangeAt() and STL iterators are the
    preferred access path - they address elements directly without any offset subtraction.
    Buffer-reuse variants do NOT own the memory and will not free it on destruction.
    @code
    int aBuffer[100];
    NCollection_Array1<int> aZero(100);      // allocates, lower=0
    NCollection_Array1<int> aWrap(aBuffer, 100); // wraps aBuffer, lower=0, not owner
    for (size_t i = 0; i < aWrap.Size(); ++i)
    aWrap.At(i) = static_cast<int>(i);
    @endcode
    """

    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, theLower: int, theUpper: int) -> None: ...

    @overload
    def __init__(self, theSize: int) -> None: ...

    @overload
    def __init__(self, theOther: NCollection_Array1__float) -> None:
        """
        Zero-based constructor from first element reference.
        When theUseBuffer is true, wraps contiguous storage starting at theBegin.
        Otherwise allocates own storage of theSize elements.
        """

    def Init(self, theValue: float) -> None:
        """Initialise the items with theValue"""

    def Size(self) -> int:
        """Size query."""

    def Length(self) -> int:
        """Length query (legacy int-returning API)."""

    def IsEmpty(self) -> bool:
        """Return TRUE if array has zero length."""

    def Lower(self) -> int:
        """Lower bound"""

    def Upper(self) -> int:
        """Upper bound"""

    def IsDeletable(self) -> bool: ...

    def Assign(self, theOther: NCollection_Array1__float) -> NCollection_Array1__float:
        """
        Replaces this array by a copy of theOther array.
        Bounds and length are copied from theOther.
        When this array wraps an external (non-owned) buffer:
        - if theOther has the same length, values are copied in place into the
        external buffer and ownership is unchanged;
        - if theOther has a different length, this array detaches from the
        external buffer and allocates a fresh owned buffer.
        Use CopyValues() to preserve this array's bounds.
        """

    def CopyValues(self, theOther: NCollection_Array1__float) -> NCollection_Array1__float:
        """
        Copies values from theOther array without changing this array bounds.
        This array should be pre-allocated and have the same length as theOther;
        otherwise exception Standard_DimensionMismatch is thrown.
        """

    def First(self) -> float:
        """@return first element"""

    def Last(self) -> float:
        """@return last element"""

    def Value(self, theIndex: int) -> float:
        """Constant value access"""

    def At(self, theIndex: int) -> float:
        """
        0-based checked access independent of Lower()/Upper().
        @param[in] theIndex 0-based index in [0, Size()-1]
        """

    def SetValue(self, theIndex: int, theItem: float) -> None:
        """Set value"""

    def UpdateLowerBound(self, theLower: int) -> None:
        """Changes the lowest bound. Do not move data"""

    def UpdateUpperBound(self, theUpper: int) -> None:
        """Changes the upper bound. Do not move data"""

    @overload
    def Resize(self, theLower: int, theUpper: int, theToCopyData: bool) -> None: ...

    @overload
    def Resize(self, theSize: int, theToCopyData: bool) -> None:
        """
        Resizes the array to specified bounds.
        No re-allocation will be done if length of array does not change,
        but existing values will not be discarded if theToCopyData set to FALSE.
        @param theLower new lower bound of array
        @param theUpper new upper bound of array
        @param theToCopyData flag to copy existing data into new array
        """

    def __call__(self, theIndex: int) -> float:
        """operator() - alias to Value"""

    def __getitem__(self, theIndex: int) -> float:
        """operator[] - alias to Value"""

    def __setitem__(self, theIndex: int, theItem: float) -> None:
        """Python addition: alias to SetValue (OCCT index)."""

    def __len__(self) -> int:
        """Python addition: alias to Length."""

    def __iter__(self) -> Iterator[float]:
        """Python addition: iterates over the values from Lower() to Upper()."""

class NCollection_HArray1__float(NCollection_Array1__float):
    """
    Template class for Handle-managed 1D arrays.
    Inherits from both NCollection_Array1<TheItemType> and Standard_Transient,
    providing reference-counted array functionality.
    """

    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, theLower: int, theUpper: int) -> None: ...

    @overload
    def __init__(self, theLower: int, theUpper: int, theValue: float) -> None: ...

    @overload
    def __init__(self, theOther: NCollection_Array1__float) -> None:
        """Default constructor."""

    def Array1(self) -> NCollection_Array1__float:
        """Returns const reference to the underlying array."""

    def ChangeArray1(self) -> NCollection_Array1__float:
        """Returns mutable reference to the underlying array."""

    def GetRefCount(self) -> int:
        """Get the reference counter of this object (Standard_Transient)."""

    def DynamicType(self) -> nanoocp.Standard.Standard_Type:
        """Returns a type descriptor about this object (Standard_Transient)."""

    def IsInstance(self, theTypeName: str) -> bool:
        """Standard_Transient::IsInstance"""

    def IsKind(self, theTypeName: str) -> bool:
        """Standard_Transient::IsKind"""

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

class NCollection_HArray1__gp_Pnt2d(NCollection_HArray1[nanoocp.gp.gp_Pnt2d]): ...
class NCollection_HArray1__gp_Pnt(NCollection_HArray1[nanoocp.gp.gp_Pnt]): ...
class NCollection_List__Poly_CoherentTriangulation_TwoIntegers:
    """
    Purpose:      Simple list to link  items together keeping the first
    and the last one.
    Inherits BaseList, adding the data item to each node.
    """

    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, theAllocator: NCollection_BaseAllocator | None) -> None: ...

    @overload
    def __init__(self, theOther: NCollection_List__Poly_CoherentTriangulation_TwoIntegers) -> None:
        """Empty constructor."""

    class Iterator:
        """
        Purpose:     This Iterator class iterates on BaseList of TListNode and is
        instantiated in List/Set/Queue/Stack
        Remark:      TListIterator is internal class
        """

        @overload
        def __init__(self) -> None: ...

        @overload
        def __init__(self, theList: NCollection_List__Poly_CoherentTriangulation_TwoIntegers) -> None:
            """Empty constructor - for later Init"""

        def Initialize(self, theList: NCollection_List__Poly_CoherentTriangulation_TwoIntegers) -> None: ...

        def More(self) -> bool:
            """Check end"""

        def Next(self) -> None:
            """Make step"""

        def Value(self) -> "Poly_CoherentTriangulation::TwoIntegers":
            """Constant Value access"""

        def ChangeValue(self) -> "Poly_CoherentTriangulation::TwoIntegers":
            """Non-const Value access"""

    def Extent(self) -> int: ...

    def Length(self) -> int:
        """
        Length - number of nodes (legacy int-returning API, synonym of Extent()).
        """

    def Size(self) -> int:
        """Size - number of nodes."""

    def IsEmpty(self) -> bool: ...

    def Allocator(self) -> NCollection_BaseAllocator:
        """Returns attached allocator"""

    def Assign(self, theOther: NCollection_List__Poly_CoherentTriangulation_TwoIntegers) -> NCollection_List__Poly_CoherentTriangulation_TwoIntegers:
        """
        Replace this list by the items of another list (theOther parameter).
        This method does not change the internal allocator.
        """

    def Clear(self, theAllocator: NCollection_BaseAllocator | None = None) -> None:
        """Clear this list"""

    def First(self) -> "Poly_CoherentTriangulation::TwoIntegers":
        """First item"""

    def Last(self) -> "Poly_CoherentTriangulation::TwoIntegers":
        """Last item"""

    @overload
    def Append(self, theItem: "Poly_CoherentTriangulation::TwoIntegers", theIter: NCollection_List__Poly_CoherentTriangulation_TwoIntegers.Iterator) -> None: ...

    @overload
    def Append(self, theOther: NCollection_List__Poly_CoherentTriangulation_TwoIntegers) -> None: ...

    @overload
    def Append(self, theItem: "Poly_CoherentTriangulation::TwoIntegers") -> "Poly_CoherentTriangulation::TwoIntegers":
        """Append one item at the end"""

    @overload
    def Prepend(self, theOther: NCollection_List__Poly_CoherentTriangulation_TwoIntegers) -> None: ...

    @overload
    def Prepend(self, theItem: "Poly_CoherentTriangulation::TwoIntegers") -> "Poly_CoherentTriangulation::TwoIntegers":
        """Prepend one item at the beginning"""

    def RemoveFirst(self) -> None:
        """RemoveFirst item"""

    def Remove(self, theIter: NCollection_List__Poly_CoherentTriangulation_TwoIntegers.Iterator) -> None:
        """
        Remove item pointed by iterator theIter;
        theIter is then set to the next item
        """

    @overload
    def InsertBefore(self, theOther: NCollection_List__Poly_CoherentTriangulation_TwoIntegers, theIter: NCollection_List__Poly_CoherentTriangulation_TwoIntegers.Iterator) -> None: ...

    @overload
    def InsertBefore(self, theItem: "Poly_CoherentTriangulation::TwoIntegers", theIter: NCollection_List__Poly_CoherentTriangulation_TwoIntegers.Iterator) -> "Poly_CoherentTriangulation::TwoIntegers":
        """InsertBefore"""

    @overload
    def InsertAfter(self, theOther: NCollection_List__Poly_CoherentTriangulation_TwoIntegers, theIter: NCollection_List__Poly_CoherentTriangulation_TwoIntegers.Iterator) -> None: ...

    @overload
    def InsertAfter(self, theItem: "Poly_CoherentTriangulation::TwoIntegers", theIter: NCollection_List__Poly_CoherentTriangulation_TwoIntegers.Iterator) -> "Poly_CoherentTriangulation::TwoIntegers":
        """InsertAfter"""

    def Reverse(self) -> None:
        """Reverse the list"""

    def Exchange(self, theOther: NCollection_List__Poly_CoherentTriangulation_TwoIntegers) -> None:
        """
        Exchange the content of two lists without re-allocations.
        Swaps all internal state including allocators, ensuring correct
        deallocation. Existing iterators remain valid but will point to
        the other list's elements.
        """

    def __len__(self) -> int:
        """Python addition: alias to Extent."""

    def __iter__(self) -> Iterator["Poly_CoherentTriangulation::TwoIntegers"]:
        """Python addition: iterates over the values."""

class NCollection_List__Poly_MakeLoops_Link:
    """
    Purpose:      Simple list to link  items together keeping the first
    and the last one.
    Inherits BaseList, adding the data item to each node.
    """

    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, theAllocator: NCollection_BaseAllocator | None) -> None: ...

    @overload
    def __init__(self, theOther: NCollection_List__Poly_MakeLoops_Link) -> None:
        """Empty constructor."""

    class Iterator:
        """
        Purpose:     This Iterator class iterates on BaseList of TListNode and is
        instantiated in List/Set/Queue/Stack
        Remark:      TListIterator is internal class
        """

        @overload
        def __init__(self) -> None: ...

        @overload
        def __init__(self, theList: NCollection_List__Poly_MakeLoops_Link) -> None:
            """Empty constructor - for later Init"""

        def Initialize(self, theList: NCollection_List__Poly_MakeLoops_Link) -> None: ...

        def More(self) -> bool:
            """Check end"""

        def Next(self) -> None:
            """Make step"""

        def Value(self) -> "Poly_MakeLoops::Link":
            """Constant Value access"""

        def ChangeValue(self) -> "Poly_MakeLoops::Link":
            """Non-const Value access"""

    def Extent(self) -> int: ...

    def Length(self) -> int:
        """
        Length - number of nodes (legacy int-returning API, synonym of Extent()).
        """

    def Size(self) -> int:
        """Size - number of nodes."""

    def IsEmpty(self) -> bool: ...

    def Allocator(self) -> NCollection_BaseAllocator:
        """Returns attached allocator"""

    def Assign(self, theOther: NCollection_List__Poly_MakeLoops_Link) -> NCollection_List__Poly_MakeLoops_Link:
        """
        Replace this list by the items of another list (theOther parameter).
        This method does not change the internal allocator.
        """

    def Clear(self, theAllocator: NCollection_BaseAllocator | None = None) -> None:
        """Clear this list"""

    def First(self) -> "Poly_MakeLoops::Link":
        """First item"""

    def Last(self) -> "Poly_MakeLoops::Link":
        """Last item"""

    @overload
    def Append(self, theItem: "Poly_MakeLoops::Link", theIter: NCollection_List__Poly_MakeLoops_Link.Iterator) -> None: ...

    @overload
    def Append(self, theOther: NCollection_List__Poly_MakeLoops_Link) -> None: ...

    @overload
    def Append(self, theItem: "Poly_MakeLoops::Link") -> "Poly_MakeLoops::Link":
        """Append one item at the end"""

    @overload
    def Prepend(self, theOther: NCollection_List__Poly_MakeLoops_Link) -> None: ...

    @overload
    def Prepend(self, theItem: "Poly_MakeLoops::Link") -> "Poly_MakeLoops::Link":
        """Prepend one item at the beginning"""

    def RemoveFirst(self) -> None:
        """RemoveFirst item"""

    @overload
    def Remove(self, theIter: NCollection_List__Poly_MakeLoops_Link.Iterator) -> None: ...

    @overload
    def Remove(self, theObject: "Poly_MakeLoops::Link") -> bool:
        """
        Remove item pointed by iterator theIter;
        theIter is then set to the next item
        """

    @overload
    def InsertBefore(self, theOther: NCollection_List__Poly_MakeLoops_Link, theIter: NCollection_List__Poly_MakeLoops_Link.Iterator) -> None: ...

    @overload
    def InsertBefore(self, theItem: "Poly_MakeLoops::Link", theIter: NCollection_List__Poly_MakeLoops_Link.Iterator) -> "Poly_MakeLoops::Link":
        """InsertBefore"""

    @overload
    def InsertAfter(self, theOther: NCollection_List__Poly_MakeLoops_Link, theIter: NCollection_List__Poly_MakeLoops_Link.Iterator) -> None: ...

    @overload
    def InsertAfter(self, theItem: "Poly_MakeLoops::Link", theIter: NCollection_List__Poly_MakeLoops_Link.Iterator) -> "Poly_MakeLoops::Link":
        """InsertAfter"""

    def Reverse(self) -> None:
        """Reverse the list"""

    def Exchange(self, theOther: NCollection_List__Poly_MakeLoops_Link) -> None:
        """
        Exchange the content of two lists without re-allocations.
        Swaps all internal state including allocators, ensuring correct
        deallocation. Existing iterators remain valid but will point to
        the other list's elements.
        """

    def __len__(self) -> int:
        """Python addition: alias to Extent."""

    def __iter__(self) -> Iterator["Poly_MakeLoops::Link"]:
        """Python addition: iterates over the values."""

    def Contains(self, theObject: "Poly_MakeLoops::Link") -> bool:
        """Return true if object is stored in the list."""

    def __contains__(self, theObject: "Poly_MakeLoops::Link") -> bool:
        """Python addition: alias to Contains."""

class NCollection_List__Handle_Poly_Triangulation(NCollection_List[nanoocp.Poly.Poly_Triangulation]): ...
class NCollection_Array1__gp_Vec(NCollection_Array1[nanoocp.gp.gp_Vec]): ...
class NCollection_Array2__gp_Vec(NCollection_Array2[nanoocp.gp.gp_Vec]): ...
class NCollection_DynamicArray__gp_Pnt2d(NCollection_DynamicArray[nanoocp.gp.gp_Pnt2d]): ...
class NCollection_Sequence__gp_Pnt2d(NCollection_Sequence[nanoocp.gp.gp_Pnt2d]): ...
class NCollection_Array2__int(NCollection_Array2[int]): ...
class NCollection_HArray2__int(NCollection_HArray2[int]): ...
class NCollection_Array1__Bnd_Box(NCollection_Array1[nanoocp.Bnd.Bnd_Box]): ...
class NCollection_HArray1__Bnd_Box(NCollection_HArray1[nanoocp.Bnd.Bnd_Box]): ...
class NCollection_List__Bnd_Range(NCollection_List[nanoocp.Bnd.Bnd_Range]): ...
