"""OCCT package NLPlate (toolkit TKGeomAlgo)"""

from typing import overload

import nanoocp.Geom
import nanoocp.Plate
import nanoocp.Standard
import nanoocp.gp


class NLPlate_HGPPConstraint(nanoocp.Standard.Standard_Transient):
    """define a PinPoint geometric Constraint used to load a Non Linear Plate"""

    def SetUVFreeSliding(self, UVFree: bool) -> None: ...

    def SetIncrementalLoadAllowed(self, ILA: bool) -> None: ...

    def SetActiveOrder(self, ActiveOrder: int) -> None: ...

    def SetUV(self, UV: nanoocp.gp.gp_XY) -> None: ...

    def SetOrientation(self, Orient: int = 0) -> None: ...

    def SetG0Criterion(self, TolDist: float) -> None: ...

    def SetG1Criterion(self, TolAng: float) -> None: ...

    def SetG2Criterion(self, TolCurv: float) -> None: ...

    def SetG3Criterion(self, TolG3: float) -> None: ...

    def UVFreeSliding(self) -> bool: ...

    def IncrementalLoadAllowed(self) -> bool: ...

    def ActiveOrder(self) -> int: ...

    def UV(self) -> nanoocp.gp.gp_XY: ...

    def Orientation(self) -> int: ...

    def IsG0(self) -> bool: ...

    def G0Target(self) -> nanoocp.gp.gp_XYZ: ...

    def G1Target(self) -> nanoocp.Plate.Plate_D1: ...

    def G2Target(self) -> nanoocp.Plate.Plate_D2: ...

    def G3Target(self) -> nanoocp.Plate.Plate_D3: ...

    def G0Criterion(self) -> float: ...

    def G1Criterion(self) -> float: ...

    def G2Criterion(self) -> float: ...

    def G3Criterion(self) -> float: ...

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

class NLPlate_HPG0Constraint(NLPlate_HGPPConstraint):
    """
    define a PinPoint G0 Constraint used to load a Non Linear
    Plate
    """

    @overload
    def __init__(self, UV: nanoocp.gp.gp_XY, Value: nanoocp.gp.gp_XYZ) -> None: ...

    @overload
    def __init__(self, theOther: NLPlate_HPG0Constraint) -> None: ...

    def SetUVFreeSliding(self, UVFree: bool) -> None: ...

    def SetIncrementalLoadAllowed(self, ILA: bool) -> None: ...

    def UVFreeSliding(self) -> bool: ...

    def IncrementalLoadAllowed(self) -> bool: ...

    def ActiveOrder(self) -> int: ...

    def IsG0(self) -> bool: ...

    def G0Target(self) -> nanoocp.gp.gp_XYZ: ...

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

class NLPlate_HPG0G1Constraint(NLPlate_HPG0Constraint):
    """
    define a PinPoint G0+G1 Constraint used to load a Non Linear
    Plate
    """

    @overload
    def __init__(self, UV: nanoocp.gp.gp_XY, Value: nanoocp.gp.gp_XYZ, D1T: nanoocp.Plate.Plate_D1) -> None: ...

    @overload
    def __init__(self, theOther: NLPlate_HPG0G1Constraint) -> None: ...

    def SetOrientation(self, Orient: int = 0) -> None: ...

    def ActiveOrder(self) -> int: ...

    def Orientation(self) -> int: ...

    def G1Target(self) -> nanoocp.Plate.Plate_D1: ...

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

class NLPlate_HPG0G2Constraint(NLPlate_HPG0G1Constraint):
    """
    define a PinPoint G0+G2 Constraint used to load a Non Linear
    Plate
    """

    @overload
    def __init__(self, UV: nanoocp.gp.gp_XY, Value: nanoocp.gp.gp_XYZ, D1T: nanoocp.Plate.Plate_D1, D2T: nanoocp.Plate.Plate_D2) -> None: ...

    @overload
    def __init__(self, theOther: NLPlate_HPG0G2Constraint) -> None: ...

    def ActiveOrder(self) -> int: ...

    def G2Target(self) -> nanoocp.Plate.Plate_D2: ...

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

class NLPlate_HPG0G3Constraint(NLPlate_HPG0G2Constraint):
    """
    define a PinPoint G0+G3 Constraint used to load a Non Linear
    Plate
    """

    @overload
    def __init__(self, UV: nanoocp.gp.gp_XY, Value: nanoocp.gp.gp_XYZ, D1T: nanoocp.Plate.Plate_D1, D2T: nanoocp.Plate.Plate_D2, D3T: nanoocp.Plate.Plate_D3) -> None: ...

    @overload
    def __init__(self, theOther: NLPlate_HPG0G3Constraint) -> None: ...

    def ActiveOrder(self) -> int: ...

    def G3Target(self) -> nanoocp.Plate.Plate_D3: ...

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

class NLPlate_HPG1Constraint(NLPlate_HGPPConstraint):
    """
    define a PinPoint (no G0) G1 Constraint used to load a Non
    Linear Plate
    """

    @overload
    def __init__(self, UV: nanoocp.gp.gp_XY, D1T: nanoocp.Plate.Plate_D1) -> None: ...

    @overload
    def __init__(self, theOther: NLPlate_HPG1Constraint) -> None: ...

    def SetIncrementalLoadAllowed(self, ILA: bool) -> None: ...

    def SetOrientation(self, Orient: int = 0) -> None: ...

    def IncrementalLoadAllowed(self) -> bool: ...

    def ActiveOrder(self) -> int: ...

    def IsG0(self) -> bool: ...

    def Orientation(self) -> int: ...

    def G1Target(self) -> nanoocp.Plate.Plate_D1: ...

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

class NLPlate_HPG2Constraint(NLPlate_HPG1Constraint):
    """
    define a PinPoint (no G0) G2 Constraint used to load a Non
    Linear Plate
    """

    @overload
    def __init__(self, UV: nanoocp.gp.gp_XY, D1T: nanoocp.Plate.Plate_D1, D2T: nanoocp.Plate.Plate_D2) -> None: ...

    @overload
    def __init__(self, theOther: NLPlate_HPG2Constraint) -> None: ...

    def ActiveOrder(self) -> int: ...

    def G2Target(self) -> nanoocp.Plate.Plate_D2: ...

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

class NLPlate_HPG3Constraint(NLPlate_HPG2Constraint):
    """
    define a PinPoint (no G0) G3 Constraint used to load a Non
    Linear Plate
    """

    @overload
    def __init__(self, UV: nanoocp.gp.gp_XY, D1T: nanoocp.Plate.Plate_D1, D2T: nanoocp.Plate.Plate_D2, D3T: nanoocp.Plate.Plate_D3) -> None: ...

    @overload
    def __init__(self, theOther: NLPlate_HPG3Constraint) -> None: ...

    def ActiveOrder(self) -> int: ...

    def G3Target(self) -> nanoocp.Plate.Plate_D3: ...

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...

class NLPlate_NLPlate:
    @overload
    def __init__(self, InitialSurface: nanoocp.Geom.Geom_Surface | None) -> None: ...

    @overload
    def __init__(self, theOther: NLPlate_NLPlate) -> None: ...

    def Load(self, GConst: NLPlate_HGPPConstraint | None) -> None: ...

    def Solve(self, ord: int = 2, InitialConsraintOrder: int = 1) -> None: ...

    def Solve2(self, ord: int = 2, InitialConsraintOrder: int = 1) -> None: ...

    def IncrementalSolve(self, ord: int = 2, InitialConsraintOrder: int = 1, NbIncrements: int = 4, UVSliding: bool = False) -> None: ...

    def IsDone(self) -> bool:
        """returns True if all has been correctly done."""

    def destroy(self) -> None: ...

    def Init(self) -> None:
        """
        reset the Plate in the initial state
        ( same as after Create((Surface))
        """

    def Evaluate(self, point2d: nanoocp.gp.gp_XY) -> nanoocp.gp.gp_XYZ: ...

    def EvaluateDerivative(self, point2d: nanoocp.gp.gp_XY, iu: int, iv: int) -> nanoocp.gp.gp_XYZ: ...

    def Continuity(self) -> int: ...

    def ConstraintsSliding(self, NbIterations: int = 3) -> None: ...

    def MaxActiveConstraintOrder(self) -> int: ...
