"""TColgp: OCCT pre-8.0 typedef names."""

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
import nanoocp.gp
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array1OfXYZ = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_XYZ]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray1OfXYZ = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_XYZ]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_HSequenceOfPnt = nanoocp.NCollection.NCollection_HSequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array1OfXYZ = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_XYZ]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray1OfXYZ = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_XYZ]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_HSequenceOfPnt = nanoocp.NCollection.NCollection_HSequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array1OfXYZ = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_XYZ]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray1OfXYZ = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_XYZ]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_HSequenceOfPnt = nanoocp.NCollection.NCollection_HSequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array1OfXYZ = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_XYZ]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray1OfXYZ = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_XYZ]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_HSequenceOfPnt = nanoocp.NCollection.NCollection_HSequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array1OfXYZ = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_XYZ]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray1OfXYZ = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_XYZ]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_HSequenceOfPnt = nanoocp.NCollection.NCollection_HSequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array1OfXYZ = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_XYZ]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray1OfXYZ = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_XYZ]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_HSequenceOfPnt = nanoocp.NCollection.NCollection_HSequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array1OfXYZ = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_XYZ]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray1OfXYZ = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_XYZ]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_HSequenceOfPnt = nanoocp.NCollection.NCollection_HSequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array1OfXYZ = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_XYZ]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray1OfXYZ = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_XYZ]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_HSequenceOfPnt = nanoocp.NCollection.NCollection_HSequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array1OfXYZ = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_XYZ]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray1OfXYZ = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_XYZ]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_HSequenceOfPnt = nanoocp.NCollection.NCollection_HSequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array1OfXYZ = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_XYZ]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray1OfXYZ = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_XYZ]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_HSequenceOfPnt = nanoocp.NCollection.NCollection_HSequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array1OfXYZ = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_XYZ]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray1OfXYZ = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_XYZ]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_HSequenceOfPnt = nanoocp.NCollection.NCollection_HSequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array1OfXYZ = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_XYZ]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray1OfXYZ = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_XYZ]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_HSequenceOfPnt = nanoocp.NCollection.NCollection_HSequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array1OfXYZ = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_XYZ]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray1OfXYZ = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_XYZ]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_HSequenceOfPnt = nanoocp.NCollection.NCollection_HSequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array1OfXYZ = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_XYZ]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray1OfXYZ = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_XYZ]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_HSequenceOfPnt = nanoocp.NCollection.NCollection_HSequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array1OfXYZ = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_XYZ]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray1OfXYZ = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_XYZ]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_HSequenceOfPnt = nanoocp.NCollection.NCollection_HSequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array1OfXYZ = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_XYZ]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray1OfXYZ = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_XYZ]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_HSequenceOfPnt = nanoocp.NCollection.NCollection_HSequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array1OfXYZ = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_XYZ]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray1OfXYZ = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_XYZ]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_HSequenceOfPnt = nanoocp.NCollection.NCollection_HSequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array1OfXYZ = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_XYZ]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray1OfXYZ = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_XYZ]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_HSequenceOfPnt = nanoocp.NCollection.NCollection_HSequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt]
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Pnt2d]
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec]
TColgp_Array1OfVec2d = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_Vec2d]
TColgp_Array1OfXYZ = nanoocp.NCollection.NCollection_Array1[nanoocp.gp.gp_XYZ]
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt]
TColgp_Array2OfPnt2d = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Pnt2d]
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2[nanoocp.gp.gp_Vec]
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt]
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_Pnt2d]
TColgp_HArray1OfXYZ = nanoocp.NCollection.NCollection_HArray1[nanoocp.gp.gp_XYZ]
TColgp_HArray2OfPnt = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt]
TColgp_HArray2OfPnt2d = nanoocp.NCollection.NCollection_HArray2[nanoocp.gp.gp_Pnt2d]
TColgp_HSequenceOfPnt = nanoocp.NCollection.NCollection_HSequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt]
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence[nanoocp.gp.gp_Pnt2d]
