"""TColgp: OCCT pre-8.0 typedef names."""

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1__gp_Pnt
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1__gp_Pnt2d
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1__gp_Vec
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2__gp_Pnt
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2__gp_Vec
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1__gp_Pnt
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1__gp_Pnt2d
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence__gp_Pnt2d

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1__gp_Pnt
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1__gp_Pnt2d
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1__gp_Vec
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2__gp_Pnt
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2__gp_Vec
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1__gp_Pnt
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1__gp_Pnt2d
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence__gp_Pnt2d

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1__gp_Pnt
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1__gp_Pnt2d
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1__gp_Vec
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2__gp_Pnt
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2__gp_Vec
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1__gp_Pnt
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1__gp_Pnt2d
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence__gp_Pnt2d

# deprecated OCCT typedef names (src/Deprecated/NCollectionAliases)
import nanoocp.NCollection
TColgp_Array1OfPnt = nanoocp.NCollection.NCollection_Array1__gp_Pnt
TColgp_Array1OfPnt2d = nanoocp.NCollection.NCollection_Array1__gp_Pnt2d
TColgp_Array1OfVec = nanoocp.NCollection.NCollection_Array1__gp_Vec
TColgp_Array2OfPnt = nanoocp.NCollection.NCollection_Array2__gp_Pnt
TColgp_Array2OfVec = nanoocp.NCollection.NCollection_Array2__gp_Vec
TColgp_HArray1OfPnt = nanoocp.NCollection.NCollection_HArray1__gp_Pnt
TColgp_HArray1OfPnt2d = nanoocp.NCollection.NCollection_HArray1__gp_Pnt2d
TColgp_SequenceOfPnt2d = nanoocp.NCollection.NCollection_Sequence__gp_Pnt2d
