"""OCCT package XCAFView (toolkit TKXCAF)"""

import enum
from typing import overload

import nanoocp.Standard
import nanoocp.TCollection
import nanoocp.gp


class XCAFView_ProjectionType(enum.IntEnum):
    """Defines projection types of view"""

    XCAFView_ProjectionType_NoCamera = 0

    XCAFView_ProjectionType_Parallel = 1

    XCAFView_ProjectionType_Central = 2

XCAFView_ProjectionType_NoCamera: XCAFView_ProjectionType = ...

XCAFView_ProjectionType_Parallel: XCAFView_ProjectionType = ...

XCAFView_ProjectionType_Central: XCAFView_ProjectionType = ...

class XCAFView_Object(nanoocp.Standard.Standard_Transient):
    """Access object for saved view"""

    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, theObj: XCAFView_Object | None) -> None: ...

    @overload
    def __init__(self, theOther: XCAFView_Object) -> None: ...

    def SetName(self, theName: nanoocp.TCollection.TCollection_HAsciiString | None) -> None: ...

    def Name(self) -> nanoocp.TCollection.TCollection_HAsciiString: ...

    def SetType(self, theType: XCAFView_ProjectionType) -> None: ...

    def Type(self) -> XCAFView_ProjectionType: ...

    def SetProjectionPoint(self, thePoint: nanoocp.gp.gp_Pnt) -> None: ...

    def ProjectionPoint(self) -> nanoocp.gp.gp_Pnt: ...

    def SetViewDirection(self, theDirection: nanoocp.gp.gp_Dir) -> None: ...

    def ViewDirection(self) -> nanoocp.gp.gp_Dir: ...

    def SetUpDirection(self, theDirection: nanoocp.gp.gp_Dir) -> None: ...

    def UpDirection(self) -> nanoocp.gp.gp_Dir: ...

    def SetZoomFactor(self, theZoomFactor: float) -> None: ...

    def ZoomFactor(self) -> float: ...

    def SetWindowHorizontalSize(self, theSize: float) -> None: ...

    def WindowHorizontalSize(self) -> float: ...

    def SetWindowVerticalSize(self, theSize: float) -> None: ...

    def WindowVerticalSize(self) -> float: ...

    def SetClippingExpression(self, theExpression: nanoocp.TCollection.TCollection_HAsciiString | None) -> None: ...

    def ClippingExpression(self) -> nanoocp.TCollection.TCollection_HAsciiString: ...

    def UnsetFrontPlaneClipping(self) -> None: ...

    def HasFrontPlaneClipping(self) -> bool: ...

    def SetFrontPlaneDistance(self, theDistance: float) -> None: ...

    def FrontPlaneDistance(self) -> float: ...

    def UnsetBackPlaneClipping(self) -> None: ...

    def HasBackPlaneClipping(self) -> bool: ...

    def SetBackPlaneDistance(self, theDistance: float) -> None: ...

    def BackPlaneDistance(self) -> float: ...

    def SetViewVolumeSidesClipping(self, theViewVolumeSidesClipping: bool) -> None: ...

    def HasViewVolumeSidesClipping(self) -> bool: ...

    def CreateGDTPoints(self, theLenght: int) -> None: ...

    def HasGDTPoints(self) -> bool: ...

    def NbGDTPoints(self) -> int: ...

    def SetGDTPoint(self, theIndex: int, thePoint: nanoocp.gp.gp_Pnt) -> None: ...

    def GDTPoint(self, theIndex: int) -> nanoocp.gp.gp_Pnt: ...

    @staticmethod
    def get_type_name() -> str: ...

    @staticmethod
    def get_type_descriptor() -> nanoocp.Standard.Standard_Type: ...

    def DynamicType(self) -> nanoocp.Standard.Standard_Type: ...
