// Generated by the nanoOCP generator: extension module for OCCT toolkit TKXmlXCAF. Do not edit.
#include "nanoocp_common.h"

void nanoocp_declare_XmlXCAFDrivers(nb::module_ &);
void nanoocp_templates_XmlXCAFDrivers(nb::module_ &);
void nanoocp_define_XmlXCAFDrivers(nb::module_ &);
void nanoocp_conversions_XmlXCAFDrivers(nb::module_ &);
void nanoocp_declare_XmlMXCAFDoc(nb::module_ &);
void nanoocp_templates_XmlMXCAFDoc(nb::module_ &);
void nanoocp_define_XmlMXCAFDoc(nb::module_ &);
void nanoocp_conversions_XmlMXCAFDoc(nb::module_ &);

NB_MODULE(_TKXmlXCAF, m) {
    m.doc() = "OCCT toolkit TKXmlXCAF";
    nb::object sys_modules = nb::module_::import_("sys").attr("modules");
    // toolkits this one links against must have registered their types first
    nb::module_::import_("nanoocp._TKXmlL");
    nb::module_::import_("nanoocp._TKBRep");
    nb::module_::import_("nanoocp._TKCDF");
    nb::module_::import_("nanoocp._TKMath");
    nb::module_::import_("nanoocp._TKernel");
    nb::module_::import_("nanoocp._TKService");
    nb::module_::import_("nanoocp._TKG2d");
    nb::module_::import_("nanoocp._TKGeomBase");
    nb::module_::import_("nanoocp._TKCAF");
    nb::module_::import_("nanoocp._TKG3d");
    nb::module_::import_("nanoocp._TKLCAF");
    nb::module_::import_("nanoocp._TKXCAF");
    nb::module_::import_("nanoocp._TKXml");
    nb::module_ m_XmlXCAFDrivers = m.def_submodule("XmlXCAFDrivers", "OCCT package XmlXCAFDrivers (toolkit TKXmlXCAF)");
    m_XmlXCAFDrivers.attr("__name__") = "nanoocp.XmlXCAFDrivers";
    sys_modules["nanoocp._TKXmlXCAF.XmlXCAFDrivers"] = m_XmlXCAFDrivers;
    nb::module_ m_XmlMXCAFDoc = m.def_submodule("XmlMXCAFDoc", "OCCT package XmlMXCAFDoc (toolkit TKXmlXCAF)");
    m_XmlMXCAFDoc.attr("__name__") = "nanoocp.XmlMXCAFDoc";
    sys_modules["nanoocp._TKXmlXCAF.XmlMXCAFDoc"] = m_XmlMXCAFDoc;
    // phase 1: all types (classes, enums) so that signatures/defaults can refer to them
    nanoocp_declare_XmlXCAFDrivers(m_XmlXCAFDrivers);
    nanoocp_declare_XmlMXCAFDoc(m_XmlMXCAFDoc);
    nanoocp_install_exception_translator(nullptr);
    // phase 2: NCollection template instances (need their element types)
    nanoocp_templates_XmlXCAFDrivers(m_XmlXCAFDrivers);
    nanoocp_templates_XmlMXCAFDoc(m_XmlMXCAFDoc);
    // phase 3: members
    nanoocp_define_XmlXCAFDrivers(m_XmlXCAFDrivers);
    nanoocp_define_XmlMXCAFDoc(m_XmlMXCAFDoc);
    // phase 4: constructors from conversion operators (every class has its own constructors by now)
    nanoocp_conversions_XmlXCAFDrivers(m_XmlXCAFDrivers);
    nanoocp_conversions_XmlMXCAFDoc(m_XmlMXCAFDoc);
}
