// Generated by the nanoOCP generator from OCCT package IFGraph (toolkit TKXSBase). Do not edit.
#include "nanoocp_common.h"
#include <IFGraph_AllConnected.hxx>
#include <IFGraph_AllShared.hxx>
#include <IFGraph_Articulations.hxx>
#include <IFGraph_Compare.hxx>
#include <IFGraph_ConnectedComponants.hxx>
#include <IFGraph_Cumulate.hxx>
#include <IFGraph_Cycles.hxx>
#include <IFGraph_ExternalSources.hxx>
#include <IFGraph_SCRoots.hxx>
#include <IFGraph_StrongComponants.hxx>
#include <IFGraph_SubPartsIterator.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <Interface_GraphContent.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Standard_Transient.hxx>

void nanoocp_declare_IFGraph(nb::module_ &m) {
    { nb::class_<IFGraph_AllConnected, Interface_GraphContent> cls(m, "IFGraph_AllConnected", R"nbdoc(this class gives content of the CONNECTED COMPONENT(S)
which include specific Entity(ies))nbdoc");
    }
    { nb::class_<IFGraph_AllShared, Interface_GraphContent> cls(m, "IFGraph_AllShared", R"nbdoc(this class determines all Entities shared by some specific
ones, at any level (those which will be lead in a Transfer
for instance))nbdoc");
    }
    { nb::class_<IFGraph_Articulations, Interface_GraphContent> cls(m, "IFGraph_Articulations", R"nbdoc(this class gives entities which are Articulation points
in a whole Model or in a sub-part
An Articulation Point divides the graph in two (or more)
disconnected sub-graphs
Identifying Articulation Points allows improving
efficiency of splitting a set of Entities into sub-sets)nbdoc");
    }
    { nb::class_<IFGraph_Compare, Interface_GraphContent> cls(m, "IFGraph_Compare", R"nbdoc(this class evaluates effect of two compared sub-parts :
cumulation (union), common part (intersection-overlapping)
part specific to first sub-part or to the second one
Results are kept in a Graph, several question can be set
Basic Iteration gives Cumulation (union))nbdoc");
    }
    { nb::class_<IFGraph_SubPartsIterator> cls(m, "IFGraph_SubPartsIterator", R"nbdoc(defines general form for graph classes of which result is
not a single iteration on Entities, but a nested one :
External iteration works on sub-parts, identified by each
class (according to its algorithm)
Internal Iteration concerns Entities of a sub-part
Sub-Parts are assumed to be disjoined; if they are not,
the first one has priority

A SubPartsIterator can work in two steps : first, load
entities which have to be processed
then, analyse to set those entities into sub-parts)nbdoc");
    }
    { nb::class_<IFGraph_ConnectedComponants, IFGraph_SubPartsIterator> cls(m, "IFGraph_ConnectedComponants", R"nbdoc(determines Connected Components in a Graph.
They define disjoined sets of Entities.)nbdoc");
    }
    { nb::class_<IFGraph_Cumulate, Interface_GraphContent> cls(m, "IFGraph_Cumulate", R"nbdoc(this class evaluates effect of cumulated sub-parts :
overlapping, forgotten entities
Results are kept in a Graph, several question can be set
Basic Iteration gives entities which are part of Cumulation)nbdoc");
    }
    { nb::class_<IFGraph_Cycles, IFGraph_SubPartsIterator> cls(m, "IFGraph_Cycles", R"nbdoc(determines strong components in a graph which are Cycles)nbdoc");
    }
    { nb::class_<IFGraph_ExternalSources, Interface_GraphContent> cls(m, "IFGraph_ExternalSources", R"nbdoc(this class gives entities which are Source of entities of
a sub-part, but are not contained by this sub-part)nbdoc");
    }
    { nb::class_<IFGraph_StrongComponants, IFGraph_SubPartsIterator> cls(m, "IFGraph_StrongComponants", R"nbdoc(determines strong components of a graph, that is
isolated entities (single components) or loops)nbdoc");
    }
    { nb::class_<IFGraph_SCRoots, IFGraph_StrongComponants> cls(m, "IFGraph_SCRoots", R"nbdoc(determines strong components in a graph which are Roots)nbdoc");
    }
}

void nanoocp_templates_IFGraph(nb::module_ &m) {
}

void nanoocp_define_IFGraph(nb::module_ &m) {
    nb::borrow<nb::class_<IFGraph_AllConnected>>(m.attr("IFGraph_AllConnected"))
        .def(nb::init<const Interface_Graph &>(), nb::arg("agraph"), R"nbdoc(creates an AllConnected from a graph, empty ready to be filled)nbdoc")
        .def(nb::init<const Interface_Graph &, const occ::handle<Standard_Transient> &>(), nb::arg("agraph"), nb::arg("ent").none(), R"nbdoc(creates an AllConnected which memorizes Entities Connected to
a given one, at any level : that is, itself, all Entities
Shared by it and Sharing it, and so on.
In other terms, this is the content of the CONNECTED COMPONENT
which include a specific Entity)nbdoc")
        .def("GetFromEntity", static_cast<void (IFGraph_AllConnected::*)(const occ::handle<Standard_Transient> &)>(&IFGraph_AllConnected::GetFromEntity), nb::arg("ent").none(), R"nbdoc(adds an entity and its Connected ones to the list (allows to
cumulate all Entities Connected by some ones)
Note that if "ent" is in the already computed list,, no entity
will be added, but if "ent" is not already in the list, a new
Connected Component will be cumulated)nbdoc")
        .def("ResetData", static_cast<void (IFGraph_AllConnected::*)()>(&IFGraph_AllConnected::ResetData), R"nbdoc(Allows to restart on a new data set)nbdoc")
        .def("Evaluate", static_cast<void (IFGraph_AllConnected::*)()>(&IFGraph_AllConnected::Evaluate), R"nbdoc(does the specific evaluation (Connected entities atall levels))nbdoc");
    nanoocp_implicit_copy_ctor<IFGraph_AllConnected>(nb::borrow<nb::class_<IFGraph_AllConnected>>(m.attr("IFGraph_AllConnected")));
    nb::implicitly_convertible<std::decay_t<const Interface_Graph &>, IFGraph_AllConnected>();
    nb::borrow<nb::class_<IFGraph_AllShared>>(m.attr("IFGraph_AllShared"))
        .def(nb::init<const Interface_Graph &>(), nb::arg("agraph"), R"nbdoc(creates an AllShared from a graph, empty ready to be filled)nbdoc")
        .def(nb::init<const Interface_Graph &, const occ::handle<Standard_Transient> &>(), nb::arg("agraph"), nb::arg("ent").none(), R"nbdoc(creates an AllShared which memrizes Entities shared by a given
one, at any level, including itself)nbdoc")
        .def("GetFromEntity", static_cast<void (IFGraph_AllShared::*)(const occ::handle<Standard_Transient> &)>(&IFGraph_AllShared::GetFromEntity), nb::arg("ent").none(), R"nbdoc(adds an entity and its shared ones to the list (allows to
cumulate all Entities shared by some ones))nbdoc")
        .def("GetFromIter", static_cast<void (IFGraph_AllShared::*)(const Interface_EntityIterator &)>(&IFGraph_AllShared::GetFromIter), nb::arg("iter"), R"nbdoc(Adds Entities from an EntityIterator and all their shared
ones at any level)nbdoc")
        .def("ResetData", static_cast<void (IFGraph_AllShared::*)()>(&IFGraph_AllShared::ResetData), R"nbdoc(Allows to restart on a new data set)nbdoc")
        .def("Evaluate", static_cast<void (IFGraph_AllShared::*)()>(&IFGraph_AllShared::Evaluate), R"nbdoc(does the specific evaluation (shared entities atall levels))nbdoc");
    nanoocp_implicit_copy_ctor<IFGraph_AllShared>(nb::borrow<nb::class_<IFGraph_AllShared>>(m.attr("IFGraph_AllShared")));
    nb::implicitly_convertible<std::decay_t<const Interface_Graph &>, IFGraph_AllShared>();
    nb::borrow<nb::class_<IFGraph_Articulations>>(m.attr("IFGraph_Articulations"))
        .def(nb::init<const Interface_Graph &, const bool>(), nb::arg("agraph"), nb::arg("whole"), R"nbdoc(creates Articulations to evaluate a Graph
whole True : works on the whole Model
whole False : remains empty, ready to work on a sub-part)nbdoc")
        .def("GetFromEntity", static_cast<void (IFGraph_Articulations::*)(const occ::handle<Standard_Transient> &)>(&IFGraph_Articulations::GetFromEntity), nb::arg("ent").none(), R"nbdoc(adds an entity and its shared ones to the list)nbdoc")
        .def("GetFromIter", static_cast<void (IFGraph_Articulations::*)(const Interface_EntityIterator &)>(&IFGraph_Articulations::GetFromIter), nb::arg("iter"), R"nbdoc(adds a list of entities (as an iterator))nbdoc")
        .def("ResetData", static_cast<void (IFGraph_Articulations::*)()>(&IFGraph_Articulations::ResetData), R"nbdoc(Allows to restart on a new data set)nbdoc")
        .def("Evaluate", static_cast<void (IFGraph_Articulations::*)()>(&IFGraph_Articulations::Evaluate), R"nbdoc(Evaluates the list of Articulation points)nbdoc");
    nanoocp_implicit_copy_ctor<IFGraph_Articulations>(nb::borrow<nb::class_<IFGraph_Articulations>>(m.attr("IFGraph_Articulations")));
    nb::borrow<nb::class_<IFGraph_Compare>>(m.attr("IFGraph_Compare"))
        .def(nb::init<const Interface_Graph &>(), nb::arg("agraph"), R"nbdoc(creates empty Compare, ready to work)nbdoc")
        .def("GetFromEntity", static_cast<void (IFGraph_Compare::*)(const occ::handle<Standard_Transient> &, const bool)>(&IFGraph_Compare::GetFromEntity), nb::arg("ent").none(), nb::arg("first"), R"nbdoc(adds an entity and its shared ones to the list :
first True means adds to the first sub-list, else to the 2nd)nbdoc")
        .def("GetFromIter", static_cast<void (IFGraph_Compare::*)(const Interface_EntityIterator &, const bool)>(&IFGraph_Compare::GetFromIter), nb::arg("iter"), nb::arg("first"), R"nbdoc(adds a list of entities (as an iterator) as such, that is,
their shared entities are not considered (use AllShared to
have them)
first True means adds to the first sub-list, else to the 2nd)nbdoc")
        .def("Merge", static_cast<void (IFGraph_Compare::*)()>(&IFGraph_Compare::Merge), R"nbdoc(merges the second list into the first one, hence the second
list is empty)nbdoc")
        .def("RemoveSecond", static_cast<void (IFGraph_Compare::*)()>(&IFGraph_Compare::RemoveSecond), R"nbdoc(Removes the contents of second list)nbdoc")
        .def("KeepCommon", static_cast<void (IFGraph_Compare::*)()>(&IFGraph_Compare::KeepCommon), R"nbdoc(Keeps only Common part, sets it as First list and clears
second list)nbdoc")
        .def("ResetData", static_cast<void (IFGraph_Compare::*)()>(&IFGraph_Compare::ResetData), R"nbdoc(Allows to restart on a new data set)nbdoc")
        .def("Evaluate", static_cast<void (IFGraph_Compare::*)()>(&IFGraph_Compare::Evaluate), R"nbdoc(Recomputes result of comparing to sub-parts)nbdoc")
        .def("Common", static_cast<Interface_EntityIterator (IFGraph_Compare::*)() const>(&IFGraph_Compare::Common), R"nbdoc(returns entities common to the both parts)nbdoc")
        .def("FirstOnly", static_cast<Interface_EntityIterator (IFGraph_Compare::*)() const>(&IFGraph_Compare::FirstOnly), R"nbdoc(returns entities which are exclusively in the first list)nbdoc")
        .def("SecondOnly", static_cast<Interface_EntityIterator (IFGraph_Compare::*)() const>(&IFGraph_Compare::SecondOnly), R"nbdoc(returns entities which are exclusively in the second part)nbdoc");
    nanoocp_implicit_copy_ctor<IFGraph_Compare>(nb::borrow<nb::class_<IFGraph_Compare>>(m.attr("IFGraph_Compare")));
    nb::implicitly_convertible<std::decay_t<const Interface_Graph &>, IFGraph_Compare>();
    nb::borrow<nb::class_<IFGraph_SubPartsIterator>>(m.attr("IFGraph_SubPartsIterator"))
        .def(nb::init<IFGraph_SubPartsIterator &>(), nb::arg("other"), R"nbdoc(Creates a SubPartIterator from another one and gets its Data
Note that only non-empty sub-parts are taken into account
PartNum is set to the last one)nbdoc")
        .def(nb::init<const Interface_Graph &, const bool>(), nb::arg("agraph"), nb::arg("whole"), R"nbdoc(Creates with a Graph, whole or parts of it
whole True  : works on the entire Model
whole False : empty, ready to be filled
SubPartIterator is set to load entities)nbdoc")
        .def("GetParts", static_cast<void (IFGraph_SubPartsIterator::*)(IFGraph_SubPartsIterator &)>(&IFGraph_SubPartsIterator::GetParts), nb::arg("other"), R"nbdoc(Gets Parts from another SubPartsIterator (in addition to the
ones already recorded)
Error if both SubPartsIterators are not based on the same Model)nbdoc")
        .def("Model", static_cast<occ::handle<Interface_InterfaceModel> (IFGraph_SubPartsIterator::*)() const>(&IFGraph_SubPartsIterator::Model), R"nbdoc(Returns the Model with which this Iterator was created)nbdoc")
        .def("AddPart", static_cast<void (IFGraph_SubPartsIterator::*)()>(&IFGraph_SubPartsIterator::AddPart), R"nbdoc(Adds an empty part and sets it to receive entities)nbdoc")
        .def("NbParts", static_cast<int (IFGraph_SubPartsIterator::*)() const>(&IFGraph_SubPartsIterator::NbParts), R"nbdoc(Returns count of registered parts)nbdoc")
        .def("PartNum", static_cast<int (IFGraph_SubPartsIterator::*)() const>(&IFGraph_SubPartsIterator::PartNum), R"nbdoc(Returns numero of part which currently receives entities
(0 at load time))nbdoc")
        .def("SetLoad", static_cast<void (IFGraph_SubPartsIterator::*)()>(&IFGraph_SubPartsIterator::SetLoad), R"nbdoc(Sets SubPartIterator to get Entities (by GetFromEntity &
GetFromIter) into load status, to be analysed later)nbdoc")
        .def("SetPartNum", static_cast<void (IFGraph_SubPartsIterator::*)(const int)>(&IFGraph_SubPartsIterator::SetPartNum), nb::arg("num"), R"nbdoc(Sets numero of receiving part to a new value
Error if not in range (1-NbParts))nbdoc")
        .def("GetFromEntity", static_cast<void (IFGraph_SubPartsIterator::*)(const occ::handle<Standard_Transient> &, const bool)>(&IFGraph_SubPartsIterator::GetFromEntity), nb::arg("ent").none(), nb::arg("shared"), R"nbdoc(Adds an Entity : into load status if in Load mode, to the
current part if there is one. If shared is True, adds
also its shared ones (shared at all levels))nbdoc")
        .def("GetFromIter", static_cast<void (IFGraph_SubPartsIterator::*)(const Interface_EntityIterator &)>(&IFGraph_SubPartsIterator::GetFromIter), nb::arg("iter"), R"nbdoc(Adds a list of Entities (into Load mode or to a Part),
given as an Iterator)nbdoc")
        .def("Reset", static_cast<void (IFGraph_SubPartsIterator::*)()>(&IFGraph_SubPartsIterator::Reset), R"nbdoc(Erases data (parts, entities) : "me" becomes empty and in
load status)nbdoc")
        .def("Evaluate", static_cast<void (IFGraph_SubPartsIterator::*)()>(&IFGraph_SubPartsIterator::Evaluate), R"nbdoc(Called by Clear, this method allows evaluation just before
iteration; its default is doing nothing, it is designed to
be redefined)nbdoc")
        .def("Loaded", static_cast<Interface_GraphContent (IFGraph_SubPartsIterator::*)() const>(&IFGraph_SubPartsIterator::Loaded), R"nbdoc(Returns entities which where loaded (not set into a sub-part))nbdoc")
        .def("LoadedGraph", static_cast<Interface_Graph (IFGraph_SubPartsIterator::*)() const>(&IFGraph_SubPartsIterator::LoadedGraph), R"nbdoc(Same as above, but under the form of a Graph)nbdoc")
        .def("IsLoaded", static_cast<bool (IFGraph_SubPartsIterator::*)(const occ::handle<Standard_Transient> &) const>(&IFGraph_SubPartsIterator::IsLoaded), nb::arg("ent").none(), R"nbdoc(Returns True if an Entity is loaded (either set into a
sub-part or not))nbdoc")
        .def("IsInPart", static_cast<bool (IFGraph_SubPartsIterator::*)(const occ::handle<Standard_Transient> &) const>(&IFGraph_SubPartsIterator::IsInPart), nb::arg("ent").none(), R"nbdoc(Returns True if an Entity is Present in a sub-part)nbdoc")
        .def("EntityPartNum", static_cast<int (IFGraph_SubPartsIterator::*)(const occ::handle<Standard_Transient> &) const>(&IFGraph_SubPartsIterator::EntityPartNum), nb::arg("ent").none(), R"nbdoc(Returns number of the sub-part in which an Entity has been set
if it is not in a sub-part (or not loaded at all), Returns 0)nbdoc")
        .def("Start", static_cast<void (IFGraph_SubPartsIterator::*)()>(&IFGraph_SubPartsIterator::Start), R"nbdoc(Sets iteration to its beginning; calls Evaluate)nbdoc")
        .def("More", static_cast<bool (IFGraph_SubPartsIterator::*)()>(&IFGraph_SubPartsIterator::More), R"nbdoc(Returns True if there are more sub-parts to iterate on
Note : an empty sub-part is not taken in account by Iteration)nbdoc")
        .def("Next", static_cast<void (IFGraph_SubPartsIterator::*)()>(&IFGraph_SubPartsIterator::Next), R"nbdoc(Sets iteration to the next sub-part
if there is not, IsSingle-Entities will raises an exception)nbdoc")
        .def("IsSingle", static_cast<bool (IFGraph_SubPartsIterator::*)() const>(&IFGraph_SubPartsIterator::IsSingle), R"nbdoc(Returns True if current sub-part is single (has only one Entity)
Error if there is no sub-part to iterate now)nbdoc")
        .def("FirstEntity", static_cast<occ::handle<Standard_Transient> (IFGraph_SubPartsIterator::*)() const>(&IFGraph_SubPartsIterator::FirstEntity), R"nbdoc(Returns the first entity of current sub-part, that is for a
Single one, the only one it contains
Error : same as above (end of iteration))nbdoc")
        .def("Entities", static_cast<Interface_EntityIterator (IFGraph_SubPartsIterator::*)() const>(&IFGraph_SubPartsIterator::Entities), R"nbdoc(Returns current sub-part, not as a "Value", but as an Iterator
on Entities it contains
Error : same as above (end of iteration))nbdoc");
    nb::borrow<nb::class_<IFGraph_ConnectedComponants>>(m.attr("IFGraph_ConnectedComponants"))
        .def(nb::init<const Interface_Graph &, const bool>(), nb::arg("agraph"), nb::arg("whole"), R"nbdoc(creates with a Graph, and will analyse :
whole True  : all the contents of the Model
whole False : sub-parts which will be given later)nbdoc")
        .def("Evaluate", static_cast<void (IFGraph_ConnectedComponants::*)()>(&IFGraph_ConnectedComponants::Evaluate), R"nbdoc(does the computation)nbdoc");
    nanoocp_implicit_copy_ctor<IFGraph_ConnectedComponants>(nb::borrow<nb::class_<IFGraph_ConnectedComponants>>(m.attr("IFGraph_ConnectedComponants")));
    nb::borrow<nb::class_<IFGraph_Cumulate>>(m.attr("IFGraph_Cumulate"))
        .def(nb::init<const Interface_Graph &>(), nb::arg("agraph"), R"nbdoc(creates empty Cumulate, ready to work)nbdoc")
        .def("GetFromEntity", static_cast<void (IFGraph_Cumulate::*)(const occ::handle<Standard_Transient> &)>(&IFGraph_Cumulate::GetFromEntity), nb::arg("ent").none(), R"nbdoc(adds an entity and its shared ones to the list)nbdoc")
        .def("GetFromIter", static_cast<void (IFGraph_Cumulate::*)(const Interface_EntityIterator &)>(&IFGraph_Cumulate::GetFromIter), nb::arg("iter"), R"nbdoc(adds a list of entities (as an iterator) as such, that is,
without their shared entities (use AllShared to have them))nbdoc")
        .def("ResetData", static_cast<void (IFGraph_Cumulate::*)()>(&IFGraph_Cumulate::ResetData), R"nbdoc(Allows to restart on a new data set)nbdoc")
        .def("Evaluate", static_cast<void (IFGraph_Cumulate::*)()>(&IFGraph_Cumulate::Evaluate), R"nbdoc(Evaluates the result of cumulation)nbdoc")
        .def("Overlapped", static_cast<Interface_EntityIterator (IFGraph_Cumulate::*)() const>(&IFGraph_Cumulate::Overlapped), R"nbdoc(returns entities which are taken several times)nbdoc")
        .def("Forgotten", static_cast<Interface_EntityIterator (IFGraph_Cumulate::*)() const>(&IFGraph_Cumulate::Forgotten), R"nbdoc(returns entities which are not taken)nbdoc")
        .def("PerCount", static_cast<Interface_EntityIterator (IFGraph_Cumulate::*)(const int) const>(&IFGraph_Cumulate::PerCount), nb::arg("count") = static_cast<std::decay_t<const int>>(1), R"nbdoc(Returns entities taken a given count of times
(0 : same as Forgotten, 1 : same as no Overlap : default))nbdoc")
        .def("NbTimes", static_cast<int (IFGraph_Cumulate::*)(const occ::handle<Standard_Transient> &) const>(&IFGraph_Cumulate::NbTimes), nb::arg("ent").none(), R"nbdoc(returns number of times an Entity has been counted
(0 means forgotten, more than 1 means overlap, 1 is normal))nbdoc")
        .def("HighestNbTimes", static_cast<int (IFGraph_Cumulate::*)() const>(&IFGraph_Cumulate::HighestNbTimes), R"nbdoc(Returns the highest number of times recorded for every Entity
(0 means empty, 1 means no overlap))nbdoc");
    nanoocp_implicit_copy_ctor<IFGraph_Cumulate>(nb::borrow<nb::class_<IFGraph_Cumulate>>(m.attr("IFGraph_Cumulate")));
    nb::implicitly_convertible<std::decay_t<const Interface_Graph &>, IFGraph_Cumulate>();
    nb::borrow<nb::class_<IFGraph_Cycles>>(m.attr("IFGraph_Cycles"))
        .def(nb::init<IFGraph_StrongComponants &>(), nb::arg("subparts"), R"nbdoc(creates from a StrongComponants which was already computed)nbdoc")
        .def(nb::init<const Interface_Graph &, const bool>(), nb::arg("agraph"), nb::arg("whole"), R"nbdoc(creates with a Graph, and will analyse :
whole True  : all the contents of the Model
whole False : sub-parts which will be given later)nbdoc")
        .def("Evaluate", static_cast<void (IFGraph_Cycles::*)()>(&IFGraph_Cycles::Evaluate), R"nbdoc(does the computation. Cycles are StrongComponants which are
not Single)nbdoc");
    nanoocp_implicit_copy_ctor<IFGraph_Cycles>(nb::borrow<nb::class_<IFGraph_Cycles>>(m.attr("IFGraph_Cycles")));
    nb::implicitly_convertible<std::decay_t<IFGraph_StrongComponants &>, IFGraph_Cycles>();
    nb::borrow<nb::class_<IFGraph_ExternalSources>>(m.attr("IFGraph_ExternalSources"))
        .def(nb::init<const Interface_Graph &>(), nb::arg("agraph"), R"nbdoc(creates empty ExternalSources, ready to work)nbdoc")
        .def("GetFromEntity", static_cast<void (IFGraph_ExternalSources::*)(const occ::handle<Standard_Transient> &)>(&IFGraph_ExternalSources::GetFromEntity), nb::arg("ent").none(), R"nbdoc(adds an entity and its shared ones to the list)nbdoc")
        .def("GetFromIter", static_cast<void (IFGraph_ExternalSources::*)(const Interface_EntityIterator &)>(&IFGraph_ExternalSources::GetFromIter), nb::arg("iter"), R"nbdoc(adds a list of entities (as an iterator) with shared ones)nbdoc")
        .def("ResetData", static_cast<void (IFGraph_ExternalSources::*)()>(&IFGraph_ExternalSources::ResetData), R"nbdoc(Allows to restart on a new data set)nbdoc")
        .def("Evaluate", static_cast<void (IFGraph_ExternalSources::*)()>(&IFGraph_ExternalSources::Evaluate), R"nbdoc(Evaluates external sources of a set of entities)nbdoc")
        .def("IsEmpty", static_cast<bool (IFGraph_ExternalSources::*)()>(&IFGraph_ExternalSources::IsEmpty), R"nbdoc(Returns True if no External Source are found
It means that we have a "root" set
(performs an Evaluation as necessary))nbdoc");
    nanoocp_implicit_copy_ctor<IFGraph_ExternalSources>(nb::borrow<nb::class_<IFGraph_ExternalSources>>(m.attr("IFGraph_ExternalSources")));
    nb::implicitly_convertible<std::decay_t<const Interface_Graph &>, IFGraph_ExternalSources>();
    nb::borrow<nb::class_<IFGraph_StrongComponants>>(m.attr("IFGraph_StrongComponants"))
        .def(nb::init<const Interface_Graph &, const bool>(), nb::arg("agraph"), nb::arg("whole"), R"nbdoc(creates with a Graph, and will analyse :
whole True  : all the contents of the Model
whole False : sub-parts which will be given later)nbdoc")
        .def("Evaluate", static_cast<void (IFGraph_StrongComponants::*)()>(&IFGraph_StrongComponants::Evaluate), R"nbdoc(does the computation)nbdoc");
    nanoocp_implicit_copy_ctor<IFGraph_StrongComponants>(nb::borrow<nb::class_<IFGraph_StrongComponants>>(m.attr("IFGraph_StrongComponants")));
    nb::borrow<nb::class_<IFGraph_SCRoots>>(m.attr("IFGraph_SCRoots"))
        .def(nb::init<IFGraph_StrongComponants &>(), nb::arg("subparts"), R"nbdoc(creates from a StrongComponants which was already computed)nbdoc")
        .def(nb::init<const Interface_Graph &, const bool>(), nb::arg("agraph"), nb::arg("whole"), R"nbdoc(creates with a Graph, and will analyse :
whole True  : all the contents of the Model
whole False : sub-parts which will be given later)nbdoc")
        .def("Evaluate", static_cast<void (IFGraph_SCRoots::*)()>(&IFGraph_SCRoots::Evaluate), R"nbdoc(does the computation)nbdoc");
    nanoocp_implicit_copy_ctor<IFGraph_SCRoots>(nb::borrow<nb::class_<IFGraph_SCRoots>>(m.attr("IFGraph_SCRoots")));
    nb::implicitly_convertible<std::decay_t<IFGraph_StrongComponants &>, IFGraph_SCRoots>();
}

void nanoocp_conversions_IFGraph(nb::module_ &m) {
}
