// Generated by the nanoOCP generator from OCCT package PrsMgr (toolkit TKV3d). Do not edit.
#include "nanoocp_common.h"
#include "nanoocp_ncollection.h"
#include <PrsMgr_DisplayStatus.hxx>
#include <PrsMgr_ListOfPresentableObjects.hxx>
#include <PrsMgr_PresentableObject.hxx>
#include <PrsMgr_Presentation.hxx>
#include <PrsMgr_PresentationManager.hxx>
#include <PrsMgr_TypeOfPresentation3d.hxx>
#include <Aspect_TypeOfFacingModel.hxx>
#include <Bnd_Box.hxx>
#include <Graphic3d_Camera.hxx>
#include <Graphic3d_ClipPlane.hxx>
#include <Graphic3d_DisplayPriority.hxx>
#include <Graphic3d_MaterialAspect.hxx>
#include <Graphic3d_NameOfMaterial.hxx>
#include <Graphic3d_SequenceOfHClipPlane.hxx>
#include <Graphic3d_Structure.hxx>
#include <Graphic3d_StructureManager.hxx>
#include <Graphic3d_TransformPers.hxx>
#include <Graphic3d_ViewAffinity.hxx>
#include <Graphic3d_ZLayerId.hxx>
#include <NCollection_List.hxx>
#include <NCollection_Sequence.hxx>
#include <Prs3d_Drawer.hxx>
#include <Prs3d_Presentation.hxx>
#include <Quantity_Color.hxx>
#include <Standard_OStream.hxx>
#include <Standard_Transient.hxx>
#include <Standard_Type.hxx>
#include <TopLoc_Datum3D.hxx>
#include <V3d_Viewer.hxx>
#include <gp_GTrsf.hxx>
#include <gp_Trsf.hxx>

void nanoocp_declare_PrsMgr(nb::module_ &m) {
    nb::enum_<PrsMgr_DisplayStatus>(m, "PrsMgr_DisplayStatus", R"nbdoc(To give the display status of an Interactive Object.)nbdoc", nb::is_arithmetic())
        .value("PrsMgr_DisplayStatus_Displayed", PrsMgr_DisplayStatus_Displayed)
        .value("PrsMgr_DisplayStatus_Erased", PrsMgr_DisplayStatus_Erased)
        .value("PrsMgr_DisplayStatus_None", PrsMgr_DisplayStatus_None)
        .value("AIS_DS_Displayed", AIS_DS_Displayed)
        .value("AIS_DS_Erased", AIS_DS_Erased)
        .value("AIS_DS_None", AIS_DS_None)
        .export_values();
    m.attr("AIS_DS_Displayed") = m.attr("PrsMgr_DisplayStatus").attr("AIS_DS_Displayed");
    m.attr("AIS_DS_Erased") = m.attr("PrsMgr_DisplayStatus").attr("AIS_DS_Erased");
    m.attr("AIS_DS_None") = m.attr("PrsMgr_DisplayStatus").attr("AIS_DS_None");
    nb::enum_<PrsMgr_TypeOfPresentation3d>(m, "PrsMgr_TypeOfPresentation3d", R"nbdoc(The type of presentation.)nbdoc", nb::is_arithmetic())
        .value("PrsMgr_TOP_AllView", PrsMgr_TOP_AllView)
        .value("PrsMgr_TOP_ProjectorDependent", PrsMgr_TOP_ProjectorDependent)
        .export_values();
    { nb::class_<PrsMgr_Presentation, Graphic3d_Structure> cls(m, "PrsMgr_Presentation");
    }
    { nb::class_<PrsMgr_PresentableObject, Standard_Transient> cls(m, "PrsMgr_PresentableObject", R"nbdoc(A framework to supply the Graphic3d structure of the object to be presented.
On the first display request, this structure is created by calling the appropriate algorithm and
retaining this framework for further display. This abstract framework is inherited in
Application Interactive Services (AIS), notably by AIS_InteractiveObject. Consequently, 3D
presentation should be handled by the relevant daughter classes and their member functions in
AIS. This is particularly true in the creation of new interactive objects.

Key interface methods to be implemented by every Selectable Object:
- AcceptDisplayMode() accepting display modes implemented by this object;
- Compute() computing presentation for the given display mode index.

Warning! Methods managing standard attributes (SetColor(), SetWidth(), SetMaterial()) have
different meaning for objects of different type (or no meaning at all). Sub-classes might
override these methods to modify Prs3d_Drawer or class properties providing a convenient
short-cut depending on application needs. For more sophisticated configuring, Prs3d_Drawer
should be modified directly, while short-cuts might be left unimplemented.)nbdoc");
    }
    { nb::class_<PrsMgr_PresentationManager, Standard_Transient> cls(m, "PrsMgr_PresentationManager", R"nbdoc(A framework to manage 3D displays, graphic entities and their updates.
Used in the AIS package (Application Interactive Services), to enable the advanced user to
define the default display mode of a new interactive object which extends the list of signatures
and types. Definition of new display types is handled by calling the presentation algorithms
provided by the StdPrs package.)nbdoc");
    }
}

void nanoocp_templates_PrsMgr(nb::module_ &m) {
    { nb::module_ home = nb::module_::import_("nanoocp._TKernel.NCollection"); nanoocp::bind_NCollection_List<opencascade::handle<PrsMgr_PresentableObject>>(home, "NCollection_List__Handle_PrsMgr_PresentableObject"); }
    { nb::module_ home = nb::module_::import_("nanoocp._TKernel.NCollection"); nanoocp::bind_NCollection_Sequence<opencascade::handle<PrsMgr_Presentation>>(home, "NCollection_Sequence__Handle_PrsMgr_Presentation"); }
}

void nanoocp_define_PrsMgr(nb::module_ &m) {
    nb::borrow<nb::class_<PrsMgr_Presentation>>(m.attr("PrsMgr_Presentation"))
        .def_static("get_type_name", static_cast<const char * (*)()>(&PrsMgr_Presentation::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&PrsMgr_Presentation::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (PrsMgr_Presentation::*)() const>(&PrsMgr_Presentation::DynamicType))
        .def("Presentation", [](PrsMgr_Presentation &self) { opencascade::handle<Graphic3d_Structure> nanoocp_result(self.Presentation()); return nanoocp_result; }, R"nbdoc(Deprecated in OCCT: Dummy to simplify porting - returns self)nbdoc")
        .def("PresentationManager", static_cast<const occ::handle<PrsMgr_PresentationManager> & (PrsMgr_Presentation::*)() const>(&PrsMgr_Presentation::PresentationManager), R"nbdoc(returns the PresentationManager in which the presentation has been created.)nbdoc")
        .def("SetUpdateStatus", static_cast<void (PrsMgr_Presentation::*)(const bool)>(&PrsMgr_Presentation::SetUpdateStatus), nb::arg("theUpdateStatus"))
        .def("MustBeUpdated", static_cast<bool (PrsMgr_Presentation::*)() const>(&PrsMgr_Presentation::MustBeUpdated))
        .def("Mode", static_cast<int (PrsMgr_Presentation::*)() const>(&PrsMgr_Presentation::Mode), R"nbdoc(Return display mode index.)nbdoc")
        .def("Display", static_cast<void (PrsMgr_Presentation::*)()>(&PrsMgr_Presentation::Display), R"nbdoc(Display structure.)nbdoc")
        .def("Erase", static_cast<void (PrsMgr_Presentation::*)()>(&PrsMgr_Presentation::Erase), R"nbdoc(Remove structure.)nbdoc")
        .def("Highlight", static_cast<void (PrsMgr_Presentation::*)(const occ::handle<Prs3d_Drawer> &)>(&PrsMgr_Presentation::Highlight), nb::arg("theStyle").none(), R"nbdoc(Highlight structure.)nbdoc")
        .def("Unhighlight", static_cast<void (PrsMgr_Presentation::*)()>(&PrsMgr_Presentation::Unhighlight), R"nbdoc(Unhighlight structure.)nbdoc")
        .def("IsDisplayed", static_cast<bool (PrsMgr_Presentation::*)() const>(&PrsMgr_Presentation::IsDisplayed), R"nbdoc(Return TRUE if structure has been displayed and in no hidden state.)nbdoc")
        .def("Clear", static_cast<void (PrsMgr_Presentation::*)(const bool)>(&PrsMgr_Presentation::Clear), nb::arg("theWithDestruction") = static_cast<std::decay_t<const bool>>(true), R"nbdoc(removes the whole content of the presentation.
Does not remove the other connected presentations.)nbdoc")
        .def("Compute", static_cast<void (PrsMgr_Presentation::*)()>(&PrsMgr_Presentation::Compute), R"nbdoc(Compute structure using presentation manager.)nbdoc")
        .def("DumpJson", [](const PrsMgr_Presentation &self, int theDepth) { std::ostringstream theOStream_stream; self.DumpJson(theOStream_stream, theDepth); return nanoocp_stream_text(theOStream_stream); }, nb::arg("theDepth") = static_cast<std::decay_t<int>>(- 1), R"nbdoc(Dumps the content of me into the stream)nbdoc");
    nanoocp_implicit_copy_ctor<PrsMgr_Presentation>(nb::borrow<nb::class_<PrsMgr_Presentation>>(m.attr("PrsMgr_Presentation")));
    nb::borrow<nb::class_<PrsMgr_PresentableObject>>(m.attr("PrsMgr_PresentableObject"))
        .def_static("get_type_name", static_cast<const char * (*)()>(&PrsMgr_PresentableObject::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&PrsMgr_PresentableObject::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::DynamicType))
        .def("Presentations", static_cast<NCollection_Sequence<opencascade::handle<PrsMgr_Presentation>> & (PrsMgr_PresentableObject::*)()>(&PrsMgr_PresentableObject::Presentations), nb::rv_policy::reference_internal, R"nbdoc(Return presentations.)nbdoc")
        .def("ZLayer", static_cast<Graphic3d_ZLayerId (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::ZLayer), R"nbdoc(Get ID of Z layer for main presentation.)nbdoc")
        .def("SetZLayer", static_cast<void (PrsMgr_PresentableObject::*)(const Graphic3d_ZLayerId)>(&PrsMgr_PresentableObject::SetZLayer), nb::arg("theLayerId"), R"nbdoc(Set Z layer ID and update all presentations of the presentable object.
The layers mechanism allows drawing objects in higher layers in overlay of objects in lower
layers.)nbdoc")
        .def("IsMutable", static_cast<bool (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::IsMutable), R"nbdoc(Returns true if object has mutable nature (content or location are be changed regularly).
Mutable object will be managed in different way than static onces (another optimizations).)nbdoc")
        .def("SetMutable", static_cast<void (PrsMgr_PresentableObject::*)(const bool)>(&PrsMgr_PresentableObject::SetMutable), nb::arg("theIsMutable"), R"nbdoc(Sets if the object has mutable nature (content or location will be changed regularly).
This method should be called before object displaying to take effect.)nbdoc")
        .def("ViewAffinity", static_cast<const occ::handle<Graphic3d_ViewAffinity> & (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::ViewAffinity), R"nbdoc(Return view affinity mask.)nbdoc")
        .def("HasDisplayMode", static_cast<bool (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::HasDisplayMode), R"nbdoc(Returns true if the Interactive Object has display mode setting overriding global setting
(within Interactive Context).)nbdoc")
        .def("DisplayMode", static_cast<int (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::DisplayMode), R"nbdoc(Returns the display mode setting of the Interactive Object.
The range of supported display mode indexes should be specified within object definition and
filtered by AccepDisplayMode().
@sa AcceptDisplayMode())nbdoc")
        .def("SetDisplayMode", static_cast<void (PrsMgr_PresentableObject::*)(const int)>(&PrsMgr_PresentableObject::SetDisplayMode), nb::arg("theMode"), R"nbdoc(Sets the display mode for the interactive object.
An object can have its own temporary display mode, which is different from that proposed by
the interactive context.
@sa AcceptDisplayMode())nbdoc")
        .def("UnsetDisplayMode", static_cast<void (PrsMgr_PresentableObject::*)()>(&PrsMgr_PresentableObject::UnsetDisplayMode), R"nbdoc(Removes display mode settings from the interactive object.)nbdoc")
        .def("HasHilightMode", static_cast<bool (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::HasHilightMode), R"nbdoc(Returns true if the Interactive Object is in highlight mode.
@sa HilightAttributes())nbdoc")
        .def("HilightMode", static_cast<int (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::HilightMode), R"nbdoc(Returns highlight display mode.
This is obsolete method for backward compatibility - use ::HilightAttributes() and
::DynamicHilightAttributes() instead.
@sa HilightAttributes())nbdoc")
        .def("SetHilightMode", static_cast<void (PrsMgr_PresentableObject::*)(const int)>(&PrsMgr_PresentableObject::SetHilightMode), nb::arg("theMode"), R"nbdoc(Sets highlight display mode.
This is obsolete method for backward compatibility - use ::HilightAttributes() and
::DynamicHilightAttributes() instead.
@sa HilightAttributes())nbdoc")
        .def("UnsetHilightMode", static_cast<void (PrsMgr_PresentableObject::*)()>(&PrsMgr_PresentableObject::UnsetHilightMode), R"nbdoc(Unsets highlight display mode.
@sa HilightAttributes())nbdoc")
        .def("AcceptDisplayMode", static_cast<bool (PrsMgr_PresentableObject::*)(const int) const>(&PrsMgr_PresentableObject::AcceptDisplayMode), nb::arg("theMode"), R"nbdoc(Returns true if the class of objects accepts specified display mode index.
The interactive context can have a default mode of representation for the set of Interactive
Objects. This mode may not be accepted by a given class of objects. Consequently, this virtual
method allowing us to get information about the class in question must be implemented. At
least one display mode index should be accepted by this method. Although subclass can leave
default implementation, it is highly desired defining exact list of supported modes instead,
which is usually an enumeration for one object or objects class sharing similar list of
display modes.)nbdoc")
        .def("DefaultDisplayMode", static_cast<int (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::DefaultDisplayMode), R"nbdoc(Returns the default display mode.)nbdoc")
        .def("ToBeUpdated", static_cast<bool (PrsMgr_PresentableObject::*)(bool) const>(&PrsMgr_PresentableObject::ToBeUpdated), nb::arg("theToIncludeHidden") = static_cast<std::decay_t<bool>>(false), R"nbdoc(Returns TRUE if any active presentation has invalidation flag.
@param theToIncludeHidden when TRUE, also checks hidden presentations)nbdoc")
        .def("SetToUpdate", static_cast<void (PrsMgr_PresentableObject::*)(int)>(&PrsMgr_PresentableObject::SetToUpdate), nb::arg("theMode"), R"nbdoc(Flags presentation to be updated; UpdatePresentations() will recompute these presentations.
@param theMode presentation (display mode) to invalidate, or -1 to invalidate them all)nbdoc")
        .def("SetToUpdate", static_cast<void (PrsMgr_PresentableObject::*)()>(&PrsMgr_PresentableObject::SetToUpdate), R"nbdoc(flags all the Presentations to be Updated.)nbdoc")
        .def("IsInfinite", static_cast<bool (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::IsInfinite), R"nbdoc(Returns true if the interactive object is infinite; FALSE by default.
This flag affects various operations operating on bounding box of graphic presentations of
this object. For instance, infinite objects are not taken in account for View FitAll. This
does not necessarily means that object is actually infinite, auxiliary objects might be also
marked with this flag to achieve desired behavior.)nbdoc")
        .def("SetInfiniteState", static_cast<void (PrsMgr_PresentableObject::*)(const bool)>(&PrsMgr_PresentableObject::SetInfiniteState), nb::arg("theFlag") = static_cast<std::decay_t<const bool>>(true), R"nbdoc(Sets if object should be considered as infinite.)nbdoc")
        .def("TypeOfPresentation3d", static_cast<PrsMgr_TypeOfPresentation3d (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::TypeOfPresentation3d), R"nbdoc(Returns information on whether the object accepts display in HLR mode or not.)nbdoc")
        .def("SetTypeOfPresentation", static_cast<void (PrsMgr_PresentableObject::*)(const PrsMgr_TypeOfPresentation3d)>(&PrsMgr_PresentableObject::SetTypeOfPresentation), nb::arg("theType"), R"nbdoc(Set type of presentation.)nbdoc")
        .def("DisplayStatus", static_cast<PrsMgr_DisplayStatus (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::DisplayStatus), R"nbdoc(Return presentation display status; PrsMgr_DisplayStatus_None by default.)nbdoc")
        .def("Attributes", static_cast<const occ::handle<Prs3d_Drawer> & (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::Attributes), R"nbdoc(@name presentation attributes
Returns the attributes settings.)nbdoc")
        .def("SetAttributes", static_cast<void (PrsMgr_PresentableObject::*)(const occ::handle<Prs3d_Drawer> &)>(&PrsMgr_PresentableObject::SetAttributes), nb::arg("theDrawer").none(), R"nbdoc(Initializes the drawing tool theDrawer.)nbdoc")
        .def("HilightAttributes", static_cast<const occ::handle<Prs3d_Drawer> & (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::HilightAttributes), R"nbdoc(Returns the hilight attributes settings.
When not NULL, overrides both Prs3d_TypeOfHighlight_LocalSelected and
Prs3d_TypeOfHighlight_Selected defined within AIS_InteractiveContext::HighlightStyle().
@sa AIS_InteractiveContext::HighlightStyle())nbdoc")
        .def("SetHilightAttributes", static_cast<void (PrsMgr_PresentableObject::*)(const occ::handle<Prs3d_Drawer> &)>(&PrsMgr_PresentableObject::SetHilightAttributes), nb::arg("theDrawer").none(), R"nbdoc(Initializes the hilight drawing tool theDrawer.)nbdoc")
        .def("DynamicHilightAttributes", static_cast<const occ::handle<Prs3d_Drawer> & (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::DynamicHilightAttributes), R"nbdoc(Returns the hilight attributes settings.
When not NULL, overrides both Prs3d_TypeOfHighlight_LocalDynamic and
Prs3d_TypeOfHighlight_Dynamic defined within AIS_InteractiveContext::HighlightStyle().
@sa AIS_InteractiveContext::HighlightStyle())nbdoc")
        .def("SetDynamicHilightAttributes", static_cast<void (PrsMgr_PresentableObject::*)(const occ::handle<Prs3d_Drawer> &)>(&PrsMgr_PresentableObject::SetDynamicHilightAttributes), nb::arg("theDrawer").none(), R"nbdoc(Initializes the dynamic hilight drawing tool.)nbdoc")
        .def("UnsetHilightAttributes", static_cast<void (PrsMgr_PresentableObject::*)()>(&PrsMgr_PresentableObject::UnsetHilightAttributes), R"nbdoc(Clears settings provided by the hilight drawing tool theDrawer.)nbdoc")
        .def("SynchronizeAspects", static_cast<void (PrsMgr_PresentableObject::*)()>(&PrsMgr_PresentableObject::SynchronizeAspects), R"nbdoc(Synchronize presentation aspects after their modification.

This method should be called after modifying primitive aspect properties (material, texture,
shader) so that modifications will take effect on already computed presentation groups (thus
avoiding re-displaying the object).)nbdoc")
        .def("TransformPersistence", static_cast<const occ::handle<Graphic3d_TransformPers> & (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::TransformPersistence), R"nbdoc(@name object transformation
Returns Transformation Persistence defining a special Local Coordinate system where this
presentable object is located or NULL handle if not defined. Position of the object having
Transformation Persistence is mutable and depends on camera position. The same applies to a
bounding box of the object.
@sa Graphic3d_TransformPers class description)nbdoc")
        .def("SetTransformPersistence", static_cast<void (PrsMgr_PresentableObject::*)(const occ::handle<Graphic3d_TransformPers> &)>(&PrsMgr_PresentableObject::SetTransformPersistence), nb::arg("theTrsfPers").none(), R"nbdoc(Sets up Transform Persistence defining a special Local Coordinate system where this object
should be located. Note that management of Transform Persistence object is more expensive than
of the normal one, because it requires its position being recomputed basing on camera position
within each draw call / traverse.
@sa Graphic3d_TransformPers class description)nbdoc")
        .def("LocalTransformationGeom", static_cast<const occ::handle<TopLoc_Datum3D> & (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::LocalTransformationGeom), R"nbdoc(Return the local transformation.
Note that the local transformation of the object having Transformation Persistence
is applied within Local Coordinate system defined by this Persistence.)nbdoc")
        .def("SetLocalTransformation", static_cast<void (PrsMgr_PresentableObject::*)(const gp_Trsf &)>(&PrsMgr_PresentableObject::SetLocalTransformation), nb::arg("theTrsf"), R"nbdoc(Sets local transformation to theTransformation.
Note that the local transformation of the object having Transformation Persistence
is applied within Local Coordinate system defined by this Persistence.)nbdoc")
        .def("SetLocalTransformation", static_cast<void (PrsMgr_PresentableObject::*)(const occ::handle<TopLoc_Datum3D> &)>(&PrsMgr_PresentableObject::SetLocalTransformation), nb::arg("theTrsf").none(), R"nbdoc(Sets local transformation to theTransformation.
Note that the local transformation of the object having Transformation Persistence
is applied within Local Coordinate system defined by this Persistence.)nbdoc")
        .def("HasTransformation", static_cast<bool (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::HasTransformation), R"nbdoc(Returns true if object has a transformation that is different from the identity.)nbdoc")
        .def("TransformationGeom", static_cast<const occ::handle<TopLoc_Datum3D> & (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::TransformationGeom), R"nbdoc(Return the transformation taking into account transformation of parent object(s).
Note that the local transformation of the object having Transformation Persistence
is applied within Local Coordinate system defined by this Persistence.)nbdoc")
        .def("LocalTransformation", static_cast<const gp_Trsf & (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::LocalTransformation), R"nbdoc(Return the local transformation.
Note that the local transformation of the object having Transformation Persistence
is applied within Local Coordinate system defined by this Persistence.)nbdoc")
        .def("Transformation", static_cast<const gp_Trsf & (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::Transformation), R"nbdoc(Return the transformation taking into account transformation of parent object(s).
Note that the local transformation of the object having Transformation Persistence
is applied within Local Coordinate system defined by this Persistence.)nbdoc")
        .def("InversedTransformation", static_cast<const gp_GTrsf & (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::InversedTransformation), R"nbdoc(Return inversed transformation.)nbdoc")
        .def("CombinedParentTransformation", static_cast<const occ::handle<TopLoc_Datum3D> & (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::CombinedParentTransformation), R"nbdoc(Return combined parent transformation.)nbdoc")
        .def("ResetTransformation", static_cast<void (PrsMgr_PresentableObject::*)()>(&PrsMgr_PresentableObject::ResetTransformation), R"nbdoc(resets local transformation to identity.)nbdoc")
        .def("UpdateTransformation", static_cast<void (PrsMgr_PresentableObject::*)()>(&PrsMgr_PresentableObject::UpdateTransformation), R"nbdoc(Updates final transformation (parent + local) of presentable object and its presentations.)nbdoc")
        .def("RecomputeTransformation", static_cast<void (PrsMgr_PresentableObject::*)(const occ::handle<Graphic3d_Camera> &)>(&PrsMgr_PresentableObject::RecomputeTransformation), nb::arg("theProjector").none(), R"nbdoc(Calculates object presentation for specific camera position.
Each of the views in the viewer and every modification such as rotation, for example, entails
recalculation.
@param theProjector [in] view orientation)nbdoc")
        .def("ClipPlanes", static_cast<const occ::handle<Graphic3d_SequenceOfHClipPlane> & (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::ClipPlanes), R"nbdoc(@name clipping planes
Get clip planes.
@return set of previously added clip planes for all display mode presentations.)nbdoc")
        .def("SetClipPlanes", static_cast<void (PrsMgr_PresentableObject::*)(const occ::handle<Graphic3d_SequenceOfHClipPlane> &)>(&PrsMgr_PresentableObject::SetClipPlanes), nb::arg("thePlanes").none(), R"nbdoc(Set clip planes for graphical clipping for all display mode presentations.
The composition of clip planes truncates the rendering space to convex volume.
Please be aware that number of supported clip plane is limited.
The planes which exceed the limit are ignored.
Besides of this, some planes can be already set in view where the object is shown:
the number of these planes should be subtracted from limit to predict the maximum
possible number of object clipping planes.)nbdoc")
        .def("AddClipPlane", static_cast<void (PrsMgr_PresentableObject::*)(const occ::handle<Graphic3d_ClipPlane> &)>(&PrsMgr_PresentableObject::AddClipPlane), nb::arg("thePlane").none(), R"nbdoc(Adds clip plane for graphical clipping for all display mode
presentations. The composition of clip planes truncates the rendering
space to convex volume. Please be aware that number of supported
clip plane is limited. The planes which exceed the limit are ignored.
Besides of this, some planes can be already set in view where the object
is shown: the number of these planes should be subtracted from limit
to predict the maximum possible number of object clipping planes.
@param[in] thePlane  the clip plane to be appended to map of clip planes.)nbdoc")
        .def("RemoveClipPlane", static_cast<void (PrsMgr_PresentableObject::*)(const occ::handle<Graphic3d_ClipPlane> &)>(&PrsMgr_PresentableObject::RemoveClipPlane), nb::arg("thePlane").none(), R"nbdoc(Removes previously added clip plane.
@param[in] thePlane  the clip plane to be removed from map of clip planes.)nbdoc")
        .def("Parent", [](const PrsMgr_PresentableObject &self) { opencascade::handle<PrsMgr_PresentableObject> nanoocp_result(self.Parent()); return nanoocp_result; }, R"nbdoc(@name parent/children properties
Returns parent of current object in scene hierarchy.)nbdoc")
        .def("Children", static_cast<const NCollection_List<opencascade::handle<PrsMgr_PresentableObject>> & (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::Children), R"nbdoc(Returns children of the current object.)nbdoc")
        .def("AddChild", static_cast<void (PrsMgr_PresentableObject::*)(const occ::handle<PrsMgr_PresentableObject> &)>(&PrsMgr_PresentableObject::AddChild), nb::arg("theObject").none(), R"nbdoc(Makes theObject child of current object in scene hierarchy.)nbdoc")
        .def("AddChildWithCurrentTransformation", static_cast<void (PrsMgr_PresentableObject::*)(const occ::handle<PrsMgr_PresentableObject> &)>(&PrsMgr_PresentableObject::AddChildWithCurrentTransformation), nb::arg("theObject").none(), R"nbdoc(Makes theObject child of current object in scene hierarchy with keeping the current global
transformation So the object keeps the same position/orientation in the global CS.)nbdoc")
        .def("RemoveChild", static_cast<void (PrsMgr_PresentableObject::*)(const occ::handle<PrsMgr_PresentableObject> &)>(&PrsMgr_PresentableObject::RemoveChild), nb::arg("theObject").none(), R"nbdoc(Removes theObject from children of current object in scene hierarchy.)nbdoc")
        .def("RemoveChildWithRestoreTransformation", static_cast<void (PrsMgr_PresentableObject::*)(const occ::handle<PrsMgr_PresentableObject> &)>(&PrsMgr_PresentableObject::RemoveChildWithRestoreTransformation), nb::arg("theObject").none(), R"nbdoc(Removes theObject from children of current object in scene hierarchy with keeping the current
global transformation. So the object keeps the same position/orientation in the global CS.)nbdoc")
        .def("HasOwnPresentations", static_cast<bool (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::HasOwnPresentations), R"nbdoc(Returns true if object should have own presentations.)nbdoc")
        .def("BoundingBox", static_cast<void (PrsMgr_PresentableObject::*)(Bnd_Box &)>(&PrsMgr_PresentableObject::BoundingBox), nb::arg("theBndBox"), R"nbdoc(Returns bounding box of object correspondingly to its current display mode.
This method requires presentation to be already computed, since it relies on bounding box of
presentation structures, which are supposed to be same/close amongst different display modes
of this object.)nbdoc")
        .def("SetIsoOnTriangulation", static_cast<void (PrsMgr_PresentableObject::*)(const bool)>(&PrsMgr_PresentableObject::SetIsoOnTriangulation), nb::arg("theIsEnabled"), R"nbdoc(@name simplified presentation properties API
Enables or disables on-triangulation build of isolines according to the flag given.)nbdoc")
        .def("CurrentFacingModel", static_cast<Aspect_TypeOfFacingModel (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::CurrentFacingModel), R"nbdoc(Returns the current facing model which is in effect.)nbdoc")
        .def("SetCurrentFacingModel", static_cast<void (PrsMgr_PresentableObject::*)(const Aspect_TypeOfFacingModel)>(&PrsMgr_PresentableObject::SetCurrentFacingModel), nb::arg("theModel") = static_cast<std::decay_t<const Aspect_TypeOfFacingModel>>(Aspect_TOFM_BOTH_SIDE), R"nbdoc(change the current facing model apply on polygons for SetColor(), SetTransparency(),
SetMaterial() methods default facing model is Aspect_TOFM_TWO_SIDE. This mean that attributes
is applying both on the front and back face.)nbdoc")
        .def("HasColor", static_cast<bool (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::HasColor), R"nbdoc(Returns true if the Interactive Object has color.)nbdoc")
        .def("Color", static_cast<void (PrsMgr_PresentableObject::*)(Quantity_Color &) const>(&PrsMgr_PresentableObject::Color), nb::arg("theColor"), R"nbdoc(Returns the color setting of the Interactive Object.)nbdoc")
        .def("SetColor", static_cast<void (PrsMgr_PresentableObject::*)(const Quantity_Color &)>(&PrsMgr_PresentableObject::SetColor), nb::arg("theColor"), R"nbdoc(Only the interactive object knowns which Drawer attribute is affected by the color, if any
(ex: for a wire,it's the wireaspect field of the drawer, but for a vertex, only the point
aspect field is affected by the color). WARNING : Do not forget to set the corresponding
fields here (hasOwnColor and myDrawer->SetColor()))nbdoc")
        .def("UnsetColor", static_cast<void (PrsMgr_PresentableObject::*)()>(&PrsMgr_PresentableObject::UnsetColor), R"nbdoc(Removes color settings. Only the Interactive Object
knows which Drawer attribute is affected by the color
setting. For a wire, for example, wire aspect is the
attribute affected. For a vertex, however, only point
aspect is affected by the color setting.)nbdoc")
        .def("HasWidth", static_cast<bool (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::HasWidth), R"nbdoc(Returns true if the Interactive Object has width.)nbdoc")
        .def("Width", static_cast<double (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::Width), R"nbdoc(Returns the width setting of the Interactive Object.)nbdoc")
        .def("SetWidth", static_cast<void (PrsMgr_PresentableObject::*)(const double)>(&PrsMgr_PresentableObject::SetWidth), nb::arg("theWidth"), R"nbdoc(Allows you to provide the setting aValue for width.
Only the Interactive Object knows which Drawer attribute is affected by the width setting.)nbdoc")
        .def("UnsetWidth", static_cast<void (PrsMgr_PresentableObject::*)()>(&PrsMgr_PresentableObject::UnsetWidth), R"nbdoc(Reset width to default value.)nbdoc")
        .def("HasMaterial", static_cast<bool (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::HasMaterial), R"nbdoc(Returns true if the Interactive Object has a setting for material.)nbdoc")
        .def("Material", static_cast<Graphic3d_NameOfMaterial (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::Material), R"nbdoc(Returns the current material setting as enumeration value.)nbdoc")
        .def("SetMaterial", static_cast<void (PrsMgr_PresentableObject::*)(const Graphic3d_MaterialAspect &)>(&PrsMgr_PresentableObject::SetMaterial), nb::arg("aName"), R"nbdoc(Sets the material aMat defining this display attribute
for the interactive object.
Material aspect determines shading aspect, color and
transparency of visible entities.)nbdoc")
        .def("UnsetMaterial", static_cast<void (PrsMgr_PresentableObject::*)()>(&PrsMgr_PresentableObject::UnsetMaterial), R"nbdoc(Removes the setting for material.)nbdoc")
        .def("IsTransparent", static_cast<bool (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::IsTransparent), R"nbdoc(Returns true if there is a transparency setting.)nbdoc")
        .def("Transparency", static_cast<double (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::Transparency), R"nbdoc(Returns the transparency setting.
This will be between 0.0 and 1.0.
At 0.0 an object will be totally opaque, and at 1.0, fully transparent.)nbdoc")
        .def("SetTransparency", static_cast<void (PrsMgr_PresentableObject::*)(const double)>(&PrsMgr_PresentableObject::SetTransparency), nb::arg("aValue") = static_cast<std::decay_t<const double>>(0.6), R"nbdoc(Attributes a setting aValue for transparency.
The transparency value should be between 0.0 and 1.0.
At 0.0 an object will be totally opaque, and at 1.0, fully transparent.
Warning At a value of 1.0, there may be nothing visible.)nbdoc")
        .def("UnsetTransparency", static_cast<void (PrsMgr_PresentableObject::*)()>(&PrsMgr_PresentableObject::UnsetTransparency), R"nbdoc(Removes the transparency setting. The object is opaque by default.)nbdoc")
        .def("HasPolygonOffsets", static_cast<bool (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::HasPolygonOffsets), R"nbdoc(Returns true if <myDrawer> has non-null shading aspect)nbdoc")
        .def("PolygonOffsets", [](const PrsMgr_PresentableObject &self) { int aMode{}; float aFactor{}; float aUnits{}; self.PolygonOffsets(aMode, aFactor, aUnits); return std::make_tuple(aMode, aFactor, aUnits); }, R"nbdoc(Retrieves current polygon offsets settings from <myDrawer>.)nbdoc")
        .def("SetPolygonOffsets", static_cast<void (PrsMgr_PresentableObject::*)(const int, const float, const float)>(&PrsMgr_PresentableObject::SetPolygonOffsets), nb::arg("aMode"), nb::arg("aFactor") = static_cast<std::decay_t<const float>>(1.0), nb::arg("aUnits") = static_cast<std::decay_t<const float>>(0.0), R"nbdoc(Sets up polygon offsets for this object.
@sa Graphic3d_Aspects::SetPolygonOffsets())nbdoc")
        .def("UnsetAttributes", static_cast<void (PrsMgr_PresentableObject::*)()>(&PrsMgr_PresentableObject::UnsetAttributes), R"nbdoc(Clears settings provided by the drawing tool aDrawer.)nbdoc")
        .def("DumpJson", [](const PrsMgr_PresentableObject &self, int theDepth) { std::ostringstream theOStream_stream; self.DumpJson(theOStream_stream, theDepth); return nanoocp_stream_text(theOStream_stream); }, nb::arg("theDepth") = static_cast<std::decay_t<int>>(- 1), R"nbdoc(Dumps the content of me into the stream)nbdoc")
        .def("ToBeUpdated", static_cast<void (PrsMgr_PresentableObject::*)(NCollection_List<int> &) const>(&PrsMgr_PresentableObject::ToBeUpdated), nb::arg("ListOfMode"), R"nbdoc(Deprecated in OCCT: This method is deprecated - UpdatePresentations() should be called instead

@name deprecated methods
gives the list of modes which are flagged "to be updated".)nbdoc")
        .def("ToPropagateVisualState", static_cast<bool (PrsMgr_PresentableObject::*)() const>(&PrsMgr_PresentableObject::ToPropagateVisualState), R"nbdoc(Get value of the flag "propagate visual state"
It means that the display/erase/color visual state is propagated automatically to all
children; by default, the flag is true)nbdoc")
        .def("SetPropagateVisualState", static_cast<void (PrsMgr_PresentableObject::*)(const bool)>(&PrsMgr_PresentableObject::SetPropagateVisualState), nb::arg("theFlag"), R"nbdoc(Change the value of the flag "propagate visual state")nbdoc");
    nb::borrow<nb::class_<PrsMgr_PresentationManager>>(m.attr("PrsMgr_PresentationManager"))
        .def(nb::new_([](const occ::handle<Graphic3d_StructureManager> & theStructureManager) { return opencascade::handle<PrsMgr_PresentationManager>(new PrsMgr_PresentationManager(theStructureManager)); }), nb::arg("theStructureManager").none(), R"nbdoc(Creates a framework to manage displays and graphic entities with the 3D view
theStructureManager.)nbdoc")
        .def_static("get_type_name", static_cast<const char * (*)()>(&PrsMgr_PresentationManager::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&PrsMgr_PresentationManager::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (PrsMgr_PresentationManager::*)() const>(&PrsMgr_PresentationManager::DynamicType))
        .def("Display", static_cast<void (PrsMgr_PresentationManager::*)(const occ::handle<PrsMgr_PresentableObject> &, const int)>(&PrsMgr_PresentationManager::Display), nb::arg("thePrsObject").none(), nb::arg("theMode") = static_cast<std::decay_t<const int>>(0), R"nbdoc(Displays the presentation of the object in the given Presentation manager with the given mode.
The mode should be enumerated by the object which inherits PresentableObject.)nbdoc")
        .def("Erase", static_cast<void (PrsMgr_PresentationManager::*)(const occ::handle<PrsMgr_PresentableObject> &, const int)>(&PrsMgr_PresentationManager::Erase), nb::arg("thePrsObject").none(), nb::arg("theMode") = static_cast<std::decay_t<const int>>(0), R"nbdoc(erases the presentation of the object in the given
Presentation manager with the given mode.
If @theMode is -1, then erases all presentations of the object.)nbdoc")
        .def("Clear", static_cast<void (PrsMgr_PresentationManager::*)(const occ::handle<PrsMgr_PresentableObject> &, const int)>(&PrsMgr_PresentationManager::Clear), nb::arg("thePrsObject").none(), nb::arg("theMode") = static_cast<std::decay_t<const int>>(0), R"nbdoc(Clears the presentation of the presentable object thePrsObject in this framework with the
display mode theMode.)nbdoc")
        .def("SetVisibility", static_cast<void (PrsMgr_PresentationManager::*)(const occ::handle<PrsMgr_PresentableObject> &, const int, const bool)>(&PrsMgr_PresentationManager::SetVisibility), nb::arg("thePrsObject").none(), nb::arg("theMode"), nb::arg("theValue"), R"nbdoc(Sets the visibility of presentable object.)nbdoc")
        .def("Unhighlight", static_cast<void (PrsMgr_PresentationManager::*)(const occ::handle<PrsMgr_PresentableObject> &)>(&PrsMgr_PresentationManager::Unhighlight), nb::arg("thePrsObject").none(), R"nbdoc(Removes highlighting from the presentation of the presentable object.)nbdoc")
        .def("SetDisplayPriority", static_cast<void (PrsMgr_PresentationManager::*)(const occ::handle<PrsMgr_PresentableObject> &, const int, const Graphic3d_DisplayPriority) const>(&PrsMgr_PresentationManager::SetDisplayPriority), nb::arg("thePrsObject").none(), nb::arg("theMode"), nb::arg("theNewPrior"), R"nbdoc(Sets the display priority theNewPrior of the
presentable object thePrsObject in this framework with the display mode theMode.)nbdoc")
        .def("DisplayPriority", static_cast<Graphic3d_DisplayPriority (PrsMgr_PresentationManager::*)(const occ::handle<PrsMgr_PresentableObject> &, const int) const>(&PrsMgr_PresentationManager::DisplayPriority), nb::arg("thePrsObject").none(), nb::arg("theMode"), R"nbdoc(Returns the display priority of the presentable object
thePrsObject in this framework with the display mode theMode.)nbdoc")
        .def("SetZLayer", static_cast<void (PrsMgr_PresentationManager::*)(const occ::handle<PrsMgr_PresentableObject> &, const Graphic3d_ZLayerId)>(&PrsMgr_PresentationManager::SetZLayer), nb::arg("thePrsObject").none(), nb::arg("theLayerId"), R"nbdoc(Set Z layer ID for all presentations of the object.)nbdoc")
        .def("GetZLayer", static_cast<Graphic3d_ZLayerId (PrsMgr_PresentationManager::*)(const occ::handle<PrsMgr_PresentableObject> &) const>(&PrsMgr_PresentationManager::GetZLayer), nb::arg("thePrsObject").none(), R"nbdoc(Get Z layer ID assigned to all presentations of the object.
Method returns -1 value if object has no presentations and is
impossible to get layer index.)nbdoc")
        .def("IsDisplayed", static_cast<bool (PrsMgr_PresentationManager::*)(const occ::handle<PrsMgr_PresentableObject> &, const int) const>(&PrsMgr_PresentationManager::IsDisplayed), nb::arg("thePrsObject").none(), nb::arg("theMode") = static_cast<std::decay_t<const int>>(0))
        .def("IsHighlighted", static_cast<bool (PrsMgr_PresentationManager::*)(const occ::handle<PrsMgr_PresentableObject> &, const int) const>(&PrsMgr_PresentationManager::IsHighlighted), nb::arg("thePrsObject").none(), nb::arg("theMode") = static_cast<std::decay_t<const int>>(0), R"nbdoc(Returns true if the presentation of the presentable
object thePrsObject in this framework with the display mode theMode is highlighted.)nbdoc")
        .def("Update", static_cast<void (PrsMgr_PresentationManager::*)(const occ::handle<PrsMgr_PresentableObject> &, const int) const>(&PrsMgr_PresentationManager::Update), nb::arg("thePrsObject").none(), nb::arg("theMode") = static_cast<std::decay_t<const int>>(0), R"nbdoc(Updates the presentation of the presentable object
thePrsObject in this framework with the display mode theMode.)nbdoc")
        .def("BeginImmediateDraw", static_cast<void (PrsMgr_PresentationManager::*)()>(&PrsMgr_PresentationManager::BeginImmediateDraw), R"nbdoc(Resets the transient list of presentations previously displayed in immediate mode
and begins accumulation of new list by following AddToImmediateList()/Color()/Highlight()
calls.)nbdoc")
        .def("ClearImmediateDraw", static_cast<void (PrsMgr_PresentationManager::*)()>(&PrsMgr_PresentationManager::ClearImmediateDraw), R"nbdoc(Resets the transient list of presentations previously displayed in immediate mode.)nbdoc")
        .def("AddToImmediateList", static_cast<void (PrsMgr_PresentationManager::*)(const occ::handle<Graphic3d_Structure> &)>(&PrsMgr_PresentationManager::AddToImmediateList), nb::arg("thePrs").none(), R"nbdoc(Stores thePrs in the transient list of presentations to be displayed in immediate mode.
Will be taken in account in EndImmediateDraw method.)nbdoc")
        .def("EndImmediateDraw", static_cast<void (PrsMgr_PresentationManager::*)(const occ::handle<V3d_Viewer> &)>(&PrsMgr_PresentationManager::EndImmediateDraw), nb::arg("theViewer").none(), R"nbdoc(Allows rapid drawing of the each view in theViewer by avoiding an update of the whole
background.)nbdoc")
        .def("RedrawImmediate", static_cast<void (PrsMgr_PresentationManager::*)(const occ::handle<V3d_Viewer> &)>(&PrsMgr_PresentationManager::RedrawImmediate), nb::arg("theViewer").none(), R"nbdoc(Clears and redisplays immediate structures of the viewer taking into account its affinity.)nbdoc")
        .def("IsImmediateModeOn", static_cast<bool (PrsMgr_PresentationManager::*)() const>(&PrsMgr_PresentationManager::IsImmediateModeOn), R"nbdoc(Returns true if Presentation Manager is accumulating transient list of presentations to be
displayed in immediate mode.)nbdoc")
        .def("Color", static_cast<void (PrsMgr_PresentationManager::*)(const occ::handle<PrsMgr_PresentableObject> &, const occ::handle<Prs3d_Drawer> &, const int, const occ::handle<PrsMgr_PresentableObject> &, const Graphic3d_ZLayerId)>(&PrsMgr_PresentationManager::Color), nb::arg("thePrsObject").none(), nb::arg("theStyle").none(), nb::arg("theMode") = static_cast<std::decay_t<const int>>(0), nb::arg("theSelObj").none() = static_cast<std::decay_t<const occ::handle<PrsMgr_PresentableObject> &>>(nullptr), nb::arg("theImmediateStructLayerId") = static_cast<std::decay_t<const Graphic3d_ZLayerId>>(Graphic3d_ZLayerId_Topmost), R"nbdoc(Highlights the graphic object thePrsObject in the color theColor.
thePrsObject has the display mode theMode;
this has the default value of 0, that is, the wireframe display mode.)nbdoc")
        .def("Connect", static_cast<void (PrsMgr_PresentationManager::*)(const occ::handle<PrsMgr_PresentableObject> &, const occ::handle<PrsMgr_PresentableObject> &, const int, const int)>(&PrsMgr_PresentationManager::Connect), nb::arg("thePrsObject").none(), nb::arg("theOtherObject").none(), nb::arg("theMode") = static_cast<std::decay_t<const int>>(0), nb::arg("theOtherMode") = static_cast<std::decay_t<const int>>(0))
        .def("Transform", static_cast<void (PrsMgr_PresentationManager::*)(const occ::handle<PrsMgr_PresentableObject> &, const occ::handle<TopLoc_Datum3D> &, const int)>(&PrsMgr_PresentationManager::Transform), nb::arg("thePrsObject").none(), nb::arg("theTransformation").none(), nb::arg("theMode") = static_cast<std::decay_t<const int>>(0), R"nbdoc(Sets the transformation theTransformation for the presentable object thePrsObject.
thePrsObject has the display mode theMode; this has the default value of 0, that is, the
wireframe display mode.)nbdoc")
        .def("StructureManager", static_cast<const occ::handle<Graphic3d_StructureManager> & (PrsMgr_PresentationManager::*)() const>(&PrsMgr_PresentationManager::StructureManager), R"nbdoc(Returns the structure manager.)nbdoc")
        .def("HasPresentation", static_cast<bool (PrsMgr_PresentationManager::*)(const occ::handle<PrsMgr_PresentableObject> &, const int) const>(&PrsMgr_PresentationManager::HasPresentation), nb::arg("thePrsObject").none(), nb::arg("theMode") = static_cast<std::decay_t<const int>>(0), R"nbdoc(Returns true if there is a presentation of the
presentable object thePrsObject in this framework, thePrsObject having the display mode
theMode.)nbdoc")
        .def("Presentation", static_cast<occ::handle<PrsMgr_Presentation> (PrsMgr_PresentationManager::*)(const occ::handle<PrsMgr_PresentableObject> &, const int, const bool, const occ::handle<PrsMgr_PresentableObject> &) const>(&PrsMgr_PresentationManager::Presentation), nb::arg("thePrsObject").none(), nb::arg("theMode") = static_cast<std::decay_t<const int>>(0), nb::arg("theToCreate") = static_cast<std::decay_t<const bool>>(false), nb::arg("theSelObj").none() = static_cast<std::decay_t<const occ::handle<PrsMgr_PresentableObject> &>>(nullptr), R"nbdoc(Returns the presentation Presentation of the presentable object thePrsObject in this
framework. When theToCreate is true - automatically creates presentation for specified mode
when not exist. Optional argument theSelObj specifies parent decomposed object to inherit its
view affinity.)nbdoc")
        .def("UpdateHighlightTrsf", static_cast<void (PrsMgr_PresentationManager::*)(const occ::handle<V3d_Viewer> &, const occ::handle<PrsMgr_PresentableObject> &, const int, const occ::handle<PrsMgr_PresentableObject> &)>(&PrsMgr_PresentationManager::UpdateHighlightTrsf), nb::arg("theViewer").none(), nb::arg("theObj").none(), nb::arg("theMode") = static_cast<std::decay_t<const int>>(0), nb::arg("theSelObj").none() = static_cast<std::decay_t<const occ::handle<PrsMgr_PresentableObject> &>>(nullptr), R"nbdoc(Allows to apply location transformation to shadow highlight presentation immediately.
@param theObj defines the base object, it local transformation will be applied to
corresponding highlight structure
@param theMode defines display mode of the base object
@param theSelObj defines the object produced after decomposition of the base object for local
selection)nbdoc");
    nanoocp_implicit_copy_ctor<PrsMgr_PresentationManager>(nb::borrow<nb::class_<PrsMgr_PresentationManager>>(m.attr("PrsMgr_PresentationManager")));
    nb::implicitly_convertible<std::decay_t<const occ::handle<Graphic3d_StructureManager> &>, PrsMgr_PresentationManager>();
    m.attr("Prs3d_Presentation") = nb::module_::import_("nanoocp._TKService.Graphic3d").attr("Graphic3d_Structure");   // Prs3d_Presentation = Graphic3d_Structure
}

void nanoocp_conversions_PrsMgr(nb::module_ &m) {
}
