// Generated by the nanoOCP generator from OCCT package BRepGProp (toolkit TKTopAlgo). Do not edit.
#include "nanoocp_common.h"
#include <BRepGProp.hxx>
#include <BRepGProp_Cinert.hxx>
#include <BRepGProp_Domain.hxx>
#include <BRepGProp_EdgeTool.hxx>
#include <BRepGProp_Face.hxx>
#include <BRepGProp_Gauss.hxx>
#include <BRepGProp_Sinert.hxx>
#include <BRepGProp_TFunction.hxx>
#include <BRepGProp_UFunction.hxx>
#include <BRepGProp_Vinert.hxx>
#include <BRepGProp_VinertGK.hxx>
#include <BRepGProp_MeshCinert.hxx>
#include <BRepGProp_MeshProps.hxx>
#include <BRepAdaptor_Curve.hxx>
#include <GProp_GProps.hxx>
#include <GProp_ValueType.hxx>
#include <GeomAbs_IsoType.hxx>
#include <GeomAbs_Shape.hxx>
#include <NCollection_Array1.hxx>
#include <NCollection_HArray1.hxx>
#include <Poly_Triangulation.hxx>
#include <TopAbs_Orientation.hxx>
#include <TopLoc_Location.hxx>
#include <TopoDS_Edge.hxx>
#include <TopoDS_Face.hxx>
#include <TopoDS_Shape.hxx>
#include <gp_Mat.hxx>
#include <gp_Pln.hxx>
#include <gp_Pnt.hxx>
#include <gp_Pnt2d.hxx>
#include <gp_Vec.hxx>
#include <gp_Vec2d.hxx>
#include <math_Function.hxx>

void nanoocp_declare_BRepGProp(nb::module_ &m) {
    { nb::class_<BRepGProp> cls(m, "BRepGProp", R"nbdoc(Provides global functions to compute a shape's global
properties for lines, surfaces or volumes, and bring
them together with the global properties already
computed for a geometric system.
The global properties computed for a system are :
- its mass,
- its center of mass,
- its matrix of inertia,
- its moment about an axis,
- its radius of gyration about an axis,
- and its principal properties of inertia such as
principal axis, principal moments, principal radius of gyration.)nbdoc");
    }
    { nb::class_<BRepGProp_Cinert, GProp_GProps> cls(m, "BRepGProp_Cinert", R"nbdoc(Computes the global properties of bounded curves
in 3D space. The curve must have at least a continuity C1.
It can be a curve as defined in the template CurveTool from
package GProp. This template gives the minimum of methods
required to evaluate the global properties of a curve 3D with
the algorithms of GProp.)nbdoc");
    }
    { nb::class_<BRepGProp_Domain> cls(m, "BRepGProp_Domain", R"nbdoc(Arc iterator. Returns only Forward and Reversed edges from
the face in an undigested order.)nbdoc");
    }
    { nb::class_<BRepGProp_EdgeTool> cls(m, "BRepGProp_EdgeTool", R"nbdoc(Provides the required methods to instantiate
CGProps from GProp with a Curve from BRepAdaptor.)nbdoc");
    }
    { nb::class_<BRepGProp_Face> cls(m, "BRepGProp_Face");
    }
    { nb::class_<BRepGProp_Gauss> cls(m, "BRepGProp_Gauss", R"nbdoc(Class performs computing of the global inertia properties
of geometric object in 3D space by adaptive and non-adaptive
2D Gauss integration algorithms.)nbdoc");
      nb::enum_<BRepGProp_Gauss::BRepGProp_GaussType>(cls, "BRepGProp_GaussType", R"nbdoc(@name public API
Describes types of geometric objects.
- Vinert is 3D closed region of space delimited with:
-- Surface;
-- Point and Surface;
-- Plane and Surface.
- Sinert is face in 3D space.)nbdoc", nb::is_arithmetic())
          .value("Vinert", BRepGProp_Gauss::Vinert)
          .value("Sinert", BRepGProp_Gauss::Sinert)
          .export_values();
    }
    { nb::class_<BRepGProp_Sinert, GProp_GProps> cls(m, "BRepGProp_Sinert", R"nbdoc(Computes the global properties of a face in 3D space.
The face 's requirements to evaluate the global properties
are defined in the template FaceTool from package GProp.)nbdoc");
    }
    { nb::class_<BRepGProp_UFunction, math_Function> cls(m, "BRepGProp_UFunction", R"nbdoc(This class represents the integrand function for
computation of an inner integral. The returned value
depends on the value type and the flag IsByPoint.

The type of returned value is the one of the following
values:
-  GProp_Mass - volume computation.
-  GProp_CenterMassX, GProp_CenterMassY,
GProp_CenterMassZ - X, Y and Z coordinates of center
of mass computation.
-  GProp_InertiaXX, GProp_InertiaYY, GProp_InertiaZZ,
GProp_InertiaXY, GProp_InertiaXZ, GProp_InertiaYZ
- moments of inertia computation.

If the flag IsByPoint is set to true, the value is
returned for the region of space that is delimited by a
surface and a point. Otherwise all computations are
performed for the region of space delimited by a surface
and a plane.)nbdoc");
    }
    { nb::class_<BRepGProp_TFunction, math_Function> cls(m, "BRepGProp_TFunction", R"nbdoc(This class represents the integrand function for the outer
integral computation. The returned value represents the
integral of UFunction. It depends on the value type and the
flag IsByPoint.)nbdoc");
    }
    { nb::class_<BRepGProp_Vinert, GProp_GProps> cls(m, "BRepGProp_Vinert", R"nbdoc(Computes the global properties of a geometric solid
(3D closed region of space) delimited with :
. a surface
. a point and a surface
. a plane and a surface

The surface can be :
. a surface limited with its parametric values U-V,
. a surface limited in U-V space with its curves of restriction,

The surface 's requirements to evaluate the global properties
are defined in the template SurfaceTool from package GProp.)nbdoc");
    }
    { nb::class_<BRepGProp_VinertGK, GProp_GProps> cls(m, "BRepGProp_VinertGK", R"nbdoc(Computes the global properties of a geometric solid
(3D closed region of space) delimited with :
-  a point and a surface
-  a plane and a surface

The surface can be :
-  a surface limited with its parametric values U-V,
(naturally restricted)
-  a surface limited in U-V space with its boundary
curves.

The surface's requirements to evaluate the global
properties are defined in the template FaceTool class from
the package GProp.

The adaptive 2D algorithm of Gauss-Kronrod integration of
double integral is used.

The inner integral is computed along U parameter of
surface. The integrand function is encapsulated in the
support class UFunction that is defined below.

The outer integral is computed along T parameter of a
bounding curve. The integrand function is encapsulated in
the support class TFunction that is defined below.)nbdoc");
    }
    { nb::class_<BRepGProp_MeshCinert, GProp_GProps> cls(m, "BRepGProp_MeshCinert", R"nbdoc(Computes the global properties of
of polylines represented by set of points.
This class is used for computation of global
properties of edge, which has no exact geometry
(3d or 2d curve), but has any of allowed
polygons.)nbdoc");
    }
    { nb::class_<BRepGProp_MeshProps, GProp_GProps> cls(m, "BRepGProp_MeshProps", R"nbdoc(Computes the global properties of a surface mesh. The mesh can be
interpreted as just a surface or as a piece of volume limited by this surface.)nbdoc");
      nb::enum_<BRepGProp_MeshProps::BRepGProp_MeshObjType>(cls, "BRepGProp_MeshObjType", R"nbdoc(Describes types of geometric objects.
- Vinert is 3D closed region of space delimited with
Point and surface mesh;
- Sinert is surface mesh in 3D space.)nbdoc", nb::is_arithmetic())
          .value("Vinert", BRepGProp_MeshProps::Vinert)
          .value("Sinert", BRepGProp_MeshProps::Sinert)
          .export_values();
    }
}

void nanoocp_templates_BRepGProp(nb::module_ &m) {
}

void nanoocp_define_BRepGProp(nb::module_ &m) {
    nanoocp_implicit_default_ctor<BRepGProp>(nb::borrow<nb::class_<BRepGProp>>(m.attr("BRepGProp")));
    nb::borrow<nb::class_<BRepGProp>>(m.attr("BRepGProp"))
        .def_static("LinearProperties", static_cast<void (*)(const TopoDS_Shape &, GProp_GProps &, const bool, const bool)>(&BRepGProp::LinearProperties), nb::arg("S"), nb::arg("LProps"), nb::arg("SkipShared") = static_cast<std::decay_t<const bool>>(false), nb::arg("UseTriangulation") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Computes the linear global properties of the shape S,
i.e. the global properties induced by each edge of the
shape S, and brings them together with the global
properties still retained by the framework LProps. If
the current system of LProps was empty, its global
properties become equal to the linear global
properties of S.
For this computation no linear density is attached to
the edges. So, for example, the added mass
corresponds to the sum of the lengths of the edges of
S. The density of the composed systems, i.e. that of
each component of the current system of LProps, and
that of S which is considered to be equal to 1, must be coherent.
Note that this coherence cannot be checked. You are
advised to use a separate framework for each
density, and then to bring these frameworks together
into a global one.
The point relative to which the inertia of the system is
computed is the reference point of the framework LProps.
Note: if your programming ensures that the framework
LProps retains only linear global properties (brought
together for example, by the function
LinearProperties) for objects the density of which is
equal to 1 (or is not defined), the function Mass will
return the total length of edges of the system analysed by LProps.
Warning
No check is performed to verify that the shape S
retains truly linear properties. If S is simply a vertex, it
is not considered to present any additional global properties.
SkipShared is a special flag, which allows taking in calculation
shared topological entities or not.
For ex., if SkipShared = True, edges, shared by two or more faces,
are taken into calculation only once.
If we have cube with sizes 1, 1, 1, its linear properties = 12
for SkipEdges = true and 24 for SkipEdges = false.
UseTriangulation is a special flag, which defines preferable
source of geometry data. If UseTriangulation = false,
exact geometry objects (curves) are used, otherwise polygons of
triangulation are used first.)nbdoc")
        .def_static("SurfaceProperties", static_cast<void (*)(const TopoDS_Shape &, GProp_GProps &, const bool, const bool)>(&BRepGProp::SurfaceProperties), nb::arg("S"), nb::arg("SProps"), nb::arg("SkipShared") = static_cast<std::decay_t<const bool>>(false), nb::arg("UseTriangulation") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Computes the surface global properties of the
shape S, i.e. the global properties induced by each
face of the shape S, and brings them together with
the global properties still retained by the framework
SProps. If the current system of SProps was empty,
its global properties become equal to the surface
global properties of S.
For this computation, no surface density is attached
to the faces. Consequently, the added mass
corresponds to the sum of the areas of the faces of
S. The density of the component systems, i.e. that
of each component of the current system of
SProps, and that of S which is considered to be
equal to 1, must be coherent.
Note that this coherence cannot be checked. You
are advised to use a framework for each different
value of density, and then to bring these
frameworks together into a global one.
The point relative to which the inertia of the system
is computed is the reference point of the framework SProps.
Note : if your programming ensures that the
framework SProps retains only surface global
properties, brought together, for example, by the
function SurfaceProperties, for objects the density
of which is equal to 1 (or is not defined), the
function Mass will return the total area of faces of
the system analysed by SProps.
Warning
No check is performed to verify that the shape S
retains truly surface properties. If S is simply a
vertex, an edge or a wire, it is not considered to
present any additional global properties.
SkipShared is a special flag, which allows taking in calculation
shared topological entities or not.
For ex., if SkipShared = True, faces, shared by two or more shells,
are taken into calculation only once.
UseTriangulation is a special flag, which defines preferable
source of geometry data. If UseTriangulation = false,
exact geometry objects (surfaces) are used,
otherwise face triangulations are used first.)nbdoc")
        .def_static("SurfaceProperties", static_cast<double (*)(const TopoDS_Shape &, GProp_GProps &, const double, const bool)>(&BRepGProp::SurfaceProperties), nb::arg("S"), nb::arg("SProps"), nb::arg("Eps"), nb::arg("SkipShared") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Updates <SProps> with the shape <S>, that contains its principal properties.
The surface properties of all the faces in <S> are computed.
Adaptive 2D Gauss integration is used.
Parameter Eps sets maximal relative error of computed mass (area) for each face.
Error is calculated as std::abs((M(i+1)-M(i))/M(i+1)), M(i+1) and M(i) are values
for two successive steps of adaptive integration.
Method returns estimation of relative error reached for whole shape.
WARNING: if Eps > 0.001 algorithm performs non-adaptive integration.
SkipShared is a special flag, which allows taking in calculation
shared topological entities or not
For ex., if SkipShared = True, faces, shared by two or more shells,
are taken into calculation only once.)nbdoc")
        .def_static("VolumeProperties", static_cast<void (*)(const TopoDS_Shape &, GProp_GProps &, const bool, const bool, const bool)>(&BRepGProp::VolumeProperties), nb::arg("S"), nb::arg("VProps"), nb::arg("OnlyClosed") = static_cast<std::decay_t<const bool>>(false), nb::arg("SkipShared") = static_cast<std::decay_t<const bool>>(false), nb::arg("UseTriangulation") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Computes the global volume properties of the solid
S, and brings them together with the global
properties still retained by the framework VProps. If
the current system of VProps was empty, its global
properties become equal to the global properties of S for volume.
For this computation, no volume density is attached
to the solid. Consequently, the added mass
corresponds to the volume of S. The density of the
component systems, i.e. that of each component of
the current system of VProps, and that of S which
is considered to be equal to 1, must be coherent to each other.
Note that this coherence cannot be checked. You
are advised to use a separate framework for each
density, and then to bring these frameworks
together into a global one.
The point relative to which the inertia of the system
is computed is the reference point of the framework VProps.
Note: if your programming ensures that the
framework VProps retains only global properties of
volume (brought together for example, by the
function VolumeProperties) for objects the density
of which is equal to 1 (or is not defined), the
function Mass will return the total volume of the
solids of the system analysed by VProps.
Warning
The shape S must represent an object whose
global volume properties can be computed. It may
be a finite solid, or a series of finite solids all
oriented in a coherent way. Nonetheless, S must be
exempt of any free boundary. Note that these
conditions of coherence are not checked by this
algorithm, and results will be false if they are not respected.
SkipShared a is special flag, which allows taking in calculation
shared topological entities or not.
For ex., if SkipShared = True, the volumes formed by the equal
(the same TShape, location and orientation) faces are taken
into calculation only once.
UseTriangulation is a special flag, which defines preferable
source of geometry data. If UseTriangulation = false,
exact geometry objects (surfaces) are used,
otherwise face triangulations are used first.)nbdoc")
        .def_static("VolumeProperties", static_cast<double (*)(const TopoDS_Shape &, GProp_GProps &, const double, const bool, const bool)>(&BRepGProp::VolumeProperties), nb::arg("S"), nb::arg("VProps"), nb::arg("Eps"), nb::arg("OnlyClosed") = static_cast<std::decay_t<const bool>>(false), nb::arg("SkipShared") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Updates <VProps> with the shape <S>, that contains its principal properties.
The volume properties of all the FORWARD and REVERSED faces in <S> are computed.
If OnlyClosed is True then computed faces must belong to closed Shells.
Adaptive 2D Gauss integration is used.
Parameter Eps sets maximal relative error of computed mass (volume) for each face.
Error is calculated as std::abs((M(i+1)-M(i))/M(i+1)), M(i+1) and M(i) are values
for two successive steps of adaptive integration.
Method returns estimation of relative error reached for whole shape.
WARNING: if Eps > 0.001 algorithm performs non-adaptive integration.
SkipShared is a special flag, which allows taking in calculation shared
topological entities or not.
For ex., if SkipShared = True, the volumes formed by the equal
(the same TShape, location and orientation)
faces are taken into calculation only once.)nbdoc")
        .def_static("VolumePropertiesGK", static_cast<double (*)(const TopoDS_Shape &, GProp_GProps &, const double, const bool, const bool, const bool, const bool, const bool)>(&BRepGProp::VolumePropertiesGK), nb::arg("S"), nb::arg("VProps"), nb::arg("Eps") = static_cast<std::decay_t<const double>>(0.001), nb::arg("OnlyClosed") = static_cast<std::decay_t<const bool>>(false), nb::arg("IsUseSpan") = static_cast<std::decay_t<const bool>>(false), nb::arg("CGFlag") = static_cast<std::decay_t<const bool>>(false), nb::arg("IFlag") = static_cast<std::decay_t<const bool>>(false), nb::arg("SkipShared") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Updates <VProps> with the shape <S>, that contains its principal properties.
The volume properties of all the FORWARD and REVERSED faces in <S> are computed.
If OnlyClosed is True then computed faces must belong to closed Shells.
Adaptive 2D Gauss integration is used.
Parameter IsUseSpan says if it is necessary to define spans on a face.
This option has an effect only for BSpline faces.
Parameter Eps sets maximal relative error of computed property for each face.
Error is delivered by the adaptive Gauss-Kronrod method of integral computation
that is used for properties computation.
Method returns estimation of relative error reached for whole shape.
Returns negative value if the computation is failed.
SkipShared is a special flag, which allows taking in calculation
shared topological entities or not.
For ex., if SkipShared = True, the volumes formed by the equal
(the same TShape, location and orientation) faces are taken into calculation only once.)nbdoc")
        .def_static("VolumePropertiesGK", static_cast<double (*)(const TopoDS_Shape &, GProp_GProps &, const gp_Pln &, const double, const bool, const bool, const bool, const bool, const bool)>(&BRepGProp::VolumePropertiesGK), nb::arg("S"), nb::arg("VProps"), nb::arg("thePln"), nb::arg("Eps") = static_cast<std::decay_t<const double>>(0.001), nb::arg("OnlyClosed") = static_cast<std::decay_t<const bool>>(false), nb::arg("IsUseSpan") = static_cast<std::decay_t<const bool>>(false), nb::arg("CGFlag") = static_cast<std::decay_t<const bool>>(false), nb::arg("IFlag") = static_cast<std::decay_t<const bool>>(false), nb::arg("SkipShared") = static_cast<std::decay_t<const bool>>(false));
    nanoocp_implicit_copy_ctor<BRepGProp>(nb::borrow<nb::class_<BRepGProp>>(m.attr("BRepGProp")));
    nb::borrow<nb::class_<BRepGProp_Cinert>>(m.attr("BRepGProp_Cinert"))
        .def(nb::init<>())
        .def(nb::init<const BRepAdaptor_Curve &, const gp_Pnt &>(), nb::arg("C"), nb::arg("CLocation"))
        .def("SetLocation", static_cast<void (BRepGProp_Cinert::*)(const gp_Pnt &)>(&BRepGProp_Cinert::SetLocation), nb::arg("CLocation"))
        .def("Perform", static_cast<void (BRepGProp_Cinert::*)(const BRepAdaptor_Curve &)>(&BRepGProp_Cinert::Perform), nb::arg("C"));
    nanoocp_implicit_copy_ctor<BRepGProp_Cinert>(nb::borrow<nb::class_<BRepGProp_Cinert>>(m.attr("BRepGProp_Cinert")));
    nanoocp_def_iter<BRepGProp_Domain>(nb::borrow<nb::class_<BRepGProp_Domain>>(m.attr("BRepGProp_Domain")), [](BRepGProp_Domain &self) { return self.Value(); });
    nb::borrow<nb::class_<BRepGProp_Domain>>(m.attr("BRepGProp_Domain"))
        .def(nb::init<>(), R"nbdoc(Empty constructor.)nbdoc")
        .def(nb::init<const TopoDS_Face &>(), nb::arg("F"), R"nbdoc(Constructor. Initializes the domain with the face.)nbdoc")
        .def("Init", static_cast<void (BRepGProp_Domain::*)(const TopoDS_Face &)>(&BRepGProp_Domain::Init), nb::arg("F"), R"nbdoc(Initializes the domain with the face.)nbdoc")
        .def("More", static_cast<bool (BRepGProp_Domain::*)()>(&BRepGProp_Domain::More), R"nbdoc(Returns True if there is another arc of curve in the list.)nbdoc")
        .def("Init", static_cast<void (BRepGProp_Domain::*)()>(&BRepGProp_Domain::Init), R"nbdoc(Initializes the exploration with the face already set.)nbdoc")
        .def("Value", static_cast<const TopoDS_Edge & (BRepGProp_Domain::*)()>(&BRepGProp_Domain::Value), R"nbdoc(Returns the current edge.)nbdoc")
        .def("Next", static_cast<void (BRepGProp_Domain::*)()>(&BRepGProp_Domain::Next), R"nbdoc(Sets the index of the arc iterator to the next arc of
curve.)nbdoc");
    nanoocp_implicit_copy_ctor<BRepGProp_Domain>(nb::borrow<nb::class_<BRepGProp_Domain>>(m.attr("BRepGProp_Domain")));
    nb::implicitly_convertible<std::decay_t<const TopoDS_Face &>, BRepGProp_Domain>();
    nanoocp_implicit_default_ctor<BRepGProp_EdgeTool>(nb::borrow<nb::class_<BRepGProp_EdgeTool>>(m.attr("BRepGProp_EdgeTool")));
    nb::borrow<nb::class_<BRepGProp_EdgeTool>>(m.attr("BRepGProp_EdgeTool"))
        .def_static("FirstParameter", static_cast<double (*)(const BRepAdaptor_Curve &)>(&BRepGProp_EdgeTool::FirstParameter), nb::arg("C"), R"nbdoc(Returns the parametric value of the start point of
the curve. The curve is oriented from the start point
to the end point.)nbdoc")
        .def_static("LastParameter", static_cast<double (*)(const BRepAdaptor_Curve &)>(&BRepGProp_EdgeTool::LastParameter), nb::arg("C"), R"nbdoc(Returns the parametric value of the end point of
the curve. The curve is oriented from the start point
to the end point.)nbdoc")
        .def_static("IntegrationOrder", static_cast<int (*)(const BRepAdaptor_Curve &)>(&BRepGProp_EdgeTool::IntegrationOrder), nb::arg("C"), R"nbdoc(Returns the number of Gauss points required to do
the integration with a good accuracy using the
Gauss method. For a polynomial curve of degree n
the maxima of accuracy is obtained with an order
of integration equal to 2*n-1.)nbdoc")
        .def_static("Value", static_cast<gp_Pnt (*)(const BRepAdaptor_Curve &, const double)>(&BRepGProp_EdgeTool::Value), nb::arg("C"), nb::arg("U"), R"nbdoc(Returns the point of parameter U on the loaded curve.)nbdoc")
        .def_static("D1", static_cast<void (*)(const BRepAdaptor_Curve &, const double, gp_Pnt &, gp_Vec &)>(&BRepGProp_EdgeTool::D1), nb::arg("C"), nb::arg("U"), nb::arg("P"), nb::arg("V1"), R"nbdoc(Returns the point of parameter U and the first derivative
at this point.)nbdoc")
        .def_static("NbIntervals", static_cast<int (*)(const BRepAdaptor_Curve &, const GeomAbs_Shape)>(&BRepGProp_EdgeTool::NbIntervals), nb::arg("C"), nb::arg("S"), R"nbdoc(Returns the number of intervals for continuity
<S>. May be one if Continuity(me) >= <S>)nbdoc")
        .def_static("Intervals", static_cast<void (*)(const BRepAdaptor_Curve &, NCollection_Array1<double> &, const GeomAbs_Shape)>(&BRepGProp_EdgeTool::Intervals), nb::arg("C"), nb::arg("T"), nb::arg("S"), R"nbdoc(Stores in <T> the parameters bounding the intervals
of continuity <S>.

The array must provide enough room to accommodate
for the parameters. i.e. T.Length() > NbIntervals())nbdoc");
    nanoocp_implicit_copy_ctor<BRepGProp_EdgeTool>(nb::borrow<nb::class_<BRepGProp_EdgeTool>>(m.attr("BRepGProp_EdgeTool")));
    nb::borrow<nb::class_<BRepGProp_Face>>(m.attr("BRepGProp_Face"))
        .def(nb::init<const bool>(), nb::arg("IsUseSpan") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Constructor. Initializes the object with a flag IsUseSpan
that says if it is necessary to define spans on a face.
This option has an effect only for BSpline faces. Spans
are returned by the methods GetUKnots and GetTKnots.)nbdoc")
        .def(nb::init<const TopoDS_Face &, const bool>(), nb::arg("F"), nb::arg("IsUseSpan") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Constructor. Initializes the object with the face and the
flag IsUseSpan that says if it is necessary to define
spans on a face. This option has an effect only for
BSpline faces. Spans are returned by the methods GetUKnots
and GetTKnots.)nbdoc")
        .def("Load", static_cast<void (BRepGProp_Face::*)(const TopoDS_Face &)>(&BRepGProp_Face::Load), nb::arg("F"))
        .def("VIntegrationOrder", static_cast<int (BRepGProp_Face::*)() const>(&BRepGProp_Face::VIntegrationOrder))
        .def("NaturalRestriction", static_cast<bool (BRepGProp_Face::*)() const>(&BRepGProp_Face::NaturalRestriction), R"nbdoc(Returns true if the face is not trimmed.)nbdoc")
        .def("GetFace", static_cast<const TopoDS_Face & (BRepGProp_Face::*)() const>(&BRepGProp_Face::GetFace), R"nbdoc(Returns the TopoDS face.)nbdoc")
        .def("Value2d", static_cast<gp_Pnt2d (BRepGProp_Face::*)(const double) const>(&BRepGProp_Face::Value2d), nb::arg("U"), R"nbdoc(Returns the value of the boundary curve of the face.)nbdoc")
        .def("SIntOrder", static_cast<int (BRepGProp_Face::*)(const double) const>(&BRepGProp_Face::SIntOrder), nb::arg("Eps"))
        .def("SVIntSubs", static_cast<int (BRepGProp_Face::*)() const>(&BRepGProp_Face::SVIntSubs))
        .def("SUIntSubs", static_cast<int (BRepGProp_Face::*)() const>(&BRepGProp_Face::SUIntSubs))
        .def("UKnots", static_cast<void (BRepGProp_Face::*)(NCollection_Array1<double> &) const>(&BRepGProp_Face::UKnots), nb::arg("Knots"))
        .def("VKnots", static_cast<void (BRepGProp_Face::*)(NCollection_Array1<double> &) const>(&BRepGProp_Face::VKnots), nb::arg("Knots"))
        .def("LIntOrder", static_cast<int (BRepGProp_Face::*)(const double) const>(&BRepGProp_Face::LIntOrder), nb::arg("Eps"))
        .def("LIntSubs", static_cast<int (BRepGProp_Face::*)() const>(&BRepGProp_Face::LIntSubs))
        .def("LKnots", static_cast<void (BRepGProp_Face::*)(NCollection_Array1<double> &) const>(&BRepGProp_Face::LKnots), nb::arg("Knots"))
        .def("UIntegrationOrder", static_cast<int (BRepGProp_Face::*)() const>(&BRepGProp_Face::UIntegrationOrder), R"nbdoc(Returns the number of points required to do the
integration in the U parametric direction with
a good accuracy.)nbdoc")
        .def("Bounds", [](const BRepGProp_Face &self) { double U1{}; double U2{}; double V1{}; double V2{}; self.Bounds(U1, U2, V1, V2); return std::make_tuple(U1, U2, V1, V2); }, R"nbdoc(Returns the parametric bounds of the Face.)nbdoc")
        .def("Normal", static_cast<void (BRepGProp_Face::*)(const double, const double, gp_Pnt &, gp_Vec &) const>(&BRepGProp_Face::Normal), nb::arg("U"), nb::arg("V"), nb::arg("P"), nb::arg("VNor"), R"nbdoc(Computes the point of parameter U, V on the Face <S> and
the normal to the face at this point.)nbdoc")
        .def("Load", static_cast<bool (BRepGProp_Face::*)(const TopoDS_Edge &)>(&BRepGProp_Face::Load), nb::arg("E"), R"nbdoc(Loading the boundary arc.
Returns FALSE if edge has no P-Curve.)nbdoc")
        .def("FirstParameter", static_cast<double (BRepGProp_Face::*)() const>(&BRepGProp_Face::FirstParameter), R"nbdoc(Returns the parametric value of the start point of
the current arc of curve.)nbdoc")
        .def("LastParameter", static_cast<double (BRepGProp_Face::*)() const>(&BRepGProp_Face::LastParameter), R"nbdoc(Returns the parametric value of the end point of
the current arc of curve.)nbdoc")
        .def("IntegrationOrder", static_cast<int (BRepGProp_Face::*)() const>(&BRepGProp_Face::IntegrationOrder), R"nbdoc(Returns the number of points required to do the
integration along the parameter of curve.)nbdoc")
        .def("D12d", static_cast<void (BRepGProp_Face::*)(const double, gp_Pnt2d &, gp_Vec2d &) const>(&BRepGProp_Face::D12d), nb::arg("U"), nb::arg("P"), nb::arg("V1"), R"nbdoc(Returns the point of parameter U and the first derivative
at this point of a boundary curve.)nbdoc")
        .def("Load", static_cast<void (BRepGProp_Face::*)(const bool, const GeomAbs_IsoType)>(&BRepGProp_Face::Load), nb::arg("IsFirstParam"), nb::arg("theIsoType"), R"nbdoc(Loading the boundary arc. This arc is either a top, bottom,
left or right bound of a UV rectangle in which the
parameters of surface are defined.
If IsFirstParam is equal to true, the face is
initialized by either left of bottom bound. Otherwise it is
initialized by the top or right one.
If theIsoType is equal to GeomAbs_IsoU, the face is
initialized with either left or right bound. Otherwise -
with either top or bottom one.)nbdoc")
        .def("GetUKnots", static_cast<occ::handle<NCollection_HArray1<double>> (BRepGProp_Face::*)(const double, const double) const>(&BRepGProp_Face::GetUKnots), nb::arg("theUMin"), nb::arg("theUMax"), R"nbdoc(Returns an array of U knots of the face. The first and last
elements of the array will be theUMin and theUMax. The
middle elements will be the U Knots of the face greater
then theUMin and lower then theUMax in increasing order.
If the face is not a BSpline, the array initialized with
theUMin and theUMax only.
@param[in] theUMin lower U bound
@param[in] theUMax upper U bound
@return array of U knot values)nbdoc")
        .def("GetUKnots__NCollection_HArray1__double", [](const BRepGProp_Face &self, const double theUMin, const double theUMax) { occ::handle<NCollection_HArray1<double>> theUKnots{}; self.GetUKnots(theUMin, theUMax, theUKnots); return theUKnots; }, nb::arg("theUMin"), nb::arg("theUMax"), R"nbdoc(GetUKnots__NCollection_HArray1__double: the C++ overload GetUKnots(const double, const double, occ::handle<NCollection_HArray1<double>> &); the suffix lists its returned out-parameters (nanoOCP R-COLLISION).
Deprecated in OCCT: Use GetUKnots() returning handle by value instead

@deprecated Use GetUKnots() returning handle by value instead.)nbdoc")
        .def("GetTKnots", static_cast<occ::handle<NCollection_HArray1<double>> (BRepGProp_Face::*)(const double, const double) const>(&BRepGProp_Face::GetTKnots), nb::arg("theTMin"), nb::arg("theTMax"), R"nbdoc(Returns an array of combination of T knots of the arc and
V knots of the face. The first and last elements of the
array will be theTMin and theTMax. The middle elements will
be the Knots of the arc and the values of parameters of
arc on which the value points have V coordinates close to V
knots of face. All the parameter will be greater then
theTMin and lower then theTMax in increasing order.
If the face is not a BSpline, the array initialized with
theTMin and theTMax only.
@param[in] theTMin lower T bound
@param[in] theTMax upper T bound
@return array of T knot values)nbdoc")
        .def("GetTKnots__NCollection_HArray1__double", [](const BRepGProp_Face &self, const double theTMin, const double theTMax) { occ::handle<NCollection_HArray1<double>> theTKnots{}; self.GetTKnots(theTMin, theTMax, theTKnots); return theTKnots; }, nb::arg("theTMin"), nb::arg("theTMax"), R"nbdoc(GetTKnots__NCollection_HArray1__double: the C++ overload GetTKnots(const double, const double, occ::handle<NCollection_HArray1<double>> &); the suffix lists its returned out-parameters (nanoOCP R-COLLISION).
Deprecated in OCCT: Use GetTKnots() returning handle by value instead

@deprecated Use GetTKnots() returning handle by value instead.)nbdoc");
    nanoocp_implicit_copy_ctor<BRepGProp_Face>(nb::borrow<nb::class_<BRepGProp_Face>>(m.attr("BRepGProp_Face")));
    nb::implicitly_convertible<std::decay_t<const bool>, BRepGProp_Face>();
    nb::implicitly_convertible<std::decay_t<const TopoDS_Face &>, BRepGProp_Face>();
    nb::borrow<nb::class_<BRepGProp_Gauss>>(m.attr("BRepGProp_Gauss"))
        .def(nb::init<const BRepGProp_Gauss::BRepGProp_GaussType>(), nb::arg("theType"), R"nbdoc(Constructor)nbdoc")
        .def("Compute", [](BRepGProp_Gauss &self, const BRepGProp_Face & theSurface, const gp_Pnt & theLocation, gp_Pnt & theOutGravityCenter, gp_Mat & theOutInertia) { double theOutMass{}; self.Compute(theSurface, theLocation, theOutMass, theOutGravityCenter, theOutInertia); return theOutMass; }, nb::arg("theSurface"), nb::arg("theLocation"), nb::arg("theOutGravityCenter"), nb::arg("theOutInertia"), R"nbdoc(Computes the global properties of a surface. Surface can be closed.
The method is quick and its precision is enough for many cases of analytical surfaces.
Non-adaptive 2D Gauss integration with predefined numbers of Gauss points
is used. Numbers of points depend on types of surfaces and curves.
Error of the computation is not calculated.
@param theSurface - bounding surface of the region;
@param theLocation - surface location;
@param[out] theOutMass - mass (volume) of region;
@param[out] theOutGravityCenter - garvity center of region;
@param[out] theOutInertia - matrix of inertia;)nbdoc")
        .def("Compute", [](BRepGProp_Gauss &self, BRepGProp_Face & theSurface, BRepGProp_Domain & theDomain, const gp_Pnt & theLocation, gp_Pnt & theOutGravityCenter, gp_Mat & theOutInertia) { double theOutMass{}; self.Compute(theSurface, theDomain, theLocation, theOutMass, theOutGravityCenter, theOutInertia); return theOutMass; }, nb::arg("theSurface"), nb::arg("theDomain"), nb::arg("theLocation"), nb::arg("theOutGravityCenter"), nb::arg("theOutInertia"), R"nbdoc(Computes the global properties of a surface. Surface can be closed.
The method is quick and its precision is enough for many cases of analytical surfaces.
Non-adaptive 2D Gauss integration with predefined numbers of Gauss points
is used. Numbers of points depend on types of surfaces and curves.
Error of the computation is not calculated.
@param theSurface - bounding surface of the region;
@param theDomain - surface boundings;
@param theLocation - surface location;
@param[out] theOutMass - mass (volume) of region;
@param[out] theOutGravityCenter - garvity center of region;
@param[out] theOutInertia - matrix of inertia;)nbdoc")
        .def("Compute", [](BRepGProp_Gauss &self, BRepGProp_Face & theSurface, BRepGProp_Domain & theDomain, const gp_Pnt & theLocation, const double theEps, gp_Pnt & theOutGravityCenter, gp_Mat & theOutInertia) { double theOutMass{}; auto nanoocp_result = self.Compute(theSurface, theDomain, theLocation, theEps, theOutMass, theOutGravityCenter, theOutInertia); return std::make_tuple(nanoocp_result, theOutMass); }, nb::arg("theSurface"), nb::arg("theDomain"), nb::arg("theLocation"), nb::arg("theEps"), nb::arg("theOutGravityCenter"), nb::arg("theOutInertia"), R"nbdoc(Computes the global properties of the face. Adaptive 2D Gauss integration is used.
If Epsilon more than 0.001 then algorithm performs non-adaptive integration.
@param theSurface - bounding surface of the region;
@param theDomain - surface boundings;
@param theLocation - surface location;
@param theEps - maximal relative error of computed mass (square) for face;
@param[out] theOutMass - mass (volume) of region;
@param[out] theOutGravityCenter - garvity center of region;
@param[out] theOutInertia - matrix of inertia;
@return value of error which is calculated as
std::abs((M(i+1)-M(i))/M(i+1)), M(i+1) and M(i) are values
for two successive steps of adaptive integration.)nbdoc");
    nanoocp_implicit_copy_ctor<BRepGProp_Gauss>(nb::borrow<nb::class_<BRepGProp_Gauss>>(m.attr("BRepGProp_Gauss")));
    nb::borrow<nb::class_<BRepGProp_Sinert>>(m.attr("BRepGProp_Sinert"))
        .def(nb::init<>())
        .def(nb::init<const BRepGProp_Face &, const gp_Pnt &>(), nb::arg("S"), nb::arg("SLocation"))
        .def(nb::init<BRepGProp_Face &, BRepGProp_Domain &, const gp_Pnt &>(), nb::arg("S"), nb::arg("D"), nb::arg("SLocation"), R"nbdoc(Builds a Sinert to evaluate the global properties of
the face <S>. If isNaturalRestriction is true the domain of S is defined
with the natural bounds, else it defined with an iterator
of Edge from TopoDS (see DomainTool from GProp))nbdoc")
        .def(nb::init<BRepGProp_Face &, const gp_Pnt &, const double>(), nb::arg("S"), nb::arg("SLocation"), nb::arg("Eps"))
        .def(nb::init<BRepGProp_Face &, BRepGProp_Domain &, const gp_Pnt &, const double>(), nb::arg("S"), nb::arg("D"), nb::arg("SLocation"), nb::arg("Eps"))
        .def("SetLocation", static_cast<void (BRepGProp_Sinert::*)(const gp_Pnt &)>(&BRepGProp_Sinert::SetLocation), nb::arg("SLocation"))
        .def("Perform", static_cast<void (BRepGProp_Sinert::*)(const BRepGProp_Face &)>(&BRepGProp_Sinert::Perform), nb::arg("S"))
        .def("Perform", static_cast<void (BRepGProp_Sinert::*)(BRepGProp_Face &, BRepGProp_Domain &)>(&BRepGProp_Sinert::Perform), nb::arg("S"), nb::arg("D"))
        .def("Perform", static_cast<double (BRepGProp_Sinert::*)(BRepGProp_Face &, const double)>(&BRepGProp_Sinert::Perform), nb::arg("S"), nb::arg("Eps"))
        .def("Perform", static_cast<double (BRepGProp_Sinert::*)(BRepGProp_Face &, BRepGProp_Domain &, const double)>(&BRepGProp_Sinert::Perform), nb::arg("S"), nb::arg("D"), nb::arg("Eps"))
        .def("GetEpsilon", static_cast<double (BRepGProp_Sinert::*)()>(&BRepGProp_Sinert::GetEpsilon), R"nbdoc(If previously used method contained Eps parameter
get actual relative error of the computation, else return 1.0.)nbdoc");
    nanoocp_implicit_copy_ctor<BRepGProp_Sinert>(nb::borrow<nb::class_<BRepGProp_Sinert>>(m.attr("BRepGProp_Sinert")));
    nb::borrow<nb::class_<BRepGProp_UFunction>>(m.attr("BRepGProp_UFunction"))
        .def("SetValueType", static_cast<void (BRepGProp_UFunction::*)(const GProp_ValueType)>(&BRepGProp_UFunction::SetValueType), nb::arg("theType"), R"nbdoc(Setting the type of the value to be returned.)nbdoc")
        .def("SetVParam", static_cast<void (BRepGProp_UFunction::*)(const double)>(&BRepGProp_UFunction::SetVParam), nb::arg("theVParam"), R"nbdoc(Setting the V parameter that is constant during the
integral computation.)nbdoc")
        .def("Value", [](BRepGProp_UFunction &self, const double X) { double F{}; auto nanoocp_result = self.Value(X, F); return std::make_tuple(nanoocp_result, F); }, nb::arg("X"), R"nbdoc(Returns a value of the function.)nbdoc");
    nanoocp_implicit_copy_ctor<BRepGProp_UFunction>(nb::borrow<nb::class_<BRepGProp_UFunction>>(m.attr("BRepGProp_UFunction")));
    nb::borrow<nb::class_<BRepGProp_TFunction>>(m.attr("BRepGProp_TFunction"))
        .def("Init", static_cast<void (BRepGProp_TFunction::*)()>(&BRepGProp_TFunction::Init))
        .def("SetNbKronrodPoints", static_cast<void (BRepGProp_TFunction::*)(const int)>(&BRepGProp_TFunction::SetNbKronrodPoints), nb::arg("theNbPoints"), R"nbdoc(Setting the expected number of Kronrod points for the outer
integral computation. This number is required for
computation of a value of tolerance for inner integral
computation. After GetStateNumber method call, this number
is recomputed by the same law as in
math_KronrodSingleIntegration, i.e. next number of points
is equal to the current number plus a square root of the
current number. If the law in math_KronrodSingleIntegration
is changed, the modification algo should be modified
accordingly.)nbdoc")
        .def("SetValueType", static_cast<void (BRepGProp_TFunction::*)(const GProp_ValueType)>(&BRepGProp_TFunction::SetValueType), nb::arg("aType"), R"nbdoc(Setting the type of the value to be returned. This
parameter is directly passed to the UFunction.)nbdoc")
        .def("SetTolerance", static_cast<void (BRepGProp_TFunction::*)(const double)>(&BRepGProp_TFunction::SetTolerance), nb::arg("aTol"), R"nbdoc(Setting the tolerance for inner integration)nbdoc")
        .def("ErrorReached", static_cast<double (BRepGProp_TFunction::*)() const>(&BRepGProp_TFunction::ErrorReached), R"nbdoc(Returns the relative reached error of all values computation since
the last call of GetStateNumber method.)nbdoc")
        .def("AbsolutError", static_cast<double (BRepGProp_TFunction::*)() const>(&BRepGProp_TFunction::AbsolutError), R"nbdoc(Returns the absolut reached error of all values computation since
the last call of GetStateNumber method.)nbdoc")
        .def("Value", [](BRepGProp_TFunction &self, const double X) { double F{}; auto nanoocp_result = self.Value(X, F); return std::make_tuple(nanoocp_result, F); }, nb::arg("X"), R"nbdoc(Returns a value of the function. The value represents an
integral of UFunction. It is computed with the predefined
tolerance using the adaptive Gauss-Kronrod method.)nbdoc")
        .def("GetStateNumber", static_cast<int (BRepGProp_TFunction::*)()>(&BRepGProp_TFunction::GetStateNumber), R"nbdoc(Redefined method. Remembers the error reached during
computation of integral values since the object creation
or the last call of GetStateNumber. It is invoked in each
algorithm from the package math. Particularly in the
algorithm math_KronrodSingleIntegration that is used to
compute the integral of TFunction.)nbdoc");
    nanoocp_implicit_copy_ctor<BRepGProp_TFunction>(nb::borrow<nb::class_<BRepGProp_TFunction>>(m.attr("BRepGProp_TFunction")));
    nb::borrow<nb::class_<BRepGProp_Vinert>>(m.attr("BRepGProp_Vinert"))
        .def(nb::init<>())
        .def(nb::init<const BRepGProp_Face &, const gp_Pnt &>(), nb::arg("S"), nb::arg("VLocation"), R"nbdoc(Computes the global properties of a region of 3D space
delimited with the surface <S> and the point VLocation. S can be closed
The method is quick and its precision is enough for many cases of analytical
surfaces.
Non-adaptive 2D Gauss integration with predefined numbers of Gauss points
is used. Numbers of points depend on types of surfaces and curves.
Error of the computation is not calculated.)nbdoc")
        .def(nb::init<BRepGProp_Face &, const gp_Pnt &, const double>(), nb::arg("S"), nb::arg("VLocation"), nb::arg("Eps"), R"nbdoc(Computes the global properties of a region of 3D space
delimited with the surface <S> and the point VLocation. S can be closed
Adaptive 2D Gauss integration is used.
Parameter Eps sets maximal relative error of computed mass (volume) for face.
Error is calculated as std::abs((M(i+1)-M(i))/M(i+1)), M(i+1) and M(i) are values
for two successive steps of adaptive integration.)nbdoc")
        .def(nb::init<const BRepGProp_Face &, const gp_Pnt &, const gp_Pnt &>(), nb::arg("S"), nb::arg("O"), nb::arg("VLocation"), R"nbdoc(Computes the global properties of the region of 3D space
delimited with the surface <S> and the point VLocation.
The method is quick and its precision is enough for many cases of analytical
surfaces.
Non-adaptive 2D Gauss integration with predefined numbers of Gauss points
is used. Numbers of points depend on types of surfaces and curves.
Error of the computation is not calculated.)nbdoc")
        .def(nb::init<const BRepGProp_Face &, const gp_Pln &, const gp_Pnt &>(), nb::arg("S"), nb::arg("Pl"), nb::arg("VLocation"), R"nbdoc(Computes the global properties of the region of 3D space
delimited with the surface <S> and the plane Pln.
The method is quick and its precision is enough for many cases of analytical
surfaces.
Non-adaptive 2D Gauss integration with predefined numbers of Gauss points
is used. Numbers of points depend on types of surfaces and curves.
Error of the computation is not calculated.)nbdoc")
        .def(nb::init<BRepGProp_Face &, BRepGProp_Domain &, const gp_Pnt &>(), nb::arg("S"), nb::arg("D"), nb::arg("VLocation"), R"nbdoc(Computes the global properties of a region of 3D space
delimited with the surface <S> and the point VLocation. S can be closed
The method is quick and its precision is enough for many cases of analytical
surfaces.
Non-adaptive 2D Gauss integration with predefined numbers of Gauss points
is used. Numbers of points depend on types of surfaces and curves.
Error of the computation is not calculated.)nbdoc")
        .def(nb::init<BRepGProp_Face &, const gp_Pnt &, const gp_Pnt &, const double>(), nb::arg("S"), nb::arg("O"), nb::arg("VLocation"), nb::arg("Eps"), R"nbdoc(Computes the global properties of the region of 3D space
delimited with the surface <S> and the point VLocation.
Adaptive 2D Gauss integration is used.
Parameter Eps sets maximal relative error of computed mass (volume) for face.
Error is calculated as std::abs((M(i+1)-M(i))/M(i+1)), M(i+1) and M(i) are values
for two successive steps of adaptive integration.
WARNING: if Eps > 0.001 algorithm performs non-adaptive integration.)nbdoc")
        .def(nb::init<BRepGProp_Face &, const gp_Pln &, const gp_Pnt &, const double>(), nb::arg("S"), nb::arg("Pl"), nb::arg("VLocation"), nb::arg("Eps"), R"nbdoc(Computes the global properties of the region of 3D space
delimited with the surface <S> and the plane Pln.
Adaptive 2D Gauss integration is used.
Parameter Eps sets maximal relative error of computed mass (volume) for face.
Error is calculated as std::abs((M(i+1)-M(i))/M(i+1)), M(i+1) and M(i) are values
for two successive steps of adaptive integration.
WARNING: if Eps > 0.001 algorithm performs non-adaptive integration.)nbdoc")
        .def(nb::init<BRepGProp_Face &, BRepGProp_Domain &, const gp_Pnt &, const double>(), nb::arg("S"), nb::arg("D"), nb::arg("VLocation"), nb::arg("Eps"), R"nbdoc(Computes the global properties of a region of 3D space
delimited with the surface <S> and the point VLocation. S can be closed
Adaptive 2D Gauss integration is used.
Parameter Eps sets maximal relative error of computed mass (volume) for face.
Error is calculated as std::abs((M(i+1)-M(i))/M(i+1)), M(i+1) and M(i) are values
for two successive steps of adaptive integration.)nbdoc")
        .def(nb::init<BRepGProp_Face &, BRepGProp_Domain &, const gp_Pnt &, const gp_Pnt &>(), nb::arg("S"), nb::arg("D"), nb::arg("O"), nb::arg("VLocation"), R"nbdoc(Computes the global properties of the region of 3D space
delimited with the surface <S> and the point VLocation.
The method is quick and its precision is enough for many cases of analytical
surfaces.
Non-adaptive 2D Gauss integration with predefined numbers of Gauss points
is used. Numbers of points depend on types of surfaces and curves.
Error of the computation is not calculated.)nbdoc")
        .def(nb::init<BRepGProp_Face &, BRepGProp_Domain &, const gp_Pln &, const gp_Pnt &>(), nb::arg("S"), nb::arg("D"), nb::arg("Pl"), nb::arg("VLocation"), R"nbdoc(Computes the global properties of the region of 3D space
delimited with the surface <S> and the plane Pln.
The method is quick and its precision is enough for many cases of analytical
surfaces.
Non-adaptive 2D Gauss integration with predefined numbers of Gauss points
is used. Numbers of points depend on types of surfaces and curves.
Error of the computation is not calculated.)nbdoc")
        .def(nb::init<BRepGProp_Face &, BRepGProp_Domain &, const gp_Pnt &, const gp_Pnt &, const double>(), nb::arg("S"), nb::arg("D"), nb::arg("O"), nb::arg("VLocation"), nb::arg("Eps"), R"nbdoc(Computes the global properties of the region of 3D space
delimited with the surface <S> and the point VLocation.
Adaptive 2D Gauss integration is used.
Parameter Eps sets maximal relative error of computed mass (volume) for face.
Error is calculated as std::abs((M(i+1)-M(i))/M(i+1)), M(i+1) and M(i) are values
for two successive steps of adaptive integration.
WARNING: if Eps > 0.001 algorithm performs non-adaptive integration.)nbdoc")
        .def(nb::init<BRepGProp_Face &, BRepGProp_Domain &, const gp_Pln &, const gp_Pnt &, const double>(), nb::arg("S"), nb::arg("D"), nb::arg("Pl"), nb::arg("VLocation"), nb::arg("Eps"), R"nbdoc(Computes the global properties of the region of 3D space
delimited with the surface <S> and the plane Pln.
Adaptive 2D Gauss integration is used.
Parameter Eps sets maximal relative error of computed mass (volume) for face.
Error is calculated as std::abs((M(i+1)-M(i))/M(i+1)), M(i+1) and M(i) are values
for two successive steps of adaptive integration.
WARNING: if Eps > 0.001 algorithm performs non-adaptive integration.)nbdoc")
        .def("SetLocation", static_cast<void (BRepGProp_Vinert::*)(const gp_Pnt &)>(&BRepGProp_Vinert::SetLocation), nb::arg("VLocation"))
        .def("Perform", static_cast<void (BRepGProp_Vinert::*)(const BRepGProp_Face &)>(&BRepGProp_Vinert::Perform), nb::arg("S"))
        .def("Perform", static_cast<double (BRepGProp_Vinert::*)(BRepGProp_Face &, const double)>(&BRepGProp_Vinert::Perform), nb::arg("S"), nb::arg("Eps"))
        .def("Perform", static_cast<void (BRepGProp_Vinert::*)(const BRepGProp_Face &, const gp_Pnt &)>(&BRepGProp_Vinert::Perform), nb::arg("S"), nb::arg("O"))
        .def("Perform", static_cast<double (BRepGProp_Vinert::*)(BRepGProp_Face &, const gp_Pnt &, const double)>(&BRepGProp_Vinert::Perform), nb::arg("S"), nb::arg("O"), nb::arg("Eps"))
        .def("Perform", static_cast<void (BRepGProp_Vinert::*)(const BRepGProp_Face &, const gp_Pln &)>(&BRepGProp_Vinert::Perform), nb::arg("S"), nb::arg("Pl"))
        .def("Perform", static_cast<double (BRepGProp_Vinert::*)(BRepGProp_Face &, const gp_Pln &, const double)>(&BRepGProp_Vinert::Perform), nb::arg("S"), nb::arg("Pl"), nb::arg("Eps"))
        .def("Perform", static_cast<void (BRepGProp_Vinert::*)(BRepGProp_Face &, BRepGProp_Domain &)>(&BRepGProp_Vinert::Perform), nb::arg("S"), nb::arg("D"))
        .def("Perform", static_cast<double (BRepGProp_Vinert::*)(BRepGProp_Face &, BRepGProp_Domain &, const double)>(&BRepGProp_Vinert::Perform), nb::arg("S"), nb::arg("D"), nb::arg("Eps"))
        .def("Perform", static_cast<void (BRepGProp_Vinert::*)(BRepGProp_Face &, BRepGProp_Domain &, const gp_Pnt &)>(&BRepGProp_Vinert::Perform), nb::arg("S"), nb::arg("D"), nb::arg("O"))
        .def("Perform", static_cast<double (BRepGProp_Vinert::*)(BRepGProp_Face &, BRepGProp_Domain &, const gp_Pnt &, const double)>(&BRepGProp_Vinert::Perform), nb::arg("S"), nb::arg("D"), nb::arg("O"), nb::arg("Eps"))
        .def("Perform", static_cast<void (BRepGProp_Vinert::*)(BRepGProp_Face &, BRepGProp_Domain &, const gp_Pln &)>(&BRepGProp_Vinert::Perform), nb::arg("S"), nb::arg("D"), nb::arg("Pl"))
        .def("Perform", static_cast<double (BRepGProp_Vinert::*)(BRepGProp_Face &, BRepGProp_Domain &, const gp_Pln &, const double)>(&BRepGProp_Vinert::Perform), nb::arg("S"), nb::arg("D"), nb::arg("Pl"), nb::arg("Eps"))
        .def("GetEpsilon", static_cast<double (BRepGProp_Vinert::*)()>(&BRepGProp_Vinert::GetEpsilon), R"nbdoc(If previously used methods contain Eps parameter
gets actual relative error of the computation, else returns 1.0.)nbdoc");
    nanoocp_implicit_copy_ctor<BRepGProp_Vinert>(nb::borrow<nb::class_<BRepGProp_Vinert>>(m.attr("BRepGProp_Vinert")));
    nb::borrow<nb::class_<BRepGProp_VinertGK>>(m.attr("BRepGProp_VinertGK"))
        .def(nb::init<>(), R"nbdoc(Empty constructor.)nbdoc")
        .def(nb::init<BRepGProp_Face &, const gp_Pnt &, const double, const bool, const bool>(), nb::arg("theSurface"), nb::arg("theLocation"), nb::arg("theTolerance") = static_cast<std::decay_t<const double>>(0.001), nb::arg("theCGFlag") = static_cast<std::decay_t<const bool>>(false), nb::arg("theIFlag") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Constructor. Computes the global properties of a region of
3D space delimited with the naturally restricted surface
and the point VLocation.)nbdoc")
        .def(nb::init<BRepGProp_Face &, const gp_Pnt &, const gp_Pnt &, const double, const bool, const bool>(), nb::arg("theSurface"), nb::arg("thePoint"), nb::arg("theLocation"), nb::arg("theTolerance") = static_cast<std::decay_t<const double>>(0.001), nb::arg("theCGFlag") = static_cast<std::decay_t<const bool>>(false), nb::arg("theIFlag") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Constructor. Computes the global properties of a region of
3D space delimited with the naturally restricted surface
and the point VLocation. The inertia is computed with
respect to thePoint.)nbdoc")
        .def(nb::init<BRepGProp_Face &, BRepGProp_Domain &, const gp_Pnt &, const double, const bool, const bool>(), nb::arg("theSurface"), nb::arg("theDomain"), nb::arg("theLocation"), nb::arg("theTolerance") = static_cast<std::decay_t<const double>>(0.001), nb::arg("theCGFlag") = static_cast<std::decay_t<const bool>>(false), nb::arg("theIFlag") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Constructor. Computes the global properties of a region of
3D space delimited with the surface bounded by the domain
and the point VLocation.)nbdoc")
        .def(nb::init<BRepGProp_Face &, const gp_Pln &, const gp_Pnt &, const double, const bool, const bool>(), nb::arg("theSurface"), nb::arg("thePlane"), nb::arg("theLocation"), nb::arg("theTolerance") = static_cast<std::decay_t<const double>>(0.001), nb::arg("theCGFlag") = static_cast<std::decay_t<const bool>>(false), nb::arg("theIFlag") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Constructor. Computes the global properties of a region of
3D space delimited with the naturally restricted surface
and the plane.)nbdoc")
        .def(nb::init<BRepGProp_Face &, BRepGProp_Domain &, const gp_Pnt &, const gp_Pnt &, const double, const bool, const bool>(), nb::arg("theSurface"), nb::arg("theDomain"), nb::arg("thePoint"), nb::arg("theLocation"), nb::arg("theTolerance") = static_cast<std::decay_t<const double>>(0.001), nb::arg("theCGFlag") = static_cast<std::decay_t<const bool>>(false), nb::arg("theIFlag") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Constructor. Computes the global properties of a region of
3D space delimited with the surface bounded by the domain
and the point VLocation. The inertia is computed with
respect to thePoint.)nbdoc")
        .def(nb::init<BRepGProp_Face &, BRepGProp_Domain &, const gp_Pln &, const gp_Pnt &, const double, const bool, const bool>(), nb::arg("theSurface"), nb::arg("theDomain"), nb::arg("thePlane"), nb::arg("theLocation"), nb::arg("theTolerance") = static_cast<std::decay_t<const double>>(0.001), nb::arg("theCGFlag") = static_cast<std::decay_t<const bool>>(false), nb::arg("theIFlag") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Constructor. Computes the global properties of a region of
3D space delimited with the surface bounded by the domain
and the plane.)nbdoc")
        .def("SetLocation", static_cast<void (BRepGProp_VinertGK::*)(const gp_Pnt &)>(&BRepGProp_VinertGK::SetLocation), nb::arg("theLocation"), R"nbdoc(Sets the vertex that delimit 3D closed region of space.)nbdoc")
        .def("Perform", static_cast<double (BRepGProp_VinertGK::*)(BRepGProp_Face &, const double, const bool, const bool)>(&BRepGProp_VinertGK::Perform), nb::arg("theSurface"), nb::arg("theTolerance") = static_cast<std::decay_t<const double>>(0.001), nb::arg("theCGFlag") = static_cast<std::decay_t<const bool>>(false), nb::arg("theIFlag") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Computes the global properties of a region of 3D space
delimited with the naturally restricted surface and the
point VLocation.)nbdoc")
        .def("Perform", static_cast<double (BRepGProp_VinertGK::*)(BRepGProp_Face &, const gp_Pnt &, const double, const bool, const bool)>(&BRepGProp_VinertGK::Perform), nb::arg("theSurface"), nb::arg("thePoint"), nb::arg("theTolerance") = static_cast<std::decay_t<const double>>(0.001), nb::arg("theCGFlag") = static_cast<std::decay_t<const bool>>(false), nb::arg("theIFlag") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Computes the global properties of a region of 3D space
delimited with the naturally restricted surface and the
point VLocation. The inertia is computed with respect to
thePoint.)nbdoc")
        .def("Perform", static_cast<double (BRepGProp_VinertGK::*)(BRepGProp_Face &, BRepGProp_Domain &, const double, const bool, const bool)>(&BRepGProp_VinertGK::Perform), nb::arg("theSurface"), nb::arg("theDomain"), nb::arg("theTolerance") = static_cast<std::decay_t<const double>>(0.001), nb::arg("theCGFlag") = static_cast<std::decay_t<const bool>>(false), nb::arg("theIFlag") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Computes the global properties of a region of 3D space
delimited with the surface bounded by the domain and the
point VLocation.)nbdoc")
        .def("Perform", static_cast<double (BRepGProp_VinertGK::*)(BRepGProp_Face &, BRepGProp_Domain &, const gp_Pnt &, const double, const bool, const bool)>(&BRepGProp_VinertGK::Perform), nb::arg("theSurface"), nb::arg("theDomain"), nb::arg("thePoint"), nb::arg("theTolerance") = static_cast<std::decay_t<const double>>(0.001), nb::arg("theCGFlag") = static_cast<std::decay_t<const bool>>(false), nb::arg("theIFlag") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Computes the global properties of a region of 3D space
delimited with the surface bounded by the domain and the
point VLocation. The inertia is computed with respect to
thePoint.)nbdoc")
        .def("Perform", static_cast<double (BRepGProp_VinertGK::*)(BRepGProp_Face &, const gp_Pln &, const double, const bool, const bool)>(&BRepGProp_VinertGK::Perform), nb::arg("theSurface"), nb::arg("thePlane"), nb::arg("theTolerance") = static_cast<std::decay_t<const double>>(0.001), nb::arg("theCGFlag") = static_cast<std::decay_t<const bool>>(false), nb::arg("theIFlag") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Computes the global properties of a region of 3D space
delimited with the naturally restricted surface and the
plane.)nbdoc")
        .def("Perform", static_cast<double (BRepGProp_VinertGK::*)(BRepGProp_Face &, BRepGProp_Domain &, const gp_Pln &, const double, const bool, const bool)>(&BRepGProp_VinertGK::Perform), nb::arg("theSurface"), nb::arg("theDomain"), nb::arg("thePlane"), nb::arg("theTolerance") = static_cast<std::decay_t<const double>>(0.001), nb::arg("theCGFlag") = static_cast<std::decay_t<const bool>>(false), nb::arg("theIFlag") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Computes the global properties of a region of 3D space
delimited with the surface bounded by the domain and the
plane.)nbdoc")
        .def("GetErrorReached", static_cast<double (BRepGProp_VinertGK::*)() const>(&BRepGProp_VinertGK::GetErrorReached), R"nbdoc(Returns the relative reached computation error.)nbdoc");
    nanoocp_implicit_copy_ctor<BRepGProp_VinertGK>(nb::borrow<nb::class_<BRepGProp_VinertGK>>(m.attr("BRepGProp_VinertGK")));
    nb::borrow<nb::class_<BRepGProp_MeshCinert>>(m.attr("BRepGProp_MeshCinert"))
        .def(nb::init<>())
        .def("SetLocation", static_cast<void (BRepGProp_MeshCinert::*)(const gp_Pnt &)>(&BRepGProp_MeshCinert::SetLocation), nb::arg("CLocation"))
        .def("Perform", static_cast<void (BRepGProp_MeshCinert::*)(const NCollection_Array1<gp_Pnt> &)>(&BRepGProp_MeshCinert::Perform), nb::arg("theNodes"), R"nbdoc(Computes the global properties of
of polylines represented by set of points.)nbdoc")
        .def_static("PreparePolygon", static_cast<occ::handle<NCollection_HArray1<gp_Pnt>> (*)(const TopoDS_Edge &)>(&BRepGProp_MeshCinert::PreparePolygon), nb::arg("theE"), R"nbdoc(Prepares set of 3d points on base of any available edge polygons:
3D polygon, polygon on triangulation, 2d polygon on surface.
@param[in] theE the edge to extract polygon from
@return array of 3D points, or null handle if edge has no polygons)nbdoc")
        .def_static("PreparePolygon__NCollection_HArray1__gp_Pnt", [](const TopoDS_Edge & theE) { occ::handle<NCollection_HArray1<gp_Pnt>> thePolyg{}; BRepGProp_MeshCinert::PreparePolygon(theE, thePolyg); return thePolyg; }, nb::arg("theE"), R"nbdoc(PreparePolygon__NCollection_HArray1__gp_Pnt: the C++ overload PreparePolygon(const TopoDS_Edge &, occ::handle<NCollection_HArray1<gp_Pnt>> &); the suffix lists its returned out-parameters (nanoOCP R-COLLISION).
Deprecated in OCCT: Use PreparePolygon() returning handle by value instead

@deprecated Use PreparePolygon() returning handle by value instead.)nbdoc");
    nanoocp_implicit_copy_ctor<BRepGProp_MeshCinert>(nb::borrow<nb::class_<BRepGProp_MeshCinert>>(m.attr("BRepGProp_MeshCinert")));
    nb::borrow<nb::class_<BRepGProp_MeshProps>>(m.attr("BRepGProp_MeshProps"))
        .def(nb::init<const BRepGProp_MeshProps::BRepGProp_MeshObjType>(), nb::arg("theType"), R"nbdoc(Constructor takes the type of object.)nbdoc")
        .def("SetLocation", static_cast<void (BRepGProp_MeshProps::*)(const gp_Pnt &)>(&BRepGProp_MeshProps::SetLocation), nb::arg("theLocation"), R"nbdoc(Sets the point relative which the calculation is to be done)nbdoc")
        .def("Perform", static_cast<void (BRepGProp_MeshProps::*)(const occ::handle<Poly_Triangulation> &, const TopLoc_Location &, const TopAbs_Orientation)>(&BRepGProp_MeshProps::Perform), nb::arg("theMesh").none(), nb::arg("theLoc"), nb::arg("theOri"), R"nbdoc(Computes the global properties of a surface mesh of 3D space.
Calculation of surface properties is performed by numerical integration
over triangle surfaces using Gauss cubature formulas.
Depending on the mesh object type used in constructor this method can
calculate the surface or volume properties of the mesh.)nbdoc")
        .def("Perform", static_cast<void (BRepGProp_MeshProps::*)(const occ::handle<Poly_Triangulation> &, const TopAbs_Orientation)>(&BRepGProp_MeshProps::Perform), nb::arg("theMesh").none(), nb::arg("theOri"))
        .def("GetMeshObjType", static_cast<BRepGProp_MeshProps::BRepGProp_MeshObjType (BRepGProp_MeshProps::*)() const>(&BRepGProp_MeshProps::GetMeshObjType), R"nbdoc(Get type of mesh object)nbdoc");
    nanoocp_implicit_copy_ctor<BRepGProp_MeshProps>(nb::borrow<nb::class_<BRepGProp_MeshProps>>(m.attr("BRepGProp_MeshProps")));
    nb::implicitly_convertible<std::decay_t<const BRepGProp_MeshProps::BRepGProp_MeshObjType>, BRepGProp_MeshProps>();
    m.attr("math_Vector") = nb::module_::import_("nanoocp._TKMath.math").attr("math_Vector");   // math_Vector = math_VectorBase<double>
}

void nanoocp_conversions_BRepGProp(nb::module_ &m) {
}
