// Generated by the nanoOCP generator from OCCT package BRepMAT2d (toolkit TKTopAlgo). Do not edit.
#include "nanoocp_common.h"
#include <BRepMAT2d_BisectingLocus.hxx>
#include <BRepMAT2d_Explorer.hxx>
#include <BRepMAT2d_LinkTopoBilo.hxx>
#include <Bisector_Bisec.hxx>
#include <Geom2d_Curve.hxx>
#include <Geom2d_Geometry.hxx>
#include <GeomAbs_JoinType.hxx>
#include <MAT_Arc.hxx>
#include <MAT_BasicElt.hxx>
#include <MAT_Graph.hxx>
#include <MAT_Node.hxx>
#include <MAT_Side.hxx>
#include <NCollection_Sequence.hxx>
#include <TopoDS_Face.hxx>
#include <TopoDS_Shape.hxx>
#include <gp_Pnt2d.hxx>

void nanoocp_declare_BRepMAT2d(nb::module_ &m) {
    { nb::class_<BRepMAT2d_BisectingLocus> cls(m, "BRepMAT2d_BisectingLocus", R"nbdoc(BisectingLocus generates and contains the Bisecting_Locus
of a set of lines from Geom2d, defined by <ExploSet>.

If the set of lines contains closed lines:
------------------------------------------
These lines cut the plane in areas.
One map can be computed for each area.

Bisecting locus computes a map in an area.
The area is defined by a side (MAT_Left,MAT_Right)
on one of the closed lines.

If the set of lines contains only open lines:
--------------------------------------------
the map recovers all the plane.

Warning: Assume the orientation of the closed lines are
compatible.

Assume the explo contains only lines located in the
area where the bisecting locus will be computed.

Assume a line don't cross itself or an other line.

Remark:
the curves coming from the explorer can be
decomposed in different parts. It the case for the
curves other than circles or lines.

The map of bisecting locus is described by a graph.
- The BasicsElements correspond to elements on
the figure described by the Explorer from BRepMAT2d.
- The Arcs correspond to the bisectors.
- The Nodes are the extremities of the arcs.)nbdoc");
    }
    { nb::class_<BRepMAT2d_Explorer> cls(m, "BRepMAT2d_Explorer", R"nbdoc(Construct an explorer from wires, face, set of curves
from Geom2d to compute the bisecting Locus.)nbdoc");
    }
    { nb::class_<BRepMAT2d_LinkTopoBilo> cls(m, "BRepMAT2d_LinkTopoBilo", R"nbdoc(Constructs links between the Wire or the Face of the explorer and
the BasicElts contained in the bisecting locus.)nbdoc");
    }
}

void nanoocp_templates_BRepMAT2d(nb::module_ &m) {
}

void nanoocp_define_BRepMAT2d(nb::module_ &m) {
    nb::borrow<nb::class_<BRepMAT2d_BisectingLocus>>(m.attr("BRepMAT2d_BisectingLocus"))
        .def(nb::init<>())
        .def("Compute", static_cast<void (BRepMAT2d_BisectingLocus::*)(BRepMAT2d_Explorer &, const int, const MAT_Side, const GeomAbs_JoinType, const bool)>(&BRepMAT2d_BisectingLocus::Compute), nb::arg("anExplo"), nb::arg("LineIndex") = static_cast<std::decay_t<const int>>(1), nb::arg("aSide") = static_cast<std::decay_t<const MAT_Side>>(MAT_Left), nb::arg("aJoinType") = static_cast<std::decay_t<const GeomAbs_JoinType>>(GeomAbs_Arc), nb::arg("IsOpenResult") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Computation of the Bisector_Locus in a set of Lines
defined in <anExplo>.
The bisecting locus are computed on the side <aSide>
from the line <LineIndex> in <anExplo>.)nbdoc")
        .def("IsDone", static_cast<bool (BRepMAT2d_BisectingLocus::*)() const>(&BRepMAT2d_BisectingLocus::IsDone), R"nbdoc(Returns True if Compute has succeeded.)nbdoc")
        .def("Graph", static_cast<occ::handle<MAT_Graph> (BRepMAT2d_BisectingLocus::*)() const>(&BRepMAT2d_BisectingLocus::Graph), R"nbdoc(Returns <theGraph> of <me>.)nbdoc")
        .def("NumberOfContours", static_cast<int (BRepMAT2d_BisectingLocus::*)() const>(&BRepMAT2d_BisectingLocus::NumberOfContours), R"nbdoc(Returns the number of contours.)nbdoc")
        .def("NumberOfElts", static_cast<int (BRepMAT2d_BisectingLocus::*)(const int) const>(&BRepMAT2d_BisectingLocus::NumberOfElts), nb::arg("IndLine"), R"nbdoc(Returns the number of BasicElts on the line
<IndLine>.)nbdoc")
        .def("NumberOfSections", static_cast<int (BRepMAT2d_BisectingLocus::*)(const int, const int) const>(&BRepMAT2d_BisectingLocus::NumberOfSections), nb::arg("IndLine"), nb::arg("Index"), R"nbdoc(Returns the number of sections of a curve.
this curve is the Indexth curve in the IndLineth contour
given by anExplo.)nbdoc")
        .def("BasicElt", static_cast<occ::handle<MAT_BasicElt> (BRepMAT2d_BisectingLocus::*)(const int, const int) const>(&BRepMAT2d_BisectingLocus::BasicElt), nb::arg("IndLine"), nb::arg("Index"), R"nbdoc(Returns the BasicElts located at the position
<Index> on the contour designed by <IndLine>.
Remark: the BasicElts on a contour are sorted.)nbdoc")
        .def("GeomElt", static_cast<occ::handle<Geom2d_Geometry> (BRepMAT2d_BisectingLocus::*)(const occ::handle<MAT_BasicElt> &) const>(&BRepMAT2d_BisectingLocus::GeomElt), nb::arg("aBasicElt").none(), R"nbdoc(Returns the geometry linked to the <BasicElt>.)nbdoc")
        .def("GeomElt", static_cast<gp_Pnt2d (BRepMAT2d_BisectingLocus::*)(const occ::handle<MAT_Node> &) const>(&BRepMAT2d_BisectingLocus::GeomElt), nb::arg("aNode").none(), R"nbdoc(Returns the geometry of type <gp> linked to
the <Node>.)nbdoc")
        .def("GeomBis", [](const BRepMAT2d_BisectingLocus &self, const occ::handle<MAT_Arc> & anArc) { bool Reverse{}; auto result = self.GeomBis(anArc, Reverse); return std::make_tuple(result, Reverse); }, nb::arg("anArc").none(), R"nbdoc(Returns the geometry of type <Bissec>
linked to the arc <ARC>.
<Reverse> is False when the FirstNode of <anArc>
correspond to the first point of geometry.)nbdoc");
    nanoocp_implicit_copy_ctor<BRepMAT2d_BisectingLocus>(nb::borrow<nb::class_<BRepMAT2d_BisectingLocus>>(m.attr("BRepMAT2d_BisectingLocus")));
    nanoocp_def_iter<BRepMAT2d_Explorer>(nb::borrow<nb::class_<BRepMAT2d_Explorer>>(m.attr("BRepMAT2d_Explorer")), [](BRepMAT2d_Explorer &self) { return self.Value(); });
    nb::borrow<nb::class_<BRepMAT2d_Explorer>>(m.attr("BRepMAT2d_Explorer"))
        .def(nb::init<>())
        .def(nb::init<const TopoDS_Face &>(), nb::arg("aFace"))
        .def("Clear", static_cast<void (BRepMAT2d_Explorer::*)()>(&BRepMAT2d_Explorer::Clear), R"nbdoc(Clear the contents of <me>.)nbdoc")
        .def("Perform", static_cast<void (BRepMAT2d_Explorer::*)(const TopoDS_Face &)>(&BRepMAT2d_Explorer::Perform), nb::arg("aFace"))
        .def("NumberOfContours", static_cast<int (BRepMAT2d_Explorer::*)() const>(&BRepMAT2d_Explorer::NumberOfContours), R"nbdoc(Returns the Number of contours.)nbdoc")
        .def("NumberOfCurves", static_cast<int (BRepMAT2d_Explorer::*)(const int) const>(&BRepMAT2d_Explorer::NumberOfCurves), nb::arg("IndexContour"), R"nbdoc(Returns the Number of Curves in the Contour number
<IndexContour>.)nbdoc")
        .def("Init", static_cast<void (BRepMAT2d_Explorer::*)(const int)>(&BRepMAT2d_Explorer::Init), nb::arg("IndexContour"), R"nbdoc(Initialisation of an Iterator on the curves of
the Contour number <IndexContour>.)nbdoc")
        .def("More", static_cast<bool (BRepMAT2d_Explorer::*)() const>(&BRepMAT2d_Explorer::More), R"nbdoc(Return False if there is no more curves on the Contour
initialised by the method Init.)nbdoc")
        .def("Next", static_cast<void (BRepMAT2d_Explorer::*)()>(&BRepMAT2d_Explorer::Next), R"nbdoc(Move to the next curve of the current Contour.)nbdoc")
        .def("Value", static_cast<occ::handle<Geom2d_Curve> (BRepMAT2d_Explorer::*)() const>(&BRepMAT2d_Explorer::Value), R"nbdoc(Returns the current curve on the current Contour.)nbdoc")
        .def("Shape", static_cast<TopoDS_Shape (BRepMAT2d_Explorer::*)() const>(&BRepMAT2d_Explorer::Shape))
        .def("Contour", static_cast<const NCollection_Sequence<opencascade::handle<Geom2d_Curve>> & (BRepMAT2d_Explorer::*)(const int) const>(&BRepMAT2d_Explorer::Contour), nb::arg("IndexContour"))
        .def("IsModified", static_cast<bool (BRepMAT2d_Explorer::*)(const TopoDS_Shape &) const>(&BRepMAT2d_Explorer::IsModified), nb::arg("aShape"))
        .def("ModifiedShape", static_cast<TopoDS_Shape (BRepMAT2d_Explorer::*)(const TopoDS_Shape &) const>(&BRepMAT2d_Explorer::ModifiedShape), nb::arg("aShape"), R"nbdoc(If the shape is not modified, returns the shape itself.)nbdoc")
        .def("GetIsClosed", static_cast<const NCollection_Sequence<bool> & (BRepMAT2d_Explorer::*)() const>(&BRepMAT2d_Explorer::GetIsClosed));
    nanoocp_implicit_copy_ctor<BRepMAT2d_Explorer>(nb::borrow<nb::class_<BRepMAT2d_Explorer>>(m.attr("BRepMAT2d_Explorer")));
    nb::implicitly_convertible<std::decay_t<const TopoDS_Face &>, BRepMAT2d_Explorer>();
    nanoocp_def_iter<BRepMAT2d_LinkTopoBilo>(nb::borrow<nb::class_<BRepMAT2d_LinkTopoBilo>>(m.attr("BRepMAT2d_LinkTopoBilo")), [](BRepMAT2d_LinkTopoBilo &self) { return self.Value(); });
    nb::borrow<nb::class_<BRepMAT2d_LinkTopoBilo>>(m.attr("BRepMAT2d_LinkTopoBilo"))
        .def(nb::init<>())
        .def(nb::init<const BRepMAT2d_Explorer &, const BRepMAT2d_BisectingLocus &>(), nb::arg("Explo"), nb::arg("BiLo"), R"nbdoc(Constructs the links Between S and BiLo.

raises if <S> is not a face.)nbdoc")
        .def("Perform", static_cast<void (BRepMAT2d_LinkTopoBilo::*)(const BRepMAT2d_Explorer &, const BRepMAT2d_BisectingLocus &)>(&BRepMAT2d_LinkTopoBilo::Perform), nb::arg("Explo"), nb::arg("BiLo"), R"nbdoc(Constructs the links Between S and BiLo.

raises if <S> is not a face or a wire.)nbdoc")
        .def("Init", static_cast<void (BRepMAT2d_LinkTopoBilo::*)(const TopoDS_Shape &)>(&BRepMAT2d_LinkTopoBilo::Init), nb::arg("S"), R"nbdoc(Initialise the Iterator on <S>
<S> is an edge or a vertex of the initial
wire or face.
raises if <S> is not an edge or a vertex.)nbdoc")
        .def("More", static_cast<bool (BRepMAT2d_LinkTopoBilo::*)()>(&BRepMAT2d_LinkTopoBilo::More), R"nbdoc(Returns True if there is a current BasicElt.)nbdoc")
        .def("Next", static_cast<void (BRepMAT2d_LinkTopoBilo::*)()>(&BRepMAT2d_LinkTopoBilo::Next), R"nbdoc(Proceed to the next BasicElt.)nbdoc")
        .def("Value", static_cast<occ::handle<MAT_BasicElt> (BRepMAT2d_LinkTopoBilo::*)() const>(&BRepMAT2d_LinkTopoBilo::Value), R"nbdoc(Returns the current BasicElt.)nbdoc")
        .def("GeneratingShape", static_cast<TopoDS_Shape (BRepMAT2d_LinkTopoBilo::*)(const occ::handle<MAT_BasicElt> &) const>(&BRepMAT2d_LinkTopoBilo::GeneratingShape), nb::arg("aBE").none(), R"nbdoc(Returns the Shape linked to <aBE>.)nbdoc");
    nanoocp_implicit_copy_ctor<BRepMAT2d_LinkTopoBilo>(nb::borrow<nb::class_<BRepMAT2d_LinkTopoBilo>>(m.attr("BRepMAT2d_LinkTopoBilo")));
}

void nanoocp_conversions_BRepMAT2d(nb::module_ &m) {
}
