// Generated by the nanoOCP generator from OCCT package Approx (toolkit TKGeomBase). Do not edit.
#include "nanoocp_common.h"
#include "nanoocp_ncollection.h"
#include <Approx_Curve2d.hxx>
#include <Approx_Curve3d.hxx>
#include <Approx_CurveOnSurface.hxx>
#include <Approx_CurvilinearParameter.hxx>
#include <Approx_CurvlinFunc.hxx>
#include <Approx_FitAndDivide.hxx>
#include <Approx_FitAndDivide2d.hxx>
#include <Approx_MCurvesToBSpCurve.hxx>
#include <Approx_ParametrizationType.hxx>
#include <Approx_SameParameter.hxx>
#include <Approx_Status.hxx>
#include <Approx_SweepApproximation.hxx>
#include <Approx_SweepFunction.hxx>
#include <Adaptor2d_Curve2d.hxx>
#include <Adaptor3d_Curve.hxx>
#include <Adaptor3d_CurveOnSurface.hxx>
#include <Adaptor3d_Surface.hxx>
#include <AppCont_Function.hxx>
#include <AppParCurves_Constraint.hxx>
#include <AppParCurves_MultiBSpCurve.hxx>
#include <AppParCurves_MultiCurve.hxx>
#include <Geom2d_BSplineCurve.hxx>
#include <Geom2d_Curve.hxx>
#include <GeomAbs_Shape.hxx>
#include <Geom_BSplineCurve.hxx>
#include <Geom_Curve.hxx>
#include <Geom_Surface.hxx>
#include <NCollection_Array1.hxx>
#include <NCollection_Array2.hxx>
#include <NCollection_Sequence.hxx>
#include <Standard_OStream.hxx>
#include <Standard_Transient.hxx>
#include <Standard_Type.hxx>
#include <gp_Pnt.hxx>
#include <gp_Pnt2d.hxx>
#include <gp_Vec.hxx>
#include <gp_Vec2d.hxx>

void nanoocp_declare_Approx(nb::module_ &m) {
    nb::enum_<Approx_ParametrizationType>(m, "Approx_ParametrizationType", nb::is_arithmetic())
        .value("Approx_ChordLength", Approx_ChordLength)
        .value("Approx_Centripetal", Approx_Centripetal)
        .value("Approx_IsoParametric", Approx_IsoParametric)
        .export_values();
    nb::enum_<Approx_Status>(m, "Approx_Status", R"nbdoc(It is an auxiliary flag being used in inner computations)nbdoc", nb::is_arithmetic())
        .value("Approx_PointsAdded", Approx_PointsAdded)
        .value("Approx_NoPointsAdded", Approx_NoPointsAdded)
        .value("Approx_NoApproximation", Approx_NoApproximation)
        .export_values();
    { nb::class_<Approx_Curve2d> cls(m, "Approx_Curve2d", R"nbdoc(Makes an approximation for HCurve2d from Adaptor3d)nbdoc");
    }
    { nb::class_<Approx_Curve3d> cls(m, "Approx_Curve3d");
    }
    { nb::class_<Approx_CurveOnSurface> cls(m, "Approx_CurveOnSurface", R"nbdoc(Approximation of curve on surface)nbdoc");
    }
    { nb::class_<Approx_CurvilinearParameter> cls(m, "Approx_CurvilinearParameter", R"nbdoc(Approximation of a Curve to make its parameter be its curvilinear abscissa.
If the curve is a curve on a surface S, C2D is the corresponding Pcurve,
we consider the curve is given by its representation
@code
S(C2D(u))
@endcode
If the curve is a curve on 2 surfaces S1 and S2 and C2D1 C2D2 are the two corresponding Pcurve,
we consider the curve is given by its representation
@code
1/2(S1(C2D1(u) + S2(C2D2(u)))
@endcode)nbdoc");
    }
    { nb::class_<Approx_CurvlinFunc, Standard_Transient> cls(m, "Approx_CurvlinFunc", R"nbdoc(defines an abstract curve with
curvilinear parametrization)nbdoc");
    }
    { nb::class_<Approx_FitAndDivide> cls(m, "Approx_FitAndDivide");
    }
    { nb::class_<Approx_FitAndDivide2d> cls(m, "Approx_FitAndDivide2d");
    }
    { nb::class_<Approx_MCurvesToBSpCurve> cls(m, "Approx_MCurvesToBSpCurve");
    }
    { nb::class_<Approx_SameParameter> cls(m, "Approx_SameParameter", R"nbdoc(Approximation of a PCurve on a surface to make its
parameter be the same that the parameter of a given 3d
reference curve.)nbdoc");
    }
    { nb::class_<Approx_SweepApproximation> cls(m, "Approx_SweepApproximation", R"nbdoc(Approximation of an Surface S(u,v)
(and eventually associate 2d Curves) defined
by section's law.

This surface is defined by a function F(u, v)
where Ft(u) = F(u, t) is a bspline curve.
To use this algorithm, you have to implement Ft(u)
as a derivative class of Approx_SweepFunction.
This algorithm can be used by blending, sweeping...)nbdoc");
    }
    { nb::class_<Approx_SweepFunction, Standard_Transient> cls(m, "Approx_SweepFunction", R"nbdoc(defined the function used by SweepApproximation to
perform sweeping application.)nbdoc");
    }
}

void nanoocp_templates_Approx(nb::module_ &m) {
    { nb::module_ home = nb::module_::import_("nanoocp._TKernel.NCollection"); nanoocp::bind_NCollection_Sequence<AppParCurves_MultiCurve>(home, "NCollection_Sequence__AppParCurves_MultiCurve"); }
}

void nanoocp_define_Approx(nb::module_ &m) {
    nb::borrow<nb::class_<Approx_Curve2d>>(m.attr("Approx_Curve2d"))
        .def(nb::init<const occ::handle<Adaptor2d_Curve2d> &, const double, const double, const double, const double, const GeomAbs_Shape, const int, const int>(), nb::arg("C2D").none(), nb::arg("First"), nb::arg("Last"), nb::arg("TolU"), nb::arg("TolV"), nb::arg("Continuity"), nb::arg("MaxDegree"), nb::arg("MaxSegments"))
        .def("IsDone", static_cast<bool (Approx_Curve2d::*)() const>(&Approx_Curve2d::IsDone))
        .def("HasResult", static_cast<bool (Approx_Curve2d::*)() const>(&Approx_Curve2d::HasResult))
        .def("Curve", static_cast<occ::handle<Geom2d_BSplineCurve> (Approx_Curve2d::*)() const>(&Approx_Curve2d::Curve))
        .def("MaxError2dU", static_cast<double (Approx_Curve2d::*)() const>(&Approx_Curve2d::MaxError2dU))
        .def("MaxError2dV", static_cast<double (Approx_Curve2d::*)() const>(&Approx_Curve2d::MaxError2dV));
    nanoocp_implicit_copy_ctor<Approx_Curve2d>(nb::borrow<nb::class_<Approx_Curve2d>>(m.attr("Approx_Curve2d")));
    nb::borrow<nb::class_<Approx_Curve3d>>(m.attr("Approx_Curve3d"))
        .def(nb::init<const occ::handle<Adaptor3d_Curve> &, const double, const GeomAbs_Shape, const int, const int>(), nb::arg("Curve").none(), nb::arg("Tol3d"), nb::arg("Order"), nb::arg("MaxSegments"), nb::arg("MaxDegree"), R"nbdoc(Approximation of a curve with respect of the
required tolerance Tol3D.)nbdoc")
        .def("Curve", static_cast<occ::handle<Geom_BSplineCurve> (Approx_Curve3d::*)() const>(&Approx_Curve3d::Curve))
        .def("IsDone", static_cast<bool (Approx_Curve3d::*)() const>(&Approx_Curve3d::IsDone), R"nbdoc(returns true if the approximation has
been done within required tolerance)nbdoc")
        .def("HasResult", static_cast<bool (Approx_Curve3d::*)() const>(&Approx_Curve3d::HasResult), R"nbdoc(returns true if the approximation did come out
with a result that is not NECESSARILY within the required
tolerance)nbdoc")
        .def("MaxError", static_cast<double (Approx_Curve3d::*)() const>(&Approx_Curve3d::MaxError), R"nbdoc(returns the Maximum Error (>0 when an approximation
has been done, 0 if no approximation))nbdoc")
        .def("Dump", [](const Approx_Curve3d &self) { std::ostringstream o_stream; self.Dump(o_stream); return nanoocp_stream_text(o_stream); }, R"nbdoc(Print on the stream 'o' information about the object)nbdoc");
    nanoocp_implicit_copy_ctor<Approx_Curve3d>(nb::borrow<nb::class_<Approx_Curve3d>>(m.attr("Approx_Curve3d")));
    nb::borrow<nb::class_<Approx_CurveOnSurface>>(m.attr("Approx_CurveOnSurface"))
        .def(nb::init<const occ::handle<Adaptor2d_Curve2d> &, const occ::handle<Adaptor3d_Surface> &, const double, const double, const double>(), nb::arg("theC2D").none(), nb::arg("theSurf").none(), nb::arg("theFirst"), nb::arg("theLast"), nb::arg("theTol"), R"nbdoc(This constructor does not call perform method.
@param theC2D   2D Curve to be approximated in 3D.
@param theSurf  Surface where 2D curve is located.
@param theFirst First parameter of resulting curve.
@param theFirst Last parameter of resulting curve.
@param theTol   Computation tolerance.)nbdoc")
        .def(nb::init<const occ::handle<Adaptor2d_Curve2d> &, const occ::handle<Adaptor3d_Surface> &, const double, const double, const double, const GeomAbs_Shape, const int, const int, const bool, const bool>(), nb::arg("C2D").none(), nb::arg("Surf").none(), nb::arg("First"), nb::arg("Last"), nb::arg("Tol"), nb::arg("Continuity"), nb::arg("MaxDegree"), nb::arg("MaxSegments"), nb::arg("Only3d") = static_cast<std::decay_t<const bool>>(false), nb::arg("Only2d") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Deprecated in OCCT: This constructor is deprecated. Use other constructor and perform method instead.

This constructor calls perform method. This constructor is deprecated.)nbdoc")
        .def("IsDone", static_cast<bool (Approx_CurveOnSurface::*)() const>(&Approx_CurveOnSurface::IsDone))
        .def("HasResult", static_cast<bool (Approx_CurveOnSurface::*)() const>(&Approx_CurveOnSurface::HasResult))
        .def("Curve3d", static_cast<occ::handle<Geom_BSplineCurve> (Approx_CurveOnSurface::*)() const>(&Approx_CurveOnSurface::Curve3d))
        .def("MaxError3d", static_cast<double (Approx_CurveOnSurface::*)() const>(&Approx_CurveOnSurface::MaxError3d))
        .def("Curve2d", static_cast<occ::handle<Geom2d_BSplineCurve> (Approx_CurveOnSurface::*)() const>(&Approx_CurveOnSurface::Curve2d))
        .def("MaxError2dU", static_cast<double (Approx_CurveOnSurface::*)() const>(&Approx_CurveOnSurface::MaxError2dU))
        .def("MaxError2dV", static_cast<double (Approx_CurveOnSurface::*)() const>(&Approx_CurveOnSurface::MaxError2dV), R"nbdoc(returns the maximum errors relatively to the U component or the V component of the
2d Curve)nbdoc")
        .def("Perform", static_cast<void (Approx_CurveOnSurface::*)(const int, const int, const GeomAbs_Shape, const bool, const bool)>(&Approx_CurveOnSurface::Perform), nb::arg("theMaxSegments"), nb::arg("theMaxDegree"), nb::arg("theContinuity"), nb::arg("theOnly3d") = static_cast<std::decay_t<const bool>>(false), nb::arg("theOnly2d") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Constructs the 3d curve. Input parameters are ignored when the input curve is
U-isoline or V-isoline.
@param theMaxSegments Maximal number of segments in the resulting spline.
@param theMaxDegree   Maximal degree of the result.
@param theContinuity  Resulting continuity.
@param theOnly3d      Determines building only 3D curve.
@param theOnly2d      Determines building only 2D curve.)nbdoc");
    nanoocp_implicit_copy_ctor<Approx_CurveOnSurface>(nb::borrow<nb::class_<Approx_CurveOnSurface>>(m.attr("Approx_CurveOnSurface")));
    nb::borrow<nb::class_<Approx_CurvilinearParameter>>(m.attr("Approx_CurvilinearParameter"))
        .def(nb::init<const occ::handle<Adaptor3d_Curve> &, const double, const GeomAbs_Shape, const int, const int>(), nb::arg("C3D").none(), nb::arg("Tol"), nb::arg("Order"), nb::arg("MaxDegree"), nb::arg("MaxSegments"), R"nbdoc(case of a free 3D curve)nbdoc")
        .def(nb::init<const occ::handle<Adaptor2d_Curve2d> &, const occ::handle<Adaptor3d_Surface> &, const double, const GeomAbs_Shape, const int, const int>(), nb::arg("C2D").none(), nb::arg("Surf").none(), nb::arg("Tol"), nb::arg("Order"), nb::arg("MaxDegree"), nb::arg("MaxSegments"), R"nbdoc(case of a curve on one surface)nbdoc")
        .def(nb::init<const occ::handle<Adaptor2d_Curve2d> &, const occ::handle<Adaptor3d_Surface> &, const occ::handle<Adaptor2d_Curve2d> &, const occ::handle<Adaptor3d_Surface> &, const double, const GeomAbs_Shape, const int, const int>(), nb::arg("C2D1").none(), nb::arg("Surf1").none(), nb::arg("C2D2").none(), nb::arg("Surf2").none(), nb::arg("Tol"), nb::arg("Order"), nb::arg("MaxDegree"), nb::arg("MaxSegments"), R"nbdoc(case of a curve on two surfaces)nbdoc")
        .def("IsDone", static_cast<bool (Approx_CurvilinearParameter::*)() const>(&Approx_CurvilinearParameter::IsDone))
        .def("HasResult", static_cast<bool (Approx_CurvilinearParameter::*)() const>(&Approx_CurvilinearParameter::HasResult))
        .def("Curve3d", static_cast<occ::handle<Geom_BSplineCurve> (Approx_CurvilinearParameter::*)() const>(&Approx_CurvilinearParameter::Curve3d), R"nbdoc(returns the Bspline curve corresponding to the reparametrized 3D curve)nbdoc")
        .def("MaxError3d", static_cast<double (Approx_CurvilinearParameter::*)() const>(&Approx_CurvilinearParameter::MaxError3d), R"nbdoc(returns the maximum error on the reparametrized 3D curve)nbdoc")
        .def("Curve2d1", static_cast<occ::handle<Geom2d_BSplineCurve> (Approx_CurvilinearParameter::*)() const>(&Approx_CurvilinearParameter::Curve2d1), R"nbdoc(returns the BsplineCurve representing the reparametrized 2D curve on the
first surface (case of a curve on one or two surfaces))nbdoc")
        .def("MaxError2d1", static_cast<double (Approx_CurvilinearParameter::*)() const>(&Approx_CurvilinearParameter::MaxError2d1), R"nbdoc(returns the maximum error on the first reparametrized 2D curve)nbdoc")
        .def("Curve2d2", static_cast<occ::handle<Geom2d_BSplineCurve> (Approx_CurvilinearParameter::*)() const>(&Approx_CurvilinearParameter::Curve2d2), R"nbdoc(returns the BsplineCurve representing the reparametrized 2D curve on the
second surface (case of a curve on two surfaces))nbdoc")
        .def("MaxError2d2", static_cast<double (Approx_CurvilinearParameter::*)() const>(&Approx_CurvilinearParameter::MaxError2d2), R"nbdoc(returns the maximum error on the second reparametrized 2D curve)nbdoc")
        .def("Dump", [](const Approx_CurvilinearParameter &self) { std::ostringstream o_stream; self.Dump(o_stream); return nanoocp_stream_text(o_stream); }, R"nbdoc(print the maximum errors(s))nbdoc");
    nanoocp_implicit_copy_ctor<Approx_CurvilinearParameter>(nb::borrow<nb::class_<Approx_CurvilinearParameter>>(m.attr("Approx_CurvilinearParameter")));
    nb::borrow<nb::class_<Approx_CurvlinFunc>>(m.attr("Approx_CurvlinFunc"))
        .def(nb::new_([](const occ::handle<Adaptor3d_Curve> & C, const double Tol) { return opencascade::handle<Approx_CurvlinFunc>(new Approx_CurvlinFunc(C, Tol)); }), nb::arg("C").none(), nb::arg("Tol"))
        .def(nb::new_([](const occ::handle<Adaptor2d_Curve2d> & C2D, const occ::handle<Adaptor3d_Surface> & S, const double Tol) { return opencascade::handle<Approx_CurvlinFunc>(new Approx_CurvlinFunc(C2D, S, Tol)); }), nb::arg("C2D").none(), nb::arg("S").none(), nb::arg("Tol"))
        .def(nb::new_([](const occ::handle<Adaptor2d_Curve2d> & C2D1, const occ::handle<Adaptor2d_Curve2d> & C2D2, const occ::handle<Adaptor3d_Surface> & S1, const occ::handle<Adaptor3d_Surface> & S2, const double Tol) { return opencascade::handle<Approx_CurvlinFunc>(new Approx_CurvlinFunc(C2D1, C2D2, S1, S2, Tol)); }), nb::arg("C2D1").none(), nb::arg("C2D2").none(), nb::arg("S1").none(), nb::arg("S2").none(), nb::arg("Tol"))
        .def("SetTol", static_cast<void (Approx_CurvlinFunc::*)(const double)>(&Approx_CurvlinFunc::SetTol), nb::arg("Tol"), R"nbdoc(---Purpose Update the tolerance to used)nbdoc")
        .def("FirstParameter", static_cast<double (Approx_CurvlinFunc::*)() const>(&Approx_CurvlinFunc::FirstParameter))
        .def("LastParameter", static_cast<double (Approx_CurvlinFunc::*)() const>(&Approx_CurvlinFunc::LastParameter))
        .def("NbIntervals", static_cast<int (Approx_CurvlinFunc::*)(const GeomAbs_Shape) const>(&Approx_CurvlinFunc::NbIntervals), nb::arg("S"), R"nbdoc(Returns the number of intervals for continuity
<S>. May be one if Continuity(me) >= <S>)nbdoc")
        .def("Intervals", static_cast<void (Approx_CurvlinFunc::*)(NCollection_Array1<double> &, const GeomAbs_Shape) const>(&Approx_CurvlinFunc::Intervals), nb::arg("T"), nb::arg("S"), R"nbdoc(Stores in <T> the parameters bounding the intervals
of continuity <S>.

The array must provide enough room to accommodate
for the parameters. i.e. T.Length() > NbIntervals())nbdoc")
        .def("Trim", static_cast<void (Approx_CurvlinFunc::*)(const double, const double, const double)>(&Approx_CurvlinFunc::Trim), nb::arg("First"), nb::arg("Last"), nb::arg("Tol"), R"nbdoc(if First < 0 or Last > 1)nbdoc")
        .def("Length", static_cast<void (Approx_CurvlinFunc::*)()>(&Approx_CurvlinFunc::Length), R"nbdoc(Computes length of the curve.)nbdoc")
        .def("Length", static_cast<double (Approx_CurvlinFunc::*)(Adaptor3d_Curve &, const double, const double) const>(&Approx_CurvlinFunc::Length), nb::arg("C"), nb::arg("FirstU"), nb::arg("LasrU"), R"nbdoc(Computes length of the curve segment.)nbdoc")
        .def("GetLength", static_cast<double (Approx_CurvlinFunc::*)() const>(&Approx_CurvlinFunc::GetLength))
        .def("GetUParameter", static_cast<double (Approx_CurvlinFunc::*)(Adaptor3d_Curve &, const double, const int) const>(&Approx_CurvlinFunc::GetUParameter), nb::arg("C"), nb::arg("S"), nb::arg("NumberOfCurve"), R"nbdoc(returns original parameter corresponding S. if
Case == 1 computation is performed on myC2D1 and mySurf1,
otherwise it is done on myC2D2 and mySurf2.)nbdoc")
        .def("GetSParameter", static_cast<double (Approx_CurvlinFunc::*)(const double) const>(&Approx_CurvlinFunc::GetSParameter), nb::arg("U"), R"nbdoc(returns original parameter corresponding S.)nbdoc")
        .def("EvalCase1", static_cast<bool (Approx_CurvlinFunc::*)(const double, const int, NCollection_Array1<double> &) const>(&Approx_CurvlinFunc::EvalCase1), nb::arg("S"), nb::arg("Order"), nb::arg("Result"), R"nbdoc(if myCase != 1)nbdoc")
        .def("EvalCase2", static_cast<bool (Approx_CurvlinFunc::*)(const double, const int, NCollection_Array1<double> &) const>(&Approx_CurvlinFunc::EvalCase2), nb::arg("S"), nb::arg("Order"), nb::arg("Result"), R"nbdoc(if myCase != 2)nbdoc")
        .def("EvalCase3", static_cast<bool (Approx_CurvlinFunc::*)(const double, const int, NCollection_Array1<double> &)>(&Approx_CurvlinFunc::EvalCase3), nb::arg("S"), nb::arg("Order"), nb::arg("Result"), R"nbdoc(if myCase != 3)nbdoc")
        .def_static("get_type_name", static_cast<const char * (*)()>(&Approx_CurvlinFunc::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&Approx_CurvlinFunc::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (Approx_CurvlinFunc::*)() const>(&Approx_CurvlinFunc::DynamicType));
    nanoocp_implicit_copy_ctor<Approx_CurvlinFunc>(nb::borrow<nb::class_<Approx_CurvlinFunc>>(m.attr("Approx_CurvlinFunc")));
    nb::borrow<nb::class_<Approx_FitAndDivide>>(m.attr("Approx_FitAndDivide"))
        .def(nb::init<const int, const int, const double, const double, const bool, const AppParCurves_Constraint, const AppParCurves_Constraint>(), nb::arg("degreemin") = static_cast<std::decay_t<const int>>(3), nb::arg("degreemax") = static_cast<std::decay_t<const int>>(8), nb::arg("Tolerance3d") = static_cast<std::decay_t<const double>>(1.0e-05), nb::arg("Tolerance2d") = static_cast<std::decay_t<const double>>(1.0e-05), nb::arg("cutting") = static_cast<std::decay_t<const bool>>(false), nb::arg("FirstC") = static_cast<std::decay_t<const AppParCurves_Constraint>>(AppParCurves_TangencyPoint), nb::arg("LastC") = static_cast<std::decay_t<const AppParCurves_Constraint>>(AppParCurves_TangencyPoint), R"nbdoc(Initializes the fields of the algorithm.)nbdoc")
        .def(nb::init<const AppCont_Function &, const int, const int, const double, const double, const bool, const AppParCurves_Constraint, const AppParCurves_Constraint>(), nb::arg("Line"), nb::arg("degreemin") = static_cast<std::decay_t<const int>>(3), nb::arg("degreemax") = static_cast<std::decay_t<const int>>(8), nb::arg("Tolerance3d") = static_cast<std::decay_t<const double>>(1.0e-5), nb::arg("Tolerance2d") = static_cast<std::decay_t<const double>>(1.0e-5), nb::arg("cutting") = static_cast<std::decay_t<const bool>>(false), nb::arg("FirstC") = static_cast<std::decay_t<const AppParCurves_Constraint>>(AppParCurves_TangencyPoint), nb::arg("LastC") = static_cast<std::decay_t<const AppParCurves_Constraint>>(AppParCurves_TangencyPoint), R"nbdoc(The MultiLine <Line> will be approximated until tolerances
will be reached.
The approximation will be done from degreemin to degreemax
with a cutting if the corresponding boolean is True.)nbdoc")
        .def("Perform", static_cast<void (Approx_FitAndDivide::*)(const AppCont_Function &)>(&Approx_FitAndDivide::Perform), nb::arg("Line"), R"nbdoc(runs the algorithm after having initialized the fields.)nbdoc")
        .def("SetDegrees", static_cast<void (Approx_FitAndDivide::*)(const int, const int)>(&Approx_FitAndDivide::SetDegrees), nb::arg("degreemin"), nb::arg("degreemax"), R"nbdoc(changes the degrees of the approximation.)nbdoc")
        .def("SetTolerances", static_cast<void (Approx_FitAndDivide::*)(const double, const double)>(&Approx_FitAndDivide::SetTolerances), nb::arg("Tolerance3d"), nb::arg("Tolerance2d"), R"nbdoc(Changes the tolerances of the approximation.)nbdoc")
        .def("SetConstraints", static_cast<void (Approx_FitAndDivide::*)(const AppParCurves_Constraint, const AppParCurves_Constraint)>(&Approx_FitAndDivide::SetConstraints), nb::arg("FirstC"), nb::arg("LastC"), R"nbdoc(Changes the constraints of the approximation.)nbdoc")
        .def("SetMaxSegments", static_cast<void (Approx_FitAndDivide::*)(const int)>(&Approx_FitAndDivide::SetMaxSegments), nb::arg("theMaxSegments"), R"nbdoc(Changes the max number of segments, which is allowed for cutting.)nbdoc")
        .def("SetInvOrder", static_cast<void (Approx_FitAndDivide::*)(const bool)>(&Approx_FitAndDivide::SetInvOrder), nb::arg("theInvOrder"), R"nbdoc(Set inverse order of degree selection:
if theInvOrdr = true, current degree is chosen by inverse order -
from maxdegree to mindegree.
By default inverse order is used.)nbdoc")
        .def("SetHangChecking", static_cast<void (Approx_FitAndDivide::*)(const bool)>(&Approx_FitAndDivide::SetHangChecking), nb::arg("theHangChecking"), R"nbdoc(Set value of hang checking flag
if this flag = true, possible hang of algorithm is checked
and algorithm is forced to stop.
By default hang checking is used.)nbdoc")
        .def("IsAllApproximated", static_cast<bool (Approx_FitAndDivide::*)() const>(&Approx_FitAndDivide::IsAllApproximated), R"nbdoc(returns False if at a moment of the approximation,
the status NoApproximation has been sent by the user
when more points were needed.)nbdoc")
        .def("IsToleranceReached", static_cast<bool (Approx_FitAndDivide::*)() const>(&Approx_FitAndDivide::IsToleranceReached), R"nbdoc(returns False if the status NoPointsAdded has been sent.)nbdoc")
        .def("Error", [](const Approx_FitAndDivide &self, const int Index) { double tol3d{}; double tol2d{}; self.Error(Index, tol3d, tol2d); return std::make_tuple(tol3d, tol2d); }, nb::arg("Index"), R"nbdoc(returns the tolerances 2d and 3d of the <Index> MultiCurve.)nbdoc")
        .def("NbMultiCurves", static_cast<int (Approx_FitAndDivide::*)() const>(&Approx_FitAndDivide::NbMultiCurves), R"nbdoc(Returns the number of MultiCurve doing the approximation
of the MultiLine.)nbdoc")
        .def("Value", static_cast<AppParCurves_MultiCurve (Approx_FitAndDivide::*)(const int) const>(&Approx_FitAndDivide::Value), nb::arg("Index") = static_cast<std::decay_t<const int>>(1), R"nbdoc(returns the approximation MultiCurve of range <Index>.)nbdoc")
        .def("Parameters", [](const Approx_FitAndDivide &self, const int Index) { double firstp{}; double lastp{}; self.Parameters(Index, firstp, lastp); return std::make_tuple(firstp, lastp); }, nb::arg("Index"));
    nanoocp_implicit_copy_ctor<Approx_FitAndDivide>(nb::borrow<nb::class_<Approx_FitAndDivide>>(m.attr("Approx_FitAndDivide")));
    nb::implicitly_convertible<std::decay_t<const AppCont_Function &>, Approx_FitAndDivide>();
    nb::implicitly_convertible<std::decay_t<const int>, Approx_FitAndDivide>();
    nb::borrow<nb::class_<Approx_FitAndDivide2d>>(m.attr("Approx_FitAndDivide2d"))
        .def(nb::init<const int, const int, const double, const double, const bool, const AppParCurves_Constraint, const AppParCurves_Constraint>(), nb::arg("degreemin") = static_cast<std::decay_t<const int>>(3), nb::arg("degreemax") = static_cast<std::decay_t<const int>>(8), nb::arg("Tolerance3d") = static_cast<std::decay_t<const double>>(1.0e-05), nb::arg("Tolerance2d") = static_cast<std::decay_t<const double>>(1.0e-05), nb::arg("cutting") = static_cast<std::decay_t<const bool>>(false), nb::arg("FirstC") = static_cast<std::decay_t<const AppParCurves_Constraint>>(AppParCurves_TangencyPoint), nb::arg("LastC") = static_cast<std::decay_t<const AppParCurves_Constraint>>(AppParCurves_TangencyPoint), R"nbdoc(Initializes the fields of the algorithm.)nbdoc")
        .def(nb::init<const AppCont_Function &, const int, const int, const double, const double, const bool, const AppParCurves_Constraint, const AppParCurves_Constraint>(), nb::arg("Line"), nb::arg("degreemin") = static_cast<std::decay_t<const int>>(3), nb::arg("degreemax") = static_cast<std::decay_t<const int>>(8), nb::arg("Tolerance3d") = static_cast<std::decay_t<const double>>(1.0e-5), nb::arg("Tolerance2d") = static_cast<std::decay_t<const double>>(1.0e-5), nb::arg("cutting") = static_cast<std::decay_t<const bool>>(false), nb::arg("FirstC") = static_cast<std::decay_t<const AppParCurves_Constraint>>(AppParCurves_TangencyPoint), nb::arg("LastC") = static_cast<std::decay_t<const AppParCurves_Constraint>>(AppParCurves_TangencyPoint), R"nbdoc(The MultiLine <Line> will be approximated until tolerances
will be reached.
The approximation will be done from degreemin to degreemax
with a cutting if the corresponding boolean is True.)nbdoc")
        .def("Perform", static_cast<void (Approx_FitAndDivide2d::*)(const AppCont_Function &)>(&Approx_FitAndDivide2d::Perform), nb::arg("Line"), R"nbdoc(runs the algorithm after having initialized the fields.)nbdoc")
        .def("SetDegrees", static_cast<void (Approx_FitAndDivide2d::*)(const int, const int)>(&Approx_FitAndDivide2d::SetDegrees), nb::arg("degreemin"), nb::arg("degreemax"), R"nbdoc(changes the degrees of the approximation.)nbdoc")
        .def("SetTolerances", static_cast<void (Approx_FitAndDivide2d::*)(const double, const double)>(&Approx_FitAndDivide2d::SetTolerances), nb::arg("Tolerance3d"), nb::arg("Tolerance2d"), R"nbdoc(Changes the tolerances of the approximation.)nbdoc")
        .def("SetConstraints", static_cast<void (Approx_FitAndDivide2d::*)(const AppParCurves_Constraint, const AppParCurves_Constraint)>(&Approx_FitAndDivide2d::SetConstraints), nb::arg("FirstC"), nb::arg("LastC"), R"nbdoc(Changes the constraints of the approximation.)nbdoc")
        .def("SetMaxSegments", static_cast<void (Approx_FitAndDivide2d::*)(const int)>(&Approx_FitAndDivide2d::SetMaxSegments), nb::arg("theMaxSegments"), R"nbdoc(Changes the max number of segments, which is allowed for cutting.)nbdoc")
        .def("SetInvOrder", static_cast<void (Approx_FitAndDivide2d::*)(const bool)>(&Approx_FitAndDivide2d::SetInvOrder), nb::arg("theInvOrder"), R"nbdoc(Set inverse order of degree selection:
if theInvOrdr = true, current degree is chosen by inverse order -
from maxdegree to mindegree.
By default inverse order is used.)nbdoc")
        .def("SetHangChecking", static_cast<void (Approx_FitAndDivide2d::*)(const bool)>(&Approx_FitAndDivide2d::SetHangChecking), nb::arg("theHangChecking"), R"nbdoc(Set value of hang checking flag
if this flag = true, possible hang of algorithm is checked
and algorithm is forced to stop.
By default hang checking is used.)nbdoc")
        .def("IsAllApproximated", static_cast<bool (Approx_FitAndDivide2d::*)() const>(&Approx_FitAndDivide2d::IsAllApproximated), R"nbdoc(returns False if at a moment of the approximation,
the status NoApproximation has been sent by the user
when more points were needed.)nbdoc")
        .def("IsToleranceReached", static_cast<bool (Approx_FitAndDivide2d::*)() const>(&Approx_FitAndDivide2d::IsToleranceReached), R"nbdoc(returns False if the status NoPointsAdded has been sent.)nbdoc")
        .def("Error", [](const Approx_FitAndDivide2d &self, const int Index) { double tol3d{}; double tol2d{}; self.Error(Index, tol3d, tol2d); return std::make_tuple(tol3d, tol2d); }, nb::arg("Index"), R"nbdoc(returns the tolerances 2d and 3d of the <Index> MultiCurve.)nbdoc")
        .def("NbMultiCurves", static_cast<int (Approx_FitAndDivide2d::*)() const>(&Approx_FitAndDivide2d::NbMultiCurves), R"nbdoc(Returns the number of MultiCurve doing the approximation
of the MultiLine.)nbdoc")
        .def("Value", static_cast<AppParCurves_MultiCurve (Approx_FitAndDivide2d::*)(const int) const>(&Approx_FitAndDivide2d::Value), nb::arg("Index") = static_cast<std::decay_t<const int>>(1), R"nbdoc(returns the approximation MultiCurve of range <Index>.)nbdoc")
        .def("Parameters", [](const Approx_FitAndDivide2d &self, const int Index) { double firstp{}; double lastp{}; self.Parameters(Index, firstp, lastp); return std::make_tuple(firstp, lastp); }, nb::arg("Index"));
    nanoocp_implicit_copy_ctor<Approx_FitAndDivide2d>(nb::borrow<nb::class_<Approx_FitAndDivide2d>>(m.attr("Approx_FitAndDivide2d")));
    nb::implicitly_convertible<std::decay_t<const AppCont_Function &>, Approx_FitAndDivide2d>();
    nb::implicitly_convertible<std::decay_t<const int>, Approx_FitAndDivide2d>();
    nb::borrow<nb::class_<Approx_MCurvesToBSpCurve>>(m.attr("Approx_MCurvesToBSpCurve"))
        .def(nb::init<>())
        .def("Reset", static_cast<void (Approx_MCurvesToBSpCurve::*)()>(&Approx_MCurvesToBSpCurve::Reset))
        .def("Append", static_cast<void (Approx_MCurvesToBSpCurve::*)(const AppParCurves_MultiCurve &)>(&Approx_MCurvesToBSpCurve::Append), nb::arg("MC"))
        .def("Perform", static_cast<void (Approx_MCurvesToBSpCurve::*)()>(&Approx_MCurvesToBSpCurve::Perform))
        .def("Perform", static_cast<void (Approx_MCurvesToBSpCurve::*)(const NCollection_Sequence<AppParCurves_MultiCurve> &)>(&Approx_MCurvesToBSpCurve::Perform), nb::arg("TheSeq"))
        .def("Value", static_cast<const AppParCurves_MultiBSpCurve & (Approx_MCurvesToBSpCurve::*)() const>(&Approx_MCurvesToBSpCurve::Value), R"nbdoc(return the composite MultiCurves as a MultiBSpCurve.)nbdoc")
        .def("ChangeValue", static_cast<const AppParCurves_MultiBSpCurve & (Approx_MCurvesToBSpCurve::*)()>(&Approx_MCurvesToBSpCurve::ChangeValue), R"nbdoc(return the composite MultiCurves as a MultiBSpCurve.)nbdoc");
    nanoocp_implicit_copy_ctor<Approx_MCurvesToBSpCurve>(nb::borrow<nb::class_<Approx_MCurvesToBSpCurve>>(m.attr("Approx_MCurvesToBSpCurve")));
    nb::borrow<nb::class_<Approx_SameParameter>>(m.attr("Approx_SameParameter"))
        .def(nb::init<const occ::handle<Geom_Curve> &, const occ::handle<Geom2d_Curve> &, const occ::handle<Geom_Surface> &, const double>(), nb::arg("C3D").none(), nb::arg("C2D").none(), nb::arg("S").none(), nb::arg("Tol"), R"nbdoc(Warning: the C3D and C2D must have the same parametric domain.)nbdoc")
        .def(nb::init<const occ::handle<Adaptor3d_Curve> &, const occ::handle<Geom2d_Curve> &, const occ::handle<Adaptor3d_Surface> &, const double>(), nb::arg("C3D").none(), nb::arg("C2D").none(), nb::arg("S").none(), nb::arg("Tol"), R"nbdoc(Warning: the C3D and C2D must have the same parametric domain.)nbdoc")
        .def(nb::init<const occ::handle<Adaptor3d_Curve> &, const occ::handle<Adaptor2d_Curve2d> &, const occ::handle<Adaptor3d_Surface> &, const double>(), nb::arg("C3D").none(), nb::arg("C2D").none(), nb::arg("S").none(), nb::arg("Tol"), R"nbdoc(Warning: the C3D and C2D must have the same parametric domain.)nbdoc")
        .def("IsDone", static_cast<bool (Approx_SameParameter::*)() const>(&Approx_SameParameter::IsDone), R"nbdoc(@Returns .false. if calculations failed,
.true. if calculations succeed)nbdoc")
        .def("TolReached", static_cast<double (Approx_SameParameter::*)() const>(&Approx_SameParameter::TolReached), R"nbdoc(@Returns tolerance (maximal distance) between 3d curve
and curve on surface, generated by 2d curve and surface.)nbdoc")
        .def("IsSameParameter", static_cast<bool (Approx_SameParameter::*)() const>(&Approx_SameParameter::IsSameParameter), R"nbdoc(Tells whether the original data had already the same
parameter up to the tolerance : in that case nothing
is done.)nbdoc")
        .def("Curve2d", static_cast<occ::handle<Geom2d_Curve> (Approx_SameParameter::*)() const>(&Approx_SameParameter::Curve2d), R"nbdoc(Returns the 2D curve that has the same parameter as
the 3D curve once evaluated on the surface up to the
specified tolerance.)nbdoc")
        .def("Curve3d", static_cast<occ::handle<Adaptor3d_Curve> (Approx_SameParameter::*)() const>(&Approx_SameParameter::Curve3d), R"nbdoc(Returns the 3D curve that has the same parameter as
the 3D curve once evaluated on the surface up to the
specified tolerance.)nbdoc")
        .def("CurveOnSurface", static_cast<occ::handle<Adaptor3d_CurveOnSurface> (Approx_SameParameter::*)() const>(&Approx_SameParameter::CurveOnSurface), R"nbdoc(Returns the 3D curve on surface that has the same parameter as
the 3D curve up to the specified tolerance.)nbdoc");
    nanoocp_implicit_copy_ctor<Approx_SameParameter>(nb::borrow<nb::class_<Approx_SameParameter>>(m.attr("Approx_SameParameter")));
    nb::borrow<nb::class_<Approx_SweepApproximation>>(m.attr("Approx_SweepApproximation"))
        .def(nb::init<const occ::handle<Approx_SweepFunction> &>(), nb::arg("Func").none())
        .def("Perform", static_cast<void (Approx_SweepApproximation::*)(const double, const double, const double, const double, const double, const double, const GeomAbs_Shape, const int, const int)>(&Approx_SweepApproximation::Perform), nb::arg("First"), nb::arg("Last"), nb::arg("Tol3d"), nb::arg("BoundTol"), nb::arg("Tol2d"), nb::arg("TolAngular"), nb::arg("Continuity") = static_cast<std::decay_t<const GeomAbs_Shape>>(GeomAbs_C0), nb::arg("Degmax") = static_cast<std::decay_t<const int>>(11), nb::arg("Segmax") = static_cast<std::decay_t<const int>>(50), R"nbdoc(Perform the Approximation
[First, Last] : Approx_SweepApproximation.cdl
Tol3d : Tolerance to surface approximation
Tol2d : Tolerance used to perform curve approximation
Normally the 2d curve are approximated with a
tolerance given by the resolution on support surfaces,
but if this tolerance is too large Tol2d is used.
TolAngular : Tolerance (in radian) to control the angle
between tangents on the section law and
tangent of iso-v on approximated surface
Continuity : The continuity in v waiting on the surface
Degmax     : The maximum degree in v required on the surface
Segmax     : The maximum number of span in v required on
the surface
Warning : The continuity ci can be obtained only if Ft is Ci)nbdoc")
        .def("Eval", [](Approx_SweepApproximation &self, const double Parameter, const int DerivativeRequest, const double First, const double Last) { double Result{}; auto nanoocp_result = self.Eval(Parameter, DerivativeRequest, First, Last, Result); return std::make_tuple(nanoocp_result, Result); }, nb::arg("Parameter"), nb::arg("DerivativeRequest"), nb::arg("First"), nb::arg("Last"), R"nbdoc(The EvaluatorFunction from AdvApprox;)nbdoc")
        .def("IsDone", static_cast<bool (Approx_SweepApproximation::*)() const>(&Approx_SweepApproximation::IsDone), R"nbdoc(returns if we have an result)nbdoc")
        .def("SurfShape", [](const Approx_SweepApproximation &self) { int UDegree{}; int VDegree{}; int NbUPoles{}; int NbVPoles{}; int NbUKnots{}; int NbVKnots{}; self.SurfShape(UDegree, VDegree, NbUPoles, NbVPoles, NbUKnots, NbVKnots); return std::make_tuple(UDegree, VDegree, NbUPoles, NbVPoles, NbUKnots, NbVKnots); })
        .def("Surface", static_cast<void (Approx_SweepApproximation::*)(NCollection_Array2<gp_Pnt> &, NCollection_Array2<double> &, NCollection_Array1<double> &, NCollection_Array1<double> &, NCollection_Array1<int> &, NCollection_Array1<int> &) const>(&Approx_SweepApproximation::Surface), nb::arg("TPoles"), nb::arg("TWeights"), nb::arg("TUKnots"), nb::arg("TVKnots"), nb::arg("TUMults"), nb::arg("TVMults"))
        .def("UDegree", static_cast<int (Approx_SweepApproximation::*)() const>(&Approx_SweepApproximation::UDegree))
        .def("VDegree", static_cast<int (Approx_SweepApproximation::*)() const>(&Approx_SweepApproximation::VDegree))
        .def("SurfPoles", static_cast<const NCollection_Array2<gp_Pnt> & (Approx_SweepApproximation::*)() const>(&Approx_SweepApproximation::SurfPoles))
        .def("SurfWeights", static_cast<const NCollection_Array2<double> & (Approx_SweepApproximation::*)() const>(&Approx_SweepApproximation::SurfWeights))
        .def("SurfUKnots", static_cast<const NCollection_Array1<double> & (Approx_SweepApproximation::*)() const>(&Approx_SweepApproximation::SurfUKnots))
        .def("SurfVKnots", static_cast<const NCollection_Array1<double> & (Approx_SweepApproximation::*)() const>(&Approx_SweepApproximation::SurfVKnots))
        .def("SurfUMults", static_cast<const NCollection_Array1<int> & (Approx_SweepApproximation::*)() const>(&Approx_SweepApproximation::SurfUMults))
        .def("SurfVMults", static_cast<const NCollection_Array1<int> & (Approx_SweepApproximation::*)() const>(&Approx_SweepApproximation::SurfVMults))
        .def("MaxErrorOnSurf", static_cast<double (Approx_SweepApproximation::*)() const>(&Approx_SweepApproximation::MaxErrorOnSurf), R"nbdoc(returns the maximum error in the surface approximation.)nbdoc")
        .def("AverageErrorOnSurf", static_cast<double (Approx_SweepApproximation::*)() const>(&Approx_SweepApproximation::AverageErrorOnSurf), R"nbdoc(returns the average error in the surface approximation.)nbdoc")
        .def("NbCurves2d", static_cast<int (Approx_SweepApproximation::*)() const>(&Approx_SweepApproximation::NbCurves2d))
        .def("Curves2dShape", [](const Approx_SweepApproximation &self) { int Degree{}; int NbPoles{}; int NbKnots{}; self.Curves2dShape(Degree, NbPoles, NbKnots); return std::make_tuple(Degree, NbPoles, NbKnots); })
        .def("Curve2d", static_cast<void (Approx_SweepApproximation::*)(const int, NCollection_Array1<gp_Pnt2d> &, NCollection_Array1<double> &, NCollection_Array1<int> &) const>(&Approx_SweepApproximation::Curve2d), nb::arg("Index"), nb::arg("TPoles"), nb::arg("TKnots"), nb::arg("TMults"))
        .def("Curves2dDegree", static_cast<int (Approx_SweepApproximation::*)() const>(&Approx_SweepApproximation::Curves2dDegree))
        .def("Curve2dPoles", static_cast<const NCollection_Array1<gp_Pnt2d> & (Approx_SweepApproximation::*)(const int) const>(&Approx_SweepApproximation::Curve2dPoles), nb::arg("Index"))
        .def("Curves2dKnots", static_cast<const NCollection_Array1<double> & (Approx_SweepApproximation::*)() const>(&Approx_SweepApproximation::Curves2dKnots))
        .def("Curves2dMults", static_cast<const NCollection_Array1<int> & (Approx_SweepApproximation::*)() const>(&Approx_SweepApproximation::Curves2dMults))
        .def("Max2dError", static_cast<double (Approx_SweepApproximation::*)(const int) const>(&Approx_SweepApproximation::Max2dError), nb::arg("Index"), R"nbdoc(returns the maximum error of the <Index>
2d curve approximation.)nbdoc")
        .def("Average2dError", static_cast<double (Approx_SweepApproximation::*)(const int) const>(&Approx_SweepApproximation::Average2dError), nb::arg("Index"), R"nbdoc(returns the average error of the <Index>
2d curve approximation.)nbdoc")
        .def("TolCurveOnSurf", static_cast<double (Approx_SweepApproximation::*)(const int) const>(&Approx_SweepApproximation::TolCurveOnSurf), nb::arg("Index"), R"nbdoc(returns the maximum 3d error of the <Index>
2d curve approximation on the Surface.)nbdoc")
        .def("Dump", [](const Approx_SweepApproximation &self) { std::ostringstream o_stream; self.Dump(o_stream); return nanoocp_stream_text(o_stream); }, R"nbdoc(display information on approximation.)nbdoc");
    nanoocp_implicit_copy_ctor<Approx_SweepApproximation>(nb::borrow<nb::class_<Approx_SweepApproximation>>(m.attr("Approx_SweepApproximation")));
    nb::implicitly_convertible<std::decay_t<const occ::handle<Approx_SweepFunction> &>, Approx_SweepApproximation>();
    nb::borrow<nb::class_<Approx_SweepFunction>>(m.attr("Approx_SweepFunction"))
        .def("D0", static_cast<bool (Approx_SweepFunction::*)(const double, const double, const double, NCollection_Array1<gp_Pnt> &, NCollection_Array1<gp_Pnt2d> &, NCollection_Array1<double> &)>(&Approx_SweepFunction::D0), nb::arg("Param"), nb::arg("First"), nb::arg("Last"), nb::arg("Poles"), nb::arg("Poles2d"), nb::arg("Weigths"), R"nbdoc(compute the section for v = param)nbdoc")
        .def("D1", static_cast<bool (Approx_SweepFunction::*)(const double, const double, const double, NCollection_Array1<gp_Pnt> &, NCollection_Array1<gp_Vec> &, NCollection_Array1<gp_Pnt2d> &, NCollection_Array1<gp_Vec2d> &, NCollection_Array1<double> &, NCollection_Array1<double> &)>(&Approx_SweepFunction::D1), nb::arg("Param"), nb::arg("First"), nb::arg("Last"), nb::arg("Poles"), nb::arg("DPoles"), nb::arg("Poles2d"), nb::arg("DPoles2d"), nb::arg("Weigths"), nb::arg("DWeigths"), R"nbdoc(compute the first derivative in v direction of the
section for v = param
Warning : It used only for C1 or C2 approximation)nbdoc")
        .def("D2", static_cast<bool (Approx_SweepFunction::*)(const double, const double, const double, NCollection_Array1<gp_Pnt> &, NCollection_Array1<gp_Vec> &, NCollection_Array1<gp_Vec> &, NCollection_Array1<gp_Pnt2d> &, NCollection_Array1<gp_Vec2d> &, NCollection_Array1<gp_Vec2d> &, NCollection_Array1<double> &, NCollection_Array1<double> &, NCollection_Array1<double> &)>(&Approx_SweepFunction::D2), nb::arg("Param"), nb::arg("First"), nb::arg("Last"), nb::arg("Poles"), nb::arg("DPoles"), nb::arg("D2Poles"), nb::arg("Poles2d"), nb::arg("DPoles2d"), nb::arg("D2Poles2d"), nb::arg("Weigths"), nb::arg("DWeigths"), nb::arg("D2Weigths"), R"nbdoc(compute the second derivative in v direction of the
section for v = param
Warning : It used only for C2 approximation)nbdoc")
        .def("Nb2dCurves", static_cast<int (Approx_SweepFunction::*)() const>(&Approx_SweepFunction::Nb2dCurves), R"nbdoc(get the number of 2d curves to approximate.)nbdoc")
        .def("SectionShape", [](const Approx_SweepFunction &self) { int NbPoles{}; int NbKnots{}; int Degree{}; self.SectionShape(NbPoles, NbKnots, Degree); return std::make_tuple(NbPoles, NbKnots, Degree); }, R"nbdoc(get the format of an section)nbdoc")
        .def("Knots", static_cast<void (Approx_SweepFunction::*)(NCollection_Array1<double> &) const>(&Approx_SweepFunction::Knots), nb::arg("TKnots"), R"nbdoc(get the Knots of the section)nbdoc")
        .def("Mults", static_cast<void (Approx_SweepFunction::*)(NCollection_Array1<int> &) const>(&Approx_SweepFunction::Mults), nb::arg("TMults"), R"nbdoc(get the Multplicities of the section)nbdoc")
        .def("IsRational", static_cast<bool (Approx_SweepFunction::*)() const>(&Approx_SweepFunction::IsRational), R"nbdoc(Returns if the sections are rational or not)nbdoc")
        .def("NbIntervals", static_cast<int (Approx_SweepFunction::*)(const GeomAbs_Shape) const>(&Approx_SweepFunction::NbIntervals), nb::arg("S"), R"nbdoc(Returns the number of intervals for continuity
<S>.
May be one if Continuity(me) >= <S>)nbdoc")
        .def("Intervals", static_cast<void (Approx_SweepFunction::*)(NCollection_Array1<double> &, const GeomAbs_Shape) const>(&Approx_SweepFunction::Intervals), nb::arg("T"), nb::arg("S"), R"nbdoc(Stores in <T> the parameters bounding the intervals
of continuity <S>.

The array must provide enough room to accommodate
for the parameters. i.e. T.Length() > NbIntervals())nbdoc")
        .def("SetInterval", static_cast<void (Approx_SweepFunction::*)(const double, const double)>(&Approx_SweepFunction::SetInterval), nb::arg("First"), nb::arg("Last"), R"nbdoc(Sets the bounds of the parametric interval on
the function
This determines the derivatives in these values if the
function is not Cn.)nbdoc")
        .def("Resolution", [](const Approx_SweepFunction &self, const int Index, const double Tol) { double TolU{}; double TolV{}; self.Resolution(Index, Tol, TolU, TolV); return std::make_tuple(TolU, TolV); }, nb::arg("Index"), nb::arg("Tol"), R"nbdoc(Returns the resolutions in the sub-space 2d <Index>
This information is useful to find a good tolerance in
2d approximation.)nbdoc")
        .def("GetTolerance", static_cast<void (Approx_SweepFunction::*)(const double, const double, const double, NCollection_Array1<double> &) const>(&Approx_SweepFunction::GetTolerance), nb::arg("BoundTol"), nb::arg("SurfTol"), nb::arg("AngleTol"), nb::arg("Tol3d"), R"nbdoc(Returns the tolerance to reach in approximation
to satisfy.
BoundTol error at the Boundary
AngleTol tangent error at the Boundary (in radian)
SurfTol error inside the surface.)nbdoc")
        .def("SetTolerance", static_cast<void (Approx_SweepFunction::*)(const double, const double)>(&Approx_SweepFunction::SetTolerance), nb::arg("Tol3d"), nb::arg("Tol2d"), R"nbdoc(Is useful, if (me) have to run numerical algorithm to perform D0, D1 or D2)nbdoc")
        .def("BarycentreOfSurf", static_cast<gp_Pnt (Approx_SweepFunction::*)() const>(&Approx_SweepFunction::BarycentreOfSurf), R"nbdoc(Get the barycentre of Surface.
An very poor estimation is sufficient.
This information is useful to perform well conditioned rational approximation.
Warning: Used only if <me> IsRational)nbdoc")
        .def("MaximalSection", static_cast<double (Approx_SweepFunction::*)() const>(&Approx_SweepFunction::MaximalSection), R"nbdoc(Returns the length of the greater section.
This information is useful to G1's control.
Warning: With an little value, approximation can be slower.)nbdoc")
        .def("GetMinimalWeight", static_cast<void (Approx_SweepFunction::*)(NCollection_Array1<double> &) const>(&Approx_SweepFunction::GetMinimalWeight), nb::arg("Weigths"), R"nbdoc(Compute the minimal value of weight for each poles in all sections.
This information is useful to control error in rational approximation.
Warning: Used only if <me> IsRational)nbdoc")
        .def_static("get_type_name", static_cast<const char * (*)()>(&Approx_SweepFunction::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&Approx_SweepFunction::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (Approx_SweepFunction::*)() const>(&Approx_SweepFunction::DynamicType));
}

void nanoocp_conversions_Approx(nb::module_ &m) {
}
