// Generated by the nanoOCP generator from OCCT package Geom2dAPI (toolkit TKGeomAlgo). Do not edit.
#include "nanoocp_common.h"
#include <Geom2dAPI_ExtremaCurveCurve.hxx>
#include <Geom2dAPI_InterCurveCurve.hxx>
#include <Geom2dAPI_Interpolate.hxx>
#include <Geom2dAPI_PointsToBSpline.hxx>
#include <Geom2dAPI_ProjectPointOnCurve.hxx>
#include <Adaptor2d_Curve2d.hxx>
#include <Approx_ParametrizationType.hxx>
#include <Extrema_Curve2dTool.hxx>
#include <Extrema_ExtCC2d.hxx>
#include <Extrema_ExtPC2d.hxx>
#include <Extrema_ExtPElC2d.hxx>
#include <Extrema_GFuncExtPC.hxx>
#include <Extrema_GGExtPC.hxx>
#include <Extrema_GGenExtPC.hxx>
#include <Extrema_POnCurv2d.hxx>
#include <Geom2dInt_GInter.hxx>
#include <Geom2d_BSplineCurve.hxx>
#include <Geom2d_Curve.hxx>
#include <GeomAbs_Shape.hxx>
#include <NCollection_Array1.hxx>
#include <NCollection_HArray1.hxx>
#include <NCollection_Sequence.hxx>
#include <gp_Pnt2d.hxx>
#include <gp_Vec2d.hxx>

void nanoocp_declare_Geom2dAPI(nb::module_ &m) {
    { nb::class_<Geom2dAPI_ExtremaCurveCurve> cls(m, "Geom2dAPI_ExtremaCurveCurve", R"nbdoc(Describes functions for computing all the extrema
between two 2D curves.
An ExtremaCurveCurve algorithm minimizes or
maximizes the distance between a point on the first
curve and a point on the second curve. Thus, it
computes the start point and end point of
perpendiculars common to the two curves (an
intersection point is not an extremum except where
the two curves are tangential at this point).
Solutions consist of pairs of points, and an extremum
is considered to be a segment joining the two points of a solution.
An ExtremaCurveCurve object provides a framework for:
-   defining the construction of the extrema,
-   implementing the construction algorithm, and
-   consulting the results.
Warning
In some cases, the nearest points between two
curves do not correspond to one of the computed
extrema. Instead, they may be given by:
-   a limit point of one curve and one of the following:
-   its orthogonal projection on the other curve,
-   a limit point of the other curve; or
-   an intersection point between the two curves.)nbdoc");
    }
    { nb::class_<Geom2dAPI_InterCurveCurve> cls(m, "Geom2dAPI_InterCurveCurve", R"nbdoc(This class implements methods for computing
-       the intersections between two 2D curves,
-       the self-intersections of a 2D curve.
Using the InterCurveCurve algorithm allows to get the following results:
-      intersection points in the case of cross intersections,
-      intersection segments in the case of tangential intersections,
-       nothing in the case of no intersections.)nbdoc");
    }
    { nb::class_<Geom2dAPI_Interpolate> cls(m, "Geom2dAPI_Interpolate", R"nbdoc(This class is used to interpolate a BsplineCurve
passing through an array of points, with a C2
Continuity if tangency is not requested at the point.
If tangency is requested at the point the continuity will
be C1. If Perodicity is requested the curve will be closed
and the junction will be the first point given. The curve will than be only C1
The curve is defined by a table of points through which it passes, and if required
by a parallel table of reals which gives the value of the parameter of each point through
which the resulting BSpline curve passes, and by vectors tangential to these points.
An Interpolate object provides a framework for: defining the constraints of the BSpline curve,
-   implementing the interpolation algorithm, and consulting the results.)nbdoc");
    }
    { nb::class_<Geom2dAPI_PointsToBSpline> cls(m, "Geom2dAPI_PointsToBSpline", R"nbdoc(This class is used to approximate a BsplineCurve
passing through an array of points, with a given
Continuity.
Describes functions for building a 2D BSpline
curve which approximates a set of points.
A PointsToBSpline object provides a framework for:
-   defining the data of the BSpline curve to be built,
-   implementing the approximation algorithm, and
-   consulting the results)nbdoc");
    }
    { nb::class_<Geom2dAPI_ProjectPointOnCurve> cls(m, "Geom2dAPI_ProjectPointOnCurve", R"nbdoc(This class implements methods for computing all the orthogonal
projections of a 2D point onto a 2D curve.)nbdoc");
    }
}

void nanoocp_templates_Geom2dAPI(nb::module_ &m) {
}

void nanoocp_define_Geom2dAPI(nb::module_ &m) {
    nb::borrow<nb::class_<Geom2dAPI_ExtremaCurveCurve>>(m.attr("Geom2dAPI_ExtremaCurveCurve"))
        .def(nb::init<const occ::handle<Geom2d_Curve> &, const occ::handle<Geom2d_Curve> &, const double, const double, const double, const double>(), nb::arg("C1").none(), nb::arg("C2").none(), nb::arg("U1min"), nb::arg("U1max"), nb::arg("U2min"), nb::arg("U2max"), R"nbdoc(Computes the extrema between
-   the portion of the curve C1 limited by the two
points of parameter (U1min,U1max), and
-   the portion of the curve C2 limited by the two
points of parameter (U2min,U2max).
Warning
Use the function NbExtrema to obtain the number
of solutions. If this algorithm fails, NbExtrema returns 0.)nbdoc")
        .def("NbExtrema", static_cast<int (Geom2dAPI_ExtremaCurveCurve::*)() const>(&Geom2dAPI_ExtremaCurveCurve::NbExtrema), R"nbdoc(Returns the number of extrema computed by this algorithm.
Note: if this algorithm fails, NbExtrema returns 0.)nbdoc")
        .def("Points", static_cast<void (Geom2dAPI_ExtremaCurveCurve::*)(const int, gp_Pnt2d &, gp_Pnt2d &) const>(&Geom2dAPI_ExtremaCurveCurve::Points), nb::arg("Index"), nb::arg("P1"), nb::arg("P2"), R"nbdoc(Returns the points P1 on the first curve and P2 on
the second curve, which are the ends of the
extremum of index Index computed by this algorithm.
Exceptions
Standard_OutOfRange if Index is not in the range [
1,NbExtrema ], where NbExtrema is the
number of extrema computed by this algorithm.)nbdoc")
        .def("Parameters", [](const Geom2dAPI_ExtremaCurveCurve &self, const int Index) { double U1{}; double U2{}; self.Parameters(Index, U1, U2); return std::make_tuple(U1, U2); }, nb::arg("Index"), R"nbdoc(Returns the parameters U1 of the point on the first
curve and U2 of the point on the second curve, which
are the ends of the extremum of index Index
computed by this algorithm.
Exceptions
Standard_OutOfRange if Index is not in the range [
1,NbExtrema ], where NbExtrema is the
number of extrema computed by this algorithm.)nbdoc")
        .def("Distance", static_cast<double (Geom2dAPI_ExtremaCurveCurve::*)(const int) const>(&Geom2dAPI_ExtremaCurveCurve::Distance), nb::arg("Index"), R"nbdoc(Computes the distance between the end points of the
extremum of index Index computed by this algorithm.
Exceptions
Standard_OutOfRange if Index is not in the range [
1,NbExtrema ], where NbExtrema is the
number of extrema computed by this algorithm.)nbdoc")
        .def("NearestPoints", static_cast<void (Geom2dAPI_ExtremaCurveCurve::*)(gp_Pnt2d &, gp_Pnt2d &) const>(&Geom2dAPI_ExtremaCurveCurve::NearestPoints), nb::arg("P1"), nb::arg("P2"), R"nbdoc(Returns the points P1 on the first curve and P2 on
the second curve, which are the ends of the shortest
extremum computed by this algorithm.
Exceptions StdFail_NotDone if this algorithm fails.)nbdoc")
        .def("LowerDistanceParameters", [](const Geom2dAPI_ExtremaCurveCurve &self) { double U1{}; double U2{}; self.LowerDistanceParameters(U1, U2); return std::make_tuple(U1, U2); }, R"nbdoc(Returns the parameters U1 of the point on the first
curve and U2 of the point on the second curve, which
are the ends of the shortest extremum computed by this algorithm.
Exceptions
StdFail_NotDone if this algorithm fails.)nbdoc")
        .def("LowerDistance", static_cast<double (Geom2dAPI_ExtremaCurveCurve::*)() const>(&Geom2dAPI_ExtremaCurveCurve::LowerDistance), R"nbdoc(Computes the distance between the end points of the
shortest extremum computed by this algorithm.
Exceptions - StdFail_NotDone if this algorithm fails.)nbdoc")
        .def("Extrema", static_cast<const Extrema_ExtCC2d & (Geom2dAPI_ExtremaCurveCurve::*)() const>(&Geom2dAPI_ExtremaCurveCurve::Extrema))
        .def("__int__", [](const Geom2dAPI_ExtremaCurveCurve &self) { return static_cast<int>(self); })
        .def("__float__", [](const Geom2dAPI_ExtremaCurveCurve &self) { return static_cast<double>(self); });
    nanoocp_implicit_copy_ctor<Geom2dAPI_ExtremaCurveCurve>(nb::borrow<nb::class_<Geom2dAPI_ExtremaCurveCurve>>(m.attr("Geom2dAPI_ExtremaCurveCurve")));
    nb::borrow<nb::class_<Geom2dAPI_InterCurveCurve>>(m.attr("Geom2dAPI_InterCurveCurve"))
        .def(nb::init<>(), R"nbdoc(Create an empty intersector. Use the
function Init for further initialization of the intersection
algorithm by curves or curve.)nbdoc")
        .def(nb::init<const occ::handle<Geom2d_Curve> &, const double>(), nb::arg("C1").none(), nb::arg("Tol") = static_cast<std::decay_t<const double>>(1.0e-6), R"nbdoc(Creates an object and computes self-intersections of the curve C1.
Tolerance value Tol, defaulted to 1.0e-6, defines the precision of
computing the intersection points.
In case of a tangential intersection, Tol also defines the
size of intersection segments (limited portions of the curves)
where the distance between all points from two curves (or a curve
in case of self-intersection) is less than Tol.
Warning
Use functions NbPoints and NbSegments to obtain the number of
solutions. If the algorithm finds no intersections NbPoints and
NbSegments return 0.)nbdoc")
        .def(nb::init<const occ::handle<Geom2d_Curve> &, const occ::handle<Geom2d_Curve> &, const double>(), nb::arg("C1").none(), nb::arg("C2").none(), nb::arg("Tol") = static_cast<std::decay_t<const double>>(1.0e-6), R"nbdoc(Creates an object and computes the
intersections between the curves C1 and C2.)nbdoc")
        .def("Init", static_cast<void (Geom2dAPI_InterCurveCurve::*)(const occ::handle<Geom2d_Curve> &, const occ::handle<Geom2d_Curve> &, const double)>(&Geom2dAPI_InterCurveCurve::Init), nb::arg("C1").none(), nb::arg("C2").none(), nb::arg("Tol") = static_cast<std::decay_t<const double>>(1.0e-6), R"nbdoc(Initializes an algorithm with the
given arguments and computes the intersections between the curves C1. and C2.)nbdoc")
        .def("Init", static_cast<void (Geom2dAPI_InterCurveCurve::*)(const occ::handle<Geom2d_Curve> &, const double)>(&Geom2dAPI_InterCurveCurve::Init), nb::arg("C1").none(), nb::arg("Tol") = static_cast<std::decay_t<const double>>(1.0e-6), R"nbdoc(Initializes an algorithm with the
given arguments and computes the self-intersections of the curve C1.
Tolerance value Tol, defaulted to 1.0e-6, defines the precision of
computing the intersection points. In case of a tangential
intersection, Tol also defines the size of intersection segments
(limited portions of the curves) where the distance between all
points from two curves (or a curve in case of self-intersection) is less than Tol.
Warning
Use functions NbPoints and NbSegments to obtain the number
of solutions. If the algorithm finds no intersections NbPoints
and NbSegments return 0.)nbdoc")
        .def("NbPoints", static_cast<int (Geom2dAPI_InterCurveCurve::*)() const>(&Geom2dAPI_InterCurveCurve::NbPoints), R"nbdoc(Returns the number of intersection-points in case of cross intersections.
NbPoints returns 0 if no intersections were found.)nbdoc")
        .def("Point", static_cast<gp_Pnt2d (Geom2dAPI_InterCurveCurve::*)(const int) const>(&Geom2dAPI_InterCurveCurve::Point), nb::arg("Index"), R"nbdoc(Returns the intersection point of index Index.
Intersection points are computed in case of cross intersections with a
precision equal to the tolerance value assigned at the time of
construction or in the function Init (this value is defaulted to 1.0e-6).
Exceptions
Standard_OutOfRange if index is not in the range [ 1,NbPoints ], where
NbPoints is the number of computed intersection points)nbdoc")
        .def("NbSegments", static_cast<int (Geom2dAPI_InterCurveCurve::*)() const>(&Geom2dAPI_InterCurveCurve::NbSegments), R"nbdoc(Returns the number of tangential intersections.
NbSegments returns 0 if no intersections were found)nbdoc")
        .def("Segment", [](const Geom2dAPI_InterCurveCurve &self, const int Index) { occ::handle<Geom2d_Curve> Curve1{}; occ::handle<Geom2d_Curve> Curve2{}; self.Segment(Index, Curve1, Curve2); return std::make_tuple(Curve1, Curve2); }, nb::arg("Index"), R"nbdoc(Use this syntax only to get
solutions of tangential intersection between two curves.
Output values Curve1 and Curve2 are the intersection segments on the
first curve and on the second curve accordingly. Parameter Index
defines a number of computed solution.
An intersection segment is a portion of an initial curve limited
by two points. The distance from each point of this segment to the
other curve is less or equal to the tolerance value assigned at the
time of construction or in function Init (this value is defaulted to 1.0e-6).
Exceptions
Standard_OutOfRange if Index is not in the range [ 1,NbSegments ],
where NbSegments is the number of computed tangential intersections.
Standard_NullObject if the algorithm is initialized for the
computing of self-intersections on a curve.)nbdoc")
        .def("Intersector", static_cast<const Geom2dInt_GInter & (Geom2dAPI_InterCurveCurve::*)() const>(&Geom2dAPI_InterCurveCurve::Intersector), R"nbdoc(return the algorithmic object from Intersection.)nbdoc");
    nanoocp_implicit_copy_ctor<Geom2dAPI_InterCurveCurve>(nb::borrow<nb::class_<Geom2dAPI_InterCurveCurve>>(m.attr("Geom2dAPI_InterCurveCurve")));
    nb::implicitly_convertible<std::decay_t<const occ::handle<Geom2d_Curve> &>, Geom2dAPI_InterCurveCurve>();
    nb::borrow<nb::class_<Geom2dAPI_Interpolate>>(m.attr("Geom2dAPI_Interpolate"))
        .def(nb::init<const occ::handle<NCollection_HArray1<gp_Pnt2d>> &, const bool, const double>(), nb::arg("Points").none(), nb::arg("PeriodicFlag"), nb::arg("Tolerance"), R"nbdoc(Tolerance is to check if the points are not too close to one an other
It is also used to check if the tangent vector is not too small.
There should be at least 2 points
if PeriodicFlag is True then the curve will be periodic.)nbdoc")
        .def(nb::init<const occ::handle<NCollection_HArray1<gp_Pnt2d>> &, const occ::handle<NCollection_HArray1<double>> &, const bool, const double>(), nb::arg("Points").none(), nb::arg("Parameters").none(), nb::arg("PeriodicFlag"), nb::arg("Tolerance"), R"nbdoc(if PeriodicFlag is True then the curve will be periodic
Warning:
There should be as many parameters as there are points
except if PeriodicFlag is True : then there should be one more
parameter to close the curve)nbdoc")
        .def("Load", static_cast<void (Geom2dAPI_Interpolate::*)(const gp_Vec2d &, const gp_Vec2d &, const bool)>(&Geom2dAPI_Interpolate::Load), nb::arg("InitialTangent"), nb::arg("FinalTangent"), nb::arg("Scale") = static_cast<std::decay_t<const bool>>(true), R"nbdoc(Assigns this constrained BSpline curve to be
tangential to vectors InitialTangent and FinalTangent
at its first and last points respectively (i.e.
the first and last points of the table of
points through which the curve passes, as
defined at the time of initialization).
<Scale> - boolean flag defining whether tangent vectors are to
be scaled according to derivatives of lagrange interpolation.)nbdoc")
        .def("Load", static_cast<void (Geom2dAPI_Interpolate::*)(const NCollection_Array1<gp_Vec2d> &, const occ::handle<NCollection_HArray1<bool>> &, const bool)>(&Geom2dAPI_Interpolate::Load), nb::arg("Tangents"), nb::arg("TangentFlags").none(), nb::arg("Scale") = static_cast<std::decay_t<const bool>>(true), R"nbdoc(Assigns this constrained BSpline curve to be
tangential to vectors defined in the table Tangents,
which is parallel to the table of points
through which the curve passes, as
defined at the time of initialization. Vectors
in the table Tangents are defined only if
the flag given in the parallel table
TangentFlags is true: only these vectors
are set as tangency constraints.
<Scale> - boolean flag defining whether tangent vectors are to
be scaled according to derivatives of lagrange interpolation.)nbdoc")
        .def("Perform", static_cast<void (Geom2dAPI_Interpolate::*)()>(&Geom2dAPI_Interpolate::Perform), R"nbdoc(Computes the constrained BSpline curve. Use the function IsDone to verify that the
computation is successful, and then the function Curve to obtain the result.)nbdoc")
        .def("Curve", static_cast<const occ::handle<Geom2d_BSplineCurve> & (Geom2dAPI_Interpolate::*)() const>(&Geom2dAPI_Interpolate::Curve), R"nbdoc(Returns the computed BSpline curve. Raises StdFail_NotDone if the interpolation fails.)nbdoc")
        .def("IsDone", static_cast<bool (Geom2dAPI_Interpolate::*)() const>(&Geom2dAPI_Interpolate::IsDone), R"nbdoc(Returns true if the constrained BSpline curve is successfully constructed.
Note: in this case, the result is given by the function Curve.)nbdoc");
    nanoocp_implicit_copy_ctor<Geom2dAPI_Interpolate>(nb::borrow<nb::class_<Geom2dAPI_Interpolate>>(m.attr("Geom2dAPI_Interpolate")));
    nb::borrow<nb::class_<Geom2dAPI_PointsToBSpline>>(m.attr("Geom2dAPI_PointsToBSpline"))
        .def(nb::init<>(), R"nbdoc(Constructs an empty approximation algorithm.
Use an Init function to define and build the BSpline curve.)nbdoc")
        .def(nb::init<const NCollection_Array1<gp_Pnt2d> &, const int, const int, const GeomAbs_Shape, const double>(), nb::arg("Points"), nb::arg("DegMin") = static_cast<std::decay_t<const int>>(3), nb::arg("DegMax") = static_cast<std::decay_t<const int>>(8), nb::arg("Continuity") = static_cast<std::decay_t<const GeomAbs_Shape>>(GeomAbs_C2), nb::arg("Tol2D") = static_cast<std::decay_t<const double>>(1.0e-6), R"nbdoc(Approximate a BSpline Curve passing through an
array of Point. The resulting BSpline will have
the following properties:
1- his degree will be in the range [Degmin,Degmax]
2- his continuity will be at least <Continuity>
3- the distance from the point <Points> to the
BSpline will be lower to Tol2D)nbdoc")
        .def(nb::init<const NCollection_Array1<gp_Pnt2d> &, const Approx_ParametrizationType, const int, const int, const GeomAbs_Shape, const double>(), nb::arg("Points"), nb::arg("ParType"), nb::arg("DegMin") = static_cast<std::decay_t<const int>>(3), nb::arg("DegMax") = static_cast<std::decay_t<const int>>(8), nb::arg("Continuity") = static_cast<std::decay_t<const GeomAbs_Shape>>(GeomAbs_C2), nb::arg("Tol2D") = static_cast<std::decay_t<const double>>(1.0e-3), R"nbdoc(Approximate a BSpline Curve passing through an
array of Point. The resulting BSpline will have
the following properties:
1- his degree will be in the range [Degmin,Degmax]
2- his continuity will be at least <Continuity>
3- the distance from the point <Points> to the
BSpline will be lower to Tol2D)nbdoc")
        .def(nb::init<const NCollection_Array1<gp_Pnt2d> &, const NCollection_Array1<double> &, const int, const int, const GeomAbs_Shape, const double>(), nb::arg("Points"), nb::arg("Parameters"), nb::arg("DegMin") = static_cast<std::decay_t<const int>>(3), nb::arg("DegMax") = static_cast<std::decay_t<const int>>(8), nb::arg("Continuity") = static_cast<std::decay_t<const GeomAbs_Shape>>(GeomAbs_C2), nb::arg("Tol2D") = static_cast<std::decay_t<const double>>(1.0e-3), R"nbdoc(Approximate a BSpline Curve passing through an
array of Point, which parameters are given by the
array <Parameters>.
The resulting BSpline will have the following
properties:
1- his degree will be in the range [Degmin,Degmax]
2- his continuity will be at least <Continuity>
3- the distance from the point <Points> to the
BSpline will be lower to Tol2D)nbdoc")
        .def(nb::init<const NCollection_Array1<double> &, const double, const double, const int, const int, const GeomAbs_Shape, const double>(), nb::arg("YValues"), nb::arg("X0"), nb::arg("DX"), nb::arg("DegMin") = static_cast<std::decay_t<const int>>(3), nb::arg("DegMax") = static_cast<std::decay_t<const int>>(8), nb::arg("Continuity") = static_cast<std::decay_t<const GeomAbs_Shape>>(GeomAbs_C2), nb::arg("Tol2D") = static_cast<std::decay_t<const double>>(1.0e-6), R"nbdoc(Approximate a BSpline Curve passing through an
array of Point. Of coordinates :

X = X0 + DX * (i-YValues.Lower())
Y = YValues(i)

With i in the range YValues.Lower(), YValues.Upper()

The BSpline will be parametrized from t = X0 to
X0 + DX * (YValues.Upper() - YValues.Lower())

And will satisfy X(t) = t

The resulting BSpline will have
the following properties:
1- his degree will be in the range [Degmin,Degmax]
2- his continuity will be at least <Continuity>
3- the distance from the point <Points> to the
BSpline will be lower to Tol2D)nbdoc")
        .def(nb::init<const NCollection_Array1<gp_Pnt2d> &, const double, const double, const double, const int, const GeomAbs_Shape, const double>(), nb::arg("Points"), nb::arg("Weight1"), nb::arg("Weight2"), nb::arg("Weight3"), nb::arg("DegMax") = static_cast<std::decay_t<const int>>(8), nb::arg("Continuity") = static_cast<std::decay_t<const GeomAbs_Shape>>(GeomAbs_C2), nb::arg("Tol3D") = static_cast<std::decay_t<const double>>(1.0e-3), R"nbdoc(Approximate a BSpline Curve passing through an
array of Point using variational smoothing algorithm,
which tries to minimize additional criterium:
Weight1*CurveLength + Weight2*Curvature + Weight3*Torsion)nbdoc")
        .def("Init", static_cast<void (Geom2dAPI_PointsToBSpline::*)(const NCollection_Array1<gp_Pnt2d> &, const int, const int, const GeomAbs_Shape, const double)>(&Geom2dAPI_PointsToBSpline::Init), nb::arg("Points"), nb::arg("DegMin") = static_cast<std::decay_t<const int>>(3), nb::arg("DegMax") = static_cast<std::decay_t<const int>>(8), nb::arg("Continuity") = static_cast<std::decay_t<const GeomAbs_Shape>>(GeomAbs_C2), nb::arg("Tol2D") = static_cast<std::decay_t<const double>>(1.0e-6), R"nbdoc(Approximate a BSpline Curve passing through an
array of Point. The resulting BSpline will have
the following properties:
1- his degree will be in the range [Degmin,Degmax]
2- his continuity will be at least <Continuity>
3- the distance from the point <Points> to the
BSpline will be lower to Tol2D)nbdoc")
        .def("Init", static_cast<void (Geom2dAPI_PointsToBSpline::*)(const NCollection_Array1<double> &, const double, const double, const int, const int, const GeomAbs_Shape, const double)>(&Geom2dAPI_PointsToBSpline::Init), nb::arg("YValues"), nb::arg("X0"), nb::arg("DX"), nb::arg("DegMin") = static_cast<std::decay_t<const int>>(3), nb::arg("DegMax") = static_cast<std::decay_t<const int>>(8), nb::arg("Continuity") = static_cast<std::decay_t<const GeomAbs_Shape>>(GeomAbs_C2), nb::arg("Tol2D") = static_cast<std::decay_t<const double>>(1.0e-6), R"nbdoc(Approximate a BSpline Curve passing through an
array of Point. Of coordinates :

X = X0 + DX * (i-YValues.Lower())
Y = YValues(i)

With i in the range YValues.Lower(), YValues.Upper()

The BSpline will be parametrized from t = X0 to
X0 + DX * (YValues.Upper() - YValues.Lower())

And will satisfy X(t) = t

The resulting BSpline will have
the following properties:
1- his degree will be in the range [Degmin,Degmax]
2- his continuity will be at least <Continuity>
3- the distance from the point <Points> to the
BSpline will be lower to Tol2D)nbdoc")
        .def("Init", static_cast<void (Geom2dAPI_PointsToBSpline::*)(const NCollection_Array1<gp_Pnt2d> &, const Approx_ParametrizationType, const int, const int, const GeomAbs_Shape, const double)>(&Geom2dAPI_PointsToBSpline::Init), nb::arg("Points"), nb::arg("ParType"), nb::arg("DegMin") = static_cast<std::decay_t<const int>>(3), nb::arg("DegMax") = static_cast<std::decay_t<const int>>(8), nb::arg("Continuity") = static_cast<std::decay_t<const GeomAbs_Shape>>(GeomAbs_C2), nb::arg("Tol2D") = static_cast<std::decay_t<const double>>(1.0e-3), R"nbdoc(Approximate a BSpline Curve passing through an
array of Point. The resulting BSpline will have
the following properties:
1- his degree will be in the range [Degmin,Degmax]
2- his continuity will be at least <Continuity>
3- the distance from the point <Points> to the
BSpline will be lower to Tol2D)nbdoc")
        .def("Init", static_cast<void (Geom2dAPI_PointsToBSpline::*)(const NCollection_Array1<gp_Pnt2d> &, const NCollection_Array1<double> &, const int, const int, const GeomAbs_Shape, const double)>(&Geom2dAPI_PointsToBSpline::Init), nb::arg("Points"), nb::arg("Parameters"), nb::arg("DegMin") = static_cast<std::decay_t<const int>>(3), nb::arg("DegMax") = static_cast<std::decay_t<const int>>(8), nb::arg("Continuity") = static_cast<std::decay_t<const GeomAbs_Shape>>(GeomAbs_C2), nb::arg("Tol2D") = static_cast<std::decay_t<const double>>(1.0e-3), R"nbdoc(Approximate a BSpline Curve passing through an
array of Point, which parameters are given by the
array <Parameters>.
The resulting BSpline will have the following
properties:
1- his degree will be in the range [Degmin,Degmax]
2- his continuity will be at least <Continuity>
3- the distance from the point <Points> to the
BSpline will be lower to Tol2D)nbdoc")
        .def("Init", static_cast<void (Geom2dAPI_PointsToBSpline::*)(const NCollection_Array1<gp_Pnt2d> &, const double, const double, const double, const int, const GeomAbs_Shape, const double)>(&Geom2dAPI_PointsToBSpline::Init), nb::arg("Points"), nb::arg("Weight1"), nb::arg("Weight2"), nb::arg("Weight3"), nb::arg("DegMax") = static_cast<std::decay_t<const int>>(8), nb::arg("Continuity") = static_cast<std::decay_t<const GeomAbs_Shape>>(GeomAbs_C2), nb::arg("Tol2D") = static_cast<std::decay_t<const double>>(1.0e-3), R"nbdoc(Approximate a BSpline Curve passing through an
array of Point using variational smoothing algorithm,
which tries to minimize additional criterium:
Weight1*CurveLength + Weight2*Curvature + Weight3*Torsion)nbdoc")
        .def("Curve", static_cast<const occ::handle<Geom2d_BSplineCurve> & (Geom2dAPI_PointsToBSpline::*)() const>(&Geom2dAPI_PointsToBSpline::Curve), R"nbdoc(Returns the approximate BSpline Curve)nbdoc")
        .def("IsDone", static_cast<bool (Geom2dAPI_PointsToBSpline::*)() const>(&Geom2dAPI_PointsToBSpline::IsDone));
    nanoocp_implicit_copy_ctor<Geom2dAPI_PointsToBSpline>(nb::borrow<nb::class_<Geom2dAPI_PointsToBSpline>>(m.attr("Geom2dAPI_PointsToBSpline")));
    nb::implicitly_convertible<std::decay_t<const NCollection_Array1<gp_Pnt2d> &>, Geom2dAPI_PointsToBSpline>();
    nb::borrow<nb::class_<Geom2dAPI_ProjectPointOnCurve>>(m.attr("Geom2dAPI_ProjectPointOnCurve"))
        .def(nb::init<>(), R"nbdoc(Constructs an empty projector algorithm. Use an Init
function to define the point and the curve on which it is going to work.)nbdoc")
        .def(nb::init<const gp_Pnt2d &, const occ::handle<Geom2d_Curve> &>(), nb::arg("P"), nb::arg("Curve").none(), R"nbdoc(Create the projection of a point <P> on a curve
<Curve>)nbdoc")
        .def(nb::init<const gp_Pnt2d &, const occ::handle<Geom2d_Curve> &, const double, const double>(), nb::arg("P"), nb::arg("Curve").none(), nb::arg("Umin"), nb::arg("Usup"), R"nbdoc(Create the projection of a point <P> on a curve
<Curve> limited by the two points of parameter Umin and Usup.
Warning
Use the function NbPoints to obtain the number of solutions. If
projection fails, NbPoints returns 0.)nbdoc")
        .def("Init", static_cast<void (Geom2dAPI_ProjectPointOnCurve::*)(const gp_Pnt2d &, const occ::handle<Geom2d_Curve> &)>(&Geom2dAPI_ProjectPointOnCurve::Init), nb::arg("P"), nb::arg("Curve").none(), R"nbdoc(Initializes this algorithm with the given arguments, and
computes the orthogonal projections of a point <P> on a curve <Curve>)nbdoc")
        .def("Init", static_cast<void (Geom2dAPI_ProjectPointOnCurve::*)(const gp_Pnt2d &, const occ::handle<Geom2d_Curve> &, const double, const double)>(&Geom2dAPI_ProjectPointOnCurve::Init), nb::arg("P"), nb::arg("Curve").none(), nb::arg("Umin"), nb::arg("Usup"), R"nbdoc(Initializes this algorithm with the given arguments, and
computes the orthogonal projections of the point P onto the portion
of the curve Curve limited by the two points of parameter Umin and Usup.)nbdoc")
        .def("NbPoints", static_cast<int (Geom2dAPI_ProjectPointOnCurve::*)() const>(&Geom2dAPI_ProjectPointOnCurve::NbPoints), R"nbdoc(return the number of of computed
orthogonal projectionn points.)nbdoc")
        .def("Point", static_cast<gp_Pnt2d (Geom2dAPI_ProjectPointOnCurve::*)(const int) const>(&Geom2dAPI_ProjectPointOnCurve::Point), nb::arg("Index"), R"nbdoc(Returns the orthogonal projection
on the curve. Index is a number of a computed point.
Exceptions
Standard_OutOfRange if Index is not in the range [ 1,NbPoints ], where
NbPoints is the number of solution points.)nbdoc")
        .def("Parameter", static_cast<double (Geom2dAPI_ProjectPointOnCurve::*)(const int) const>(&Geom2dAPI_ProjectPointOnCurve::Parameter), nb::arg("Index"), R"nbdoc(Returns the parameter on the curve
of a point which is the orthogonal projection. Index is a number of a
computed projected point.
Exceptions
Standard_OutOfRange if Index is not in the range [ 1,NbPoints ], where
NbPoints is the number of solution points.)nbdoc")
        .def("Parameter__float", [](const Geom2dAPI_ProjectPointOnCurve &self, const int Index) { double U{}; self.Parameter(Index, U); return U; }, nb::arg("Index"), R"nbdoc(Parameter__float: the C++ overload Parameter(const int, double &); the suffix lists its returned out-parameters (nanoOCP R-COLLISION).
Returns the parameter on the curve
of a point which is the orthogonal projection. Index is a number of a
computed projected point.
Exceptions
Standard_OutOfRange if Index is not in the range [ 1,NbPoints ], where
NbPoints is the number of solution points)nbdoc")
        .def("Distance", static_cast<double (Geom2dAPI_ProjectPointOnCurve::*)(const int) const>(&Geom2dAPI_ProjectPointOnCurve::Distance), nb::arg("Index"), R"nbdoc(Computes the distance between the
point and its computed orthogonal projection on the curve. Index is a
number of computed projected point.
Exceptions
Standard_OutOfRange if Index is not in the range [ 1,NbPoints ], where
NbPoints is the number of solution points.)nbdoc")
        .def("NearestPoint", static_cast<gp_Pnt2d (Geom2dAPI_ProjectPointOnCurve::*)() const>(&Geom2dAPI_ProjectPointOnCurve::NearestPoint), R"nbdoc(Returns the nearest orthogonal projection of the point on the curve.
Exceptions
StdFail_NotDone if this algorithm fails.)nbdoc")
        .def("LowerDistanceParameter", static_cast<double (Geom2dAPI_ProjectPointOnCurve::*)() const>(&Geom2dAPI_ProjectPointOnCurve::LowerDistanceParameter), R"nbdoc(Returns the parameter on the curve
of the nearest orthogonal projection of the point.
Exceptions
StdFail_NotDone if this algorithm fails.)nbdoc")
        .def("LowerDistance", static_cast<double (Geom2dAPI_ProjectPointOnCurve::*)() const>(&Geom2dAPI_ProjectPointOnCurve::LowerDistance), R"nbdoc(Computes the distance between the
point and its nearest orthogonal projection on the curve.
Exceptions
StdFail_NotDone if this algorithm fails.)nbdoc")
        .def("Extrema", static_cast<const Extrema_ExtPC2d & (Geom2dAPI_ProjectPointOnCurve::*)() const>(&Geom2dAPI_ProjectPointOnCurve::Extrema), R"nbdoc(return the algorithmic object from Extrema)nbdoc")
        .def("__int__", [](const Geom2dAPI_ProjectPointOnCurve &self) { return static_cast<int>(self); })
        .def("__float__", [](const Geom2dAPI_ProjectPointOnCurve &self) { return static_cast<double>(self); });
    nanoocp_implicit_copy_ctor<Geom2dAPI_ProjectPointOnCurve>(nb::borrow<nb::class_<Geom2dAPI_ProjectPointOnCurve>>(m.attr("Geom2dAPI_ProjectPointOnCurve")));
}

void nanoocp_conversions_Geom2dAPI(nb::module_ &m) {
    nanoocp_conversion_handle<Geom2dAPI_Interpolate, Geom2d_BSplineCurve>(nb::module_::import_("nanoocp._TKG2d.Geom2d").attr("Geom2d_BSplineCurve"), true);
    nanoocp_conversion_handle<Geom2dAPI_PointsToBSpline, Geom2d_BSplineCurve>(nb::module_::import_("nanoocp._TKG2d.Geom2d").attr("Geom2d_BSplineCurve"), true);
    nanoocp_conversion<Geom2dAPI_ProjectPointOnCurve, gp_Pnt2d>(nb::module_::import_("nanoocp._TKMath.gp").attr("gp_Pnt2d"), true);
}
