// Generated by the nanoOCP generator from OCCT package Geom2dHatch (toolkit TKGeomAlgo). Do not edit.
#include "nanoocp_common.h"
#include <Geom2dHatch_Classifier.hxx>
#include <Geom2dHatch_Element.hxx>
#include <Geom2dHatch_Elements.hxx>
#include <Geom2dHatch_FClass2dOfClassifier.hxx>
#include <Geom2dHatch_Hatcher.hxx>
#include <Geom2dHatch_Hatching.hxx>
#include <Geom2dHatch_Intersector.hxx>
#include <Geom2dAdaptor_Curve.hxx>
#include <Geom2dInt_GInter.hxx>
#include <Geom2d_Curve.hxx>
#include <HatchGen_Domain.hxx>
#include <HatchGen_ErrorStatus.hxx>
#include <HatchGen_PointOnHatching.hxx>
#include <IntRes2d_Position.hxx>
#include <TopAbs_Orientation.hxx>
#include <TopAbs_State.hxx>
#include <gp_Dir2d.hxx>
#include <gp_Lin2d.hxx>
#include <gp_Pnt2d.hxx>

void nanoocp_declare_Geom2dHatch(nb::module_ &m) {
    { nb::class_<Geom2dHatch_Intersector, Geom2dInt_GInter> cls(m, "Geom2dHatch_Intersector");
    }
    { nb::class_<Geom2dHatch_FClass2dOfClassifier> cls(m, "Geom2dHatch_FClass2dOfClassifier");
    }
    { nb::class_<Geom2dHatch_Classifier> cls(m, "Geom2dHatch_Classifier");
    }
    { nb::class_<Geom2dHatch_Element> cls(m, "Geom2dHatch_Element");
    }
    { nb::class_<Geom2dHatch_Elements> cls(m, "Geom2dHatch_Elements");
    }
    { nb::class_<Geom2dHatch_Hatching> cls(m, "Geom2dHatch_Hatching");
    }
    { nb::class_<Geom2dHatch_Hatcher> cls(m, "Geom2dHatch_Hatcher");
    }
}

void nanoocp_templates_Geom2dHatch(nb::module_ &m) {
}

void nanoocp_define_Geom2dHatch(nb::module_ &m) {
    nb::borrow<nb::class_<Geom2dHatch_Intersector>>(m.attr("Geom2dHatch_Intersector"))
        .def(nb::init<>())
        .def(nb::init<const double, const double>(), nb::arg("Confusion"), nb::arg("Tangency"), R"nbdoc(Creates an intersector.)nbdoc")
        .def("ConfusionTolerance", static_cast<double (Geom2dHatch_Intersector::*)() const>(&Geom2dHatch_Intersector::ConfusionTolerance), R"nbdoc(Returns the confusion tolerance of the
intersector.)nbdoc")
        .def("SetConfusionTolerance", static_cast<void (Geom2dHatch_Intersector::*)(const double)>(&Geom2dHatch_Intersector::SetConfusionTolerance), nb::arg("Confusion"), R"nbdoc(Sets the confusion tolerance of the intersector.)nbdoc")
        .def("TangencyTolerance", static_cast<double (Geom2dHatch_Intersector::*)() const>(&Geom2dHatch_Intersector::TangencyTolerance), R"nbdoc(Returns the tangency tolerance of the
intersector.)nbdoc")
        .def("SetTangencyTolerance", static_cast<void (Geom2dHatch_Intersector::*)(const double)>(&Geom2dHatch_Intersector::SetTangencyTolerance), nb::arg("Tangency"), R"nbdoc(Sets the tangency tolerance of the intersector.)nbdoc")
        .def("Intersect", static_cast<void (Geom2dHatch_Intersector::*)(const Geom2dAdaptor_Curve &, const Geom2dAdaptor_Curve &)>(&Geom2dHatch_Intersector::Intersect), nb::arg("C1"), nb::arg("C2"), R"nbdoc(Intersects the curves C1 and C2.
The results are retrieved by the usual methods
described in IntRes2d_Intersection.
Creates an intersector.)nbdoc")
        .def("Perform", static_cast<void (Geom2dHatch_Intersector::*)(const gp_Lin2d &, const double, const double, const Geom2dAdaptor_Curve &)>(&Geom2dHatch_Intersector::Perform), nb::arg("L"), nb::arg("P"), nb::arg("Tol"), nb::arg("E"), R"nbdoc(Performs the intersection between the 2d line
segment (<L>, <P>) and the Curve <E>. The line
segment is the part of the 2d line <L> of
parameter range [0, <P>] (P is positive and can be
RealLast()). Tol is the Tolerance on the segment.
The order is relevant, the first argument is the
segment, the second the Edge.)nbdoc")
        .def("LocalGeometry", [](const Geom2dHatch_Intersector &self, const Geom2dAdaptor_Curve & E, const double U, gp_Dir2d & T, gp_Dir2d & N) { double C{}; self.LocalGeometry(E, U, T, N, C); return C; }, nb::arg("E"), nb::arg("U"), nb::arg("T"), nb::arg("N"), R"nbdoc(Returns in <T>, <N> and <C> the tangent, normal
and curvature of the edge <E> at parameter value
<U>.)nbdoc");
    nanoocp_implicit_copy_ctor<Geom2dHatch_Intersector>(nb::borrow<nb::class_<Geom2dHatch_Intersector>>(m.attr("Geom2dHatch_Intersector")));
    nb::borrow<nb::class_<Geom2dHatch_FClass2dOfClassifier>>(m.attr("Geom2dHatch_FClass2dOfClassifier"))
        .def(nb::init<>(), R"nbdoc(Creates an undefined classifier.)nbdoc")
        .def("Reset", static_cast<void (Geom2dHatch_FClass2dOfClassifier::*)(const gp_Lin2d &, const double, const double)>(&Geom2dHatch_FClass2dOfClassifier::Reset), nb::arg("L"), nb::arg("P"), nb::arg("Tol"), R"nbdoc(Starts a classification process. The point to
classify is the origin of the line <L>. <P> is
the original length of the segment on <L> used to
compute intersections. <Tol> is the tolerance
attached to the line segment in intersections.)nbdoc")
        .def("Compare", static_cast<void (Geom2dHatch_FClass2dOfClassifier::*)(const Geom2dAdaptor_Curve &, const TopAbs_Orientation)>(&Geom2dHatch_FClass2dOfClassifier::Compare), nb::arg("E"), nb::arg("Or"), R"nbdoc(Updates the classification process with the edge
<E> from the boundary.)nbdoc")
        .def("Parameter", static_cast<double (Geom2dHatch_FClass2dOfClassifier::*)() const>(&Geom2dHatch_FClass2dOfClassifier::Parameter), R"nbdoc(Returns the current value of the parameter.)nbdoc")
        .def("Intersector", static_cast<Geom2dHatch_Intersector & (Geom2dHatch_FClass2dOfClassifier::*)()>(&Geom2dHatch_FClass2dOfClassifier::Intersector), nb::rv_policy::reference_internal, R"nbdoc(Returns the intersecting algorithm.)nbdoc")
        .def("ClosestIntersection", static_cast<int (Geom2dHatch_FClass2dOfClassifier::*)() const>(&Geom2dHatch_FClass2dOfClassifier::ClosestIntersection), R"nbdoc(Returns 0 if the last compared edge had no
relevant intersection. Else returns the index of
this intersection in the last intersection
algorithm.)nbdoc")
        .def("State", static_cast<TopAbs_State (Geom2dHatch_FClass2dOfClassifier::*)() const>(&Geom2dHatch_FClass2dOfClassifier::State), R"nbdoc(Returns the current state of the point.)nbdoc")
        .def("IsHeadOrEnd", static_cast<bool (Geom2dHatch_FClass2dOfClassifier::*)() const>(&Geom2dHatch_FClass2dOfClassifier::IsHeadOrEnd), R"nbdoc(Returns the true if the closest intersection point
represents head or end of the edge. Returns false
otherwise.)nbdoc");
    nanoocp_implicit_copy_ctor<Geom2dHatch_FClass2dOfClassifier>(nb::borrow<nb::class_<Geom2dHatch_FClass2dOfClassifier>>(m.attr("Geom2dHatch_FClass2dOfClassifier")));
    nb::borrow<nb::class_<Geom2dHatch_Classifier>>(m.attr("Geom2dHatch_Classifier"))
        .def(nb::init<>(), R"nbdoc(Empty constructor, undefined algorithm.)nbdoc")
        .def(nb::init<Geom2dHatch_Elements &, const gp_Pnt2d &, const double>(), nb::arg("F"), nb::arg("P"), nb::arg("Tol"), R"nbdoc(Creates an algorithm to classify the Point P with
Tolerance <T> on the face described by <F>.)nbdoc")
        .def("Perform", static_cast<void (Geom2dHatch_Classifier::*)(Geom2dHatch_Elements &, const gp_Pnt2d &, const double)>(&Geom2dHatch_Classifier::Perform), nb::arg("F"), nb::arg("P"), nb::arg("Tol"), R"nbdoc(Classify the Point P with Tolerance <T> on the
face described by <F>.)nbdoc")
        .def("State", static_cast<TopAbs_State (Geom2dHatch_Classifier::*)() const>(&Geom2dHatch_Classifier::State), R"nbdoc(Returns the result of the classification.)nbdoc")
        .def("Rejected", static_cast<bool (Geom2dHatch_Classifier::*)() const>(&Geom2dHatch_Classifier::Rejected), R"nbdoc(Returns True when the state was computed by a
rejection. The state is OUT.)nbdoc")
        .def("NoWires", static_cast<bool (Geom2dHatch_Classifier::*)() const>(&Geom2dHatch_Classifier::NoWires), R"nbdoc(Returns True if the face contains no wire.
The state is IN.)nbdoc")
        .def("Edge", [](const Geom2dHatch_Classifier &self) { opencascade::handle<Geom2dAdaptor_Curve> result(&(self.Edge())); return result; }, R"nbdoc(Returns the Edge used to determine the
classification. When the State is ON this is the
Edge containing the point.)nbdoc")
        .def("EdgeParameter", static_cast<double (Geom2dHatch_Classifier::*)() const>(&Geom2dHatch_Classifier::EdgeParameter), R"nbdoc(Returns the parameter on Edge() used to determine the
classification.)nbdoc")
        .def("Position", static_cast<IntRes2d_Position (Geom2dHatch_Classifier::*)() const>(&Geom2dHatch_Classifier::Position), R"nbdoc(Returns the position of the point on the edge
returned by Edge.)nbdoc");
    nanoocp_implicit_copy_ctor<Geom2dHatch_Classifier>(nb::borrow<nb::class_<Geom2dHatch_Classifier>>(m.attr("Geom2dHatch_Classifier")));
    nb::borrow<nb::class_<Geom2dHatch_Element>>(m.attr("Geom2dHatch_Element"))
        .def(nb::init<>())
        .def(nb::init<const Geom2dAdaptor_Curve &, const TopAbs_Orientation>(), nb::arg("Curve"), nb::arg("Orientation") = static_cast<std::decay_t<const TopAbs_Orientation>>(TopAbs_FORWARD), R"nbdoc(Creates an element.)nbdoc")
        .def("Curve", [](const Geom2dHatch_Element &self) { opencascade::handle<Geom2dAdaptor_Curve> result(&(self.Curve())); return result; }, R"nbdoc(Returns the curve associated to the element.)nbdoc")
        .def("ChangeCurve", [](Geom2dHatch_Element &self) { opencascade::handle<Geom2dAdaptor_Curve> result(&(self.ChangeCurve())); return result; }, R"nbdoc(Returns the curve associated to the element.)nbdoc")
        .def("Orientation", static_cast<void (Geom2dHatch_Element::*)(const TopAbs_Orientation)>(&Geom2dHatch_Element::Orientation), nb::arg("Orientation"), R"nbdoc(Sets the orientation of the element.)nbdoc")
        .def("Orientation", static_cast<TopAbs_Orientation (Geom2dHatch_Element::*)() const>(&Geom2dHatch_Element::Orientation), R"nbdoc(Returns the orientation of the element.)nbdoc");
    nanoocp_implicit_copy_ctor<Geom2dHatch_Element>(nb::borrow<nb::class_<Geom2dHatch_Element>>(m.attr("Geom2dHatch_Element")));
    nb::implicitly_convertible<std::decay_t<const Geom2dAdaptor_Curve &>, Geom2dHatch_Element>();
    nb::borrow<nb::class_<Geom2dHatch_Elements>>(m.attr("Geom2dHatch_Elements"))
        .def(nb::init<>())
        .def(nb::init<const Geom2dHatch_Elements &>(), nb::arg("Other"))
        .def("Clear", static_cast<void (Geom2dHatch_Elements::*)()>(&Geom2dHatch_Elements::Clear))
        .def("Bind", static_cast<bool (Geom2dHatch_Elements::*)(const int, const Geom2dHatch_Element &)>(&Geom2dHatch_Elements::Bind), nb::arg("K"), nb::arg("I"))
        .def("IsBound", static_cast<bool (Geom2dHatch_Elements::*)(const int) const>(&Geom2dHatch_Elements::IsBound), nb::arg("K"))
        .def("UnBind", static_cast<bool (Geom2dHatch_Elements::*)(const int)>(&Geom2dHatch_Elements::UnBind), nb::arg("K"))
        .def("Find", static_cast<const Geom2dHatch_Element & (Geom2dHatch_Elements::*)(const int) const>(&Geom2dHatch_Elements::Find), nb::arg("K"))
        .def("ChangeFind", static_cast<Geom2dHatch_Element & (Geom2dHatch_Elements::*)(const int)>(&Geom2dHatch_Elements::ChangeFind), nb::rv_policy::reference_internal, nb::arg("K"))
        .def("__call__", static_cast<Geom2dHatch_Element & (Geom2dHatch_Elements::*)(const int)>(&Geom2dHatch_Elements::operator()), nb::rv_policy::reference_internal, nb::arg("K"), nb::is_operator())
        .def("CheckPoint", static_cast<bool (Geom2dHatch_Elements::*)(gp_Pnt2d &)>(&Geom2dHatch_Elements::CheckPoint), nb::arg("P"))
        .def("Reject", static_cast<bool (Geom2dHatch_Elements::*)(const gp_Pnt2d &) const>(&Geom2dHatch_Elements::Reject), nb::arg("P"))
        .def("Segment", [](Geom2dHatch_Elements &self, const gp_Pnt2d & P, gp_Lin2d & L) { double Par{}; auto result = self.Segment(P, L, Par); return std::make_tuple(result, Par); }, nb::arg("P"), nb::arg("L"))
        .def("OtherSegment", [](Geom2dHatch_Elements &self, const gp_Pnt2d & P, gp_Lin2d & L) { double Par{}; auto result = self.OtherSegment(P, L, Par); return std::make_tuple(result, Par); }, nb::arg("P"), nb::arg("L"))
        .def("InitWires", static_cast<void (Geom2dHatch_Elements::*)()>(&Geom2dHatch_Elements::InitWires))
        .def("MoreWires", static_cast<bool (Geom2dHatch_Elements::*)() const>(&Geom2dHatch_Elements::MoreWires))
        .def("NextWire", static_cast<void (Geom2dHatch_Elements::*)()>(&Geom2dHatch_Elements::NextWire))
        .def("RejectWire", static_cast<bool (Geom2dHatch_Elements::*)(const gp_Lin2d &, const double) const>(&Geom2dHatch_Elements::RejectWire), nb::arg("L"), nb::arg("Par"))
        .def("InitEdges", static_cast<void (Geom2dHatch_Elements::*)()>(&Geom2dHatch_Elements::InitEdges))
        .def("MoreEdges", static_cast<bool (Geom2dHatch_Elements::*)() const>(&Geom2dHatch_Elements::MoreEdges))
        .def("NextEdge", static_cast<void (Geom2dHatch_Elements::*)()>(&Geom2dHatch_Elements::NextEdge))
        .def("RejectEdge", static_cast<bool (Geom2dHatch_Elements::*)(const gp_Lin2d &, const double) const>(&Geom2dHatch_Elements::RejectEdge), nb::arg("L"), nb::arg("Par"))
        .def("CurrentEdge", [](const Geom2dHatch_Elements &self, Geom2dAdaptor_Curve & E) { TopAbs_Orientation Or{}; self.CurrentEdge(E, Or); return Or; }, nb::arg("E"));
    nb::borrow<nb::class_<Geom2dHatch_Hatching>>(m.attr("Geom2dHatch_Hatching"))
        .def(nb::init<>())
        .def(nb::init<const Geom2dAdaptor_Curve &>(), nb::arg("Curve"), R"nbdoc(Creates a hatching.)nbdoc")
        .def("Curve", [](const Geom2dHatch_Hatching &self) { opencascade::handle<Geom2dAdaptor_Curve> result(&(self.Curve())); return result; }, R"nbdoc(Returns the curve associated to the hatching.)nbdoc")
        .def("ChangeCurve", [](Geom2dHatch_Hatching &self) { opencascade::handle<Geom2dAdaptor_Curve> result(&(self.ChangeCurve())); return result; }, R"nbdoc(Returns the curve associated to the hatching.)nbdoc")
        .def("TrimDone", static_cast<void (Geom2dHatch_Hatching::*)(const bool)>(&Geom2dHatch_Hatching::TrimDone), nb::arg("Flag"), R"nbdoc(Sets the flag about the trimming computations to the
given value.)nbdoc")
        .def("TrimDone", static_cast<bool (Geom2dHatch_Hatching::*)() const>(&Geom2dHatch_Hatching::TrimDone), R"nbdoc(Returns the flag about the trimming computations.)nbdoc")
        .def("TrimFailed", static_cast<void (Geom2dHatch_Hatching::*)(const bool)>(&Geom2dHatch_Hatching::TrimFailed), nb::arg("Flag"), R"nbdoc(Sets the flag about the trimming failure to the
given value.)nbdoc")
        .def("TrimFailed", static_cast<bool (Geom2dHatch_Hatching::*)() const>(&Geom2dHatch_Hatching::TrimFailed), R"nbdoc(Returns the flag about the trimming failure.)nbdoc")
        .def("IsDone", static_cast<void (Geom2dHatch_Hatching::*)(const bool)>(&Geom2dHatch_Hatching::IsDone), nb::arg("Flag"), R"nbdoc(Sets the flag about the domains computation to the
given value.)nbdoc")
        .def("IsDone", static_cast<bool (Geom2dHatch_Hatching::*)() const>(&Geom2dHatch_Hatching::IsDone), R"nbdoc(Returns the flag about the domains computation.)nbdoc")
        .def("Status", static_cast<void (Geom2dHatch_Hatching::*)(const HatchGen_ErrorStatus)>(&Geom2dHatch_Hatching::Status), nb::arg("theStatus"), R"nbdoc(Sets the error status.)nbdoc")
        .def("Status", static_cast<HatchGen_ErrorStatus (Geom2dHatch_Hatching::*)() const>(&Geom2dHatch_Hatching::Status), R"nbdoc(Returns the error status.)nbdoc")
        .def("AddPoint", static_cast<void (Geom2dHatch_Hatching::*)(const HatchGen_PointOnHatching &, const double)>(&Geom2dHatch_Hatching::AddPoint), nb::arg("Point"), nb::arg("Confusion"), R"nbdoc(Adds an intersection point to the hatching.)nbdoc")
        .def("NbPoints", static_cast<int (Geom2dHatch_Hatching::*)() const>(&Geom2dHatch_Hatching::NbPoints), R"nbdoc(Returns the number of intersection points
of the hatching.)nbdoc")
        .def("Point", static_cast<const HatchGen_PointOnHatching & (Geom2dHatch_Hatching::*)(const int) const>(&Geom2dHatch_Hatching::Point), nb::arg("Index"), R"nbdoc(Returns the Index-th intersection point of the
hatching.
The exception OutOfRange is raised if
Index < 1 or Index > NbPoints.)nbdoc")
        .def("ChangePoint", static_cast<HatchGen_PointOnHatching & (Geom2dHatch_Hatching::*)(const int)>(&Geom2dHatch_Hatching::ChangePoint), nb::rv_policy::reference_internal, nb::arg("Index"), R"nbdoc(Returns the Index-th intersection point of the
hatching.
The exception OutOfRange is raised if
Index < 1 or Index > NbPoints.)nbdoc")
        .def("RemPoint", static_cast<void (Geom2dHatch_Hatching::*)(const int)>(&Geom2dHatch_Hatching::RemPoint), nb::arg("Index"), R"nbdoc(Removes the Index-th intersection point of the
hatching.
The exception OutOfRange is raised if
Index < 1 or Index > NbPoints.)nbdoc")
        .def("ClrPoints", static_cast<void (Geom2dHatch_Hatching::*)()>(&Geom2dHatch_Hatching::ClrPoints), R"nbdoc(Removes all the intersection points of the hatching.)nbdoc")
        .def("AddDomain", static_cast<void (Geom2dHatch_Hatching::*)(const HatchGen_Domain &)>(&Geom2dHatch_Hatching::AddDomain), nb::arg("Domain"), R"nbdoc(Adds a domain to the hatching.)nbdoc")
        .def("NbDomains", static_cast<int (Geom2dHatch_Hatching::*)() const>(&Geom2dHatch_Hatching::NbDomains), R"nbdoc(Returns the number of domains of the hatching.)nbdoc")
        .def("Domain", static_cast<const HatchGen_Domain & (Geom2dHatch_Hatching::*)(const int) const>(&Geom2dHatch_Hatching::Domain), nb::arg("Index"), R"nbdoc(Returns the Index-th domain of the hatching.
The exception OutOfRange is raised if
Index < 1 or Index > NbDomains.)nbdoc")
        .def("RemDomain", static_cast<void (Geom2dHatch_Hatching::*)(const int)>(&Geom2dHatch_Hatching::RemDomain), nb::arg("Index"), R"nbdoc(Removes the Index-th domain of the hatching.
The exception OutOfRange is raised if
Index < 1 or Index > NbDomains.)nbdoc")
        .def("ClrDomains", static_cast<void (Geom2dHatch_Hatching::*)()>(&Geom2dHatch_Hatching::ClrDomains), R"nbdoc(Removes all the domains of the hatching.)nbdoc")
        .def("ClassificationPoint", static_cast<gp_Pnt2d (Geom2dHatch_Hatching::*)() const>(&Geom2dHatch_Hatching::ClassificationPoint), R"nbdoc(Returns a point on the curve.
This point will be used for the classification.)nbdoc");
    nanoocp_implicit_copy_ctor<Geom2dHatch_Hatching>(nb::borrow<nb::class_<Geom2dHatch_Hatching>>(m.attr("Geom2dHatch_Hatching")));
    nb::implicitly_convertible<std::decay_t<const Geom2dAdaptor_Curve &>, Geom2dHatch_Hatching>();
    nb::borrow<nb::class_<Geom2dHatch_Hatcher>>(m.attr("Geom2dHatch_Hatcher"))
        .def(nb::init<const Geom2dHatch_Intersector &, const double, const double, const bool, const bool>(), nb::arg("Intersector"), nb::arg("Confusion2d"), nb::arg("Confusion3d"), nb::arg("KeepPnt") = static_cast<std::decay_t<const bool>>(false), nb::arg("KeepSeg") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Returns an empty hatcher.)nbdoc")
        .def("Intersector", static_cast<void (Geom2dHatch_Hatcher::*)(const Geom2dHatch_Intersector &)>(&Geom2dHatch_Hatcher::Intersector), nb::arg("Intersector"), R"nbdoc(Sets the associated intersector.)nbdoc")
        .def("Intersector", static_cast<const Geom2dHatch_Intersector & (Geom2dHatch_Hatcher::*)()>(&Geom2dHatch_Hatcher::Intersector), R"nbdoc(Returns the associated intersector.)nbdoc")
        .def("ChangeIntersector", static_cast<Geom2dHatch_Intersector & (Geom2dHatch_Hatcher::*)()>(&Geom2dHatch_Hatcher::ChangeIntersector), nb::rv_policy::reference_internal, R"nbdoc(Returns the associated intersector.)nbdoc")
        .def("Confusion2d", static_cast<void (Geom2dHatch_Hatcher::*)(const double)>(&Geom2dHatch_Hatcher::Confusion2d), nb::arg("Confusion"), R"nbdoc(Sets the confusion tolerance.)nbdoc")
        .def("Confusion2d", static_cast<double (Geom2dHatch_Hatcher::*)() const>(&Geom2dHatch_Hatcher::Confusion2d), R"nbdoc(Returns the 2d confusion tolerance, i.e. the value under
which two points are considered identical in the
parametric space of the hatching.)nbdoc")
        .def("Confusion3d", static_cast<void (Geom2dHatch_Hatcher::*)(const double)>(&Geom2dHatch_Hatcher::Confusion3d), nb::arg("Confusion"), R"nbdoc(Sets the confusion tolerance.)nbdoc")
        .def("Confusion3d", static_cast<double (Geom2dHatch_Hatcher::*)() const>(&Geom2dHatch_Hatcher::Confusion3d), R"nbdoc(Returns the 3d confusion tolerance, i.e. the value under
which two points are considered identical in the
3d space of the hatching.)nbdoc")
        .def("KeepPoints", static_cast<void (Geom2dHatch_Hatcher::*)(const bool)>(&Geom2dHatch_Hatcher::KeepPoints), nb::arg("Keep"), R"nbdoc(Sets the above flag.)nbdoc")
        .def("KeepPoints", static_cast<bool (Geom2dHatch_Hatcher::*)() const>(&Geom2dHatch_Hatcher::KeepPoints), R"nbdoc(Returns the flag about the points consideration.)nbdoc")
        .def("KeepSegments", static_cast<void (Geom2dHatch_Hatcher::*)(const bool)>(&Geom2dHatch_Hatcher::KeepSegments), nb::arg("Keep"), R"nbdoc(Sets the above flag.)nbdoc")
        .def("KeepSegments", static_cast<bool (Geom2dHatch_Hatcher::*)() const>(&Geom2dHatch_Hatcher::KeepSegments), R"nbdoc(Returns the flag about the segments consideration.)nbdoc")
        .def("Clear", static_cast<void (Geom2dHatch_Hatcher::*)()>(&Geom2dHatch_Hatcher::Clear), R"nbdoc(Removes all the hatchings and all the elements.)nbdoc")
        .def("ElementCurve", [](const Geom2dHatch_Hatcher &self, const int IndE) { opencascade::handle<Geom2dAdaptor_Curve> result(&(self.ElementCurve(IndE))); return result; }, nb::arg("IndE"), R"nbdoc(Returns the curve associated to the IndE-th element.)nbdoc")
        .def("AddElement", static_cast<int (Geom2dHatch_Hatcher::*)(const Geom2dAdaptor_Curve &, const TopAbs_Orientation)>(&Geom2dHatch_Hatcher::AddElement), nb::arg("Curve"), nb::arg("Orientation") = static_cast<std::decay_t<const TopAbs_Orientation>>(TopAbs_FORWARD), R"nbdoc(Adds an element to the hatcher and returns its index.)nbdoc")
        .def("AddElement", static_cast<int (Geom2dHatch_Hatcher::*)(const occ::handle<Geom2d_Curve> &, const TopAbs_Orientation)>(&Geom2dHatch_Hatcher::AddElement), nb::arg("Curve").none(), nb::arg("Orientation") = static_cast<std::decay_t<const TopAbs_Orientation>>(TopAbs_FORWARD), R"nbdoc(Adds an element to the hatcher and returns its index.)nbdoc")
        .def("RemElement", static_cast<void (Geom2dHatch_Hatcher::*)(const int)>(&Geom2dHatch_Hatcher::RemElement), nb::arg("IndE"), R"nbdoc(Removes the IndE-th element from the hatcher.)nbdoc")
        .def("ClrElements", static_cast<void (Geom2dHatch_Hatcher::*)()>(&Geom2dHatch_Hatcher::ClrElements), R"nbdoc(Removes all the elements from the hatcher.)nbdoc")
        .def("HatchingCurve", [](const Geom2dHatch_Hatcher &self, const int IndH) { opencascade::handle<Geom2dAdaptor_Curve> result(&(self.HatchingCurve(IndH))); return result; }, nb::arg("IndH"), R"nbdoc(Returns the curve associated to the IndH-th hatching.)nbdoc")
        .def("AddHatching", static_cast<int (Geom2dHatch_Hatcher::*)(const Geom2dAdaptor_Curve &)>(&Geom2dHatch_Hatcher::AddHatching), nb::arg("Curve"), R"nbdoc(Adds a hatching to the hatcher and returns its index.)nbdoc")
        .def("RemHatching", static_cast<void (Geom2dHatch_Hatcher::*)(const int)>(&Geom2dHatch_Hatcher::RemHatching), nb::arg("IndH"), R"nbdoc(Removes the IndH-th hatching from the hatcher.)nbdoc")
        .def("ClrHatchings", static_cast<void (Geom2dHatch_Hatcher::*)()>(&Geom2dHatch_Hatcher::ClrHatchings), R"nbdoc(Removes all the hatchings from the hatcher.)nbdoc")
        .def("NbPoints", static_cast<int (Geom2dHatch_Hatcher::*)(const int) const>(&Geom2dHatch_Hatcher::NbPoints), nb::arg("IndH"), R"nbdoc(Returns the number of intersection points of
the IndH-th hatching.)nbdoc")
        .def("Point", static_cast<const HatchGen_PointOnHatching & (Geom2dHatch_Hatcher::*)(const int, const int) const>(&Geom2dHatch_Hatcher::Point), nb::arg("IndH"), nb::arg("IndP"), R"nbdoc(Returns the IndP-th intersection point of the
IndH-th hatching.)nbdoc")
        .def("Trim", static_cast<void (Geom2dHatch_Hatcher::*)()>(&Geom2dHatch_Hatcher::Trim), R"nbdoc(Trims all the hatchings of the hatcher by all the
elements of the hatcher.)nbdoc")
        .def("Trim", static_cast<int (Geom2dHatch_Hatcher::*)(const Geom2dAdaptor_Curve &)>(&Geom2dHatch_Hatcher::Trim), nb::arg("Curve"), R"nbdoc(Adds a hatching to the hatcher and trims it by
the elements already given and returns its index.)nbdoc")
        .def("Trim", static_cast<void (Geom2dHatch_Hatcher::*)(const int)>(&Geom2dHatch_Hatcher::Trim), nb::arg("IndH"), R"nbdoc(Trims the IndH-th hatching by the elements
already given.)nbdoc")
        .def("ComputeDomains", static_cast<void (Geom2dHatch_Hatcher::*)()>(&Geom2dHatch_Hatcher::ComputeDomains), R"nbdoc(Computes the domains of all the hatchings.)nbdoc")
        .def("ComputeDomains", static_cast<void (Geom2dHatch_Hatcher::*)(const int)>(&Geom2dHatch_Hatcher::ComputeDomains), nb::arg("IndH"), R"nbdoc(Computes the domains of the IndH-th hatching.)nbdoc")
        .def("TrimDone", static_cast<bool (Geom2dHatch_Hatcher::*)(const int) const>(&Geom2dHatch_Hatcher::TrimDone), nb::arg("IndH"), R"nbdoc(Returns the fact that the intersections were computed
for the IndH-th hatching.)nbdoc")
        .def("TrimFailed", static_cast<bool (Geom2dHatch_Hatcher::*)(const int) const>(&Geom2dHatch_Hatcher::TrimFailed), nb::arg("IndH"), R"nbdoc(Returns the fact that the intersections failed
for the IndH-th hatching.)nbdoc")
        .def("IsDone", static_cast<bool (Geom2dHatch_Hatcher::*)(const int) const>(&Geom2dHatch_Hatcher::IsDone), nb::arg("IndH"), R"nbdoc(Returns the fact that the domains were computed
for the IndH-th hatching.)nbdoc")
        .def("Status", static_cast<HatchGen_ErrorStatus (Geom2dHatch_Hatcher::*)(const int) const>(&Geom2dHatch_Hatcher::Status), nb::arg("IndH"), R"nbdoc(Returns the status about the IndH-th hatching.)nbdoc")
        .def("NbDomains", static_cast<int (Geom2dHatch_Hatcher::*)(const int) const>(&Geom2dHatch_Hatcher::NbDomains), nb::arg("IndH"), R"nbdoc(Returns the number of domains of the IndH-th hatching.
Only ONE "INFINITE" domain means that the hatching is
fully included in the contour defined by the elements.)nbdoc")
        .def("Domain", static_cast<const HatchGen_Domain & (Geom2dHatch_Hatcher::*)(const int, const int) const>(&Geom2dHatch_Hatcher::Domain), nb::arg("IndH"), nb::arg("IDom"), R"nbdoc(Returns the IDom-th domain of the IndH-th hatching.)nbdoc")
        .def("Dump", static_cast<void (Geom2dHatch_Hatcher::*)() const>(&Geom2dHatch_Hatcher::Dump), R"nbdoc(Dump the hatcher.)nbdoc");
    nanoocp_implicit_copy_ctor<Geom2dHatch_Hatcher>(nb::borrow<nb::class_<Geom2dHatch_Hatcher>>(m.attr("Geom2dHatch_Hatcher")));
}

void nanoocp_conversions_Geom2dHatch(nb::module_ &m) {
}
