// Generated by the nanoOCP generator from OCCT package Hatch (toolkit TKGeomAlgo). Do not edit.
#include "nanoocp_common.h"
#include <Hatch_Hatcher.hxx>
#include <Hatch_Line.hxx>
#include <Hatch_LineForm.hxx>
#include <Hatch_Parameter.hxx>
#include <gp_Dir2d.hxx>
#include <gp_Lin2d.hxx>
#include <gp_Pnt2d.hxx>

void nanoocp_declare_Hatch(nb::module_ &m) {
    nb::enum_<Hatch_LineForm>(m, "Hatch_LineForm", R"nbdoc(Form of a trimmed line)nbdoc", nb::is_arithmetic())
        .value("Hatch_XLINE", Hatch_XLINE)
        .value("Hatch_YLINE", Hatch_YLINE)
        .value("Hatch_ANYLINE", Hatch_ANYLINE)
        .export_values();
    { nb::class_<Hatch_Parameter> cls(m, "Hatch_Parameter", R"nbdoc(Stores an intersection on a line represented by :

* A Real parameter.

* A flag True when the parameter starts an interval.)nbdoc");
    }
    { nb::class_<Hatch_Line> cls(m, "Hatch_Line", R"nbdoc(Stores a Line in the Hatcher. Represented by:

* A Lin2d from gp, the geometry of the line.

* Bounding parameters for the line.

* A sorted List of Parameters, the intersections
on the line.)nbdoc");
    }
    { nb::class_<Hatch_Hatcher> cls(m, "Hatch_Hatcher", R"nbdoc(The Hatcher is an algorithm to compute cross
hatchings in a 2d plane. It is mainly dedicated to
display purpose.

Computing cross hatchings is a 3 steps process :

1. The users stores in the Hatcher a set of 2d
lines to be trimmed. Methods in the "Lines"
category.

2. The user trims the lines with a boundary. The
inside of a boundary is on the left side. Methods
in the "Trimming" category.

3. The user reads back the trimmed lines. Methods
in the "Results" category.

The result is a set of parameter intervals on the
line. The first parameter of an Interval may be
RealFirst() and the last may be RealLast().

A line can be a line parallel to the axis (X or Y
line or a 2D line.

The Hatcher has two modes :

* The "Oriented" mode, where the orientation of
the trimming curves is considered. The hatch are
kept on the left of the trimming curve. In this
mode infinite hatch can be computed.

* The "UnOriented" mode, where the hatch are
always finite.)nbdoc");
    }
}

void nanoocp_templates_Hatch(nb::module_ &m) {
}

void nanoocp_define_Hatch(nb::module_ &m) {
    nb::borrow<nb::class_<Hatch_Parameter>>(m.attr("Hatch_Parameter"))
        .def(nb::init<>())
        .def(nb::init<const double, const bool, const int, const double>(), nb::arg("Par1"), nb::arg("Start"), nb::arg("Index") = static_cast<std::decay_t<const int>>(0), nb::arg("Par2") = static_cast<std::decay_t<const double>>(0));
    nanoocp_implicit_copy_ctor<Hatch_Parameter>(nb::borrow<nb::class_<Hatch_Parameter>>(m.attr("Hatch_Parameter")));
    nb::borrow<nb::class_<Hatch_Line>>(m.attr("Hatch_Line"))
        .def(nb::init<>())
        .def(nb::init<const gp_Lin2d &, const Hatch_LineForm>(), nb::arg("L"), nb::arg("T"))
        .def("AddIntersection", static_cast<void (Hatch_Line::*)(const double, const bool, const int, const double, const double)>(&Hatch_Line::AddIntersection), nb::arg("Par1"), nb::arg("Start"), nb::arg("Index"), nb::arg("Par2"), nb::arg("theToler"), R"nbdoc(Insert a new intersection in the sorted list.)nbdoc");
    nanoocp_implicit_copy_ctor<Hatch_Line>(nb::borrow<nb::class_<Hatch_Line>>(m.attr("Hatch_Line")));
    nb::borrow<nb::class_<Hatch_Hatcher>>(m.attr("Hatch_Hatcher"))
        .def(nb::init<const double, const bool>(), nb::arg("Tol"), nb::arg("Oriented") = static_cast<std::decay_t<const bool>>(true), R"nbdoc(Returns an empty hatcher. <Tol> is the tolerance
for intersections.)nbdoc")
        .def("Tolerance", static_cast<void (Hatch_Hatcher::*)(const double)>(&Hatch_Hatcher::Tolerance), nb::arg("Tol"))
        .def("Tolerance", static_cast<double (Hatch_Hatcher::*)() const>(&Hatch_Hatcher::Tolerance))
        .def("AddLine", static_cast<void (Hatch_Hatcher::*)(const gp_Lin2d &, const Hatch_LineForm)>(&Hatch_Hatcher::AddLine), nb::arg("L"), nb::arg("T") = static_cast<std::decay_t<const Hatch_LineForm>>(Hatch_ANYLINE), R"nbdoc(Add a line <L> to be trimmed. <T> the type is
only kept from information. It is not used in the
computation.)nbdoc")
        .def("AddLine", static_cast<void (Hatch_Hatcher::*)(const gp_Dir2d &, const double)>(&Hatch_Hatcher::AddLine), nb::arg("D"), nb::arg("Dist"), R"nbdoc(Add an infinite line on direction <D> at distance
<Dist> from the origin to be trimmed. <Dist> may
be negative.

If O is the origin of the 2D plane, and V the
vector perpendicular to D (in the direct direction).

A point P is on the line if :
OP dot V = Dist
The parameter of P on the line is
OP dot D)nbdoc")
        .def("AddXLine", static_cast<void (Hatch_Hatcher::*)(const double)>(&Hatch_Hatcher::AddXLine), nb::arg("X"), R"nbdoc(Add an infinite line parallel to the Y-axis at
abciss <X>.)nbdoc")
        .def("AddYLine", static_cast<void (Hatch_Hatcher::*)(const double)>(&Hatch_Hatcher::AddYLine), nb::arg("Y"), R"nbdoc(Add an infinite line parallel to the X-axis at
ordinate <Y>.)nbdoc")
        .def("Trim", static_cast<void (Hatch_Hatcher::*)(const gp_Lin2d &, const int)>(&Hatch_Hatcher::Trim), nb::arg("L"), nb::arg("Index") = static_cast<std::decay_t<const int>>(0), R"nbdoc(Trims the lines at intersections with <L>.)nbdoc")
        .def("Trim", static_cast<void (Hatch_Hatcher::*)(const gp_Lin2d &, const double, const double, const int)>(&Hatch_Hatcher::Trim), nb::arg("L"), nb::arg("Start"), nb::arg("End"), nb::arg("Index") = static_cast<std::decay_t<const int>>(0), R"nbdoc(Trims the lines at intersections with <L> in the
parameter range <Start>, <End>)nbdoc")
        .def("Trim", static_cast<void (Hatch_Hatcher::*)(const gp_Pnt2d &, const gp_Pnt2d &, const int)>(&Hatch_Hatcher::Trim), nb::arg("P1"), nb::arg("P2"), nb::arg("Index") = static_cast<std::decay_t<const int>>(0), R"nbdoc(Trims the line at intersection with the oriented
segment P1,P2.)nbdoc")
        .def("NbIntervals", static_cast<int (Hatch_Hatcher::*)() const>(&Hatch_Hatcher::NbIntervals), R"nbdoc(Returns the total number of intervals on all the
lines.)nbdoc")
        .def("NbLines", static_cast<int (Hatch_Hatcher::*)() const>(&Hatch_Hatcher::NbLines), R"nbdoc(Returns the number of lines.)nbdoc")
        .def("Line", static_cast<const gp_Lin2d & (Hatch_Hatcher::*)(const int) const>(&Hatch_Hatcher::Line), nb::arg("I"), R"nbdoc(Returns the line of index <I>.)nbdoc")
        .def("LineForm", static_cast<Hatch_LineForm (Hatch_Hatcher::*)(const int) const>(&Hatch_Hatcher::LineForm), nb::arg("I"), R"nbdoc(Returns the type of the line of index <I>.)nbdoc")
        .def("IsXLine", static_cast<bool (Hatch_Hatcher::*)(const int) const>(&Hatch_Hatcher::IsXLine), nb::arg("I"), R"nbdoc(Returns True if the line of index <I> has a
constant X value.)nbdoc")
        .def("IsYLine", static_cast<bool (Hatch_Hatcher::*)(const int) const>(&Hatch_Hatcher::IsYLine), nb::arg("I"), R"nbdoc(Returns True if the line of index <I> has a
constant Y value.)nbdoc")
        .def("Coordinate", static_cast<double (Hatch_Hatcher::*)(const int) const>(&Hatch_Hatcher::Coordinate), nb::arg("I"), R"nbdoc(Returns the X or Y coordinate of the line of index
<I> if it is a X or a Y line.)nbdoc")
        .def("NbIntervals", static_cast<int (Hatch_Hatcher::*)(const int) const>(&Hatch_Hatcher::NbIntervals), nb::arg("I"), R"nbdoc(Returns the number of intervals on line of index <I>.)nbdoc")
        .def("Start", static_cast<double (Hatch_Hatcher::*)(const int, const int) const>(&Hatch_Hatcher::Start), nb::arg("I"), nb::arg("J"), R"nbdoc(Returns the first parameter of interval <J> on
line <I>.)nbdoc")
        .def("StartIndex", [](const Hatch_Hatcher &self, const int I, const int J) { int Index{}; double Par2{}; self.StartIndex(I, J, Index, Par2); return std::make_tuple(Index, Par2); }, nb::arg("I"), nb::arg("J"), R"nbdoc(Returns the first Index and Par2 of interval <J> on
line <I>.)nbdoc")
        .def("End", static_cast<double (Hatch_Hatcher::*)(const int, const int) const>(&Hatch_Hatcher::End), nb::arg("I"), nb::arg("J"), R"nbdoc(Returns the last parameter of interval <J> on
line <I>.)nbdoc")
        .def("EndIndex", [](const Hatch_Hatcher &self, const int I, const int J) { int Index{}; double Par2{}; self.EndIndex(I, J, Index, Par2); return std::make_tuple(Index, Par2); }, nb::arg("I"), nb::arg("J"), R"nbdoc(Returns the last Index and Par2 of interval <J> on
line <I>.)nbdoc");
    nanoocp_implicit_copy_ctor<Hatch_Hatcher>(nb::borrow<nb::class_<Hatch_Hatcher>>(m.attr("Hatch_Hatcher")));
    nb::implicitly_convertible<std::decay_t<const double>, Hatch_Hatcher>();
}

void nanoocp_conversions_Hatch(nb::module_ &m) {
}
