// Generated by the nanoOCP generator from OCCT package HelixBRep (toolkit TKHelix). Do not edit.
#include "nanoocp_common.h"
#include <HelixBRep_BuilderHelix.hxx>
#include <GeomAbs_Shape.hxx>
#include <NCollection_Array1.hxx>
#include <TopoDS_Shape.hxx>
#include <gp_Ax3.hxx>

void nanoocp_declare_HelixBRep(nb::module_ &m) {
    { nb::class_<HelixBRep_BuilderHelix> cls(m, "HelixBRep_BuilderHelix", R"nbdoc(Implementation of building helix wire
Values of Error Status returned by algo:
0 - OK
1 - object is just initialized, it means that no input parameters were set
2 - approximation fails

10 - R < tolerance - starting point is too close to axis
11 - step (Pitch) < tolerance
12 - Height < tolerance
13 - TaperAngle < 0 or TaperAngle > Pi/2 - TolAng
Warning Status:
0 - OK
1 - tolerance reached by approximation > requested tolerance.)nbdoc");
    }
}

void nanoocp_templates_HelixBRep(nb::module_ &m) {
}

void nanoocp_define_HelixBRep(nb::module_ &m) {
    nb::borrow<nb::class_<HelixBRep_BuilderHelix>>(m.attr("HelixBRep_BuilderHelix"))
        .def(nb::init<>(), R"nbdoc(Empty constructor)nbdoc")
        .def("SetParameters", static_cast<void (HelixBRep_BuilderHelix::*)(const gp_Ax3 &, const NCollection_Array1<double> &, const NCollection_Array1<double> &, const NCollection_Array1<double> &, const NCollection_Array1<bool> &)>(&HelixBRep_BuilderHelix::SetParameters), nb::arg("theAxis"), nb::arg("theDiams"), nb::arg("theHeights"), nb::arg("thePitches"), nb::arg("theIsPitches"), R"nbdoc(Sets parameters of general composite helix)nbdoc")
        .def("SetParameters", static_cast<void (HelixBRep_BuilderHelix::*)(const gp_Ax3 &, const double, const NCollection_Array1<double> &, const NCollection_Array1<double> &, const NCollection_Array1<bool> &)>(&HelixBRep_BuilderHelix::SetParameters), nb::arg("theAxis"), nb::arg("theDiam"), nb::arg("theHeights"), nb::arg("thePitches"), nb::arg("theIsPitches"), R"nbdoc(Sets parameters of pure helix)nbdoc")
        .def("SetParameters", static_cast<void (HelixBRep_BuilderHelix::*)(const gp_Ax3 &, const double, const double, const NCollection_Array1<double> &, const NCollection_Array1<double> &, const NCollection_Array1<bool> &)>(&HelixBRep_BuilderHelix::SetParameters), nb::arg("theAxis"), nb::arg("theDiam1"), nb::arg("theDiam2"), nb::arg("theHeights"), nb::arg("thePitches"), nb::arg("theIsPitches"), R"nbdoc(Sets parameters of pure spiral)nbdoc")
        .def("SetParameters", static_cast<void (HelixBRep_BuilderHelix::*)(const gp_Ax3 &, const NCollection_Array1<double> &, const NCollection_Array1<double> &, const NCollection_Array1<double> &)>(&HelixBRep_BuilderHelix::SetParameters), nb::arg("theAxis"), nb::arg("theDiams"), nb::arg("thePitches"), nb::arg("theNbTurns"), R"nbdoc(Sets parameters of general composite helix)nbdoc")
        .def("SetParameters", static_cast<void (HelixBRep_BuilderHelix::*)(const gp_Ax3 &, const double, const NCollection_Array1<double> &, const NCollection_Array1<double> &)>(&HelixBRep_BuilderHelix::SetParameters), nb::arg("theAxis"), nb::arg("theDiam"), nb::arg("thePitches"), nb::arg("theNbTurns"), R"nbdoc(Sets parameters of pure helix)nbdoc")
        .def("SetParameters", static_cast<void (HelixBRep_BuilderHelix::*)(const gp_Ax3 &, const double, const double, const NCollection_Array1<double> &, const NCollection_Array1<double> &)>(&HelixBRep_BuilderHelix::SetParameters), nb::arg("theAxis"), nb::arg("theDiam1"), nb::arg("theDiam2"), nb::arg("thePitches"), nb::arg("theNbTurns"), R"nbdoc(Sets parameters of pure spiral)nbdoc")
        .def("SetApproxParameters", static_cast<void (HelixBRep_BuilderHelix::*)(const double, const int, const GeomAbs_Shape)>(&HelixBRep_BuilderHelix::SetApproxParameters), nb::arg("theTolerance"), nb::arg("theMaxDegree"), nb::arg("theContinuity"), R"nbdoc(Sets parameters for approximation)nbdoc")
        .def("Perform", static_cast<void (HelixBRep_BuilderHelix::*)()>(&HelixBRep_BuilderHelix::Perform), R"nbdoc(Performs calculations)nbdoc")
        .def("ToleranceReached", static_cast<double (HelixBRep_BuilderHelix::*)() const>(&HelixBRep_BuilderHelix::ToleranceReached), R"nbdoc(Gets tolerance reached by approximation)nbdoc")
        .def("ErrorStatus", static_cast<int (HelixBRep_BuilderHelix::*)() const>(&HelixBRep_BuilderHelix::ErrorStatus), R"nbdoc(Returns error status of algorithm)nbdoc")
        .def("WarningStatus", static_cast<int (HelixBRep_BuilderHelix::*)() const>(&HelixBRep_BuilderHelix::WarningStatus), R"nbdoc(Returns warning status of algorithm)nbdoc")
        .def("Shape", static_cast<const TopoDS_Shape & (HelixBRep_BuilderHelix::*)() const>(&HelixBRep_BuilderHelix::Shape), R"nbdoc(Gets result of algorithm)nbdoc");
    nanoocp_implicit_copy_ctor<HelixBRep_BuilderHelix>(nb::borrow<nb::class_<HelixBRep_BuilderHelix>>(m.attr("HelixBRep_BuilderHelix")));
}

void nanoocp_conversions_HelixBRep(nb::module_ &m) {
}
