class NCollection_Sequence(Generic[_T]):
    """NCollection_Sequence<T>: doubly linked, 1-based indexed sequence (OCCT)."""
    class Iterator(Generic[_IT]):
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, theSeq: NCollection_Sequence[_IT], isStart: bool = True) -> None: ...
        def More(self) -> bool: ...
        def Next(self) -> None: ...
        def Value(self) -> _IT: ...
        def __iter__(self) -> Self: ...
        def __next__(self) -> _IT: ...
        def ChangeValue(self) -> _IT: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theAllocator: nanocct.NCollection.NCollection_BaseAllocator | None) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_Sequence[_T]) -> None: ...
    def Length(self) -> int: ...
    def Size(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Lower(self) -> int: ...
    def Upper(self) -> int: ...
    def Allocator(self) -> nanocct.NCollection.NCollection_BaseAllocator: ...
    def Reverse(self) -> None: ...
    def Exchange(self, I: int, J: int) -> None: ...
    def Clear(self, theAllocator: nanocct.NCollection.NCollection_BaseAllocator | None = None) -> None: ...
    def Assign(self, theOther: NCollection_Sequence[_T]) -> Self: ...
    @overload
    def Remove(self, thePosition: NCollection_Sequence.Iterator[_T]) -> None: ...
    @overload
    def Remove(self, theIndex: int) -> None: ...
    @overload
    def Remove(self, theFromIndex: int, theToIndex: int) -> None: ...
    @overload
    def Append(self, theItem: _T) -> None: ...
    @overload
    def Append(self, theSeq: NCollection_Sequence[_T]) -> None: ...
    @overload
    def Prepend(self, theItem: _T) -> None: ...
    @overload
    def Prepend(self, theSeq: NCollection_Sequence[_T]) -> None: ...
    @overload
    def InsertBefore(self, theIndex: int, theItem: _T) -> None: ...
    @overload
    def InsertBefore(self, theIndex: int, theSeq: NCollection_Sequence[_T]) -> None: ...
    @overload
    def InsertAfter(self, thePosition: NCollection_Sequence.Iterator[_T], theItem: _T) -> None: ...
    @overload
    def InsertAfter(self, theIndex: int, theSeq: NCollection_Sequence[_T]) -> None: ...
    @overload
    def InsertAfter(self, theIndex: int, theItem: _T) -> None: ...
    def Split(self, theIndex: int, theSeq: NCollection_Sequence[_T]) -> None: ...
    def First(self) -> _T: ...
    def Last(self) -> _T: ...
    def ChangeFirst(self) -> _T: ...
    def ChangeLast(self) -> _T: ...
    def Value(self, theIndex: int) -> _T: ...
    def ChangeValue(self, theIndex: int) -> _T: ...
    def SetValue(self, theIndex: int, theItem: _T) -> None: ...
    def At(self, theIndex: int) -> _T: ...
    def ChangeAt(self, theIndex: int) -> _T: ...
    def __call__(self, theIndex: int) -> _T: ...
    def __getitem__(self, theIndex: int) -> _T: ...
    def __setitem__(self, theIndex: int, theItem: _T) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> collections.abc.Iterator[_T]: ...
