class NCollection_HArray1(nanoocp.Standard.Standard_Transient, Generic[_T]):
    """NCollection_HArray1<T>: handle-managed (Standard_Transient) NCollection_Array1<T>."""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theLower: int, theUpper: int) -> None: ...
    @overload
    def __init__(self, theLower: int, theUpper: int, theValue: _T) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_Array1[_T]) -> None: ...
    def Array1(self) -> NCollection_Array1[_T]: ...
    def ChangeArray1(self) -> Self: ...
    def Init(self, theValue: _T) -> None: ...
    def Size(self) -> int: ...
    def Length(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Lower(self) -> int: ...
    def Upper(self) -> int: ...
    def IsDeletable(self) -> bool: ...
    def Assign(self, theOther: NCollection_Array1[_T]) -> Self: ...
    def CopyValues(self, theOther: NCollection_Array1[_T]) -> Self: ...
    def First(self) -> _T: ...
    def Last(self) -> _T: ...
    def Value(self, theIndex: int) -> _T: ...
    def At(self, theIndex: int) -> _T: ...
    def SetValue(self, theIndex: int, theItem: _T) -> None: ...
    def UpdateLowerBound(self, theLower: int) -> None: ...
    def UpdateUpperBound(self, theUpper: int) -> None: ...
    @overload
    def Resize(self, theLower: int, theUpper: int, theToCopyData: bool) -> None: ...
    @overload
    def Resize(self, theSize: int, theToCopyData: bool) -> None: ...
    def ChangeFirst(self) -> _T: ...
    def ChangeLast(self) -> _T: ...
    def ChangeValue(self, theIndex: int) -> _T: ...
    def ChangeAt(self, theIndex: int) -> _T: ...
    def __call__(self, theIndex: int) -> _T: ...
    def __getitem__(self, theIndex: int) -> _T: ...
    def __setitem__(self, theIndex: int, theItem: _T) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_T]: ...
