class NCollection_Map(Generic[_K]):
    """NCollection_Map<Key>: hashed set of keys (OCCT)."""
    class Iterator(Generic[_K]):
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, theMap: NCollection_Map[_K]) -> None: ...
        def Initialize(self, theMap: NCollection_Map[_K]) -> None: ...
        def Reset(self) -> None: ...
        def More(self) -> bool: ...
        def Next(self) -> None: ...
        def Value(self) -> _K: ...
        def Key(self) -> _K: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theNbBuckets: int, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None = None) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_Map[_K]) -> None: ...
    def NbBuckets(self) -> int: ...
    def Extent(self) -> int: ...
    def Length(self) -> int: ...
    def Size(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Allocator(self) -> nanoocp.NCollection.NCollection_BaseAllocator: ...
    def Exchange(self, theOther: NCollection_Map[_K]) -> None: ...
    def Assign(self, theOther: NCollection_Map[_K]) -> Self: ...
    def ReSize(self, N: int) -> None: ...
    @overload
    def Clear(self, doReleaseMemory: bool = True) -> None: ...
    @overload
    def Clear(self, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None) -> None: ...
    def Add(self, theKey: _K) -> bool: ...
    def Added(self, theKey: _K) -> _K: ...
    @overload
    def Contains(self, theKey: _K) -> bool: ...
    @overload
    def Contains(self, theOther: NCollection_Map[_K]) -> bool: ...
    def Remove(self, theKey: _K) -> bool: ...
    def IsEqual(self, theOther: NCollection_Map[_K]) -> bool: ...
    def Union(self, theLeft: NCollection_Map[_K], theRight: NCollection_Map[_K]) -> None: ...
    def Unite(self, theOther: NCollection_Map[_K]) -> bool: ...
    def HasIntersection(self, theMap: NCollection_Map[_K]) -> bool: ...
    def Intersection(self, theLeft: NCollection_Map[_K], theRight: NCollection_Map[_K]) -> None: ...
    def Intersect(self, theOther: NCollection_Map[_K]) -> bool: ...
    def Subtraction(self, theLeft: NCollection_Map[_K], theRight: NCollection_Map[_K]) -> None: ...
    def Subtract(self, theOther: NCollection_Map[_K]) -> bool: ...
    def Difference(self, theLeft: NCollection_Map[_K], theRight: NCollection_Map[_K]) -> None: ...
    def Differ(self, theOther: NCollection_Map[_K]) -> bool: ...
    def __contains__(self, theKey: _K) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_K]: ...
