class NCollection_DoubleMap(Generic[_K, _V]):
    """NCollection_DoubleMap<Key1, Key2>: bidirectional hashed map (OCCT). _V stands for Key2."""
    class Iterator(Generic[_IK, _IV]):
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, theMap: NCollection_DoubleMap[_IK, _IV]) -> None: ...
        def Initialize(self, theMap: NCollection_DoubleMap[_IK, _IV]) -> None: ...
        def Reset(self) -> None: ...
        def More(self) -> bool: ...
        def Next(self) -> None: ...
        def Key1(self) -> _IK: ...
        def Key2(self) -> _IV: ...
        def Value(self) -> _IV: ...
        def __iter__(self) -> Self: ...
        def __next__(self) -> _IV: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theNbBuckets: int, theAllocator: OCP3x.NCollection.NCollection_BaseAllocator | None = None) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_DoubleMap[_K, _V]) -> None: ...
    def NbBuckets(self) -> int: ...
    def Extent(self) -> int: ...
    def Length(self) -> int: ...
    def Size(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Allocator(self) -> OCP3x.NCollection.NCollection_BaseAllocator: ...
    def Exchange(self, theOther: NCollection_DoubleMap[_K, _V]) -> None: ...
    def Assign(self, theOther: NCollection_DoubleMap[_K, _V]) -> Self: ...
    def ReSize(self, N: int) -> None: ...
    @overload
    def Clear(self, doReleaseMemory: bool = True) -> None: ...
    @overload
    def Clear(self, theAllocator: OCP3x.NCollection.NCollection_BaseAllocator | None) -> None: ...
    def Bind(self, theKey1: _K, theKey2: _V) -> None: ...
    def TryBind(self, theKey1: _K, theKey2: _V) -> bool: ...
    def AreBound(self, theKey1: _K, theKey2: _V) -> bool: ...
    def IsBound1(self, theKey1: _K) -> bool: ...
    def IsBound2(self, theKey2: _V) -> bool: ...
    def UnBind1(self, theKey1: _K) -> bool: ...
    def UnBind2(self, theKey2: _V) -> bool: ...
    @overload
    def Find1(self, theKey1: _K) -> _V: ...
    @overload
    def Find1(self, theKey1: _K, theKey2: _V) -> bool: ...
    def Seek1(self, theKey1: _K) -> _V | None: ...
    @overload
    def Find2(self, theKey2: _V) -> _K: ...
    @overload
    def Find2(self, theKey2: _V, theKey1: _K) -> bool: ...
    def Seek2(self, theKey2: _V) -> _K | None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[tuple[_K, _V]]: ...
    def items(self) -> list[tuple[_K, _V]]: ...
