class NCollection_DataMap(Generic[_K, _V]):
    """NCollection_DataMap<Key, Item>: hashed map from keys to items (OCCT)."""
    class Iterator(Generic[_K, _V]):
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, theMap: NCollection_DataMap[_K, _V]) -> None: ...
        def Initialize(self, theMap: NCollection_DataMap[_K, _V]) -> None: ...
        def Reset(self) -> None: ...
        def More(self) -> bool: ...
        def Next(self) -> None: ...
        def Value(self) -> _V: ...
        def ChangeValue(self) -> _V: ...
        def Key(self) -> _K: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theNbBuckets: int, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None = None) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_DataMap[_K, _V]) -> None: ...
    def NbBuckets(self) -> int: ...
    def Extent(self) -> int: ...
    def Length(self) -> int: ...
    def Size(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Allocator(self) -> nanoocp.NCollection.NCollection_BaseAllocator: ...
    def Exchange(self, theOther: NCollection_DataMap[_K, _V]) -> None: ...
    def Assign(self, theOther: NCollection_DataMap[_K, _V]) -> Self: ...
    def ReSize(self, N: int) -> None: ...
    @overload
    def Clear(self, doReleaseMemory: bool = True) -> None: ...
    @overload
    def Clear(self, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None) -> None: ...
    def Bind(self, theKey: _K, theItem: _V) -> bool: ...
    def Bound(self, theKey: _K, theItem: _V) -> _V: ...
    def TryBind(self, theKey: _K, theItem: _V) -> bool: ...
    def TryBound(self, theKey: _K, theItem: _V) -> _V: ...
    def IsBound(self, theKey: _K) -> bool: ...
    def UnBind(self, theKey: _K) -> bool: ...
    def Seek(self, theKey: _K) -> _V | None: ...
    def ChangeSeek(self, theKey: _K) -> _V | None: ...
    @overload
    def Find(self, theKey: _K) -> _V: ...
    @overload
    def Find(self, theKey: _K, theValue: _V) -> bool: ...
    def ChangeFind(self, theKey: _K) -> _V: ...
    def __call__(self, theKey: _K) -> _V: ...
    def __contains__(self, theKey: _K) -> bool: ...
    def __getitem__(self, theKey: _K) -> _V: ...
    def __setitem__(self, theKey: _K, theItem: _V) -> None: ...
    def __delitem__(self, theKey: _K) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_K]: ...
    def items(self) -> list[tuple[_K, _V]]: ...
