class NCollection_DynamicArray(Generic[_T]):
    """NCollection_DynamicArray<T>: growable 0-based array (OCCT)."""
    @overload
    def __init__(self, theIncrement: int = 256) -> None: ...
    @overload
    def __init__(self, theIncrement: int, theAlloc: nanocct.NCollection.NCollection_BaseAllocator | None) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_DynamicArray[_T]) -> None: ...
    def Size(self) -> int: ...
    def Length(self) -> int: ...
    def Lower(self) -> int: ...
    def Upper(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Assign(self, theOther: NCollection_DynamicArray[_T], theOwnAllocator: bool = True) -> Self: ...
    def Append(self, theValue: _T) -> _T: ...
    def InsertAfter(self, theIndex: int, theValue: _T) -> _T: ...
    def InsertBefore(self, theIndex: int, theValue: _T) -> _T: ...
    def EraseLast(self) -> None: ...
    def Appended(self) -> _T: ...
    def Value(self, theIndex: int) -> _T: ...
    def First(self) -> _T: ...
    def Last(self) -> _T: ...
    def SetValue(self, theIndex: int, theValue: _T) -> _T: ...
    def Clear(self, theReleaseMemory: bool = False) -> None: ...
    def SetIncrement(self, theIncrement: int) -> None: ...
    def __call__(self, theIndex: int) -> _T: ...
    def __getitem__(self, theIndex: int) -> _T: ...
    def __setitem__(self, theIndex: int, theItem: _T) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> collections.abc.Iterator[_T]: ...
