class NCollection_HArray1(NCollection_Array1[_T]):
    """NCollection_HArray1<T>: handle-managed (Standard_Transient) NCollection_Array1<T>. Bound with base
    NCollection_Array1 (offset-0 base); the Standard_Transient members are bound directly."""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theLower: int, theUpper: int) -> None: ...
    @overload
    def __init__(self, theLower: int, theUpper: int, theValue: _T) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_Array1[_T]) -> None: ...
    def Array1(self) -> NCollection_Array1[_T]: ...
    def ChangeArray1(self) -> Self: ...
    def GetRefCount(self) -> int: ...
    def DynamicType(self) -> nanocct.Standard.Standard_Type: ...
    def IsInstance(self, theTypeName: str) -> bool: ...
    def IsKind(self, theTypeName: str) -> bool: ...
    @staticmethod
    def get_type_name_s() -> str: ...
    @staticmethod
    def get_type_descriptor_s() -> nanocct.Standard.Standard_Type: ...
