class NCollection_LinearVector(Generic[_T]):
    """NCollection_LinearVector<T>: contiguous 0-based vector with size_t indices (OCCT 8).
    Instantiations are the concrete classes NCollection_LinearVector__<T>; NCollection_LinearVector[T] returns them."""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theCapacity: int) -> None: ...
    @overload
    def __init__(self, theSize: int, theValue: _T) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_LinearVector[_T]) -> None: ...
    def HasData(self) -> bool: ...
    def Empty(self) -> bool: ...
    @staticmethod
    def MaxSize() -> int: ...
    def Size(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Capacity(self) -> int: ...
    def Reserve(self, theCapacity: int) -> None: ...
    @overload
    def Resize(self, theSize: int) -> None: ...
    @overload
    def Resize(self, theSize: int, theValue: _T) -> None: ...
    def Value(self, theIndex: int) -> _T: ...
    def ChangeValue(self, theIndex: int) -> _T: ...
    def First(self) -> _T: ...
    def ChangeFirst(self) -> _T: ...
    def Last(self) -> _T: ...
    def ChangeLast(self) -> _T: ...
    def Append(self, theValue: _T) -> _T: ...
    def Appended(self) -> _T: ...
    def SetValue(self, theIndex: int, theValue: _T) -> _T: ...
    def InsertBefore(self, theIndex: int, theValue: _T) -> None: ...
    def InsertAfter(self, theIndex: int, theValue: _T) -> None: ...
    def EraseLast(self) -> None: ...
    @overload
    def Erase(self, theIndex: int) -> None: ...
    @overload
    def Erase(self, theFrom: int, theTo: int) -> None: ...
    def Clear(self, theReleaseMemory: bool = False) -> None: ...
    def ToArray1(self) -> NCollection_Array1[_T]: ...
    def __call__(self, theIndex: int) -> _T: ...
    def __getitem__(self, theIndex: int) -> _T: ...
    def __setitem__(self, theIndex: int, theItem: _T) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_T]: ...
