class NCollection_Array2(NCollection_Array1[_T]):
    """NCollection_Array2<T>: 2D array with user-defined row/column ranges (OCCT); derives from NCollection_Array1."""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theRowLower: int, theRowUpper: int, theColLower: int, theColUpper: int) -> None: ...
    @overload
    def __init__(self, theNbRows: int, theNbCols: int) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_Array2[_T]) -> None: ...
    @staticmethod
    def BeginPosition(theRowLower: int, theRowUpper: int, theColLower: int, theColUpper: int) -> int: ...
    @staticmethod
    def LastPosition(theRowLower: int, theRowUpper: int, theColLower: int, theColUpper: int) -> int: ...
    def NbRows(self) -> int: ...
    def NbColumns(self) -> int: ...
    def RowLength(self) -> int: ...
    def ColLength(self) -> int: ...
    def LowerRow(self) -> int: ...
    def UpperRow(self) -> int: ...
    def LowerCol(self) -> int: ...
    def UpperCol(self) -> int: ...
    def UpdateLowerRow(self, theLowerRow: int) -> None: ...
    def UpdateLowerCol(self, theLowerCol: int) -> None: ...
    def UpdateUpperRow(self, theUpperRow: int) -> None: ...
    def UpdateUpperCol(self, theUpperCol: int) -> None: ...
    def Assign(self, theOther: NCollection_Array2[_T]) -> Self: ...  # type: ignore[override]
    def CopyValues(self, theOther: NCollection_Array2[_T]) -> Self: ...  # type: ignore[override]
    def Value(self, theRow: int, theCol: int) -> _T: ...  # type: ignore[override]
    def ChangeValue(self, theRow: int, theCol: int) -> _T: ...  # type: ignore[override]
    def SetValue(self, theRow: int, theCol: int, theItem: _T) -> None: ...  # type: ignore[override]
    def At(self, theRow: int, theCol: int) -> _T: ...  # type: ignore[override]
    def ChangeAt(self, theRow: int, theCol: int) -> _T: ...  # type: ignore[override]
    @overload
    def Resize(self, theRowLower: int, theRowUpper: int, theColLower: int, theColUpper: int, theToCopyData: bool) -> None: ...
    @overload
    def Resize(self, theNbRows: int, theNbCols: int, theToCopyData: bool) -> None: ...
    @overload
    def ResizeWithTrim(self, theRowLower: int, theRowUpper: int, theColLower: int, theColUpper: int, theToCopyData: bool) -> None: ...
    @overload
    def ResizeWithTrim(self, theNbRows: int, theNbCols: int, theToCopyData: bool) -> None: ...
    def __call__(self, theRow: int, theCol: int) -> _T: ...  # type: ignore[override]
    def __getitem__(self, theRowCol: tuple[int, int]) -> _T: ...  # type: ignore[override]
    def __setitem__(self, theRowCol: tuple[int, int], theItem: _T) -> None: ...  # type: ignore[override]
