class NCollection_Array1(Generic[_T]):
    """NCollection_Array1<T>: unidimensional array of fixed size with user-defined index range (OCCT).
    Instantiations are the concrete classes NCollection_Array1__<T>; NCollection_Array1[T] returns them."""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theLower: int, theUpper: int) -> None: ...
    @overload
    def __init__(self, theSize: int) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_Array1[_T]) -> None: ...
    def Init(self, theValue: _T) -> None: ...
    def Size(self) -> int: ...
    def Length(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Lower(self) -> int: ...
    def Upper(self) -> int: ...
    def IsDeletable(self) -> bool: ...
    def Assign(self, theOther: NCollection_Array1[_T]) -> Self: ...
    def CopyValues(self, theOther: NCollection_Array1[_T]) -> Self: ...
    def First(self) -> _T: ...
    def Last(self) -> _T: ...
    def Value(self, theIndex: int) -> _T: ...
    def At(self, theIndex: int) -> _T: ...
    def SetValue(self, theIndex: int, theItem: _T) -> None: ...
    def UpdateLowerBound(self, theLower: int) -> None: ...
    def UpdateUpperBound(self, theUpper: int) -> None: ...
    @overload
    def Resize(self, theLower: int, theUpper: int, theToCopyData: bool) -> None: ...
    @overload
    def Resize(self, theSize: int, theToCopyData: bool) -> None: ...
    def __call__(self, theIndex: int) -> _T: ...
    def __getitem__(self, theIndex: int) -> _T: ...
    def __setitem__(self, theIndex: int, theItem: _T) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> collections.abc.Iterator[_T]: ...
