class NCollection_Shared(Generic[_T]):
    """NCollection_Shared<T>: T made a Standard_Transient (handle-managed). The concrete instantiation
    derives from T's bound class, so T's API is available."""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theOther: _T) -> None: ...
    def GetRefCount(self) -> int: ...
    def DynamicType(self) -> OCP3x.Standard.Standard_Type: ...
    def IsInstance(self, theTypeName: str) -> bool: ...
    def IsKind(self, theTypeName: str) -> bool: ...
    @staticmethod
    def get_type_name() -> str: ...
    @staticmethod
    def get_type_descriptor() -> OCP3x.Standard.Standard_Type: ...
