class NCollection_HSequence(NCollection_Sequence[_T]):
    """NCollection_HSequence<T>: handle-managed (Standard_Transient) NCollection_Sequence<T>."""
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_Sequence[_T]) -> None: ...
    def Sequence(self) -> NCollection_Sequence[_T]: ...
    def ChangeSequence(self) -> Self: ...
    def GetRefCount(self) -> int: ...
    def DynamicType(self) -> nanocct.Standard.Standard_Type: ...
    def IsInstance(self, theTypeName: str) -> bool: ...
    def IsKind(self, theTypeName: str) -> bool: ...
    @staticmethod
    def get_type_name() -> str: ...
    @staticmethod
    def get_type_descriptor() -> nanocct.Standard.Standard_Type: ...
