class NCollection_IndexedDataMap(Generic[_K, _V, _H]):
    """NCollection_IndexedDataMap<Key, Item>: hashed map with a stable 1-based index (OCCT)."""
    class Iterator(Generic[_IK, _IV, _IH]):
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, theMap: NCollection_IndexedDataMap[_IK, _IV, _IH]) -> None: ...
        def More(self) -> bool: ...
        def Next(self) -> None: ...
        def Value(self) -> _IV: ...
        def __iter__(self) -> Self: ...
        def __next__(self) -> _IV: ...
        def ChangeValue(self) -> _IV: ...
        def Key(self) -> _IK: ...
        def Index(self) -> int: ...
        def IsEqual(self, theOther: NCollection_IndexedDataMap.Iterator[_IK, _IV, _IH]) -> bool: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theNbBuckets: int, theAllocator: nanocct.NCollection.NCollection_BaseAllocator | None = None) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_IndexedDataMap[_K, _V, _H]) -> None: ...
    def NbBuckets(self) -> int: ...
    def Extent(self) -> int: ...
    def Length(self) -> int: ...
    def Size(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Allocator(self) -> nanocct.NCollection.NCollection_BaseAllocator: ...
    def Exchange(self, theOther: NCollection_IndexedDataMap[_K, _V, _H]) -> None: ...
    def Assign(self, theOther: NCollection_IndexedDataMap[_K, _V, _H]) -> Self: ...
    def ReSize(self, N: int) -> None: ...
    @overload
    def Clear(self, doReleaseMemory: bool = True) -> None: ...
    @overload
    def Clear(self, theAllocator: nanocct.NCollection.NCollection_BaseAllocator | None) -> None: ...
    def Add(self, theKey: _K, theItem: _V) -> int: ...
    def TryBound(self, theKey: _K, theItem: _V) -> _V: ...
    def TryBind(self, theKey: _K, theItem: _V) -> bool: ...
    def Bind(self, theKey: _K, theItem: _V) -> bool: ...
    def Bound(self, theKey: _K, theItem: _V) -> _V: ...
    def Contains(self, theKey: _K) -> bool: ...
    def Substitute(self, theIndex: int, theKey: _K, theItem: _V) -> None: ...
    def Swap(self, theIndex1: int, theIndex2: int) -> None: ...
    def RemoveLast(self) -> None: ...
    def RemoveFromIndex(self, theIndex: int) -> None: ...
    def RemoveKey(self, theKey: _K) -> None: ...
    def FindKey(self, theIndex: int) -> _K: ...
    def FindFromIndex(self, theIndex: int) -> _V: ...
    def ChangeFromIndex(self, theIndex: int) -> _V: ...
    def FindIndex(self, theKey: _K) -> int: ...
    @overload
    def FindFromKey(self, theKey: _K) -> _V: ...
    @overload
    def FindFromKey(self, theKey: _K, theValue: _V) -> bool: ...
    def ChangeFromKey(self, theKey: _K) -> _V: ...
    def Seek(self, theKey: _K) -> _V | None: ...
    def ChangeSeek(self, theKey: _K) -> _V | None: ...
    def __call__(self, theIndex: int) -> _V: ...
    def __contains__(self, theKey: _K) -> bool: ...
    def __getitem__(self, theIndex: int) -> _V: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> collections.abc.Iterator[_K]: ...
    def items(self) -> list[tuple[_K, _V]]: ...
