class NCollection_List(Generic[_T]):
    """NCollection_List<T>: singly linked list (OCCT). NCollection_List[T] returns the bound instantiation."""
    class Iterator(Generic[_IT]):
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, theList: NCollection_List[_IT]) -> None: ...
        def Initialize(self, theList: NCollection_List[_IT]) -> None: ...
        def More(self) -> bool: ...
        def Next(self) -> None: ...
        def Value(self) -> _IT: ...
        def __iter__(self) -> Self: ...
        def __next__(self) -> _IT: ...
        def ChangeValue(self) -> _IT: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theAllocator: nanocct.NCollection.NCollection_BaseAllocator | None) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_List[_T]) -> None: ...
    def Extent(self) -> int: ...
    def Length(self) -> int: ...
    def Size(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Allocator(self) -> nanocct.NCollection.NCollection_BaseAllocator: ...
    def Assign(self, theOther: NCollection_List[_T]) -> Self: ...
    def Clear(self, theAllocator: nanocct.NCollection.NCollection_BaseAllocator | None = None) -> None: ...
    def First(self) -> _T: ...
    def Last(self) -> _T: ...
    @overload
    def Append(self, theItem: _T) -> _T: ...
    @overload
    def Append(self, theItem: _T, theIter: NCollection_List.Iterator[_T]) -> None: ...
    @overload
    def Append(self, theOther: NCollection_List[_T]) -> None: ...
    @overload
    def Prepend(self, theItem: _T) -> _T: ...
    @overload
    def Prepend(self, theOther: NCollection_List[_T]) -> None: ...
    def RemoveFirst(self) -> None: ...
    @overload
    def Remove(self, theIter: NCollection_List.Iterator[_T]) -> None: ...
    @overload
    def Remove(self, theObject: _T) -> bool: ...
    @overload
    def InsertBefore(self, theItem: _T, theIter: NCollection_List.Iterator[_T]) -> _T: ...
    @overload
    def InsertBefore(self, theOther: NCollection_List[_T], theIter: NCollection_List.Iterator[_T]) -> None: ...
    @overload
    def InsertAfter(self, theItem: _T, theIter: NCollection_List.Iterator[_T]) -> _T: ...
    @overload
    def InsertAfter(self, theOther: NCollection_List[_T], theIter: NCollection_List.Iterator[_T]) -> None: ...
    def Reverse(self) -> None: ...
    def Exchange(self, theOther: NCollection_List[_T]) -> None: ...
    def Contains(self, theObject: _T) -> bool: ...
    def __contains__(self, theObject: _T) -> bool: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_T]: ...
