class NCollection_HArray2(NCollection_Array2[_T]):
    """NCollection_HArray2<T>: handle-managed (Standard_Transient) NCollection_Array2<T>."""
    @overload
    def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int) -> None: ...
    @overload
    def __init__(self, theRowLow: int, theRowUpp: int, theColLow: int, theColUpp: int, theValue: _T) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_Array2[_T]) -> None: ...
    def Array2(self) -> NCollection_Array2[_T]: ...
    def ChangeArray2(self) -> Self: ...
    def GetRefCount(self) -> int: ...
    def DynamicType(self) -> nanocct.Standard.Standard_Type: ...
    def IsInstance(self, theTypeName: str) -> bool: ...
    def IsKind(self, theTypeName: str) -> bool: ...
    @staticmethod
    def get_type_name() -> str: ...
    @staticmethod
    def get_type_descriptor() -> nanocct.Standard.Standard_Type: ...
