class NCollection_IndexedMap(Generic[_K]):
    """NCollection_IndexedMap<Key>: hashed set of keys with a stable 1-based index (OCCT)."""
    class Iterator(Generic[_IK]):
        @overload
        def __init__(self) -> None: ...
        @overload
        def __init__(self, theMap: NCollection_IndexedMap[_IK]) -> None: ...
        def More(self) -> bool: ...
        def Next(self) -> None: ...
        def Value(self) -> _IK: ...
        def __iter__(self) -> Self: ...
        def __next__(self) -> _IK: ...
        def Index(self) -> int: ...
        def IsEqual(self, theOther: NCollection_IndexedMap.Iterator[_IK]) -> bool: ...
    @overload
    def __init__(self) -> None: ...
    @overload
    def __init__(self, theNbBuckets: int, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None = None) -> None: ...
    @overload
    def __init__(self, theOther: NCollection_IndexedMap[_K]) -> None: ...
    def NbBuckets(self) -> int: ...
    def Extent(self) -> int: ...
    def Length(self) -> int: ...
    def Size(self) -> int: ...
    def IsEmpty(self) -> bool: ...
    def Allocator(self) -> nanoocp.NCollection.NCollection_BaseAllocator: ...
    def Exchange(self, theOther: NCollection_IndexedMap[_K]) -> None: ...
    def Assign(self, theOther: NCollection_IndexedMap[_K]) -> Self: ...
    def ReSize(self, N: int) -> None: ...
    @overload
    def Clear(self, doReleaseMemory: bool = True) -> None: ...
    @overload
    def Clear(self, theAllocator: nanoocp.NCollection.NCollection_BaseAllocator | None) -> None: ...
    def Add(self, theKey: _K) -> int: ...
    def Added(self, theKey: _K) -> _K: ...
    def Contains(self, theKey: _K) -> bool: ...
    def Substitute(self, theIndex: int, theKey: _K) -> None: ...
    def Swap(self, theIndex1: int, theIndex2: int) -> None: ...
    def RemoveLast(self) -> None: ...
    def RemoveFromIndex(self, theIndex: int) -> None: ...
    def RemoveKey(self, theKey: _K) -> bool: ...
    def FindKey(self, theIndex: int) -> _K: ...
    def FindIndex(self, theKey: _K) -> int: ...
    def __call__(self, theIndex: int) -> _K: ...
    def __contains__(self, theKey: _K) -> bool: ...
    def __getitem__(self, theIndex: int) -> _K: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_K]: ...
