// Generated by the nanoOCP generator from OCCT package BinDrivers (toolkit TKBin). Do not edit.
#include "nanoocp_common.h"
#include <BinDrivers.hxx>
#include <BinDrivers_DocumentRetrievalDriver.hxx>
#include <BinDrivers_DocumentStorageDriver.hxx>
#include <BinDrivers_Marker.hxx>
#include <BinLDrivers_DocumentRetrievalDriver.hxx>
#include <BinLDrivers_DocumentSection.hxx>
#include <BinLDrivers_DocumentStorageDriver.hxx>
#include <BinMDF_ADriverTable.hxx>
#include <Message_Messenger.hxx>
#include <Message_ProgressRange.hxx>
#include <Standard_GUID.hxx>
#include <Standard_IStream.hxx>
#include <Standard_OStream.hxx>
#include <Standard_Transient.hxx>
#include <Standard_Type.hxx>
#include <Storage_Position.hxx>
#include <TDocStd_Application.hxx>
#include <TDocStd_FormatVersion.hxx>

void nanoocp_declare_BinDrivers(nb::module_ &m) {
    nb::enum_<BinDrivers_Marker>(m, "BinDrivers_Marker", nb::is_arithmetic())
        .value("BinDrivers_ENDATTRLIST", BinDrivers_ENDATTRLIST)
        .value("BinDrivers_ENDLABEL", BinDrivers_ENDLABEL)
        .export_values();
    { nb::class_<BinDrivers> cls(m, "BinDrivers");
    }
    { nb::class_<BinDrivers_DocumentRetrievalDriver, BinLDrivers_DocumentRetrievalDriver> cls(m, "BinDrivers_DocumentRetrievalDriver");
    }
    { nb::class_<BinDrivers_DocumentStorageDriver, BinLDrivers_DocumentStorageDriver> cls(m, "BinDrivers_DocumentStorageDriver", R"nbdoc(persistent implementation of storage a document in a binary file)nbdoc");
    }
}

void nanoocp_templates_BinDrivers(nb::module_ &m) {
}

void nanoocp_define_BinDrivers(nb::module_ &m) {
    nanoocp_implicit_default_ctor<BinDrivers>(nb::borrow<nb::class_<BinDrivers>>(m.attr("BinDrivers")));
    nb::borrow<nb::class_<BinDrivers>>(m.attr("BinDrivers"))
        .def_static("Factory", static_cast<const occ::handle<Standard_Transient> & (*)(const Standard_GUID &)>(&BinDrivers::Factory), nb::arg("theGUID"))
        .def_static("DefineFormat", static_cast<void (*)(const occ::handle<TDocStd_Application> &)>(&BinDrivers::DefineFormat), nb::arg("theApp").none(), R"nbdoc(Defines format "BinOcaf" and registers its read and write drivers
in the specified application)nbdoc")
        .def_static("AttributeDrivers", static_cast<occ::handle<BinMDF_ADriverTable> (*)(const occ::handle<Message_Messenger> &)>(&BinDrivers::AttributeDrivers), nb::arg("MsgDrv").none(), R"nbdoc(Creates the table of drivers of types supported)nbdoc");
    nanoocp_implicit_copy_ctor<BinDrivers>(nb::borrow<nb::class_<BinDrivers>>(m.attr("BinDrivers")));
    nb::borrow<nb::class_<BinDrivers_DocumentRetrievalDriver>>(m.attr("BinDrivers_DocumentRetrievalDriver"))
        .def(nb::new_([]() { return opencascade::handle<BinDrivers_DocumentRetrievalDriver>(new BinDrivers_DocumentRetrievalDriver()); }), R"nbdoc(Constructor)nbdoc")
        .def("AttributeDrivers", static_cast<occ::handle<BinMDF_ADriverTable> (BinDrivers_DocumentRetrievalDriver::*)(const occ::handle<Message_Messenger> &)>(&BinDrivers_DocumentRetrievalDriver::AttributeDrivers), nb::arg("theMsgDriver").none())
        .def("ReadShapeSection", [](BinDrivers_DocumentRetrievalDriver &self, BinLDrivers_DocumentSection & theSection, const nanoocp::BinaryInput &theIS, const bool isMess, const Message_ProgressRange & theRange) { std::stringstream theIS_stream(theIS.data); self.ReadShapeSection(theSection, theIS_stream, isMess, theRange); }, nb::arg("theSection"), nb::arg("theIS"), nb::arg("isMess") = static_cast<std::decay_t<const bool>>(false), nb::arg("theRange") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()))
        .def("CheckShapeSection", [](BinDrivers_DocumentRetrievalDriver &self, const Storage_Position & thePos, const nanoocp::BinaryInput &theIS) { std::stringstream theIS_stream(theIS.data); self.CheckShapeSection(thePos, theIS_stream); }, nb::arg("thePos"), nb::arg("theIS"))
        .def("Clear", static_cast<void (BinDrivers_DocumentRetrievalDriver::*)()>(&BinDrivers_DocumentRetrievalDriver::Clear), R"nbdoc(Clears the NamedShape driver)nbdoc")
        .def("EnableQuickPartReading", static_cast<void (BinDrivers_DocumentRetrievalDriver::*)(const occ::handle<Message_Messenger> &, bool)>(&BinDrivers_DocumentRetrievalDriver::EnableQuickPartReading), nb::arg("theMessageDriver").none(), nb::arg("theValue"), R"nbdoc(Enables reading in the quick part access mode.)nbdoc")
        .def_static("get_type_name", static_cast<const char * (*)()>(&BinDrivers_DocumentRetrievalDriver::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&BinDrivers_DocumentRetrievalDriver::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (BinDrivers_DocumentRetrievalDriver::*)() const>(&BinDrivers_DocumentRetrievalDriver::DynamicType));
    nanoocp_implicit_copy_ctor<BinDrivers_DocumentRetrievalDriver>(nb::borrow<nb::class_<BinDrivers_DocumentRetrievalDriver>>(m.attr("BinDrivers_DocumentRetrievalDriver")));
    nb::borrow<nb::class_<BinDrivers_DocumentStorageDriver>>(m.attr("BinDrivers_DocumentStorageDriver"))
        .def(nb::new_([]() { return opencascade::handle<BinDrivers_DocumentStorageDriver>(new BinDrivers_DocumentStorageDriver()); }), R"nbdoc(Constructor)nbdoc")
        .def("AttributeDrivers", static_cast<occ::handle<BinMDF_ADriverTable> (BinDrivers_DocumentStorageDriver::*)(const occ::handle<Message_Messenger> &)>(&BinDrivers_DocumentStorageDriver::AttributeDrivers), nb::arg("theMsgDriver").none())
        .def("WriteShapeSection", [](BinDrivers_DocumentStorageDriver &self, BinLDrivers_DocumentSection & theDocSection, const TDocStd_FormatVersion theDocVer, const Message_ProgressRange & theRange) { std::ostringstream theOS_stream; self.WriteShapeSection(theDocSection, theOS_stream, theDocVer, theRange); return nanoocp_stream_bytes(theOS_stream); }, nb::arg("theDocSection"), nb::arg("theDocVer"), nb::arg("theRange") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()), R"nbdoc(implements the procedure of writing a shape section to file)nbdoc")
        .def("IsWithTriangles", static_cast<bool (BinDrivers_DocumentStorageDriver::*)() const>(&BinDrivers_DocumentStorageDriver::IsWithTriangles), R"nbdoc(Return true if shape should be stored with triangles.)nbdoc")
        .def("IsWithNormals", static_cast<bool (BinDrivers_DocumentStorageDriver::*)() const>(&BinDrivers_DocumentStorageDriver::IsWithNormals), R"nbdoc(Return true if shape should be stored with triangulation normals.)nbdoc")
        .def("SetWithTriangles", static_cast<void (BinDrivers_DocumentStorageDriver::*)(const occ::handle<Message_Messenger> &, const bool)>(&BinDrivers_DocumentStorageDriver::SetWithTriangles), nb::arg("theMessageDriver").none(), nb::arg("theWithTriangulation"), R"nbdoc(Set if triangulation should be stored or not.)nbdoc")
        .def("SetWithNormals", static_cast<void (BinDrivers_DocumentStorageDriver::*)(const occ::handle<Message_Messenger> &, const bool)>(&BinDrivers_DocumentStorageDriver::SetWithNormals), nb::arg("theMessageDriver").none(), nb::arg("theWithTriangulation"), R"nbdoc(Set if triangulation should be stored with normals or not.)nbdoc")
        .def("EnableQuickPartWriting", static_cast<void (BinDrivers_DocumentStorageDriver::*)(const occ::handle<Message_Messenger> &, const bool)>(&BinDrivers_DocumentStorageDriver::EnableQuickPartWriting), nb::arg("theMessageDriver").none(), nb::arg("theValue"), R"nbdoc(Enables writing in the quick part access mode.)nbdoc")
        .def("Clear", static_cast<void (BinDrivers_DocumentStorageDriver::*)()>(&BinDrivers_DocumentStorageDriver::Clear), R"nbdoc(Clears the NamedShape driver)nbdoc")
        .def_static("get_type_name", static_cast<const char * (*)()>(&BinDrivers_DocumentStorageDriver::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&BinDrivers_DocumentStorageDriver::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (BinDrivers_DocumentStorageDriver::*)() const>(&BinDrivers_DocumentStorageDriver::DynamicType));
    nanoocp_implicit_copy_ctor<BinDrivers_DocumentStorageDriver>(nb::borrow<nb::class_<BinDrivers_DocumentStorageDriver>>(m.attr("BinDrivers_DocumentStorageDriver")));
}

void nanoocp_conversions_BinDrivers(nb::module_ &m) {
}
