// Generated by the nanoOCP generator from OCCT package HeaderSection (toolkit TKDESTEP). Do not edit.
#include "nanoocp_common.h"
#include <HeaderSection.hxx>
#include <HeaderSection_FileDescription.hxx>
#include <HeaderSection_FileName.hxx>
#include <HeaderSection_FileSchema.hxx>
#include <HeaderSection_Protocol.hxx>
#include <Interface_InterfaceModel.hxx>
#include <NCollection_HArray1.hxx>
#include <Standard_Transient.hxx>
#include <Standard_Type.hxx>
#include <StepData_Protocol.hxx>
#include <TCollection_HAsciiString.hxx>

void nanoocp_declare_HeaderSection(nb::module_ &m) {
    { nb::class_<HeaderSection> cls(m, "HeaderSection");
    }
    { nb::class_<HeaderSection_FileDescription, Standard_Transient> cls(m, "HeaderSection_FileDescription");
    }
    { nb::class_<HeaderSection_FileName, Standard_Transient> cls(m, "HeaderSection_FileName");
    }
    { nb::class_<HeaderSection_FileSchema, Standard_Transient> cls(m, "HeaderSection_FileSchema");
    }
    { nb::class_<HeaderSection_Protocol, StepData_Protocol> cls(m, "HeaderSection_Protocol", R"nbdoc(Protocol for HeaderSection Entities
It requires HeaderSection as a Resource)nbdoc");
    }
}

void nanoocp_templates_HeaderSection(nb::module_ &m) {
}

void nanoocp_define_HeaderSection(nb::module_ &m) {
    nanoocp_implicit_default_ctor<HeaderSection>(nb::borrow<nb::class_<HeaderSection>>(m.attr("HeaderSection")));
    nb::borrow<nb::class_<HeaderSection>>(m.attr("HeaderSection"))
        .def_static("Protocol", static_cast<occ::handle<HeaderSection_Protocol> (*)()>(&HeaderSection::Protocol), R"nbdoc(creates a Protocol)nbdoc");
    nanoocp_implicit_copy_ctor<HeaderSection>(nb::borrow<nb::class_<HeaderSection>>(m.attr("HeaderSection")));
    nb::borrow<nb::class_<HeaderSection_FileDescription>>(m.attr("HeaderSection_FileDescription"))
        .def(nb::new_([]() { return opencascade::handle<HeaderSection_FileDescription>(new HeaderSection_FileDescription()); }), R"nbdoc(Returns a FileDescription)nbdoc")
        .def("Init", static_cast<void (HeaderSection_FileDescription::*)(const occ::handle<NCollection_HArray1<opencascade::handle<TCollection_HAsciiString>>> &, const occ::handle<TCollection_HAsciiString> &)>(&HeaderSection_FileDescription::Init), nb::arg("aDescription").none(), nb::arg("aImplementationLevel").none())
        .def("SetDescription", static_cast<void (HeaderSection_FileDescription::*)(const occ::handle<NCollection_HArray1<opencascade::handle<TCollection_HAsciiString>>> &)>(&HeaderSection_FileDescription::SetDescription), nb::arg("aDescription").none())
        .def("Description", static_cast<occ::handle<NCollection_HArray1<opencascade::handle<TCollection_HAsciiString>>> (HeaderSection_FileDescription::*)() const>(&HeaderSection_FileDescription::Description))
        .def("DescriptionValue", static_cast<occ::handle<TCollection_HAsciiString> (HeaderSection_FileDescription::*)(const int) const>(&HeaderSection_FileDescription::DescriptionValue), nb::arg("num"))
        .def("NbDescription", static_cast<int (HeaderSection_FileDescription::*)() const>(&HeaderSection_FileDescription::NbDescription))
        .def("SetImplementationLevel", static_cast<void (HeaderSection_FileDescription::*)(const occ::handle<TCollection_HAsciiString> &)>(&HeaderSection_FileDescription::SetImplementationLevel), nb::arg("aImplementationLevel").none())
        .def("ImplementationLevel", static_cast<occ::handle<TCollection_HAsciiString> (HeaderSection_FileDescription::*)() const>(&HeaderSection_FileDescription::ImplementationLevel))
        .def_static("get_type_name", static_cast<const char * (*)()>(&HeaderSection_FileDescription::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&HeaderSection_FileDescription::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (HeaderSection_FileDescription::*)() const>(&HeaderSection_FileDescription::DynamicType));
    nanoocp_implicit_copy_ctor<HeaderSection_FileDescription>(nb::borrow<nb::class_<HeaderSection_FileDescription>>(m.attr("HeaderSection_FileDescription")));
    nb::borrow<nb::class_<HeaderSection_FileName>>(m.attr("HeaderSection_FileName"))
        .def(nb::new_([]() { return opencascade::handle<HeaderSection_FileName>(new HeaderSection_FileName()); }), R"nbdoc(Returns a FileName)nbdoc")
        .def("Init", static_cast<void (HeaderSection_FileName::*)(const occ::handle<TCollection_HAsciiString> &, const occ::handle<TCollection_HAsciiString> &, const occ::handle<NCollection_HArray1<opencascade::handle<TCollection_HAsciiString>>> &, const occ::handle<NCollection_HArray1<opencascade::handle<TCollection_HAsciiString>>> &, const occ::handle<TCollection_HAsciiString> &, const occ::handle<TCollection_HAsciiString> &, const occ::handle<TCollection_HAsciiString> &)>(&HeaderSection_FileName::Init), nb::arg("aName").none(), nb::arg("aTimeStamp").none(), nb::arg("aAuthor").none(), nb::arg("aOrganization").none(), nb::arg("aPreprocessorVersion").none(), nb::arg("aOriginatingSystem").none(), nb::arg("aAuthorisation").none())
        .def("SetName", static_cast<void (HeaderSection_FileName::*)(const occ::handle<TCollection_HAsciiString> &)>(&HeaderSection_FileName::SetName), nb::arg("aName").none())
        .def("Name", static_cast<occ::handle<TCollection_HAsciiString> (HeaderSection_FileName::*)() const>(&HeaderSection_FileName::Name))
        .def("SetTimeStamp", static_cast<void (HeaderSection_FileName::*)(const occ::handle<TCollection_HAsciiString> &)>(&HeaderSection_FileName::SetTimeStamp), nb::arg("aTimeStamp").none())
        .def("TimeStamp", static_cast<occ::handle<TCollection_HAsciiString> (HeaderSection_FileName::*)() const>(&HeaderSection_FileName::TimeStamp))
        .def("SetAuthor", static_cast<void (HeaderSection_FileName::*)(const occ::handle<NCollection_HArray1<opencascade::handle<TCollection_HAsciiString>>> &)>(&HeaderSection_FileName::SetAuthor), nb::arg("aAuthor").none())
        .def("Author", static_cast<occ::handle<NCollection_HArray1<opencascade::handle<TCollection_HAsciiString>>> (HeaderSection_FileName::*)() const>(&HeaderSection_FileName::Author))
        .def("AuthorValue", static_cast<occ::handle<TCollection_HAsciiString> (HeaderSection_FileName::*)(const int) const>(&HeaderSection_FileName::AuthorValue), nb::arg("num"))
        .def("NbAuthor", static_cast<int (HeaderSection_FileName::*)() const>(&HeaderSection_FileName::NbAuthor))
        .def("SetOrganization", static_cast<void (HeaderSection_FileName::*)(const occ::handle<NCollection_HArray1<opencascade::handle<TCollection_HAsciiString>>> &)>(&HeaderSection_FileName::SetOrganization), nb::arg("aOrganization").none())
        .def("Organization", static_cast<occ::handle<NCollection_HArray1<opencascade::handle<TCollection_HAsciiString>>> (HeaderSection_FileName::*)() const>(&HeaderSection_FileName::Organization))
        .def("OrganizationValue", static_cast<occ::handle<TCollection_HAsciiString> (HeaderSection_FileName::*)(const int) const>(&HeaderSection_FileName::OrganizationValue), nb::arg("num"))
        .def("NbOrganization", static_cast<int (HeaderSection_FileName::*)() const>(&HeaderSection_FileName::NbOrganization))
        .def("SetPreprocessorVersion", static_cast<void (HeaderSection_FileName::*)(const occ::handle<TCollection_HAsciiString> &)>(&HeaderSection_FileName::SetPreprocessorVersion), nb::arg("aPreprocessorVersion").none())
        .def("PreprocessorVersion", static_cast<occ::handle<TCollection_HAsciiString> (HeaderSection_FileName::*)() const>(&HeaderSection_FileName::PreprocessorVersion))
        .def("SetOriginatingSystem", static_cast<void (HeaderSection_FileName::*)(const occ::handle<TCollection_HAsciiString> &)>(&HeaderSection_FileName::SetOriginatingSystem), nb::arg("aOriginatingSystem").none())
        .def("OriginatingSystem", static_cast<occ::handle<TCollection_HAsciiString> (HeaderSection_FileName::*)() const>(&HeaderSection_FileName::OriginatingSystem))
        .def("SetAuthorisation", static_cast<void (HeaderSection_FileName::*)(const occ::handle<TCollection_HAsciiString> &)>(&HeaderSection_FileName::SetAuthorisation), nb::arg("aAuthorisation").none())
        .def("Authorisation", static_cast<occ::handle<TCollection_HAsciiString> (HeaderSection_FileName::*)() const>(&HeaderSection_FileName::Authorisation))
        .def_static("get_type_name", static_cast<const char * (*)()>(&HeaderSection_FileName::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&HeaderSection_FileName::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (HeaderSection_FileName::*)() const>(&HeaderSection_FileName::DynamicType));
    nanoocp_implicit_copy_ctor<HeaderSection_FileName>(nb::borrow<nb::class_<HeaderSection_FileName>>(m.attr("HeaderSection_FileName")));
    nb::borrow<nb::class_<HeaderSection_FileSchema>>(m.attr("HeaderSection_FileSchema"))
        .def(nb::new_([]() { return opencascade::handle<HeaderSection_FileSchema>(new HeaderSection_FileSchema()); }), R"nbdoc(Returns a FileSchema)nbdoc")
        .def("Init", static_cast<void (HeaderSection_FileSchema::*)(const occ::handle<NCollection_HArray1<opencascade::handle<TCollection_HAsciiString>>> &)>(&HeaderSection_FileSchema::Init), nb::arg("aSchemaIdentifiers").none())
        .def("SetSchemaIdentifiers", static_cast<void (HeaderSection_FileSchema::*)(const occ::handle<NCollection_HArray1<opencascade::handle<TCollection_HAsciiString>>> &)>(&HeaderSection_FileSchema::SetSchemaIdentifiers), nb::arg("aSchemaIdentifiers").none())
        .def("SchemaIdentifiers", static_cast<occ::handle<NCollection_HArray1<opencascade::handle<TCollection_HAsciiString>>> (HeaderSection_FileSchema::*)() const>(&HeaderSection_FileSchema::SchemaIdentifiers))
        .def("SchemaIdentifiersValue", static_cast<occ::handle<TCollection_HAsciiString> (HeaderSection_FileSchema::*)(const int) const>(&HeaderSection_FileSchema::SchemaIdentifiersValue), nb::arg("num"))
        .def("NbSchemaIdentifiers", static_cast<int (HeaderSection_FileSchema::*)() const>(&HeaderSection_FileSchema::NbSchemaIdentifiers))
        .def_static("get_type_name", static_cast<const char * (*)()>(&HeaderSection_FileSchema::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&HeaderSection_FileSchema::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (HeaderSection_FileSchema::*)() const>(&HeaderSection_FileSchema::DynamicType));
    nanoocp_implicit_copy_ctor<HeaderSection_FileSchema>(nb::borrow<nb::class_<HeaderSection_FileSchema>>(m.attr("HeaderSection_FileSchema")));
    nb::borrow<nb::class_<HeaderSection_Protocol>>(m.attr("HeaderSection_Protocol"))
        .def(nb::new_([]() { return opencascade::handle<HeaderSection_Protocol>(new HeaderSection_Protocol()); }))
        .def("TypeNumber", static_cast<int (HeaderSection_Protocol::*)(const occ::handle<Standard_Type> &) const>(&HeaderSection_Protocol::TypeNumber), nb::arg("atype").none(), R"nbdoc(Returns a Case Number for each of the HeaderSection Entities)nbdoc")
        .def("SchemaName", static_cast<const char * (HeaderSection_Protocol::*)(const occ::handle<Interface_InterfaceModel> &) const>(&HeaderSection_Protocol::SchemaName), nb::arg("arg0").none())
        .def_static("get_type_name", static_cast<const char * (*)()>(&HeaderSection_Protocol::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&HeaderSection_Protocol::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (HeaderSection_Protocol::*)() const>(&HeaderSection_Protocol::DynamicType));
    nanoocp_implicit_copy_ctor<HeaderSection_Protocol>(nb::borrow<nb::class_<HeaderSection_Protocol>>(m.attr("HeaderSection_Protocol")));
}

void nanoocp_conversions_HeaderSection(nb::module_ &m) {
}
