// Generated by the nanoOCP generator from OCCT package STEPControl (toolkit TKDESTEP). Do not edit.
#include "nanoocp_common.h"
#include <STEPControl_ActorRead.hxx>
#include <STEPControl_ActorWrite.hxx>
#include <STEPControl_Controller.hxx>
#include <STEPControl_Reader.hxx>
#include <STEPControl_StepModelType.hxx>
#include <STEPControl_Writer.hxx>
#include <DESTEP_Parameters.hxx>
#include <DE_ShapeFixParameters.hxx>
#include <IFSelect_ReturnStatus.hxx>
#include <Interface_InterfaceModel.hxx>
#include <Message_ProgressRange.hxx>
#include <NCollection_DataMap.hxx>
#include <NCollection_HSequence.hxx>
#include <NCollection_Sequence.hxx>
#include <Standard_Transient.hxx>
#include <Standard_Type.hxx>
#include <StepData_Factors.hxx>
#include <StepData_StepModel.hxx>
#include <StepGeom_Axis2Placement3d.hxx>
#include <StepGeom_GeometricRepresentationItem.hxx>
#include <StepRepr_Representation.hxx>
#include <StepRepr_RepresentationRelationship.hxx>
#include <StepShape_ShapeDefinitionRepresentation.hxx>
#include <TCollection_AsciiString.hxx>
#include <TopoDS_Shape.hxx>
#include <Transfer_ActorOfFinderProcess.hxx>
#include <Transfer_ActorOfTransientProcess.hxx>
#include <Transfer_Binder.hxx>
#include <Transfer_Finder.hxx>
#include <Transfer_FinderProcess.hxx>
#include <Transfer_TransientProcess.hxx>
#include <XSControl_Controller.hxx>
#include <XSControl_Reader.hxx>
#include <XSControl_WorkSession.hxx>
#include <gp_Trsf.hxx>

void nanoocp_declare_STEPControl(nb::module_ &m) {
    nb::enum_<STEPControl_StepModelType>(m, "STEPControl_StepModelType", R"nbdoc(Gives you the choice of translation mode for an Open
CASCADE shape that is being translated to STEP.
- STEPControl_AsIs translates an Open CASCADE shape to its
highest possible STEP representation.
- STEPControl_ManifoldSolidBrep translates an Open CASCADE shape
to a STEP manifold_solid_brep or brep_with_voids entity.
- STEPControl_FacetedBrep translates an Open CASCADE shape
into a STEP faceted_brep entity.
-  STEPControl_ShellBasedSurfaceModel translates an Open CASCADE shape
into a STEP shell_based_surface_model entity.
- STEPControl_GeometricCurveSet
translates an Open CASCADE shape into a STEP geometric_curve_set entity.)nbdoc", nb::is_arithmetic())
        .value("STEPControl_AsIs", STEPControl_AsIs)
        .value("STEPControl_ManifoldSolidBrep", STEPControl_ManifoldSolidBrep)
        .value("STEPControl_BrepWithVoids", STEPControl_BrepWithVoids)
        .value("STEPControl_FacetedBrep", STEPControl_FacetedBrep)
        .value("STEPControl_FacetedBrepAndBrepWithVoids", STEPControl_FacetedBrepAndBrepWithVoids)
        .value("STEPControl_ShellBasedSurfaceModel", STEPControl_ShellBasedSurfaceModel)
        .value("STEPControl_GeometricCurveSet", STEPControl_GeometricCurveSet)
        .value("STEPControl_Hybrid", STEPControl_Hybrid)
        .export_values();
    { nb::class_<STEPControl_ActorRead, Transfer_ActorOfTransientProcess> cls(m, "STEPControl_ActorRead", R"nbdoc(This class performs the transfer of an Entity from
AP214 and AP203, either Geometric or Topologic.

I.E. for each type of Entity, it invokes the appropriate Tool
then returns the Binder which contains the Result)nbdoc");
    }
    { nb::class_<STEPControl_ActorWrite, Transfer_ActorOfFinderProcess> cls(m, "STEPControl_ActorWrite", R"nbdoc(This class performs the transfer of a Shape from TopoDS
to AP203 or AP214 (CD2 or DIS))nbdoc");
    }
    { nb::class_<STEPControl_Controller, XSControl_Controller> cls(m, "STEPControl_Controller", R"nbdoc(defines basic controller for STEP processor)nbdoc");
    }
    { nb::class_<STEPControl_Reader, XSControl_Reader> cls(m, "STEPControl_Reader", R"nbdoc(Reads STEP files, checks them and translates their contents
into Open CASCADE models. The STEP data can be that of
a whole model or that of a specific list of entities in the model.
As in XSControl_Reader, you specify the list using a selection.
For the translation of iges files it is possible to use next sequence:
To change translation parameters
class Interface_Static should be used before beginning of
translation (see STEP Parameters and General Parameters)
Creation of reader - STEPControl_Reader reader;
To load s file in a model use method reader.ReadFile("filename.stp")
To print load results reader.PrintCheckLoad(failsonly,mode)
where mode is equal to the value of enumeration IFSelect_PrintCount
For definition number of candidates :
int nbroots = reader. NbRootsForTransfer();
To transfer entities from a model the following methods can be used:
for the whole model - reader.TransferRoots();
to transfer a list of entities: reader.TransferList(list);
to transfer one entity occ::handle<Standard_Transient>
ent = reader.RootForTransfer(num);
reader.TransferEntity(ent), or
reader.TransferOneRoot(num), or
reader.TransferOne(num), or
reader.TransferRoot(num)
To obtain the result the following method can be used:
reader.NbShapes() and reader.Shape(num); or reader.OneShape();
To print the results of transfer use method:
reader.PrintCheckTransfer(failwarn,mode);
where printfail is equal to the value of enumeration
IFSelect_PrintFail, mode see above; or reader.PrintStatsTransfer();
Gets correspondence between a STEP entity and a result
shape obtained from it.
occ::handle<XSControl_WorkSession>
WS = reader.WS();
if ( WS->TransferReader()->HasResult(ent) )
TopoDS_Shape shape = WS->TransferReader()->ShapeResult(ent);)nbdoc");
    }
    { nb::class_<STEPControl_Writer> cls(m, "STEPControl_Writer", R"nbdoc(This class creates and writes
STEP files from Open CASCADE models. A STEP file can be
written to an existing STEP file or to a new one.
Translation can be performed in one or several operations. Each
translation operation outputs a distinct root entity in the STEP file.)nbdoc");
    }
}

void nanoocp_templates_STEPControl(nb::module_ &m) {
}

void nanoocp_define_STEPControl(nb::module_ &m) {
    nb::borrow<nb::class_<STEPControl_ActorRead>>(m.attr("STEPControl_ActorRead"))
        .def(nb::new_([](const occ::handle<Interface_InterfaceModel> & theModel) { return opencascade::handle<STEPControl_ActorRead>(new STEPControl_ActorRead(theModel)); }), nb::arg("theModel").none())
        .def("Recognize", static_cast<bool (STEPControl_ActorRead::*)(const occ::handle<Standard_Transient> &)>(&STEPControl_ActorRead::Recognize), nb::arg("start").none())
        .def("Transfer", static_cast<occ::handle<Transfer_Binder> (STEPControl_ActorRead::*)(const occ::handle<Standard_Transient> &, const occ::handle<Transfer_TransientProcess> &, const Message_ProgressRange &)>(&STEPControl_ActorRead::Transfer), nb::arg("start").none(), nb::arg("TP").none(), nb::arg("theProgress") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()))
        .def("TransferShape", static_cast<occ::handle<Transfer_Binder> (STEPControl_ActorRead::*)(const occ::handle<Standard_Transient> &, const occ::handle<Transfer_TransientProcess> &, const StepData_Factors &, const bool, const bool, const Message_ProgressRange &)>(&STEPControl_ActorRead::TransferShape), nb::arg("start").none(), nb::arg("TP").none(), nb::arg("theLocalFactors") = static_cast<std::decay_t<const StepData_Factors &>>(StepData_Factors()), nb::arg("isManifold") = static_cast<std::decay_t<const bool>>(true), nb::arg("theUseTrsf") = static_cast<std::decay_t<const bool>>(false), nb::arg("theProgress") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()), R"nbdoc(theUseTrsf - special flag for using Axis2Placement from ShapeRepresentation for transform root
shape)nbdoc")
        .def("PrepareUnits", static_cast<void (STEPControl_ActorRead::*)(const occ::handle<StepRepr_Representation> &, const occ::handle<Transfer_TransientProcess> &, StepData_Factors &)>(&STEPControl_ActorRead::PrepareUnits), nb::arg("rep").none(), nb::arg("TP").none(), nb::arg("theLocalFactors"), R"nbdoc(set units and tolerances context by given ShapeRepresentation)nbdoc")
        .def("ResetUnits", static_cast<void (STEPControl_ActorRead::*)(const occ::handle<StepData_StepModel> &, StepData_Factors &)>(&STEPControl_ActorRead::ResetUnits), nb::arg("theModel").none(), nb::arg("theLocalFactors"), R"nbdoc(reset units and tolerances context to default
(mm, radians, read.precision.val, etc.))nbdoc")
        .def("SetModel", static_cast<void (STEPControl_ActorRead::*)(const occ::handle<Interface_InterfaceModel> &)>(&STEPControl_ActorRead::SetModel), nb::arg("theModel").none(), R"nbdoc(Set model)nbdoc")
        .def("ComputeTransformation", static_cast<bool (STEPControl_ActorRead::*)(const occ::handle<StepGeom_Axis2Placement3d> &, const occ::handle<StepGeom_Axis2Placement3d> &, const occ::handle<StepRepr_Representation> &, const occ::handle<StepRepr_Representation> &, const occ::handle<Transfer_TransientProcess> &, gp_Trsf &, const StepData_Factors &)>(&STEPControl_ActorRead::ComputeTransformation), nb::arg("Origin").none(), nb::arg("Target").none(), nb::arg("OrigContext").none(), nb::arg("TargContext").none(), nb::arg("TP").none(), nb::arg("Trsf"), nb::arg("theLocalFactors") = static_cast<std::decay_t<const StepData_Factors &>>(StepData_Factors()), R"nbdoc(Computes transformation defined by two axis placements (in MAPPED_ITEM
or ITEM_DEFINED_TRANSFORMATION) taking into account their
representation contexts (i.e. units, which may be different)
Returns True if transformation is computed and is not an identity.)nbdoc")
        .def("ComputeSRRWT", static_cast<bool (STEPControl_ActorRead::*)(const occ::handle<StepRepr_RepresentationRelationship> &, const occ::handle<Transfer_TransientProcess> &, gp_Trsf &, const StepData_Factors &)>(&STEPControl_ActorRead::ComputeSRRWT), nb::arg("SRR").none(), nb::arg("TP").none(), nb::arg("Trsf"), nb::arg("theLocalFactors") = static_cast<std::decay_t<const StepData_Factors &>>(StepData_Factors()), R"nbdoc(Computes transformation defined by given
REPRESENTATION_RELATIONSHIP_WITH_TRANSFORMATION)nbdoc")
        .def_static("get_type_name", static_cast<const char * (*)()>(&STEPControl_ActorRead::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&STEPControl_ActorRead::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (STEPControl_ActorRead::*)() const>(&STEPControl_ActorRead::DynamicType));
    nanoocp_implicit_copy_ctor<STEPControl_ActorRead>(nb::borrow<nb::class_<STEPControl_ActorRead>>(m.attr("STEPControl_ActorRead")));
    nb::implicitly_convertible<std::decay_t<const occ::handle<Interface_InterfaceModel> &>, STEPControl_ActorRead>();
    nb::borrow<nb::class_<STEPControl_ActorWrite>>(m.attr("STEPControl_ActorWrite"))
        .def(nb::new_([]() { return opencascade::handle<STEPControl_ActorWrite>(new STEPControl_ActorWrite()); }))
        .def("Recognize", static_cast<bool (STEPControl_ActorWrite::*)(const occ::handle<Transfer_Finder> &)>(&STEPControl_ActorWrite::Recognize), nb::arg("start").none())
        .def("Transfer", static_cast<occ::handle<Transfer_Binder> (STEPControl_ActorWrite::*)(const occ::handle<Transfer_Finder> &, const occ::handle<Transfer_FinderProcess> &, const Message_ProgressRange &)>(&STEPControl_ActorWrite::Transfer), nb::arg("start").none(), nb::arg("FP").none(), nb::arg("theProgress") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()))
        .def("TransferSubShape", [](STEPControl_ActorWrite &self, const occ::handle<Transfer_Finder> & start, const occ::handle<StepShape_ShapeDefinitionRepresentation> & SDR, const occ::handle<Transfer_FinderProcess> & FP, const StepData_Factors & theLocalFactors, const occ::handle<NCollection_HSequence<TopoDS_Shape>> & shapeGroup, const bool isManifold, const Message_ProgressRange & theProgress) { occ::handle<StepGeom_GeometricRepresentationItem> AX1{}; auto nanoocp_result = self.TransferSubShape(start, SDR, AX1, FP, theLocalFactors, shapeGroup, isManifold, theProgress); return std::make_tuple(nanoocp_result, AX1); }, nb::arg("start").none(), nb::arg("SDR").none(), nb::arg("FP").none(), nb::arg("theLocalFactors") = static_cast<std::decay_t<const StepData_Factors &>>(StepData_Factors()), nb::arg("shapeGroup").none() = static_cast<std::decay_t<const occ::handle<NCollection_HSequence<TopoDS_Shape>> &>>(nullptr), nb::arg("isManifold") = static_cast<std::decay_t<const bool>>(true), nb::arg("theProgress") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()))
        .def("TransferShape", static_cast<occ::handle<Transfer_Binder> (STEPControl_ActorWrite::*)(const occ::handle<Transfer_Finder> &, const occ::handle<StepShape_ShapeDefinitionRepresentation> &, const occ::handle<Transfer_FinderProcess> &, const StepData_Factors &, const occ::handle<NCollection_HSequence<TopoDS_Shape>> &, const bool, const Message_ProgressRange &)>(&STEPControl_ActorWrite::TransferShape), nb::arg("start").none(), nb::arg("SDR").none(), nb::arg("FP").none(), nb::arg("theLocalFactors") = static_cast<std::decay_t<const StepData_Factors &>>(StepData_Factors()), nb::arg("shapeGroup").none() = static_cast<std::decay_t<const occ::handle<NCollection_HSequence<TopoDS_Shape>> &>>(nullptr), nb::arg("isManifold") = static_cast<std::decay_t<const bool>>(true), nb::arg("theProgress") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()))
        .def("TransferCompound", static_cast<occ::handle<Transfer_Binder> (STEPControl_ActorWrite::*)(const occ::handle<Transfer_Finder> &, const occ::handle<StepShape_ShapeDefinitionRepresentation> &, const occ::handle<Transfer_FinderProcess> &, const StepData_Factors &, const Message_ProgressRange &)>(&STEPControl_ActorWrite::TransferCompound), nb::arg("start").none(), nb::arg("SDR").none(), nb::arg("FP").none(), nb::arg("theLocalFactors") = static_cast<std::decay_t<const StepData_Factors &>>(StepData_Factors()), nb::arg("theProgress") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()))
        .def("SetMode", static_cast<void (STEPControl_ActorWrite::*)(const STEPControl_StepModelType)>(&STEPControl_ActorWrite::SetMode), nb::arg("M"))
        .def("Mode", static_cast<STEPControl_StepModelType (STEPControl_ActorWrite::*)() const>(&STEPControl_ActorWrite::Mode))
        .def("SetGroupMode", static_cast<void (STEPControl_ActorWrite::*)(const int)>(&STEPControl_ActorWrite::SetGroupMode), nb::arg("mode"))
        .def("GroupMode", static_cast<int (STEPControl_ActorWrite::*)() const>(&STEPControl_ActorWrite::GroupMode))
        .def("SetTolerance", static_cast<void (STEPControl_ActorWrite::*)(const double)>(&STEPControl_ActorWrite::SetTolerance), nb::arg("Tol"))
        .def("IsAssembly", static_cast<bool (STEPControl_ActorWrite::*)(const occ::handle<StepData_StepModel> &, TopoDS_Shape &) const>(&STEPControl_ActorWrite::IsAssembly), nb::arg("theModel").none(), nb::arg("S"), R"nbdoc(Customizable method to check whether shape S should
be written as assembly or not
Default implementation uses flag GroupMode and analyses
the shape itself
NOTE: this method can modify shape)nbdoc")
        .def_static("get_type_name", static_cast<const char * (*)()>(&STEPControl_ActorWrite::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&STEPControl_ActorWrite::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (STEPControl_ActorWrite::*)() const>(&STEPControl_ActorWrite::DynamicType));
    nanoocp_implicit_copy_ctor<STEPControl_ActorWrite>(nb::borrow<nb::class_<STEPControl_ActorWrite>>(m.attr("STEPControl_ActorWrite")));
    nb::borrow<nb::class_<STEPControl_Controller>>(m.attr("STEPControl_Controller"))
        .def(nb::new_([]() { return opencascade::handle<STEPControl_Controller>(new STEPControl_Controller()); }), R"nbdoc(Initializes the use of STEP Norm (the first time) and
returns a Controller)nbdoc")
        .def("NewModel", static_cast<occ::handle<Interface_InterfaceModel> (STEPControl_Controller::*)() const>(&STEPControl_Controller::NewModel), R"nbdoc(Creates a new empty Model ready to receive data of the Norm.
It is taken from STEP Template Model)nbdoc")
        .def("ActorRead", static_cast<occ::handle<Transfer_ActorOfTransientProcess> (STEPControl_Controller::*)(const occ::handle<Interface_InterfaceModel> &) const>(&STEPControl_Controller::ActorRead), nb::arg("theModel").none(), R"nbdoc(Returns the Actor for Read attached to the pair (norm,appli))nbdoc")
        .def("Customise", [](STEPControl_Controller &self, occ::handle<XSControl_WorkSession> WS) { self.Customise(WS); return WS; }, nb::arg("WS").none())
        .def("TransferWriteShape", static_cast<IFSelect_ReturnStatus (STEPControl_Controller::*)(const TopoDS_Shape &, const occ::handle<Transfer_FinderProcess> &, const occ::handle<Interface_InterfaceModel> &, const int, const Message_ProgressRange &) const>(&STEPControl_Controller::TransferWriteShape), nb::arg("shape"), nb::arg("FP").none(), nb::arg("model").none(), nb::arg("modetrans") = static_cast<std::decay_t<const int>>(0), nb::arg("theProgress") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()), R"nbdoc(Takes one Shape and transfers it to the InterfaceModel
(already created by NewModel for instance)
<modeshape> is to be interpreted by each kind of XstepAdaptor
Returns a status : 0 OK  1 No result  2 Fail  -1 bad modeshape
-2 bad model (requires a StepModel)
modeshape : 1 Facetted BRep, 2 Shell, 3 Manifold Solid)nbdoc")
        .def_static("Init", static_cast<bool (*)()>(&STEPControl_Controller::Init), R"nbdoc(Standard Initialisation. It creates a Controller for STEP
and records it to various names, available to select it later
Returns True when done, False if could not be done)nbdoc")
        .def_static("get_type_name", static_cast<const char * (*)()>(&STEPControl_Controller::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&STEPControl_Controller::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (STEPControl_Controller::*)() const>(&STEPControl_Controller::DynamicType));
    nanoocp_implicit_copy_ctor<STEPControl_Controller>(nb::borrow<nb::class_<STEPControl_Controller>>(m.attr("STEPControl_Controller")));
    nb::borrow<nb::class_<STEPControl_Reader>>(m.attr("STEPControl_Reader"))
        .def(nb::init<>(), R"nbdoc(Creates a reader object with an empty STEP model.)nbdoc")
        .def(nb::init<const occ::handle<XSControl_WorkSession> &, const bool>(), nb::arg("WS").none(), nb::arg("scratch") = static_cast<std::decay_t<const bool>>(true), R"nbdoc(Creates a Reader for STEP from an already existing Session
Clears the session if it was not yet set for STEP)nbdoc")
        .def("StepModel", static_cast<occ::handle<StepData_StepModel> (STEPControl_Reader::*)() const>(&STEPControl_Reader::StepModel), R"nbdoc(Returns the model as a StepModel.
It can then be consulted (header, product))nbdoc")
        .def("ReadFile", static_cast<IFSelect_ReturnStatus (STEPControl_Reader::*)(const char *const)>(&STEPControl_Reader::ReadFile), nb::arg("filename"), R"nbdoc(Loads a file and returns the read status
Zero for a Model which compies with the Controller)nbdoc")
        .def("ReadStream", [](STEPControl_Reader &self, const char *const theName, const nanoocp::TextInput &theIStream) { std::stringstream theIStream_stream(theIStream.text); auto nanoocp_result = self.ReadStream(theName, theIStream_stream); return nanoocp_result; }, nb::arg("theName"), nb::arg("theIStream"), R"nbdoc(Loads a file from stream and returns the read status)nbdoc")
        .def("ReadFile", static_cast<IFSelect_ReturnStatus (STEPControl_Reader::*)(const char *const, const DESTEP_Parameters &)>(&STEPControl_Reader::ReadFile), nb::arg("filename"), nb::arg("theParams"), R"nbdoc(Loads a file and returns the read status
Zero for a Model which compies with the Controller)nbdoc")
        .def("ReadStream", [](STEPControl_Reader &self, const char *const theName, const DESTEP_Parameters & theParams, const nanoocp::TextInput &theIStream) { std::stringstream theIStream_stream(theIStream.text); auto nanoocp_result = self.ReadStream(theName, theParams, theIStream_stream); return nanoocp_result; }, nb::arg("theName"), nb::arg("theParams"), nb::arg("theIStream"), R"nbdoc(Loads a file from stream and returns the read status)nbdoc")
        .def("TransferRoot", static_cast<bool (STEPControl_Reader::*)(const int, const Message_ProgressRange &)>(&STEPControl_Reader::TransferRoot), nb::arg("num") = static_cast<std::decay_t<const int>>(1), nb::arg("theProgress") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()), R"nbdoc(Transfers a root given its rank in the list of candidate roots
Default is the first one
Returns True if a shape has resulted, false else
Same as inherited TransferOneRoot, kept for compatibility)nbdoc")
        .def("NbRootsForTransfer", static_cast<int (STEPControl_Reader::*)()>(&STEPControl_Reader::NbRootsForTransfer), R"nbdoc(Determines the list of root entities from Model which are candidate for
a transfer to a Shape (type of entities is PRODUCT))nbdoc")
        .def("FileUnits", static_cast<void (STEPControl_Reader::*)(NCollection_Sequence<TCollection_AsciiString> &, NCollection_Sequence<TCollection_AsciiString> &, NCollection_Sequence<TCollection_AsciiString> &)>(&STEPControl_Reader::FileUnits), nb::arg("theUnitLengthNames"), nb::arg("theUnitAngleNames"), nb::arg("theUnitSolidAngleNames"), R"nbdoc(Returns sequence of all unit names for shape representations
found in file)nbdoc")
        .def("SetSystemLengthUnit", static_cast<void (STEPControl_Reader::*)(const double)>(&STEPControl_Reader::SetSystemLengthUnit), nb::arg("theLengthUnit"), R"nbdoc(Sets system length unit used by transfer process.
Performs only if a model is not NULL)nbdoc")
        .def("SystemLengthUnit", static_cast<double (STEPControl_Reader::*)() const>(&STEPControl_Reader::SystemLengthUnit), R"nbdoc(Returns system length unit used by transfer process.
Performs only if a model is not NULL)nbdoc");
    nanoocp_implicit_copy_ctor<STEPControl_Reader>(nb::borrow<nb::class_<STEPControl_Reader>>(m.attr("STEPControl_Reader")));
    nb::implicitly_convertible<std::decay_t<const occ::handle<XSControl_WorkSession> &>, STEPControl_Reader>();
    nb::borrow<nb::class_<STEPControl_Writer>>(m.attr("STEPControl_Writer"))
        .def(nb::init<>(), R"nbdoc(Creates a Writer from scratch)nbdoc")
        .def(nb::init<const occ::handle<XSControl_WorkSession> &, const bool>(), nb::arg("WS").none(), nb::arg("scratch") = static_cast<std::decay_t<const bool>>(true), R"nbdoc(Creates a Writer from an already existing Session
If <scratch> is True (D), clears already recorded data)nbdoc")
        .def("SetTolerance", static_cast<void (STEPControl_Writer::*)(const double)>(&STEPControl_Writer::SetTolerance), nb::arg("Tol"), R"nbdoc(Sets a length-measure value that
will be written to uncertainty-measure-with-unit
when the next shape is translated.)nbdoc")
        .def("UnsetTolerance", static_cast<void (STEPControl_Writer::*)()>(&STEPControl_Writer::UnsetTolerance), R"nbdoc(Unsets the tolerance formerly forced by SetTolerance)nbdoc")
        .def("SetWS", static_cast<void (STEPControl_Writer::*)(const occ::handle<XSControl_WorkSession> &, const bool)>(&STEPControl_Writer::SetWS), nb::arg("WS").none(), nb::arg("scratch") = static_cast<std::decay_t<const bool>>(true), R"nbdoc(Sets a specific session to <me>)nbdoc")
        .def("WS", static_cast<occ::handle<XSControl_WorkSession> (STEPControl_Writer::*)() const>(&STEPControl_Writer::WS), R"nbdoc(Returns the session used in <me>)nbdoc")
        .def("Model", static_cast<occ::handle<StepData_StepModel> (STEPControl_Writer::*)(const bool)>(&STEPControl_Writer::Model), nb::arg("newone") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Returns the produced model. Produces a new one if not yet done
or if <newone> is True
This method allows for instance to edit product or header
data before writing.)nbdoc")
        .def("Transfer", static_cast<IFSelect_ReturnStatus (STEPControl_Writer::*)(const TopoDS_Shape &, const STEPControl_StepModelType, const bool, const Message_ProgressRange &)>(&STEPControl_Writer::Transfer), nb::arg("sh"), nb::arg("mode"), nb::arg("compgraph") = static_cast<std::decay_t<const bool>>(true), nb::arg("theProgress") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()), R"nbdoc(Translates shape sh to a STEP
entity. mode defines the STEP entity type to be output:
- STEPControlStd_AsIs translates a shape to its highest possible
STEP representation.
- STEPControlStd_ManifoldSolidBrep translates a shape to a STEP
manifold_solid_brep or brep_with_voids entity.
- STEPControlStd_FacetedBrep translates a shape into a STEP
faceted_brep entity.
- STEPControlStd_ShellBasedSurfaceModel translates a shape into a STEP
shell_based_surface_model entity.
- STEPControlStd_GeometricCurveSet translates a shape into a STEP
geometric_curve_set entity.)nbdoc")
        .def("Transfer", static_cast<IFSelect_ReturnStatus (STEPControl_Writer::*)(const TopoDS_Shape &, const STEPControl_StepModelType, const DESTEP_Parameters &, const bool, const Message_ProgressRange &)>(&STEPControl_Writer::Transfer), nb::arg("sh"), nb::arg("mode"), nb::arg("theParams"), nb::arg("compgraph") = static_cast<std::decay_t<const bool>>(true), nb::arg("theProgress") = static_cast<std::decay_t<const Message_ProgressRange &>>(Message_ProgressRange()), R"nbdoc(Translates shape sh to a STEP entity)nbdoc")
        .def("Write", static_cast<IFSelect_ReturnStatus (STEPControl_Writer::*)(const char *const)>(&STEPControl_Writer::Write), nb::arg("theFileName"), R"nbdoc(Writes a STEP model in the file identified by filename.)nbdoc")
        .def("WriteStream", [](STEPControl_Writer &self) { std::ostringstream theOStream_stream; auto nanoocp_result = self.WriteStream(theOStream_stream); return std::make_tuple(nanoocp_result, nanoocp_stream_text(theOStream_stream)); }, R"nbdoc(Writes a STEP model in the std::ostream.)nbdoc")
        .def("PrintStatsTransfer", static_cast<void (STEPControl_Writer::*)(const int, const int) const>(&STEPControl_Writer::PrintStatsTransfer), nb::arg("what"), nb::arg("mode") = static_cast<std::decay_t<const int>>(0), R"nbdoc(Displays the statistics for the
last translation. what defines the kind of statistics that are displayed:
- 0 gives general statistics (number of translated roots,
number of warnings, number of fail messages),
- 1 gives root results,
- 2 gives statistics for all checked entities,
- 3 gives the list of translated entities,
- 4 gives warning and fail messages,
- 5 gives fail messages only.
mode is used according to the use of what. If what is 0, mode is
ignored. If what is 1, 2 or 3, mode defines the following:
- 0 lists the numbers of STEP entities in a STEP model,
- 1 gives the number, identifier, type and result type for each
STEP entity and/or its status (fail, warning, etc.),
- 2 gives maximum information for each STEP entity (i.e. checks),
- 3 gives the number of entities by the type of a STEP entity,
- 4 gives the number of of STEP entities per result type and/or status,
- 5 gives the number of pairs (STEP or result type and status),
- 6 gives the number of pairs (STEP or result type and status)
AND the list of entity numbers in the STEP model.)nbdoc")
        .def("CleanDuplicateEntities", static_cast<void (STEPControl_Writer::*)()>(&STEPControl_Writer::CleanDuplicateEntities))
        .def("SetShapeFixParameters", static_cast<void (STEPControl_Writer::*)(const NCollection_DataMap<TCollection_AsciiString, TCollection_AsciiString> &)>(&STEPControl_Writer::SetShapeFixParameters), nb::arg("theParameters"), R"nbdoc(Sets parameters for shape processing.
@param theParameters the parameters for shape processing.)nbdoc")
        .def("SetShapeFixParameters", static_cast<void (STEPControl_Writer::*)(const DE_ShapeFixParameters &)>(&STEPControl_Writer::SetShapeFixParameters), nb::arg("theParameters"), R"nbdoc(Sets parameters for shape processing.
Parameters from @p theParameters are converted and stored in the internal map.
@param theParameters the parameters for shape processing.)nbdoc")
        .def("SetShapeFixParameters", static_cast<void (STEPControl_Writer::*)(const DE_ShapeFixParameters &, const NCollection_DataMap<TCollection_AsciiString, TCollection_AsciiString> &)>(&STEPControl_Writer::SetShapeFixParameters), nb::arg("theParameters"), nb::arg("theAdditionalParameters"), R"nbdoc(Sets parameters for shape processing.
Parameters from @p theParameters are copied to the internal map.
Parameters from @p theAdditionalParameters are copied to the internal map
if they are not present in @p theParameters.
@param theParameters the parameters for shape processing.
@param theAdditionalParameters the additional parameters for shape processing.)nbdoc")
        .def("GetShapeFixParameters", static_cast<const NCollection_DataMap<TCollection_AsciiString, TCollection_AsciiString> & (STEPControl_Writer::*)() const>(&STEPControl_Writer::GetShapeFixParameters), R"nbdoc(Returns parameters for shape processing that was set by SetParameters() method.
@return the parameters for shape processing. Empty map if no parameters were set.)nbdoc")
        .def("SetShapeProcessFlags", static_cast<void (STEPControl_Writer::*)(const std::bitset<18> &)>(&STEPControl_Writer::SetShapeProcessFlags), nb::arg("theFlags"), R"nbdoc(Sets flags defining operations to be performed on shapes.
@param theFlags The flags defining operations to be performed on shapes.)nbdoc")
        .def("GetShapeProcessFlags", static_cast<const std::pair<std::bitset<18>, bool> & (STEPControl_Writer::*)() const>(&STEPControl_Writer::GetShapeProcessFlags), R"nbdoc(Returns flags defining operations to be performed on shapes.
@return Pair of values defining operations to be performed on shapes and a boolean value
that indicates whether the flags were set.)nbdoc");
    nanoocp_implicit_copy_ctor<STEPControl_Writer>(nb::borrow<nb::class_<STEPControl_Writer>>(m.attr("STEPControl_Writer")));
    nb::implicitly_convertible<std::decay_t<const occ::handle<XSControl_WorkSession> &>, STEPControl_Writer>();
}

void nanoocp_conversions_STEPControl(nb::module_ &m) {
}
