// Generated by the nanoOCP generator from OCCT package STEPSelections (toolkit TKDESTEP). Do not edit.
#include "nanoocp_common.h"
#include "nanoocp_ncollection.h"
#include <STEPSelections_AssemblyComponent.hxx>
#include <STEPSelections_AssemblyExplorer.hxx>
#include <STEPSelections_AssemblyLink.hxx>
#include <STEPSelections_Counter.hxx>
#include <STEPSelections_SelectAssembly.hxx>
#include <STEPSelections_SelectDerived.hxx>
#include <STEPSelections_SelectFaces.hxx>
#include <STEPSelections_SelectForTransfer.hxx>
#include <STEPSelections_SelectGSCurves.hxx>
#include <STEPSelections_SelectInstances.hxx>
#include <IFSelect_SelectExplore.hxx>
#include <Interface_EntityIterator.hxx>
#include <Interface_Graph.hxx>
#include <Interface_InterfaceModel.hxx>
#include <NCollection_HSequence.hxx>
#include <Standard_OStream.hxx>
#include <Standard_Transient.hxx>
#include <Standard_Type.hxx>
#include <StepBasic_ProductDefinition.hxx>
#include <StepRepr_NextAssemblyUsageOccurrence.hxx>
#include <StepSelect_StepType.hxx>
#include <StepShape_ShapeDefinitionRepresentation.hxx>
#include <TCollection_AsciiString.hxx>
#include <XSControl_SelectForTransfer.hxx>
#include <XSControl_TransferReader.hxx>

void nanoocp_declare_STEPSelections(nb::module_ &m) {
    { nb::class_<STEPSelections_AssemblyLink, Standard_Transient> cls(m, "STEPSelections_AssemblyLink");
    }
    { nb::class_<STEPSelections_AssemblyComponent, Standard_Transient> cls(m, "STEPSelections_AssemblyComponent");
    }
    { nb::class_<STEPSelections_AssemblyExplorer> cls(m, "STEPSelections_AssemblyExplorer");
    }
    { nb::class_<STEPSelections_Counter> cls(m, "STEPSelections_Counter");
    }
    { nb::class_<STEPSelections_SelectAssembly, IFSelect_SelectExplore> cls(m, "STEPSelections_SelectAssembly");
    }
    { nb::class_<STEPSelections_SelectDerived, StepSelect_StepType> cls(m, "STEPSelections_SelectDerived");
    }
    { nb::class_<STEPSelections_SelectFaces, IFSelect_SelectExplore> cls(m, "STEPSelections_SelectFaces", R"nbdoc(This selection returns "STEP faces")nbdoc");
    }
    { nb::class_<STEPSelections_SelectForTransfer, XSControl_SelectForTransfer> cls(m, "STEPSelections_SelectForTransfer");
    }
    { nb::class_<STEPSelections_SelectGSCurves, IFSelect_SelectExplore> cls(m, "STEPSelections_SelectGSCurves", R"nbdoc(This selection returns "curves in the geometric_set (except composite curves)")nbdoc");
    }
    { nb::class_<STEPSelections_SelectInstances, IFSelect_SelectExplore> cls(m, "STEPSelections_SelectInstances");
    }
}

void nanoocp_templates_STEPSelections(nb::module_ &m) {
    { nb::module_ home = nb::module_::import_("nanoocp._TKernel.NCollection"); nanoocp::bind_NCollection_Sequence<opencascade::handle<STEPSelections_AssemblyLink>>(home, "NCollection_Sequence__Handle_STEPSelections_AssemblyLink"); }
    { nb::module_ home = nb::module_::import_("nanoocp._TKernel.NCollection"); nanoocp::bind_NCollection_HSequence<opencascade::handle<STEPSelections_AssemblyLink>>(home, "NCollection_HSequence__Handle_STEPSelections_AssemblyLink"); }
}

void nanoocp_define_STEPSelections(nb::module_ &m) {
    nb::borrow<nb::class_<STEPSelections_AssemblyLink>>(m.attr("STEPSelections_AssemblyLink"))
        .def(nb::new_([]() { return opencascade::handle<STEPSelections_AssemblyLink>(new STEPSelections_AssemblyLink()); }))
        .def(nb::new_([](const occ::handle<StepRepr_NextAssemblyUsageOccurrence> & nauo, const occ::handle<Standard_Transient> & item, const occ::handle<STEPSelections_AssemblyComponent> & part) { return opencascade::handle<STEPSelections_AssemblyLink>(new STEPSelections_AssemblyLink(nauo, item, part)); }), nb::arg("nauo").none(), nb::arg("item").none(), nb::arg("part").none())
        .def("GetNAUO", static_cast<occ::handle<StepRepr_NextAssemblyUsageOccurrence> (STEPSelections_AssemblyLink::*)() const>(&STEPSelections_AssemblyLink::GetNAUO))
        .def("GetItem", static_cast<occ::handle<Standard_Transient> (STEPSelections_AssemblyLink::*)() const>(&STEPSelections_AssemblyLink::GetItem))
        .def("GetComponent", static_cast<occ::handle<STEPSelections_AssemblyComponent> (STEPSelections_AssemblyLink::*)() const>(&STEPSelections_AssemblyLink::GetComponent))
        .def("SetNAUO", static_cast<void (STEPSelections_AssemblyLink::*)(const occ::handle<StepRepr_NextAssemblyUsageOccurrence> &)>(&STEPSelections_AssemblyLink::SetNAUO), nb::arg("nauo").none())
        .def("SetItem", static_cast<void (STEPSelections_AssemblyLink::*)(const occ::handle<Standard_Transient> &)>(&STEPSelections_AssemblyLink::SetItem), nb::arg("item").none())
        .def("SetComponent", static_cast<void (STEPSelections_AssemblyLink::*)(const occ::handle<STEPSelections_AssemblyComponent> &)>(&STEPSelections_AssemblyLink::SetComponent), nb::arg("part").none())
        .def_static("get_type_name", static_cast<const char * (*)()>(&STEPSelections_AssemblyLink::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&STEPSelections_AssemblyLink::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (STEPSelections_AssemblyLink::*)() const>(&STEPSelections_AssemblyLink::DynamicType));
    nanoocp_implicit_copy_ctor<STEPSelections_AssemblyLink>(nb::borrow<nb::class_<STEPSelections_AssemblyLink>>(m.attr("STEPSelections_AssemblyLink")));
    nb::borrow<nb::class_<STEPSelections_AssemblyComponent>>(m.attr("STEPSelections_AssemblyComponent"))
        .def(nb::new_([]() { return opencascade::handle<STEPSelections_AssemblyComponent>(new STEPSelections_AssemblyComponent()); }))
        .def(nb::new_([](const occ::handle<StepShape_ShapeDefinitionRepresentation> & sdr, const occ::handle<NCollection_HSequence<opencascade::handle<STEPSelections_AssemblyLink>>> & list) { return opencascade::handle<STEPSelections_AssemblyComponent>(new STEPSelections_AssemblyComponent(sdr, list)); }), nb::arg("sdr").none(), nb::arg("list").none())
        .def("GetSDR", static_cast<occ::handle<StepShape_ShapeDefinitionRepresentation> (STEPSelections_AssemblyComponent::*)() const>(&STEPSelections_AssemblyComponent::GetSDR))
        .def("GetList", static_cast<occ::handle<NCollection_HSequence<opencascade::handle<STEPSelections_AssemblyLink>>> (STEPSelections_AssemblyComponent::*)() const>(&STEPSelections_AssemblyComponent::GetList))
        .def("SetSDR", static_cast<void (STEPSelections_AssemblyComponent::*)(const occ::handle<StepShape_ShapeDefinitionRepresentation> &)>(&STEPSelections_AssemblyComponent::SetSDR), nb::arg("sdr").none())
        .def("SetList", static_cast<void (STEPSelections_AssemblyComponent::*)(const occ::handle<NCollection_HSequence<opencascade::handle<STEPSelections_AssemblyLink>>> &)>(&STEPSelections_AssemblyComponent::SetList), nb::arg("list").none())
        .def_static("get_type_name", static_cast<const char * (*)()>(&STEPSelections_AssemblyComponent::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&STEPSelections_AssemblyComponent::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (STEPSelections_AssemblyComponent::*)() const>(&STEPSelections_AssemblyComponent::DynamicType));
    nanoocp_implicit_copy_ctor<STEPSelections_AssemblyComponent>(nb::borrow<nb::class_<STEPSelections_AssemblyComponent>>(m.attr("STEPSelections_AssemblyComponent")));
    nb::borrow<nb::class_<STEPSelections_AssemblyExplorer>>(m.attr("STEPSelections_AssemblyExplorer"))
        .def(nb::init<const Interface_Graph &>(), nb::arg("G"))
        .def("Init", static_cast<void (STEPSelections_AssemblyExplorer::*)(const Interface_Graph &)>(&STEPSelections_AssemblyExplorer::Init), nb::arg("G"))
        .def("Dump", [](const STEPSelections_AssemblyExplorer &self) { std::ostringstream os_stream; self.Dump(os_stream); return nanoocp_stream_text(os_stream); })
        .def("FindSDRWithProduct", static_cast<occ::handle<StepShape_ShapeDefinitionRepresentation> (STEPSelections_AssemblyExplorer::*)(const occ::handle<StepBasic_ProductDefinition> &) const>(&STEPSelections_AssemblyExplorer::FindSDRWithProduct), nb::arg("product").none())
        .def("FillListWithGraph", static_cast<void (STEPSelections_AssemblyExplorer::*)(const occ::handle<STEPSelections_AssemblyComponent> &)>(&STEPSelections_AssemblyExplorer::FillListWithGraph), nb::arg("cmp").none())
        .def("FindItemWithNAUO", static_cast<occ::handle<Standard_Transient> (STEPSelections_AssemblyExplorer::*)(const occ::handle<StepRepr_NextAssemblyUsageOccurrence> &) const>(&STEPSelections_AssemblyExplorer::FindItemWithNAUO), nb::arg("nauo").none())
        .def("NbAssemblies", static_cast<int (STEPSelections_AssemblyExplorer::*)() const>(&STEPSelections_AssemblyExplorer::NbAssemblies), R"nbdoc(Returns the number of root assemblies;)nbdoc")
        .def("Root", static_cast<occ::handle<STEPSelections_AssemblyComponent> (STEPSelections_AssemblyExplorer::*)(const int) const>(&STEPSelections_AssemblyExplorer::Root), nb::arg("rank") = static_cast<std::decay_t<const int>>(1), R"nbdoc(Returns root of assenbly by its rank;)nbdoc");
    nanoocp_implicit_copy_ctor<STEPSelections_AssemblyExplorer>(nb::borrow<nb::class_<STEPSelections_AssemblyExplorer>>(m.attr("STEPSelections_AssemblyExplorer")));
    nb::implicitly_convertible<std::decay_t<const Interface_Graph &>, STEPSelections_AssemblyExplorer>();
    nb::borrow<nb::class_<STEPSelections_Counter>>(m.attr("STEPSelections_Counter"))
        .def(nb::init<>())
        .def("Count", static_cast<void (STEPSelections_Counter::*)(const Interface_Graph &, const occ::handle<Standard_Transient> &)>(&STEPSelections_Counter::Count), nb::arg("graph"), nb::arg("start").none())
        .def("Clear", static_cast<void (STEPSelections_Counter::*)()>(&STEPSelections_Counter::Clear))
        .def("NbInstancesOfFaces", static_cast<int (STEPSelections_Counter::*)() const>(&STEPSelections_Counter::NbInstancesOfFaces))
        .def("NbInstancesOfShells", static_cast<int (STEPSelections_Counter::*)() const>(&STEPSelections_Counter::NbInstancesOfShells))
        .def("NbInstancesOfSolids", static_cast<int (STEPSelections_Counter::*)() const>(&STEPSelections_Counter::NbInstancesOfSolids))
        .def("NbInstancesOfEdges", static_cast<int (STEPSelections_Counter::*)() const>(&STEPSelections_Counter::NbInstancesOfEdges))
        .def("NbInstancesOfWires", static_cast<int (STEPSelections_Counter::*)() const>(&STEPSelections_Counter::NbInstancesOfWires))
        .def("NbSourceFaces", static_cast<int (STEPSelections_Counter::*)() const>(&STEPSelections_Counter::NbSourceFaces))
        .def("NbSourceShells", static_cast<int (STEPSelections_Counter::*)() const>(&STEPSelections_Counter::NbSourceShells))
        .def("NbSourceSolids", static_cast<int (STEPSelections_Counter::*)() const>(&STEPSelections_Counter::NbSourceSolids))
        .def("NbSourceEdges", static_cast<int (STEPSelections_Counter::*)() const>(&STEPSelections_Counter::NbSourceEdges))
        .def("NbSourceWires", static_cast<int (STEPSelections_Counter::*)() const>(&STEPSelections_Counter::NbSourceWires));
    nanoocp_implicit_copy_ctor<STEPSelections_Counter>(nb::borrow<nb::class_<STEPSelections_Counter>>(m.attr("STEPSelections_Counter")));
    nb::borrow<nb::class_<STEPSelections_SelectAssembly>>(m.attr("STEPSelections_SelectAssembly"))
        .def(nb::new_([]() { return opencascade::handle<STEPSelections_SelectAssembly>(new STEPSelections_SelectAssembly()); }))
        .def("Explore", static_cast<bool (STEPSelections_SelectAssembly::*)(const int, const occ::handle<Standard_Transient> &, const Interface_Graph &, Interface_EntityIterator &) const>(&STEPSelections_SelectAssembly::Explore), nb::arg("level"), nb::arg("ent").none(), nb::arg("G"), nb::arg("explored"), R"nbdoc(Explores an entity, to take its faces
Works recursively)nbdoc")
        .def("ExploreLabel", static_cast<TCollection_AsciiString (STEPSelections_SelectAssembly::*)() const>(&STEPSelections_SelectAssembly::ExploreLabel), R"nbdoc(Returns a text defining the criterium : "Assembly structures")nbdoc")
        .def_static("get_type_name", static_cast<const char * (*)()>(&STEPSelections_SelectAssembly::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&STEPSelections_SelectAssembly::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (STEPSelections_SelectAssembly::*)() const>(&STEPSelections_SelectAssembly::DynamicType));
    nanoocp_implicit_copy_ctor<STEPSelections_SelectAssembly>(nb::borrow<nb::class_<STEPSelections_SelectAssembly>>(m.attr("STEPSelections_SelectAssembly")));
    nb::borrow<nb::class_<STEPSelections_SelectDerived>>(m.attr("STEPSelections_SelectDerived"))
        .def(nb::new_([]() { return opencascade::handle<STEPSelections_SelectDerived>(new STEPSelections_SelectDerived()); }))
        .def("Matches", static_cast<bool (STEPSelections_SelectDerived::*)(const occ::handle<Standard_Transient> &, const occ::handle<Interface_InterfaceModel> &, const TCollection_AsciiString &, const bool) const>(&STEPSelections_SelectDerived::Matches), nb::arg("ent").none(), nb::arg("model").none(), nb::arg("text"), nb::arg("exact"))
        .def_static("get_type_name", static_cast<const char * (*)()>(&STEPSelections_SelectDerived::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&STEPSelections_SelectDerived::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (STEPSelections_SelectDerived::*)() const>(&STEPSelections_SelectDerived::DynamicType));
    nanoocp_implicit_copy_ctor<STEPSelections_SelectDerived>(nb::borrow<nb::class_<STEPSelections_SelectDerived>>(m.attr("STEPSelections_SelectDerived")));
    nb::borrow<nb::class_<STEPSelections_SelectFaces>>(m.attr("STEPSelections_SelectFaces"))
        .def(nb::new_([]() { return opencascade::handle<STEPSelections_SelectFaces>(new STEPSelections_SelectFaces()); }))
        .def("Explore", static_cast<bool (STEPSelections_SelectFaces::*)(const int, const occ::handle<Standard_Transient> &, const Interface_Graph &, Interface_EntityIterator &) const>(&STEPSelections_SelectFaces::Explore), nb::arg("level"), nb::arg("ent").none(), nb::arg("G"), nb::arg("explored"), R"nbdoc(Explores an entity, to take its faces
Works recursively)nbdoc")
        .def("ExploreLabel", static_cast<TCollection_AsciiString (STEPSelections_SelectFaces::*)() const>(&STEPSelections_SelectFaces::ExploreLabel), R"nbdoc(Returns a text defining the criterium : "Faces")nbdoc")
        .def_static("get_type_name", static_cast<const char * (*)()>(&STEPSelections_SelectFaces::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&STEPSelections_SelectFaces::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (STEPSelections_SelectFaces::*)() const>(&STEPSelections_SelectFaces::DynamicType));
    nanoocp_implicit_copy_ctor<STEPSelections_SelectFaces>(nb::borrow<nb::class_<STEPSelections_SelectFaces>>(m.attr("STEPSelections_SelectFaces")));
    nb::borrow<nb::class_<STEPSelections_SelectForTransfer>>(m.attr("STEPSelections_SelectForTransfer"))
        .def(nb::new_([]() { return opencascade::handle<STEPSelections_SelectForTransfer>(new STEPSelections_SelectForTransfer()); }))
        .def(nb::new_([](const occ::handle<XSControl_TransferReader> & TR) { return opencascade::handle<STEPSelections_SelectForTransfer>(new STEPSelections_SelectForTransfer(TR)); }), nb::arg("TR").none())
        .def("RootResult", static_cast<Interface_EntityIterator (STEPSelections_SelectForTransfer::*)(const Interface_Graph &) const>(&STEPSelections_SelectForTransfer::RootResult), nb::arg("G"))
        .def_static("get_type_name", static_cast<const char * (*)()>(&STEPSelections_SelectForTransfer::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&STEPSelections_SelectForTransfer::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (STEPSelections_SelectForTransfer::*)() const>(&STEPSelections_SelectForTransfer::DynamicType));
    nanoocp_implicit_copy_ctor<STEPSelections_SelectForTransfer>(nb::borrow<nb::class_<STEPSelections_SelectForTransfer>>(m.attr("STEPSelections_SelectForTransfer")));
    nb::implicitly_convertible<std::decay_t<const occ::handle<XSControl_TransferReader> &>, STEPSelections_SelectForTransfer>();
    nb::borrow<nb::class_<STEPSelections_SelectGSCurves>>(m.attr("STEPSelections_SelectGSCurves"))
        .def(nb::new_([]() { return opencascade::handle<STEPSelections_SelectGSCurves>(new STEPSelections_SelectGSCurves()); }))
        .def("Explore", static_cast<bool (STEPSelections_SelectGSCurves::*)(const int, const occ::handle<Standard_Transient> &, const Interface_Graph &, Interface_EntityIterator &) const>(&STEPSelections_SelectGSCurves::Explore), nb::arg("level"), nb::arg("ent").none(), nb::arg("G"), nb::arg("explored"))
        .def("ExploreLabel", static_cast<TCollection_AsciiString (STEPSelections_SelectGSCurves::*)() const>(&STEPSelections_SelectGSCurves::ExploreLabel), R"nbdoc(Returns a text defining the criterium : "Curves")nbdoc")
        .def_static("get_type_name", static_cast<const char * (*)()>(&STEPSelections_SelectGSCurves::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&STEPSelections_SelectGSCurves::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (STEPSelections_SelectGSCurves::*)() const>(&STEPSelections_SelectGSCurves::DynamicType));
    nanoocp_implicit_copy_ctor<STEPSelections_SelectGSCurves>(nb::borrow<nb::class_<STEPSelections_SelectGSCurves>>(m.attr("STEPSelections_SelectGSCurves")));
    nb::borrow<nb::class_<STEPSelections_SelectInstances>>(m.attr("STEPSelections_SelectInstances"))
        .def(nb::new_([]() { return opencascade::handle<STEPSelections_SelectInstances>(new STEPSelections_SelectInstances()); }))
        .def("RootResult", static_cast<Interface_EntityIterator (STEPSelections_SelectInstances::*)(const Interface_Graph &) const>(&STEPSelections_SelectInstances::RootResult), nb::arg("G"))
        .def("Explore", static_cast<bool (STEPSelections_SelectInstances::*)(const int, const occ::handle<Standard_Transient> &, const Interface_Graph &, Interface_EntityIterator &) const>(&STEPSelections_SelectInstances::Explore), nb::arg("level"), nb::arg("ent").none(), nb::arg("G"), nb::arg("explored"))
        .def("ExploreLabel", static_cast<TCollection_AsciiString (STEPSelections_SelectInstances::*)() const>(&STEPSelections_SelectInstances::ExploreLabel), R"nbdoc(Returns a text defining the criterium : "Instances")nbdoc")
        .def_static("get_type_name", static_cast<const char * (*)()>(&STEPSelections_SelectInstances::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&STEPSelections_SelectInstances::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (STEPSelections_SelectInstances::*)() const>(&STEPSelections_SelectInstances::DynamicType));
    nanoocp_implicit_copy_ctor<STEPSelections_SelectInstances>(nb::borrow<nb::class_<STEPSelections_SelectInstances>>(m.attr("STEPSelections_SelectInstances")));
}

void nanoocp_conversions_STEPSelections(nb::module_ &m) {
}
