// Generated by the nanoOCP generator from OCCT package BinObjMgt (toolkit TKBinL). Do not edit.
#include "nanoocp_common.h"
#include "nanoocp_ncollection.h"
#include <BinObjMgt_PByte.hxx>
#include <BinObjMgt_PChar.hxx>
#include <BinObjMgt_Persistent.hxx>
#include <BinObjMgt_PExtChar.hxx>
#include <BinObjMgt_PInteger.hxx>
#include <BinObjMgt_Position.hxx>
#include <BinObjMgt_PReal.hxx>
#include <BinObjMgt_PShortReal.hxx>
#include <BinObjMgt_RRelocationTable.hxx>
#include <NCollection_DataMap.hxx>
#include <Standard_GUID.hxx>
#include <Standard_IStream.hxx>
#include <Standard_OStream.hxx>
#include <Standard_Transient.hxx>
#include <Standard_Type.hxx>
#include <Storage_HeaderData.hxx>
#include <TCollection_AsciiString.hxx>
#include <TCollection_ExtendedString.hxx>
#include <TDF_Data.hxx>
#include <TDF_Label.hxx>

void nanoocp_declare_BinObjMgt(nb::module_ &m) {
    { nb::class_<BinObjMgt_Position, Standard_Transient> cls(m, "BinObjMgt_Position", R"nbdoc(Stores and manipulates position in the stream.)nbdoc");
    }
    { nb::class_<BinObjMgt_Persistent> cls(m, "BinObjMgt_Persistent", R"nbdoc(Binary persistent representation of an object.
Really it is used as a buffer for read/write an object.

It takes care of Little/Big endian by inversing bytes
in objects of standard types (see FSD_FileHeader.hxx
for the default value of DO_INVERSE).)nbdoc");
    }
}

void nanoocp_templates_BinObjMgt(nb::module_ &m) {
    { nb::module_ home = nb::module_::import_("nanoocp._TKernel.NCollection"); nanoocp::bind_NCollection_DataMap<int, opencascade::handle<Standard_Transient>>(home, "NCollection_DataMap__int__Handle_Standard_Transient"); }
    { nb::class_<BinObjMgt_RRelocationTable, NCollection_DataMap<int, opencascade::handle<Standard_Transient>>> cls(m, "BinObjMgt_RRelocationTable", R"nbdoc(Retrieval relocation table is modeled as a child class of
NCollection_DataMap<int, occ::handle<Standard_Transient>> that stores a handle to the file
header section. With that attribute drivers have access to the file header
section.)nbdoc");
    }
}

void nanoocp_define_BinObjMgt(nb::module_ &m) {
    nb::borrow<nb::class_<BinObjMgt_Position>>(m.attr("BinObjMgt_Position"))
        .def("StoreSize", [](BinObjMgt_Position &self) { std::ostringstream theStream_stream; self.StoreSize(theStream_stream); return nanoocp_stream_bytes(theStream_stream); }, R"nbdoc(Stores the difference between the current position and the stored one.)nbdoc")
        .def("WriteSize", [](BinObjMgt_Position &self, const bool theDummy) { std::ostringstream theStream_stream; self.WriteSize(theStream_stream, theDummy); return nanoocp_stream_bytes(theStream_stream); }, nb::arg("theDummy") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Writes stored size at the stored position. Changes the current stream position.
If theDummy is true, is writes to the current position zero size.)nbdoc")
        .def_static("get_type_name", static_cast<const char * (*)()>(&BinObjMgt_Position::get_type_name))
        .def_static("get_type_descriptor", static_cast<const occ::handle<Standard_Type> & (*)()>(&BinObjMgt_Position::get_type_descriptor))
        .def("DynamicType", static_cast<const occ::handle<Standard_Type> & (BinObjMgt_Position::*)() const>(&BinObjMgt_Position::DynamicType));
    nanoocp_implicit_copy_ctor<BinObjMgt_Position>(nb::borrow<nb::class_<BinObjMgt_Position>>(m.attr("BinObjMgt_Position")));
    nb::borrow<nb::class_<BinObjMgt_Persistent>>(m.attr("BinObjMgt_Persistent"))
        .def(nb::init<>(), R"nbdoc(Empty constructor)nbdoc")
        .def("PutCharacter", static_cast<BinObjMgt_Persistent & (BinObjMgt_Persistent::*)(const char)>(&BinObjMgt_Persistent::PutCharacter), nb::rv_policy::reference_internal, nb::arg("theValue"))
        .def("PutByte", static_cast<BinObjMgt_Persistent & (BinObjMgt_Persistent::*)(const uint8_t)>(&BinObjMgt_Persistent::PutByte), nb::rv_policy::reference_internal, nb::arg("theValue"))
        .def("PutExtCharacter", static_cast<BinObjMgt_Persistent & (BinObjMgt_Persistent::*)(const char16_t)>(&BinObjMgt_Persistent::PutExtCharacter), nb::rv_policy::reference_internal, nb::arg("theValue"))
        .def("PutInteger", static_cast<BinObjMgt_Persistent & (BinObjMgt_Persistent::*)(const int)>(&BinObjMgt_Persistent::PutInteger), nb::rv_policy::reference_internal, nb::arg("theValue"))
        .def("PutBoolean", static_cast<BinObjMgt_Persistent & (BinObjMgt_Persistent::*)(const bool)>(&BinObjMgt_Persistent::PutBoolean), nb::rv_policy::reference_internal, nb::arg("theValue"))
        .def("PutReal", static_cast<BinObjMgt_Persistent & (BinObjMgt_Persistent::*)(const double)>(&BinObjMgt_Persistent::PutReal), nb::rv_policy::reference_internal, nb::arg("theValue"))
        .def("PutShortReal", static_cast<BinObjMgt_Persistent & (BinObjMgt_Persistent::*)(const float)>(&BinObjMgt_Persistent::PutShortReal), nb::rv_policy::reference_internal, nb::arg("theValue"))
        .def("PutCString", static_cast<BinObjMgt_Persistent & (BinObjMgt_Persistent::*)(const char *const)>(&BinObjMgt_Persistent::PutCString), nb::rv_policy::reference_internal, nb::arg("theValue"), R"nbdoc(Offset in output buffer is not aligned)nbdoc")
        .def("PutAsciiString", static_cast<BinObjMgt_Persistent & (BinObjMgt_Persistent::*)(const TCollection_AsciiString &)>(&BinObjMgt_Persistent::PutAsciiString), nb::rv_policy::reference_internal, nb::arg("theValue"), R"nbdoc(Offset in output buffer is word-aligned)nbdoc")
        .def("PutExtendedString", static_cast<BinObjMgt_Persistent & (BinObjMgt_Persistent::*)(const TCollection_ExtendedString &)>(&BinObjMgt_Persistent::PutExtendedString), nb::rv_policy::reference_internal, nb::arg("theValue"), R"nbdoc(Offset in output buffer is word-aligned)nbdoc")
        .def("PutLabel", static_cast<BinObjMgt_Persistent & (BinObjMgt_Persistent::*)(const TDF_Label &)>(&BinObjMgt_Persistent::PutLabel), nb::rv_policy::reference_internal, nb::arg("theValue"))
        .def("PutGUID", static_cast<BinObjMgt_Persistent & (BinObjMgt_Persistent::*)(const Standard_GUID &)>(&BinObjMgt_Persistent::PutGUID), nb::rv_policy::reference_internal, nb::arg("theValue"))
        .def("GetCharacter", [](const BinObjMgt_Persistent &self) { char theValue{}; self.GetCharacter(theValue); return theValue; })
        .def("GetByte", [](const BinObjMgt_Persistent &self) { uint8_t theValue{}; self.GetByte(theValue); return theValue; })
        .def("GetExtCharacter", [](const BinObjMgt_Persistent &self) { char16_t theValue{}; self.GetExtCharacter(theValue); return theValue; })
        .def("GetInteger", [](const BinObjMgt_Persistent &self) { int theValue{}; self.GetInteger(theValue); return theValue; })
        .def("GetBoolean", [](const BinObjMgt_Persistent &self) { bool theValue{}; self.GetBoolean(theValue); return theValue; })
        .def("GetReal", [](const BinObjMgt_Persistent &self) { double theValue{}; self.GetReal(theValue); return theValue; })
        .def("GetShortReal", [](const BinObjMgt_Persistent &self) { float theValue{}; self.GetShortReal(theValue); return theValue; })
        .def("GetAsciiString", static_cast<const BinObjMgt_Persistent & (BinObjMgt_Persistent::*)(TCollection_AsciiString &) const>(&BinObjMgt_Persistent::GetAsciiString), nb::arg("theValue"))
        .def("GetExtendedString", static_cast<const BinObjMgt_Persistent & (BinObjMgt_Persistent::*)(TCollection_ExtendedString &) const>(&BinObjMgt_Persistent::GetExtendedString), nb::arg("theValue"))
        .def("GetLabel", static_cast<const BinObjMgt_Persistent & (BinObjMgt_Persistent::*)(const occ::handle<TDF_Data> &, TDF_Label &) const>(&BinObjMgt_Persistent::GetLabel), nb::arg("theDS").none(), nb::arg("theValue"))
        .def("GetGUID", static_cast<const BinObjMgt_Persistent & (BinObjMgt_Persistent::*)(Standard_GUID &) const>(&BinObjMgt_Persistent::GetGUID), nb::arg("theValue"))
        .def("Position", static_cast<int (BinObjMgt_Persistent::*)() const>(&BinObjMgt_Persistent::Position), R"nbdoc(Tells the current position for get/put)nbdoc")
        .def("SetPosition", static_cast<bool (BinObjMgt_Persistent::*)(const int) const>(&BinObjMgt_Persistent::SetPosition), nb::arg("thePos"), R"nbdoc(Sets the current position for get/put.
Resets an error state depending on the validity of thePos.
Returns the new state (value of IsOK()))nbdoc")
        .def("Truncate", static_cast<void (BinObjMgt_Persistent::*)()>(&BinObjMgt_Persistent::Truncate), R"nbdoc(Truncates the buffer by current position,
i.e. updates mySize)nbdoc")
        .def("IsError", static_cast<bool (BinObjMgt_Persistent::*)() const>(&BinObjMgt_Persistent::IsError), R"nbdoc(Indicates an error after Get methods or SetPosition)nbdoc")
        .def("__not__", static_cast<bool (BinObjMgt_Persistent::*)() const>(&BinObjMgt_Persistent::operator!), nb::is_operator())
        .def("IsOK", static_cast<bool (BinObjMgt_Persistent::*)() const>(&BinObjMgt_Persistent::IsOK), R"nbdoc(Indicates a good state after Get methods or SetPosition)nbdoc")
        .def("Init", static_cast<void (BinObjMgt_Persistent::*)()>(&BinObjMgt_Persistent::Init), R"nbdoc(Initializes me to reuse again)nbdoc")
        .def("SetId", static_cast<void (BinObjMgt_Persistent::*)(const int)>(&BinObjMgt_Persistent::SetId), nb::arg("theId"), R"nbdoc(Sets the Id of the object)nbdoc")
        .def("SetTypeId", static_cast<void (BinObjMgt_Persistent::*)(const int)>(&BinObjMgt_Persistent::SetTypeId), nb::arg("theId"), R"nbdoc(Sets the Id of the type of the object)nbdoc")
        .def("Id", static_cast<int (BinObjMgt_Persistent::*)() const>(&BinObjMgt_Persistent::Id), R"nbdoc(Returns the Id of the object)nbdoc")
        .def("TypeId", static_cast<int (BinObjMgt_Persistent::*)() const>(&BinObjMgt_Persistent::TypeId), R"nbdoc(Returns the Id of the type of the object)nbdoc")
        .def("Length", static_cast<int (BinObjMgt_Persistent::*)() const>(&BinObjMgt_Persistent::Length), R"nbdoc(Returns the length of data)nbdoc")
        .def("Write", [](BinObjMgt_Persistent &self, const bool theDirectStream) { std::ostringstream theOS_stream; self.Write(theOS_stream, theDirectStream); return nanoocp_stream_bytes(theOS_stream); }, nb::arg("theDirectStream") = static_cast<std::decay_t<const bool>>(false), R"nbdoc(Stores <me> to the stream.
inline Standard_OStream& operator<< (Standard_OStream&,
BinObjMgt_Persistent&) is also available.
If theDirectStream is true, after this data the direct stream data is stored.)nbdoc")
        .def("Read", [](BinObjMgt_Persistent &self, const nanoocp::BinaryInput &theIS) { std::stringstream theIS_stream(theIS.data); self.Read(theIS_stream); }, nb::arg("theIS"), R"nbdoc(Retrieves <me> from the stream.
inline Standard_IStream& operator>> (Standard_IStream&,
BinObjMgt_Persistent&) is also available)nbdoc")
        .def("Destroy", static_cast<void (BinObjMgt_Persistent::*)()>(&BinObjMgt_Persistent::Destroy), R"nbdoc(Frees the allocated memory;
This object can be reused after call to Init)nbdoc")
        .def("IsDirect", static_cast<bool (BinObjMgt_Persistent::*)()>(&BinObjMgt_Persistent::IsDirect), R"nbdoc(Returns true if after this record a direct writing to the stream is performed.)nbdoc")
        .def("StreamStart", static_cast<occ::handle<BinObjMgt_Position> (BinObjMgt_Persistent::*)()>(&BinObjMgt_Persistent::StreamStart), R"nbdoc(Returns the start position of the direct writing in the stream)nbdoc")
        .def("__bool__", [](const BinObjMgt_Persistent &self) { return static_cast<bool>(self); });
    nanoocp_implicit_copy_ctor<BinObjMgt_Persistent>(nb::borrow<nb::class_<BinObjMgt_Persistent>>(m.attr("BinObjMgt_Persistent")));
    nanoocp_implicit_default_ctor<BinObjMgt_RRelocationTable>(nb::borrow<nb::class_<BinObjMgt_RRelocationTable>>(m.attr("BinObjMgt_RRelocationTable")));
    nb::borrow<nb::class_<BinObjMgt_RRelocationTable>>(m.attr("BinObjMgt_RRelocationTable"))
        .def("GetHeaderData", static_cast<const occ::handle<Storage_HeaderData> & (BinObjMgt_RRelocationTable::*)() const>(&BinObjMgt_RRelocationTable::GetHeaderData), R"nbdoc(Returns a handle to the header data of the file that is begin read)nbdoc")
        .def("SetHeaderData", static_cast<void (BinObjMgt_RRelocationTable::*)(const occ::handle<Storage_HeaderData> &)>(&BinObjMgt_RRelocationTable::SetHeaderData), nb::arg("theHeaderData").none(), R"nbdoc(Sets the storage header data.

@param theHeaderData header data of the file that is begin read)nbdoc")
        .def("Clear", static_cast<void (BinObjMgt_RRelocationTable::*)(const bool)>(&BinObjMgt_RRelocationTable::Clear), nb::arg("doReleaseMemory") = static_cast<std::decay_t<const bool>>(true));
    nanoocp_implicit_copy_ctor<BinObjMgt_RRelocationTable>(nb::borrow<nb::class_<BinObjMgt_RRelocationTable>>(m.attr("BinObjMgt_RRelocationTable")));
}

void nanoocp_conversions_BinObjMgt(nb::module_ &m) {
}
