"""OCCT package NCollection (toolkit TKernel)."""
import importlib as _importlib

from nanoocp._TKernel import NCollection as _ext
from nanoocp._TKernel.NCollection import *  # noqa: F401,F403


# NCollection_Xxx[T] -> bound class (Design.md 6a); tables generated from manifest.json
from nanoocp._templates import Template as _Template

NCollection_Array1 = _Template("NCollection_Array1", "nanoocp.NCollection", {
    (('nanoocp.AppDef', 'AppDef_MultiPointConstraint'),): "NCollection_Array1__AppDef_MultiPointConstraint",
    (('nanoocp.AppParCurves', 'AppParCurves_ConstraintCouple'),): "NCollection_Array1__AppParCurves_ConstraintCouple",
    (('nanoocp.AppParCurves', 'AppParCurves_MultiPoint'),): "NCollection_Array1__AppParCurves_MultiPoint",
    (('nanoocp.Aspect', 'Aspect_TrackedDevicePose'),): "NCollection_Array1__Aspect_TrackedDevicePose",
    (('nanoocp.BRepGraphInc', 'ParityOrientation'),): "NCollection_Array1__BRepGraphInc_ParityOrientation",
    (('nanoocp.BRepGraph', 'BRepGraph.EditorView.BoundaryIssue'),): "NCollection_Array1__BRepGraph_EditorView_BoundaryIssue",
    (('nanoocp.BRepGraph', 'BRepGraph_ItemUID'),): "NCollection_Array1__BRepGraph_ItemUID",
    (('nanoocp.BRepGraph', 'BRepGraph_NodeId'),): "NCollection_Array1__BRepGraph_NodeId",
    (('nanoocp.BRepGraph', 'BRepGraph_CoEdgeId'),): "NCollection_Array1__BRepGraph_NodeId_Typed__BRepGraph_NodeId_Kind_CoEdge",
    (('nanoocp.BRepGraph', 'BRepGraph_EdgeId'),): "NCollection_Array1__BRepGraph_NodeId_Typed__BRepGraph_NodeId_Kind_Edge",
    (('nanoocp.BRepGraph', 'BRepGraph_FaceId'),): "NCollection_Array1__BRepGraph_NodeId_Typed__BRepGraph_NodeId_Kind_Face",
    (('nanoocp.BRepGraph', 'BRepGraph_ProductId'),): "NCollection_Array1__BRepGraph_NodeId_Typed__BRepGraph_NodeId_Kind_Product",
    (('nanoocp.BRepGraph', 'BRepGraph_ShellId'),): "NCollection_Array1__BRepGraph_NodeId_Typed__BRepGraph_NodeId_Kind_Shell",
    (('nanoocp.BRepGraph', 'BRepGraph_SolidId'),): "NCollection_Array1__BRepGraph_NodeId_Typed__BRepGraph_NodeId_Kind_Solid",
    (('nanoocp.BRepGraph', 'BRepGraph_WireId'),): "NCollection_Array1__BRepGraph_NodeId_Typed__BRepGraph_NodeId_Kind_Wire",
    (('nanoocp.BRepGraph', 'BRepGraph_RefId'),): "NCollection_Array1__BRepGraph_RefId",
    (('nanoocp.BRepGraph', 'BRepGraph_ChildRefId'),): "NCollection_Array1__BRepGraph_RefId_Typed__BRepGraph_RefId_Kind_Child",
    (('nanoocp.BRepGraph', 'BRepGraph_FaceRefId'),): "NCollection_Array1__BRepGraph_RefId_Typed__BRepGraph_RefId_Kind_Face",
    (('nanoocp.BRepGraph', 'BRepGraph_OccurrenceRefId'),): "NCollection_Array1__BRepGraph_RefId_Typed__BRepGraph_RefId_Kind_Occurrence",
    (('nanoocp.BRepGraph', 'BRepGraph_ShellRefId'),): "NCollection_Array1__BRepGraph_RefId_Typed__BRepGraph_RefId_Kind_Shell",
    (('nanoocp.BRepGraph', 'BRepGraph_SolidRefId'),): "NCollection_Array1__BRepGraph_RefId_Typed__BRepGraph_RefId_Kind_Solid",
    (('nanoocp.BRepGraph', 'BRepGraph_WireRefId'),): "NCollection_Array1__BRepGraph_RefId_Typed__BRepGraph_RefId_Kind_Wire",
    (('nanoocp.BRepGraph', 'BRepGraph_UID'),): "NCollection_Array1__BRepGraph_UID",
    (('nanoocp.BRepGraph', 'BRepGraph_Validate.Issue'),): "NCollection_Array1__BRepGraph_Validate_Issue",
    (('nanoocp.BRepMesh', 'BRepMesh_Vertex'),): "NCollection_Array1__BRepMesh_Vertex",
    (('nanoocp.Bnd', 'Bnd_Box'),): "NCollection_Array1__Bnd_Box",
    (('nanoocp.ChFiDS', 'ChFiDS_CircSection'),): "NCollection_Array1__ChFiDS_CircSection",
    (('nanoocp.Geom2dGridEval', 'CurveD1'),): "NCollection_Array1__Geom2dGridEval_CurveD1",
    (('nanoocp.Geom2dGridEval', 'CurveD2'),): "NCollection_Array1__Geom2dGridEval_CurveD2",
    (('nanoocp.Geom2dGridEval', 'CurveD3'),): "NCollection_Array1__Geom2dGridEval_CurveD3",
    (('nanoocp.Geom', 'Geom_Curve.ResD1'),): "NCollection_Array1__Geom_Curve_ResD1",
    (('nanoocp.Geom', 'Geom_Curve.ResD2'),): "NCollection_Array1__Geom_Curve_ResD2",
    (('nanoocp.Geom', 'Geom_Curve.ResD3'),): "NCollection_Array1__Geom_Curve_ResD3",
    (('nanoocp.Geom', 'Geom_Surface.ResD1'),): "NCollection_Array1__Geom_Surface_ResD1",
    (('nanoocp.Geom', 'Geom_Surface.ResD2'),): "NCollection_Array1__Geom_Surface_ResD2",
    (('nanoocp.Geom', 'Geom_Surface.ResD3'),): "NCollection_Array1__Geom_Surface_ResD3",
    (('nanoocp.Graphic3d', 'Graphic3d_Attribute'),): "NCollection_Array1__Graphic3d_Attribute",
    (('nanoocp.Graphic3d', 'Graphic3d_FrameStatsData'),): "NCollection_Array1__Graphic3d_FrameStatsData",
    (('nanoocp.HLRAlgo', 'HLRAlgo_PolyHidingData'),): "NCollection_Array1__HLRAlgo_PolyHidingData",
    (('nanoocp.HLRAlgo', 'HLRAlgo_PolyInternalSegment'),): "NCollection_Array1__HLRAlgo_PolyInternalSegment",
    (('nanoocp.HLRAlgo', 'HLRAlgo_TriangleData'),): "NCollection_Array1__HLRAlgo_TriangleData",
    (('nanoocp.HLRBRep', 'HLRBRep_EdgeData'),): "NCollection_Array1__HLRBRep_EdgeData",
    (('nanoocp.HLRBRep', 'HLRBRep_FaceData'),): "NCollection_Array1__HLRBRep_FaceData",
    (('nanoocp.Adaptor3d', 'Adaptor3d_Curve'),): "NCollection_Array1__Handle_Adaptor3d_Curve",
    (('nanoocp.Geom2d', 'Geom2d_BSplineCurve'),): "NCollection_Array1__Handle_Geom2d_BSplineCurve",
    (('nanoocp.Geom2d', 'Geom2d_BezierCurve'),): "NCollection_Array1__Handle_Geom2d_BezierCurve",
    (('nanoocp.Geom2d', 'Geom2d_Curve'),): "NCollection_Array1__Handle_Geom2d_Curve",
    (('nanoocp.Geom', 'Geom_BSplineCurve'),): "NCollection_Array1__Handle_Geom_BSplineCurve",
    (('nanoocp.Geom', 'Geom_BezierCurve'),): "NCollection_Array1__Handle_Geom_BezierCurve",
    (('nanoocp.Geom', 'Geom_BezierSurface'),): "NCollection_Array1__Handle_Geom_BezierSurface",
    (('nanoocp.Geom', 'Geom_Curve'),): "NCollection_Array1__Handle_Geom_Curve",
    (('nanoocp.Geom', 'Geom_Surface'),): "NCollection_Array1__Handle_Geom_Surface",
    (('nanoocp.Graphic3d', 'Graphic3d_TextureMap'),): "NCollection_Array1__Handle_Graphic3d_TextureMap",
    (('nanoocp.HLRAlgo', 'HLRAlgo_PolyData'),): "NCollection_Array1__Handle_HLRAlgo_PolyData",
    (('nanoocp.HLRAlgo', 'HLRAlgo_PolyInternalNode'),): "NCollection_Array1__Handle_HLRAlgo_PolyInternalNode",
    (('nanoocp.HLRAlgo', 'HLRAlgo_PolyShellData'),): "NCollection_Array1__Handle_HLRAlgo_PolyShellData",
    (('nanoocp.IGESAppli', 'IGESAppli_FiniteElement'),): "NCollection_Array1__Handle_IGESAppli_FiniteElement",
    (('nanoocp.IGESAppli', 'IGESAppli_Node'),): "NCollection_Array1__Handle_IGESAppli_Node",
    (('nanoocp.IGESData', 'IGESData_IGESEntity'),): "NCollection_Array1__Handle_IGESData_IGESEntity",
    (('nanoocp.IGESData', 'IGESData_LineFontEntity'),): "NCollection_Array1__Handle_IGESData_LineFontEntity",
    (('nanoocp.IGESData', 'IGESData_ViewKindEntity'),): "NCollection_Array1__Handle_IGESData_ViewKindEntity",
    (('nanoocp.IGESDefs', 'IGESDefs_TabularData'),): "NCollection_Array1__Handle_IGESDefs_TabularData",
    (('nanoocp.IGESDimen', 'IGESDimen_GeneralNote'),): "NCollection_Array1__Handle_IGESDimen_GeneralNote",
    (('nanoocp.IGESDimen', 'IGESDimen_LeaderArrow'),): "NCollection_Array1__Handle_IGESDimen_LeaderArrow",
    (('nanoocp.IGESDraw', 'IGESDraw_ConnectPoint'),): "NCollection_Array1__Handle_IGESDraw_ConnectPoint",
    (('nanoocp.IGESGeom', 'IGESGeom_Boundary'),): "NCollection_Array1__Handle_IGESGeom_Boundary",
    (('nanoocp.IGESGeom', 'IGESGeom_CurveOnSurface'),): "NCollection_Array1__Handle_IGESGeom_CurveOnSurface",
    (('nanoocp.IGESGeom', 'IGESGeom_TransformationMatrix'),): "NCollection_Array1__Handle_IGESGeom_TransformationMatrix",
    (('nanoocp.IGESGraph', 'IGESGraph_Color'),): "NCollection_Array1__Handle_IGESGraph_Color",
    (('nanoocp.IGESGraph', 'IGESGraph_TextDisplayTemplate'),): "NCollection_Array1__Handle_IGESGraph_TextDisplayTemplate",
    (('nanoocp.IGESGraph', 'IGESGraph_TextFontDef'),): "NCollection_Array1__Handle_IGESGraph_TextFontDef",
    (('nanoocp.IGESSolid', 'IGESSolid_Face'),): "NCollection_Array1__Handle_IGESSolid_Face",
    (('nanoocp.IGESSolid', 'IGESSolid_Loop'),): "NCollection_Array1__Handle_IGESSolid_Loop",
    (('nanoocp.IGESSolid', 'IGESSolid_Shell'),): "NCollection_Array1__Handle_IGESSolid_Shell",
    (('nanoocp.IGESSolid', 'IGESSolid_VertexList'),): "NCollection_Array1__Handle_IGESSolid_VertexList",
    (('nanoocp.Image', 'Image_PixMap'),): "NCollection_Array1__Handle_Image_PixMap",
    (('nanoocp.Poly', 'Poly_PolygonOnTriangulation'),): "NCollection_Array1__Handle_Poly_PolygonOnTriangulation",
    (('nanoocp.SelectMgr', 'SelectMgr_EntityOwner'),): "NCollection_Array1__Handle_SelectMgr_EntityOwner",
    (('nanoocp.Standard', 'Standard_Persistent'),): "NCollection_Array1__Handle_Standard_Persistent",
    (('nanoocp.Standard', 'Standard_Transient'),): "NCollection_Array1__Handle_Standard_Transient",
    (('nanoocp.StepBasic', 'StepBasic_Approval'),): "NCollection_Array1__Handle_StepBasic_Approval",
    (('nanoocp.StepBasic', 'StepBasic_DerivedUnitElement'),): "NCollection_Array1__Handle_StepBasic_DerivedUnitElement",
    (('nanoocp.StepBasic', 'StepBasic_Document'),): "NCollection_Array1__Handle_StepBasic_Document",
    (('nanoocp.StepBasic', 'StepBasic_NamedUnit'),): "NCollection_Array1__Handle_StepBasic_NamedUnit",
    (('nanoocp.StepBasic', 'StepBasic_Organization'),): "NCollection_Array1__Handle_StepBasic_Organization",
    (('nanoocp.StepBasic', 'StepBasic_Person'),): "NCollection_Array1__Handle_StepBasic_Person",
    (('nanoocp.StepBasic', 'StepBasic_Product'),): "NCollection_Array1__Handle_StepBasic_Product",
    (('nanoocp.StepBasic', 'StepBasic_ProductContext'),): "NCollection_Array1__Handle_StepBasic_ProductContext",
    (('nanoocp.StepBasic', 'StepBasic_UncertaintyMeasureWithUnit'),): "NCollection_Array1__Handle_StepBasic_UncertaintyMeasureWithUnit",
    (('nanoocp.StepDimTol', 'StepDimTol_DatumReference'),): "NCollection_Array1__Handle_StepDimTol_DatumReference",
    (('nanoocp.StepDimTol', 'StepDimTol_DatumReferenceCompartment'),): "NCollection_Array1__Handle_StepDimTol_DatumReferenceCompartment",
    (('nanoocp.StepDimTol', 'StepDimTol_DatumReferenceElement'),): "NCollection_Array1__Handle_StepDimTol_DatumReferenceElement",
    (('nanoocp.StepElement', 'StepElement_CurveElementEndReleasePacket'),): "NCollection_Array1__Handle_StepElement_CurveElementEndReleasePacket",
    (('nanoocp.StepElement', 'StepElement_CurveElementSectionDefinition'),): "NCollection_Array1__Handle_StepElement_CurveElementSectionDefinition",
    (('nanoocp.StepElement', 'StepElement_SurfaceSection'),): "NCollection_Array1__Handle_StepElement_SurfaceSection",
    (('nanoocp.StepElement', 'StepElement_VolumeElementPurposeMember'),): "NCollection_Array1__Handle_StepElement_VolumeElementPurposeMember",
    (('nanoocp.StepFEA', 'StepFEA_CurveElementEndOffset'),): "NCollection_Array1__Handle_StepFEA_CurveElementEndOffset",
    (('nanoocp.StepFEA', 'StepFEA_CurveElementEndRelease'),): "NCollection_Array1__Handle_StepFEA_CurveElementEndRelease",
    (('nanoocp.StepFEA', 'StepFEA_CurveElementInterval'),): "NCollection_Array1__Handle_StepFEA_CurveElementInterval",
    (('nanoocp.StepFEA', 'StepFEA_ElementRepresentation'),): "NCollection_Array1__Handle_StepFEA_ElementRepresentation",
    (('nanoocp.StepFEA', 'StepFEA_NodeRepresentation'),): "NCollection_Array1__Handle_StepFEA_NodeRepresentation",
    (('nanoocp.StepGeom', 'StepGeom_CartesianPoint'),): "NCollection_Array1__Handle_StepGeom_CartesianPoint",
    (('nanoocp.StepGeom', 'StepGeom_CompositeCurveSegment'),): "NCollection_Array1__Handle_StepGeom_CompositeCurveSegment",
    (('nanoocp.StepGeom', 'StepGeom_SurfacePatch'),): "NCollection_Array1__Handle_StepGeom_SurfacePatch",
    (('nanoocp.StepRepr', 'StepRepr_MaterialPropertyRepresentation'),): "NCollection_Array1__Handle_StepRepr_MaterialPropertyRepresentation",
    (('nanoocp.StepRepr', 'StepRepr_PropertyDefinitionRepresentation'),): "NCollection_Array1__Handle_StepRepr_PropertyDefinitionRepresentation",
    (('nanoocp.StepRepr', 'StepRepr_RepresentationItem'),): "NCollection_Array1__Handle_StepRepr_RepresentationItem",
    (('nanoocp.StepRepr', 'StepRepr_ShapeAspect'),): "NCollection_Array1__Handle_StepRepr_ShapeAspect",
    (('nanoocp.StepShape', 'StepShape_ConnectedEdgeSet'),): "NCollection_Array1__Handle_StepShape_ConnectedEdgeSet",
    (('nanoocp.StepShape', 'StepShape_ConnectedFaceSet'),): "NCollection_Array1__Handle_StepShape_ConnectedFaceSet",
    (('nanoocp.StepShape', 'StepShape_Edge'),): "NCollection_Array1__Handle_StepShape_Edge",
    (('nanoocp.StepShape', 'StepShape_Face'),): "NCollection_Array1__Handle_StepShape_Face",
    (('nanoocp.StepShape', 'StepShape_FaceBound'),): "NCollection_Array1__Handle_StepShape_FaceBound",
    (('nanoocp.StepShape', 'StepShape_OrientedClosedShell'),): "NCollection_Array1__Handle_StepShape_OrientedClosedShell",
    (('nanoocp.StepShape', 'StepShape_OrientedEdge'),): "NCollection_Array1__Handle_StepShape_OrientedEdge",
    (('nanoocp.StepVisual', 'StepVisual_CurveStyleFontPattern'),): "NCollection_Array1__Handle_StepVisual_CurveStyleFontPattern",
    (('nanoocp.StepVisual', 'StepVisual_PresentationStyleAssignment'),): "NCollection_Array1__Handle_StepVisual_PresentationStyleAssignment",
    (('nanoocp.StepVisual', 'StepVisual_TessellatedItem'),): "NCollection_Array1__Handle_StepVisual_TessellatedItem",
    (('nanoocp.StepVisual', 'StepVisual_TessellatedStructuredItem'),): "NCollection_Array1__Handle_StepVisual_TessellatedStructuredItem",
    (('nanoocp.TCollection', 'TCollection_HAsciiString'),): "NCollection_Array1__Handle_TCollection_HAsciiString",
    (('nanoocp.IntWalk', 'IntWalk_WalkingData'),): "NCollection_Array1__IntWalk_WalkingData",
    (('nanoocp.NCollection', 'NCollection_List__int'),): "NCollection_Array1__NCollection_List__int",
    (('nanoocp.BVH', 'BVH_Vec2d'),): "NCollection_Array1__NCollection_Vec2__double",
    (('nanoocp.BVH', 'BVH_Vec2f'),): "NCollection_Array1__NCollection_Vec2__float",
    (('nanoocp.BVH', 'BVH_Vec2i'),): "NCollection_Array1__NCollection_Vec2__int",
    (('nanoocp.BVH', 'BVH_Vec3d'),): "NCollection_Array1__NCollection_Vec3__double",
    (('nanoocp.Quantity', 'NCollection_Vec3__float'),): "NCollection_Array1__NCollection_Vec3__float",
    (('nanoocp.BVH', 'BVH_Vec3i'),): "NCollection_Array1__NCollection_Vec3__int",
    (('nanoocp.BVH', 'BVH_Vec4d'),): "NCollection_Array1__NCollection_Vec4__double",
    (('nanoocp.Quantity', 'NCollection_Vec4__float'),): "NCollection_Array1__NCollection_Vec4__float",
    (('nanoocp.BVH', 'BVH_Vec4i'),): "NCollection_Array1__NCollection_Vec4__int",
    (('nanoocp.Plate', 'Plate_PinpointConstraint'),): "NCollection_Array1__Plate_PinpointConstraint",
    (('nanoocp.Poly', 'Poly_Triangle'),): "NCollection_Array1__Poly_Triangle",
    (('nanoocp.Quantity', 'Quantity_Color'),): "NCollection_Array1__Quantity_Color",
    (('nanoocp.SelectMgr', 'SelectMgr_BVHThreadPool.BVHThread'),): "NCollection_Array1__SelectMgr_BVHThreadPool_BVHThread",
    (('nanoocp.StepAP203', 'StepAP203_ApprovedItem'),): "NCollection_Array1__StepAP203_ApprovedItem",
    (('nanoocp.StepAP203', 'StepAP203_CertifiedItem'),): "NCollection_Array1__StepAP203_CertifiedItem",
    (('nanoocp.StepAP203', 'StepAP203_ChangeRequestItem'),): "NCollection_Array1__StepAP203_ChangeRequestItem",
    (('nanoocp.StepAP203', 'StepAP203_ClassifiedItem'),): "NCollection_Array1__StepAP203_ClassifiedItem",
    (('nanoocp.StepAP203', 'StepAP203_ContractedItem'),): "NCollection_Array1__StepAP203_ContractedItem",
    (('nanoocp.StepAP203', 'StepAP203_DateTimeItem'),): "NCollection_Array1__StepAP203_DateTimeItem",
    (('nanoocp.StepAP203', 'StepAP203_PersonOrganizationItem'),): "NCollection_Array1__StepAP203_PersonOrganizationItem",
    (('nanoocp.StepAP203', 'StepAP203_SpecifiedItem'),): "NCollection_Array1__StepAP203_SpecifiedItem",
    (('nanoocp.StepAP203', 'StepAP203_StartRequestItem'),): "NCollection_Array1__StepAP203_StartRequestItem",
    (('nanoocp.StepAP203', 'StepAP203_WorkItem'),): "NCollection_Array1__StepAP203_WorkItem",
    (('nanoocp.StepAP214', 'StepAP214_ApprovalItem'),): "NCollection_Array1__StepAP214_ApprovalItem",
    (('nanoocp.StepAP214', 'StepAP214_AutoDesignDateAndPersonItem'),): "NCollection_Array1__StepAP214_AutoDesignDateAndPersonItem",
    (('nanoocp.StepAP214', 'StepAP214_AutoDesignDateAndTimeItem'),): "NCollection_Array1__StepAP214_AutoDesignDateAndTimeItem",
    (('nanoocp.StepAP214', 'StepAP214_AutoDesignDatedItem'),): "NCollection_Array1__StepAP214_AutoDesignDatedItem",
    (('nanoocp.StepAP214', 'StepAP214_AutoDesignGeneralOrgItem'),): "NCollection_Array1__StepAP214_AutoDesignGeneralOrgItem",
    (('nanoocp.StepAP214', 'StepAP214_AutoDesignGroupedItem'),): "NCollection_Array1__StepAP214_AutoDesignGroupedItem",
    (('nanoocp.StepAP214', 'StepAP214_AutoDesignPresentedItemSelect'),): "NCollection_Array1__StepAP214_AutoDesignPresentedItemSelect",
    (('nanoocp.StepAP214', 'StepAP214_AutoDesignReferencingItem'),): "NCollection_Array1__StepAP214_AutoDesignReferencingItem",
    (('nanoocp.StepAP214', 'StepAP214_DateAndTimeItem'),): "NCollection_Array1__StepAP214_DateAndTimeItem",
    (('nanoocp.StepAP214', 'StepAP214_DateItem'),): "NCollection_Array1__StepAP214_DateItem",
    (('nanoocp.StepAP214', 'StepAP214_DocumentReferenceItem'),): "NCollection_Array1__StepAP214_DocumentReferenceItem",
    (('nanoocp.StepAP214', 'StepAP214_ExternalIdentificationItem'),): "NCollection_Array1__StepAP214_ExternalIdentificationItem",
    (('nanoocp.StepAP214', 'StepAP214_GroupItem'),): "NCollection_Array1__StepAP214_GroupItem",
    (('nanoocp.StepAP214', 'StepAP214_OrganizationItem'),): "NCollection_Array1__StepAP214_OrganizationItem",
    (('nanoocp.StepAP214', 'StepAP214_PersonAndOrganizationItem'),): "NCollection_Array1__StepAP214_PersonAndOrganizationItem",
    (('nanoocp.StepAP214', 'StepAP214_PresentedItemSelect'),): "NCollection_Array1__StepAP214_PresentedItemSelect",
    (('nanoocp.StepAP214', 'StepAP214_SecurityClassificationItem'),): "NCollection_Array1__StepAP214_SecurityClassificationItem",
    (('nanoocp.StepDimTol', 'StepDimTol_DatumReferenceModifier'),): "NCollection_Array1__StepDimTol_DatumReferenceModifier",
    (('nanoocp.StepDimTol', 'StepDimTol_DatumSystemOrReference'),): "NCollection_Array1__StepDimTol_DatumSystemOrReference",
    (('nanoocp.StepDimTol', 'StepDimTol_GeometricToleranceModifier'),): "NCollection_Array1__StepDimTol_GeometricToleranceModifier",
    (('nanoocp.StepDimTol', 'StepDimTol_ToleranceZoneTarget'),): "NCollection_Array1__StepDimTol_ToleranceZoneTarget",
    (('nanoocp.StepElement', 'StepElement_MeasureOrUnspecifiedValue'),): "NCollection_Array1__StepElement_MeasureOrUnspecifiedValue",
    (('nanoocp.StepFEA', 'StepFEA_DegreeOfFreedom'),): "NCollection_Array1__StepFEA_DegreeOfFreedom",
    (('nanoocp.StepGeom', 'StepGeom_PcurveOrSurface'),): "NCollection_Array1__StepGeom_PcurveOrSurface",
    (('nanoocp.StepGeom', 'StepGeom_SurfaceBoundary'),): "NCollection_Array1__StepGeom_SurfaceBoundary",
    (('nanoocp.StepGeom', 'StepGeom_TrimmingSelect'),): "NCollection_Array1__StepGeom_TrimmingSelect",
    (('nanoocp.StepShape', 'StepShape_GeometricSetSelect'),): "NCollection_Array1__StepShape_GeometricSetSelect",
    (('nanoocp.StepShape', 'StepShape_ShapeDimensionRepresentationItem'),): "NCollection_Array1__StepShape_ShapeDimensionRepresentationItem",
    (('nanoocp.StepShape', 'StepShape_Shell'),): "NCollection_Array1__StepShape_Shell",
    (('nanoocp.StepShape', 'StepShape_ValueQualifier'),): "NCollection_Array1__StepShape_ValueQualifier",
    (('nanoocp.StepVisual', 'StepVisual_AnnotationPlaneElement'),): "NCollection_Array1__StepVisual_AnnotationPlaneElement",
    (('nanoocp.StepVisual', 'StepVisual_BoxCharacteristicSelect'),): "NCollection_Array1__StepVisual_BoxCharacteristicSelect",
    (('nanoocp.StepVisual', 'StepVisual_CameraModelD3MultiClippingInterectionSelect'),): "NCollection_Array1__StepVisual_CameraModelD3MultiClippingInterectionSelect",
    (('nanoocp.StepVisual', 'StepVisual_CameraModelD3MultiClippingUnionSelect'),): "NCollection_Array1__StepVisual_CameraModelD3MultiClippingUnionSelect",
    (('nanoocp.StepVisual', 'StepVisual_DirectionCountSelect'),): "NCollection_Array1__StepVisual_DirectionCountSelect",
    (('nanoocp.StepVisual', 'StepVisual_DraughtingCalloutElement'),): "NCollection_Array1__StepVisual_DraughtingCalloutElement",
    (('nanoocp.StepVisual', 'StepVisual_FillStyleSelect'),): "NCollection_Array1__StepVisual_FillStyleSelect",
    (('nanoocp.StepVisual', 'StepVisual_InvisibleItem'),): "NCollection_Array1__StepVisual_InvisibleItem",
    (('nanoocp.StepVisual', 'StepVisual_LayeredItem'),): "NCollection_Array1__StepVisual_LayeredItem",
    (('nanoocp.StepVisual', 'StepVisual_PresentationStyleSelect'),): "NCollection_Array1__StepVisual_PresentationStyleSelect",
    (('nanoocp.StepVisual', 'StepVisual_RenderingPropertiesSelect'),): "NCollection_Array1__StepVisual_RenderingPropertiesSelect",
    (('nanoocp.StepVisual', 'StepVisual_StyleContextSelect'),): "NCollection_Array1__StepVisual_StyleContextSelect",
    (('nanoocp.StepVisual', 'StepVisual_SurfaceStyleElementSelect'),): "NCollection_Array1__StepVisual_SurfaceStyleElementSelect",
    (('nanoocp.StepVisual', 'StepVisual_TessellatedEdgeOrVertex'),): "NCollection_Array1__StepVisual_TessellatedEdgeOrVertex",
    (('nanoocp.StepVisual', 'StepVisual_TextOrCharacter'),): "NCollection_Array1__StepVisual_TextOrCharacter",
    (('nanoocp.TCollection', 'TCollection_AsciiString'),): "NCollection_Array1__TCollection_AsciiString",
    (('nanoocp.TCollection', 'TCollection_ExtendedString'),): "NCollection_Array1__TCollection_ExtendedString",
    (('nanoocp.TDF', 'TDF_Label'),): "NCollection_Array1__TDF_Label",
    (('nanoocp.TopLoc', 'TopLoc_Location'),): "NCollection_Array1__TopLoc_Location",
    (('nanoocp.TopOpeBRep', 'TopOpeBRep_LineInter'),): "NCollection_Array1__TopOpeBRep_LineInter",
    (('nanoocp.TopoDS', 'TopoDS_Shape'),): "NCollection_Array1__TopoDS_Shape",
    (('builtins', 'bool'),): "NCollection_Array1__bool",
    (('builtins', 'float'),): "NCollection_Array1__double",
    (('nanoocp.gp', 'gp_Dir'),): "NCollection_Array1__gp_Dir",
    (('nanoocp.gp', 'gp_Lin'),): "NCollection_Array1__gp_Lin",
    (('nanoocp.gp', 'gp_Pnt'),): "NCollection_Array1__gp_Pnt",
    (('nanoocp.gp', 'gp_Pnt2d'),): "NCollection_Array1__gp_Pnt2d",
    (('nanoocp.gp', 'gp_Trsf'),): "NCollection_Array1__gp_Trsf",
    (('nanoocp.gp', 'gp_Vec'),): "NCollection_Array1__gp_Vec",
    (('nanoocp.gp', 'gp_Vec2d'),): "NCollection_Array1__gp_Vec2d",
    (('nanoocp.gp', 'gp_XY'),): "NCollection_Array1__gp_XY",
    (('nanoocp.gp', 'gp_XYZ'),): "NCollection_Array1__gp_XYZ",
    (('builtins', 'int'),): "NCollection_Array1__int",
    (('nanoocp.NCollection', 'NCollection_HArray1__double'),): "NCollection_Array1__opencascade_handle__NCollection_HArray1__double",
    (('nanoocp.NCollection', 'NCollection_HArray1__int'),): "NCollection_Array1__opencascade_handle__NCollection_HArray1__int",
    (('nanoocp.NCollection', 'NCollection_HSequence__Handle_StepElement_CurveElementPurposeMember'),): "NCollection_Array1__opencascade_handle__NCollection_HSequence__Handle_StepElement_CurveElementPurposeMember",
    (('nanoocp.NCollection', 'NCollection_HSequence__Handle_StepElement_SurfaceElementPurposeMember'),): "NCollection_Array1__opencascade_handle__NCollection_HSequence__Handle_StepElement_SurfaceElementPurposeMember",
})
NCollection_Array2 = _Template("NCollection_Array2", "nanoocp.NCollection", {
    (('nanoocp.Geom', 'Geom_Surface.ResD1'),): "NCollection_Array2__Geom_Surface_ResD1",
    (('nanoocp.Geom', 'Geom_Surface.ResD2'),): "NCollection_Array2__Geom_Surface_ResD2",
    (('nanoocp.Geom', 'Geom_Surface.ResD3'),): "NCollection_Array2__Geom_Surface_ResD3",
    (('nanoocp.Geom', 'Geom_BezierSurface'),): "NCollection_Array2__Handle_Geom_BezierSurface",
    (('nanoocp.Geom', 'Geom_Surface'),): "NCollection_Array2__Handle_Geom_Surface",
    (('nanoocp.Standard', 'Standard_Transient'),): "NCollection_Array2__Handle_Standard_Transient",
    (('nanoocp.StepGeom', 'StepGeom_CartesianPoint'),): "NCollection_Array2__Handle_StepGeom_CartesianPoint",
    (('nanoocp.StepGeom', 'StepGeom_SurfacePatch'),): "NCollection_Array2__Handle_StepGeom_SurfacePatch",
    (('nanoocp.TopoDS', 'TopoDS_Shape'),): "NCollection_Array2__TopoDS_Shape",
    (('builtins', 'float'),): "NCollection_Array2__double",
    (('nanoocp.gp', 'gp_Pnt'),): "NCollection_Array2__gp_Pnt",
    (('nanoocp.gp', 'gp_Pnt2d'),): "NCollection_Array2__gp_Pnt2d",
    (('nanoocp.gp', 'gp_Vec'),): "NCollection_Array2__gp_Vec",
    (('nanoocp.gp', 'gp_XYZ'),): "NCollection_Array2__gp_XYZ",
    (('builtins', 'int'),): "NCollection_Array2__int",
    (('nanoocp.NCollection', 'NCollection_HArray1__double'),): "NCollection_Array2__opencascade_handle__NCollection_HArray1__double",
    (('nanoocp.NCollection', 'NCollection_HArray1__int'),): "NCollection_Array2__opencascade_handle__NCollection_HArray1__int",
})
NCollection_DataMap = _Template("NCollection_DataMap", "nanoocp.NCollection", {
    (('nanoocp.BRepGraph', 'BRepGraph_ItemUID'), ('nanoocp.NCollection', 'NCollection_LinearVector__BRepGraph_ItemUID')): "NCollection_DataMap__BRepGraph_ItemUID__NCollection_LinearVector__BRepGraph_ItemUID",
    (('nanoocp.BRepGraph', 'BRepGraph_NodeId'), ('nanoocp.NCollection', 'NCollection_LinearVector__BRepGraph_NodeId')): "NCollection_DataMap__BRepGraph_NodeId__NCollection_LinearVector__BRepGraph_NodeId",
    (('nanoocp.BRepGraph', 'BRepGraph_UID'), ('nanoocp.NCollection', 'NCollection_LinearVector__BRepGraph_UID')): "NCollection_DataMap__BRepGraph_UID__NCollection_LinearVector__BRepGraph_UID",
    (('nanoocp.Graphic3d', 'Graphic3d_Aspects'), ('nanoocp.Graphic3d', 'Graphic3d_Aspects')): "NCollection_DataMap__Handle_Graphic3d_Aspects__Handle_Graphic3d_Aspects",
    (('nanoocp.SelectMgr', 'SelectMgr_EntityOwner'), ('builtins', 'int')): "NCollection_DataMap__Handle_SelectMgr_EntityOwner__int",
    (('nanoocp.Standard', 'Standard_Transient'), ('nanoocp.Standard', 'Standard_Transient')): "NCollection_DataMap__Handle_Standard_Transient__Handle_Standard_Transient",
    (('nanoocp.Standard', 'Standard_Transient'), ('nanoocp.NCollection', 'NCollection_List__Message_Msg')): "NCollection_DataMap__Handle_Standard_Transient__NCollection_List__Message_Msg",
    (('nanoocp.StepRepr', 'StepRepr_RepresentationItem'), ('nanoocp.TopoDS', 'TopoDS_Shape')): "NCollection_DataMap__Handle_StepRepr_RepresentationItem__TopoDS_Shape",
    (('nanoocp.StepShape', 'StepShape_TopologicalRepresentationItem'), ('nanoocp.TopoDS', 'TopoDS_Shape')): "NCollection_DataMap__Handle_StepShape_TopologicalRepresentationItem__TopoDS_Shape",
    (('nanoocp.TDF', 'TDF_Attribute'), ('nanoocp.TDF', 'TDF_Attribute')): "NCollection_DataMap__Handle_TDF_Attribute__Handle_TDF_Attribute",
    (('nanoocp.XCAFDimTolObjects', 'XCAFDimTolObjects_GeomToleranceObject'), ('nanoocp.XCAFDimTolObjects', 'XCAFDimTolObjects_DatumObject')): "NCollection_DataMap__Handle_XCAFDimTolObjects_GeomToleranceObject__Handle_XCAFDimTolObjects_DatumObject",
    (('nanoocp.XCAFDoc', 'XCAFDoc_VisMaterial'), ('nanoocp.XCAFDoc', 'XCAFDoc_VisMaterial')): "NCollection_DataMap__Handle_XCAFDoc_VisMaterial__Handle_XCAFDoc_VisMaterial",
    (('nanoocp.TCollection', 'TCollection_AsciiString'), ('nanoocp.STEPCAFControl', 'STEPCAFControl_ExternFile')): "NCollection_DataMap__TCollection_AsciiString__Handle_STEPCAFControl_ExternFile",
    (('nanoocp.TCollection', 'TCollection_AsciiString'), ('nanoocp.Standard', 'Standard_Transient')): "NCollection_DataMap__TCollection_AsciiString__Handle_Standard_Transient",
    (('nanoocp.TCollection', 'TCollection_AsciiString'), ('nanoocp.XmlMDF', 'XmlMDF_ADriver')): "NCollection_DataMap__TCollection_AsciiString__Handle_XmlMDF_ADriver",
    (('nanoocp.TCollection', 'TCollection_AsciiString'), ('nanoocp.NCollection', 'NCollection_IndexedDataMap__TCollection_AsciiString__Handle_DE_ConfigurationNode')): "NCollection_DataMap__TCollection_AsciiString__NCollection_IndexedDataMap__TCollection_AsciiString__Handle_DE_ConfigurationNode",
    (('nanoocp.TCollection', 'TCollection_AsciiString'), ('nanoocp.TCollection', 'TCollection_AsciiString')): "NCollection_DataMap__TCollection_AsciiString__TCollection_AsciiString",
    (('nanoocp.TCollection', 'TCollection_AsciiString'), ('nanoocp.TopoDS', 'TopoDS_Shape')): "NCollection_DataMap__TCollection_AsciiString__TopoDS_Shape",
    (('nanoocp.TCollection', 'TCollection_AsciiString'), ('builtins', 'int')): "NCollection_DataMap__TCollection_AsciiString__int",
    (('nanoocp.TCollection', 'TCollection_ExtendedString'), ('nanoocp.CDM', 'CDM_MetaData')): "NCollection_DataMap__TCollection_ExtendedString__Handle_CDM_MetaData",
    (('nanoocp.TCollection', 'TCollection_ExtendedString'), ('nanoocp.TCollection', 'TCollection_ExtendedString')): "NCollection_DataMap__TCollection_ExtendedString__TCollection_ExtendedString",
    (('nanoocp.TCollection', 'TCollection_ExtendedString'), ('builtins', 'float')): "NCollection_DataMap__TCollection_ExtendedString__double",
    (('nanoocp.TCollection', 'TCollection_ExtendedString'), ('builtins', 'int')): "NCollection_DataMap__TCollection_ExtendedString__int",
    (('nanoocp.TCollection', 'TCollection_ExtendedString'), ('nanoocp.NCollection', 'NCollection_HArray1__double')): "NCollection_DataMap__TCollection_ExtendedString__opencascade_handle__NCollection_HArray1__double",
    (('nanoocp.TCollection', 'TCollection_ExtendedString'), ('nanoocp.NCollection', 'NCollection_HArray1__int')): "NCollection_DataMap__TCollection_ExtendedString__opencascade_handle__NCollection_HArray1__int",
    (('nanoocp.TDF', 'TDF_Label'), ('nanoocp.TDF', 'TDF_Label')): "NCollection_DataMap__TDF_Label__TDF_Label",
    (('nanoocp.TDF', 'TDF_Label'), ('builtins', 'int')): "NCollection_DataMap__TDF_Label__int",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.BRepGraph', 'BRepGraph_NodeId'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_DataMap__TopoDS_Shape__BRepGraph_NodeId__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.BRepOffset', 'BRepOffset_Offset'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_DataMap__TopoDS_Shape__BRepOffset_Offset__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.BRepTopAdaptor', 'BRepTopAdaptor_Tool'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_DataMap__TopoDS_Shape__BRepTopAdaptor_Tool__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.Bnd', 'Bnd_Box'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_DataMap__TopoDS_Shape__Bnd_Box__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.AIS', 'AIS_ColoredDrawer'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_DataMap__TopoDS_Shape__Handle_AIS_ColoredDrawer__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.Standard', 'Standard_Transient'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_DataMap__TopoDS_Shape__Handle_Standard_Transient__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.NCollection', 'NCollection_List__Message_Msg'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_DataMap__TopoDS_Shape__NCollection_List__Message_Msg__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.NCollection', 'NCollection_List__TopoDS_Shape'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_DataMap__TopoDS_Shape__NCollection_List__TopoDS_Shape__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.NCollection', 'NCollection_List__double'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_DataMap__TopoDS_Shape__NCollection_List__double__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.TDF', 'TDF_Label'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_DataMap__TopoDS_Shape__TDF_Label__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.TopAbs', 'TopAbs_State'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_DataMap__TopoDS_Shape__TopAbs_State__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.TopOpeBRepDS', 'TopOpeBRepDS_ListOfShapeOn1State'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_DataMap__TopoDS_Shape__TopOpeBRepDS_ListOfShapeOn1State__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_DataMap__TopoDS_Shape__TopoDS_Shape__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('builtins', 'float'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_DataMap__TopoDS_Shape__double__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('builtins', 'int')): "NCollection_DataMap__TopoDS_Shape__int",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('builtins', 'int'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_DataMap__TopoDS_Shape__int__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.NCollection', 'NCollection_HArray2__TopoDS_Shape'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_DataMap__TopoDS_Shape__opencascade_handle__NCollection_HArray2__TopoDS_Shape__TopTools_ShapeMapHasher",
    (('nanoocp.gp', 'gp_Pnt'), ('nanoocp.Standard', 'Standard_Transient')): "NCollection_DataMap__gp_Pnt__Handle_Standard_Transient",
    (('builtins', 'int'), ('nanoocp.MAT', 'MAT_BasicElt')): "NCollection_DataMap__int__Handle_MAT_BasicElt",
    (('builtins', 'int'), ('nanoocp.Standard', 'Standard_Transient')): "NCollection_DataMap__int__Handle_Standard_Transient",
    (('builtins', 'int'), ('nanoocp.NCollection', 'NCollection_List__TopoDS_Shape')): "NCollection_DataMap__int__NCollection_List__TopoDS_Shape",
    (('builtins', 'int'), ('nanoocp.TColStd', 'TColStd_PackedMapOfInteger')): "NCollection_DataMap__int__NCollection_PackedMap__int",
    (('builtins', 'int'), ('nanoocp.NCollection', 'NCollection_Shared__NCollection_List__int')): "NCollection_DataMap__int__NCollection_Shared__NCollection_List__int",
    (('builtins', 'int'), ('nanoocp.TopoDS', 'TopoDS_Shape')): "NCollection_DataMap__int__TopoDS_Shape",
    (('builtins', 'int'), ('builtins', 'bool')): "NCollection_DataMap__int__bool",
    (('builtins', 'int'), ('builtins', 'float')): "NCollection_DataMap__int__double",
    (('builtins', 'int'), ('builtins', 'int')): "NCollection_DataMap__int__int",
})
NCollection_DoubleMap = _Template("NCollection_DoubleMap", "nanoocp.NCollection", {
    (('builtins', 'int'), ('nanoocp.TCollection', 'TCollection_AsciiString')): "NCollection_DoubleMap__int__TCollection_AsciiString",
    (('builtins', 'int'), ('nanoocp.TDF', 'TDF_Label')): "NCollection_DoubleMap__int__TDF_Label",
})
NCollection_DynamicArray = _Template("NCollection_DynamicArray", "nanoocp.NCollection", {
    (('nanoocp.BOPDS', 'BOPDS_Curve'),): "NCollection_DynamicArray__BOPDS_Curve",
    (('nanoocp.BOPDS', 'BOPDS_FaceInfo'),): "NCollection_DynamicArray__BOPDS_FaceInfo",
    (('nanoocp.BOPDS', 'BOPDS_InterfEE'),): "NCollection_DynamicArray__BOPDS_InterfEE",
    (('nanoocp.BOPDS', 'BOPDS_InterfEF'),): "NCollection_DynamicArray__BOPDS_InterfEF",
    (('nanoocp.BOPDS', 'BOPDS_InterfEZ'),): "NCollection_DynamicArray__BOPDS_InterfEZ",
    (('nanoocp.BOPDS', 'BOPDS_InterfFF'),): "NCollection_DynamicArray__BOPDS_InterfFF",
    (('nanoocp.BOPDS', 'BOPDS_InterfFZ'),): "NCollection_DynamicArray__BOPDS_InterfFZ",
    (('nanoocp.BOPDS', 'BOPDS_InterfVE'),): "NCollection_DynamicArray__BOPDS_InterfVE",
    (('nanoocp.BOPDS', 'BOPDS_InterfVF'),): "NCollection_DynamicArray__BOPDS_InterfVF",
    (('nanoocp.BOPDS', 'BOPDS_InterfVV'),): "NCollection_DynamicArray__BOPDS_InterfVV",
    (('nanoocp.BOPDS', 'BOPDS_InterfVZ'),): "NCollection_DynamicArray__BOPDS_InterfVZ",
    (('nanoocp.BOPDS', 'BOPDS_InterfZZ'),): "NCollection_DynamicArray__BOPDS_InterfZZ",
    (('nanoocp.BOPDS', 'BOPDS_Point'),): "NCollection_DynamicArray__BOPDS_Point",
    (('nanoocp.BRepExtrema', 'BRepExtrema_ProximityDistTool.ProxPnt_Status'),): "NCollection_DynamicArray__BRepExtrema_ProximityDistTool_ProxPnt_Status",
    (('nanoocp.BRepMesh', 'BRepMesh_Circle'),): "NCollection_DynamicArray__BRepMesh_Circle",
    (('nanoocp.BRepMesh', 'BRepMesh_Triangle'),): "NCollection_DynamicArray__BRepMesh_Triangle",
    (('nanoocp.BRepMesh', 'BRepMesh_Vertex'),): "NCollection_DynamicArray__BRepMesh_Vertex",
    (('nanoocp.ExtremaPC', 'ExtremumResult'),): "NCollection_DynamicArray__ExtremaPC_ExtremumResult",
    (('nanoocp.Adaptor3d', 'Adaptor3d_Surface'),): "NCollection_DynamicArray__Handle_Adaptor3d_Surface",
    (('nanoocp.IMeshData', 'IMeshData_Edge'),): "NCollection_DynamicArray__Handle_IMeshData_Edge",
    (('nanoocp.IMeshData', 'IMeshData_Face'),): "NCollection_DynamicArray__Handle_IMeshData_Face",
    (('nanoocp.IMeshData', 'IMeshData_PCurve'),): "NCollection_DynamicArray__Handle_IMeshData_PCurve",
    (('nanoocp.IMeshData', 'IMeshData_Wire'),): "NCollection_DynamicArray__Handle_IMeshData_Wire",
    (('nanoocp.Select3D', 'Select3D_SensitiveEntity'),): "NCollection_DynamicArray__Handle_Select3D_SensitiveEntity",
    (('nanoocp.SelectMgr', 'SelectMgr_SensitiveEntity'),): "NCollection_DynamicArray__Handle_SelectMgr_SensitiveEntity",
    (('nanoocp.Standard', 'Standard_Transient'),): "NCollection_DynamicArray__Handle_Standard_Transient",
    (('nanoocp.IntPatch', 'IntPatch_BVHTraversal.TrianglePair'),): "NCollection_DynamicArray__IntPatch_BVHTraversal_TrianglePair",
    (('nanoocp.MathRoot', 'NullInterval'),): "NCollection_DynamicArray__MathRoot_NullInterval",
    (('nanoocp.NCollection', 'NCollection_List__Handle_BOPDS_PaveBlock'),): "NCollection_DynamicArray__NCollection_List__Handle_BOPDS_PaveBlock",
    (('nanoocp.BVH', 'BVH_Vec2f'),): "NCollection_DynamicArray__NCollection_Vec2__float",
    (('nanoocp.BVH', 'BVH_Vec4d'),): "NCollection_DynamicArray__NCollection_Vec4__double",
    (('nanoocp.Poly', 'Poly_CoherentLink'),): "NCollection_DynamicArray__Poly_CoherentLink",
    (('nanoocp.Poly', 'Poly_CoherentNode'),): "NCollection_DynamicArray__Poly_CoherentNode",
    (('nanoocp.Poly', 'Poly_CoherentTriangle'),): "NCollection_DynamicArray__Poly_CoherentTriangle",
    (('nanoocp.TopAbs', 'TopAbs_Orientation'),): "NCollection_DynamicArray__TopAbs_Orientation",
    (('nanoocp.TopoDS', 'TopoDS_Shape'),): "NCollection_DynamicArray__TopoDS_Shape",
    (('builtins', 'bool'),): "NCollection_DynamicArray__bool",
    (('builtins', 'float'),): "NCollection_DynamicArray__double",
    (('nanoocp.gp', 'gp_Pnt2d'),): "NCollection_DynamicArray__gp_Pnt2d",
    (('nanoocp.gp', 'gp_XYZ'),): "NCollection_DynamicArray__gp_XYZ",
    (('builtins', 'int'),): "NCollection_DynamicArray__int",
    (('nanoocp.NCollection', 'NCollection_HSequence__int'),): "NCollection_DynamicArray__opencascade_handle__NCollection_HSequence__int",
})
NCollection_HArray1 = _Template("NCollection_HArray1", "nanoocp.NCollection", {
    (('nanoocp.AppParCurves', 'AppParCurves_ConstraintCouple'),): "NCollection_HArray1__AppParCurves_ConstraintCouple",
    (('nanoocp.Bnd', 'Bnd_Box'),): "NCollection_HArray1__Bnd_Box",
    (('nanoocp.ChFiDS', 'ChFiDS_CircSection'),): "NCollection_HArray1__ChFiDS_CircSection",
    (('nanoocp.HLRAlgo', 'HLRAlgo_PolyHidingData'),): "NCollection_HArray1__HLRAlgo_PolyHidingData",
    (('nanoocp.HLRAlgo', 'HLRAlgo_TriangleData'),): "NCollection_HArray1__HLRAlgo_TriangleData",
    (('nanoocp.Adaptor3d', 'Adaptor3d_Curve'),): "NCollection_HArray1__Handle_Adaptor3d_Curve",
    (('nanoocp.Geom2d', 'Geom2d_BSplineCurve'),): "NCollection_HArray1__Handle_Geom2d_BSplineCurve",
    (('nanoocp.Geom2d', 'Geom2d_Curve'),): "NCollection_HArray1__Handle_Geom2d_Curve",
    (('nanoocp.Geom', 'Geom_BSplineCurve'),): "NCollection_HArray1__Handle_Geom_BSplineCurve",
    (('nanoocp.Geom', 'Geom_Curve'),): "NCollection_HArray1__Handle_Geom_Curve",
    (('nanoocp.IGESAppli', 'IGESAppli_FiniteElement'),): "NCollection_HArray1__Handle_IGESAppli_FiniteElement",
    (('nanoocp.IGESAppli', 'IGESAppli_Node'),): "NCollection_HArray1__Handle_IGESAppli_Node",
    (('nanoocp.IGESData', 'IGESData_IGESEntity'),): "NCollection_HArray1__Handle_IGESData_IGESEntity",
    (('nanoocp.IGESData', 'IGESData_LineFontEntity'),): "NCollection_HArray1__Handle_IGESData_LineFontEntity",
    (('nanoocp.IGESData', 'IGESData_ViewKindEntity'),): "NCollection_HArray1__Handle_IGESData_ViewKindEntity",
    (('nanoocp.IGESDefs', 'IGESDefs_TabularData'),): "NCollection_HArray1__Handle_IGESDefs_TabularData",
    (('nanoocp.IGESDimen', 'IGESDimen_GeneralNote'),): "NCollection_HArray1__Handle_IGESDimen_GeneralNote",
    (('nanoocp.IGESDimen', 'IGESDimen_LeaderArrow'),): "NCollection_HArray1__Handle_IGESDimen_LeaderArrow",
    (('nanoocp.IGESDraw', 'IGESDraw_ConnectPoint'),): "NCollection_HArray1__Handle_IGESDraw_ConnectPoint",
    (('nanoocp.IGESGeom', 'IGESGeom_Boundary'),): "NCollection_HArray1__Handle_IGESGeom_Boundary",
    (('nanoocp.IGESGeom', 'IGESGeom_CurveOnSurface'),): "NCollection_HArray1__Handle_IGESGeom_CurveOnSurface",
    (('nanoocp.IGESGeom', 'IGESGeom_TransformationMatrix'),): "NCollection_HArray1__Handle_IGESGeom_TransformationMatrix",
    (('nanoocp.IGESGraph', 'IGESGraph_Color'),): "NCollection_HArray1__Handle_IGESGraph_Color",
    (('nanoocp.IGESGraph', 'IGESGraph_TextDisplayTemplate'),): "NCollection_HArray1__Handle_IGESGraph_TextDisplayTemplate",
    (('nanoocp.IGESGraph', 'IGESGraph_TextFontDef'),): "NCollection_HArray1__Handle_IGESGraph_TextFontDef",
    (('nanoocp.IGESSolid', 'IGESSolid_Face'),): "NCollection_HArray1__Handle_IGESSolid_Face",
    (('nanoocp.IGESSolid', 'IGESSolid_Loop'),): "NCollection_HArray1__Handle_IGESSolid_Loop",
    (('nanoocp.IGESSolid', 'IGESSolid_Shell'),): "NCollection_HArray1__Handle_IGESSolid_Shell",
    (('nanoocp.IGESSolid', 'IGESSolid_VertexList'),): "NCollection_HArray1__Handle_IGESSolid_VertexList",
    (('nanoocp.Standard', 'Standard_Persistent'),): "NCollection_HArray1__Handle_Standard_Persistent",
    (('nanoocp.Standard', 'Standard_Transient'),): "NCollection_HArray1__Handle_Standard_Transient",
    (('nanoocp.StepBasic', 'StepBasic_Approval'),): "NCollection_HArray1__Handle_StepBasic_Approval",
    (('nanoocp.StepBasic', 'StepBasic_DerivedUnitElement'),): "NCollection_HArray1__Handle_StepBasic_DerivedUnitElement",
    (('nanoocp.StepBasic', 'StepBasic_Document'),): "NCollection_HArray1__Handle_StepBasic_Document",
    (('nanoocp.StepBasic', 'StepBasic_NamedUnit'),): "NCollection_HArray1__Handle_StepBasic_NamedUnit",
    (('nanoocp.StepBasic', 'StepBasic_Organization'),): "NCollection_HArray1__Handle_StepBasic_Organization",
    (('nanoocp.StepBasic', 'StepBasic_Person'),): "NCollection_HArray1__Handle_StepBasic_Person",
    (('nanoocp.StepBasic', 'StepBasic_Product'),): "NCollection_HArray1__Handle_StepBasic_Product",
    (('nanoocp.StepBasic', 'StepBasic_ProductContext'),): "NCollection_HArray1__Handle_StepBasic_ProductContext",
    (('nanoocp.StepBasic', 'StepBasic_UncertaintyMeasureWithUnit'),): "NCollection_HArray1__Handle_StepBasic_UncertaintyMeasureWithUnit",
    (('nanoocp.StepDimTol', 'StepDimTol_DatumReference'),): "NCollection_HArray1__Handle_StepDimTol_DatumReference",
    (('nanoocp.StepDimTol', 'StepDimTol_DatumReferenceCompartment'),): "NCollection_HArray1__Handle_StepDimTol_DatumReferenceCompartment",
    (('nanoocp.StepDimTol', 'StepDimTol_DatumReferenceElement'),): "NCollection_HArray1__Handle_StepDimTol_DatumReferenceElement",
    (('nanoocp.StepElement', 'StepElement_CurveElementEndReleasePacket'),): "NCollection_HArray1__Handle_StepElement_CurveElementEndReleasePacket",
    (('nanoocp.StepElement', 'StepElement_CurveElementSectionDefinition'),): "NCollection_HArray1__Handle_StepElement_CurveElementSectionDefinition",
    (('nanoocp.StepElement', 'StepElement_SurfaceSection'),): "NCollection_HArray1__Handle_StepElement_SurfaceSection",
    (('nanoocp.StepElement', 'StepElement_VolumeElementPurposeMember'),): "NCollection_HArray1__Handle_StepElement_VolumeElementPurposeMember",
    (('nanoocp.StepFEA', 'StepFEA_CurveElementEndOffset'),): "NCollection_HArray1__Handle_StepFEA_CurveElementEndOffset",
    (('nanoocp.StepFEA', 'StepFEA_CurveElementEndRelease'),): "NCollection_HArray1__Handle_StepFEA_CurveElementEndRelease",
    (('nanoocp.StepFEA', 'StepFEA_CurveElementInterval'),): "NCollection_HArray1__Handle_StepFEA_CurveElementInterval",
    (('nanoocp.StepFEA', 'StepFEA_ElementRepresentation'),): "NCollection_HArray1__Handle_StepFEA_ElementRepresentation",
    (('nanoocp.StepFEA', 'StepFEA_NodeRepresentation'),): "NCollection_HArray1__Handle_StepFEA_NodeRepresentation",
    (('nanoocp.StepGeom', 'StepGeom_CartesianPoint'),): "NCollection_HArray1__Handle_StepGeom_CartesianPoint",
    (('nanoocp.StepGeom', 'StepGeom_CompositeCurveSegment'),): "NCollection_HArray1__Handle_StepGeom_CompositeCurveSegment",
    (('nanoocp.StepRepr', 'StepRepr_MaterialPropertyRepresentation'),): "NCollection_HArray1__Handle_StepRepr_MaterialPropertyRepresentation",
    (('nanoocp.StepRepr', 'StepRepr_PropertyDefinitionRepresentation'),): "NCollection_HArray1__Handle_StepRepr_PropertyDefinitionRepresentation",
    (('nanoocp.StepRepr', 'StepRepr_RepresentationItem'),): "NCollection_HArray1__Handle_StepRepr_RepresentationItem",
    (('nanoocp.StepRepr', 'StepRepr_ShapeAspect'),): "NCollection_HArray1__Handle_StepRepr_ShapeAspect",
    (('nanoocp.StepShape', 'StepShape_ConnectedEdgeSet'),): "NCollection_HArray1__Handle_StepShape_ConnectedEdgeSet",
    (('nanoocp.StepShape', 'StepShape_ConnectedFaceSet'),): "NCollection_HArray1__Handle_StepShape_ConnectedFaceSet",
    (('nanoocp.StepShape', 'StepShape_Edge'),): "NCollection_HArray1__Handle_StepShape_Edge",
    (('nanoocp.StepShape', 'StepShape_Face'),): "NCollection_HArray1__Handle_StepShape_Face",
    (('nanoocp.StepShape', 'StepShape_FaceBound'),): "NCollection_HArray1__Handle_StepShape_FaceBound",
    (('nanoocp.StepShape', 'StepShape_OrientedClosedShell'),): "NCollection_HArray1__Handle_StepShape_OrientedClosedShell",
    (('nanoocp.StepShape', 'StepShape_OrientedEdge'),): "NCollection_HArray1__Handle_StepShape_OrientedEdge",
    (('nanoocp.StepVisual', 'StepVisual_CurveStyleFontPattern'),): "NCollection_HArray1__Handle_StepVisual_CurveStyleFontPattern",
    (('nanoocp.StepVisual', 'StepVisual_PresentationStyleAssignment'),): "NCollection_HArray1__Handle_StepVisual_PresentationStyleAssignment",
    (('nanoocp.StepVisual', 'StepVisual_TessellatedStructuredItem'),): "NCollection_HArray1__Handle_StepVisual_TessellatedStructuredItem",
    (('nanoocp.TCollection', 'TCollection_HAsciiString'),): "NCollection_HArray1__Handle_TCollection_HAsciiString",
    (('nanoocp.NCollection', 'NCollection_List__int'),): "NCollection_HArray1__NCollection_List__int",
    (('nanoocp.Poly', 'Poly_Triangle'),): "NCollection_HArray1__Poly_Triangle",
    (('nanoocp.Quantity', 'Quantity_Color'),): "NCollection_HArray1__Quantity_Color",
    (('nanoocp.StepAP203', 'StepAP203_ApprovedItem'),): "NCollection_HArray1__StepAP203_ApprovedItem",
    (('nanoocp.StepAP203', 'StepAP203_CertifiedItem'),): "NCollection_HArray1__StepAP203_CertifiedItem",
    (('nanoocp.StepAP203', 'StepAP203_ChangeRequestItem'),): "NCollection_HArray1__StepAP203_ChangeRequestItem",
    (('nanoocp.StepAP203', 'StepAP203_ClassifiedItem'),): "NCollection_HArray1__StepAP203_ClassifiedItem",
    (('nanoocp.StepAP203', 'StepAP203_ContractedItem'),): "NCollection_HArray1__StepAP203_ContractedItem",
    (('nanoocp.StepAP203', 'StepAP203_DateTimeItem'),): "NCollection_HArray1__StepAP203_DateTimeItem",
    (('nanoocp.StepAP203', 'StepAP203_PersonOrganizationItem'),): "NCollection_HArray1__StepAP203_PersonOrganizationItem",
    (('nanoocp.StepAP203', 'StepAP203_SpecifiedItem'),): "NCollection_HArray1__StepAP203_SpecifiedItem",
    (('nanoocp.StepAP203', 'StepAP203_StartRequestItem'),): "NCollection_HArray1__StepAP203_StartRequestItem",
    (('nanoocp.StepAP203', 'StepAP203_WorkItem'),): "NCollection_HArray1__StepAP203_WorkItem",
    (('nanoocp.StepAP214', 'StepAP214_ApprovalItem'),): "NCollection_HArray1__StepAP214_ApprovalItem",
    (('nanoocp.StepAP214', 'StepAP214_AutoDesignDateAndPersonItem'),): "NCollection_HArray1__StepAP214_AutoDesignDateAndPersonItem",
    (('nanoocp.StepAP214', 'StepAP214_AutoDesignDateAndTimeItem'),): "NCollection_HArray1__StepAP214_AutoDesignDateAndTimeItem",
    (('nanoocp.StepAP214', 'StepAP214_AutoDesignDatedItem'),): "NCollection_HArray1__StepAP214_AutoDesignDatedItem",
    (('nanoocp.StepAP214', 'StepAP214_AutoDesignGeneralOrgItem'),): "NCollection_HArray1__StepAP214_AutoDesignGeneralOrgItem",
    (('nanoocp.StepAP214', 'StepAP214_AutoDesignGroupedItem'),): "NCollection_HArray1__StepAP214_AutoDesignGroupedItem",
    (('nanoocp.StepAP214', 'StepAP214_AutoDesignPresentedItemSelect'),): "NCollection_HArray1__StepAP214_AutoDesignPresentedItemSelect",
    (('nanoocp.StepAP214', 'StepAP214_AutoDesignReferencingItem'),): "NCollection_HArray1__StepAP214_AutoDesignReferencingItem",
    (('nanoocp.StepAP214', 'StepAP214_DateAndTimeItem'),): "NCollection_HArray1__StepAP214_DateAndTimeItem",
    (('nanoocp.StepAP214', 'StepAP214_DateItem'),): "NCollection_HArray1__StepAP214_DateItem",
    (('nanoocp.StepAP214', 'StepAP214_DocumentReferenceItem'),): "NCollection_HArray1__StepAP214_DocumentReferenceItem",
    (('nanoocp.StepAP214', 'StepAP214_ExternalIdentificationItem'),): "NCollection_HArray1__StepAP214_ExternalIdentificationItem",
    (('nanoocp.StepAP214', 'StepAP214_GroupItem'),): "NCollection_HArray1__StepAP214_GroupItem",
    (('nanoocp.StepAP214', 'StepAP214_OrganizationItem'),): "NCollection_HArray1__StepAP214_OrganizationItem",
    (('nanoocp.StepAP214', 'StepAP214_PersonAndOrganizationItem'),): "NCollection_HArray1__StepAP214_PersonAndOrganizationItem",
    (('nanoocp.StepAP214', 'StepAP214_PresentedItemSelect'),): "NCollection_HArray1__StepAP214_PresentedItemSelect",
    (('nanoocp.StepAP214', 'StepAP214_SecurityClassificationItem'),): "NCollection_HArray1__StepAP214_SecurityClassificationItem",
    (('nanoocp.StepDimTol', 'StepDimTol_DatumReferenceModifier'),): "NCollection_HArray1__StepDimTol_DatumReferenceModifier",
    (('nanoocp.StepDimTol', 'StepDimTol_DatumSystemOrReference'),): "NCollection_HArray1__StepDimTol_DatumSystemOrReference",
    (('nanoocp.StepDimTol', 'StepDimTol_GeometricToleranceModifier'),): "NCollection_HArray1__StepDimTol_GeometricToleranceModifier",
    (('nanoocp.StepDimTol', 'StepDimTol_ToleranceZoneTarget'),): "NCollection_HArray1__StepDimTol_ToleranceZoneTarget",
    (('nanoocp.StepElement', 'StepElement_MeasureOrUnspecifiedValue'),): "NCollection_HArray1__StepElement_MeasureOrUnspecifiedValue",
    (('nanoocp.StepFEA', 'StepFEA_DegreeOfFreedom'),): "NCollection_HArray1__StepFEA_DegreeOfFreedom",
    (('nanoocp.StepGeom', 'StepGeom_PcurveOrSurface'),): "NCollection_HArray1__StepGeom_PcurveOrSurface",
    (('nanoocp.StepGeom', 'StepGeom_SurfaceBoundary'),): "NCollection_HArray1__StepGeom_SurfaceBoundary",
    (('nanoocp.StepGeom', 'StepGeom_TrimmingSelect'),): "NCollection_HArray1__StepGeom_TrimmingSelect",
    (('nanoocp.StepShape', 'StepShape_GeometricSetSelect'),): "NCollection_HArray1__StepShape_GeometricSetSelect",
    (('nanoocp.StepShape', 'StepShape_ShapeDimensionRepresentationItem'),): "NCollection_HArray1__StepShape_ShapeDimensionRepresentationItem",
    (('nanoocp.StepShape', 'StepShape_Shell'),): "NCollection_HArray1__StepShape_Shell",
    (('nanoocp.StepShape', 'StepShape_ValueQualifier'),): "NCollection_HArray1__StepShape_ValueQualifier",
    (('nanoocp.StepVisual', 'StepVisual_AnnotationPlaneElement'),): "NCollection_HArray1__StepVisual_AnnotationPlaneElement",
    (('nanoocp.StepVisual', 'StepVisual_BoxCharacteristicSelect'),): "NCollection_HArray1__StepVisual_BoxCharacteristicSelect",
    (('nanoocp.StepVisual', 'StepVisual_CameraModelD3MultiClippingInterectionSelect'),): "NCollection_HArray1__StepVisual_CameraModelD3MultiClippingInterectionSelect",
    (('nanoocp.StepVisual', 'StepVisual_CameraModelD3MultiClippingUnionSelect'),): "NCollection_HArray1__StepVisual_CameraModelD3MultiClippingUnionSelect",
    (('nanoocp.StepVisual', 'StepVisual_DirectionCountSelect'),): "NCollection_HArray1__StepVisual_DirectionCountSelect",
    (('nanoocp.StepVisual', 'StepVisual_DraughtingCalloutElement'),): "NCollection_HArray1__StepVisual_DraughtingCalloutElement",
    (('nanoocp.StepVisual', 'StepVisual_FillStyleSelect'),): "NCollection_HArray1__StepVisual_FillStyleSelect",
    (('nanoocp.StepVisual', 'StepVisual_InvisibleItem'),): "NCollection_HArray1__StepVisual_InvisibleItem",
    (('nanoocp.StepVisual', 'StepVisual_LayeredItem'),): "NCollection_HArray1__StepVisual_LayeredItem",
    (('nanoocp.StepVisual', 'StepVisual_PresentationStyleSelect'),): "NCollection_HArray1__StepVisual_PresentationStyleSelect",
    (('nanoocp.StepVisual', 'StepVisual_RenderingPropertiesSelect'),): "NCollection_HArray1__StepVisual_RenderingPropertiesSelect",
    (('nanoocp.StepVisual', 'StepVisual_StyleContextSelect'),): "NCollection_HArray1__StepVisual_StyleContextSelect",
    (('nanoocp.StepVisual', 'StepVisual_SurfaceStyleElementSelect'),): "NCollection_HArray1__StepVisual_SurfaceStyleElementSelect",
    (('nanoocp.StepVisual', 'StepVisual_TessellatedEdgeOrVertex'),): "NCollection_HArray1__StepVisual_TessellatedEdgeOrVertex",
    (('nanoocp.StepVisual', 'StepVisual_TextOrCharacter'),): "NCollection_HArray1__StepVisual_TextOrCharacter",
    (('nanoocp.TCollection', 'TCollection_AsciiString'),): "NCollection_HArray1__TCollection_AsciiString",
    (('nanoocp.TCollection', 'TCollection_ExtendedString'),): "NCollection_HArray1__TCollection_ExtendedString",
    (('nanoocp.TDF', 'TDF_Label'),): "NCollection_HArray1__TDF_Label",
    (('nanoocp.TopOpeBRep', 'TopOpeBRep_LineInter'),): "NCollection_HArray1__TopOpeBRep_LineInter",
    (('nanoocp.TopoDS', 'TopoDS_Shape'),): "NCollection_HArray1__TopoDS_Shape",
    (('builtins', 'bool'),): "NCollection_HArray1__bool",
    (('builtins', 'float'),): "NCollection_HArray1__double",
    (('nanoocp.gp', 'gp_Dir'),): "NCollection_HArray1__gp_Dir",
    (('nanoocp.gp', 'gp_Pnt'),): "NCollection_HArray1__gp_Pnt",
    (('nanoocp.gp', 'gp_Pnt2d'),): "NCollection_HArray1__gp_Pnt2d",
    (('nanoocp.gp', 'gp_XY'),): "NCollection_HArray1__gp_XY",
    (('nanoocp.gp', 'gp_XYZ'),): "NCollection_HArray1__gp_XYZ",
    (('builtins', 'int'),): "NCollection_HArray1__int",
    (('nanoocp.NCollection', 'NCollection_HSequence__Handle_StepElement_CurveElementPurposeMember'),): "NCollection_HArray1__opencascade_handle__NCollection_HSequence__Handle_StepElement_CurveElementPurposeMember",
    (('nanoocp.NCollection', 'NCollection_HSequence__Handle_StepElement_SurfaceElementPurposeMember'),): "NCollection_HArray1__opencascade_handle__NCollection_HSequence__Handle_StepElement_SurfaceElementPurposeMember",
})
NCollection_HArray2 = _Template("NCollection_HArray2", "nanoocp.NCollection", {
    (('nanoocp.Geom', 'Geom_Surface'),): "NCollection_HArray2__Handle_Geom_Surface",
    (('nanoocp.Standard', 'Standard_Transient'),): "NCollection_HArray2__Handle_Standard_Transient",
    (('nanoocp.StepGeom', 'StepGeom_CartesianPoint'),): "NCollection_HArray2__Handle_StepGeom_CartesianPoint",
    (('nanoocp.StepGeom', 'StepGeom_SurfacePatch'),): "NCollection_HArray2__Handle_StepGeom_SurfacePatch",
    (('nanoocp.TopoDS', 'TopoDS_Shape'),): "NCollection_HArray2__TopoDS_Shape",
    (('builtins', 'float'),): "NCollection_HArray2__double",
    (('nanoocp.gp', 'gp_Pnt'),): "NCollection_HArray2__gp_Pnt",
    (('nanoocp.gp', 'gp_Pnt2d'),): "NCollection_HArray2__gp_Pnt2d",
    (('nanoocp.gp', 'gp_XYZ'),): "NCollection_HArray2__gp_XYZ",
    (('builtins', 'int'),): "NCollection_HArray2__int",
    (('nanoocp.NCollection', 'NCollection_HArray1__double'),): "NCollection_HArray2__opencascade_handle__NCollection_HArray1__double",
    (('nanoocp.NCollection', 'NCollection_HArray1__int'),): "NCollection_HArray2__opencascade_handle__NCollection_HArray1__int",
})
NCollection_HSequence = _Template("NCollection_HSequence", "nanoocp.NCollection", {
    (('nanoocp.AIS', 'AIS_InteractiveObject'),): "NCollection_HSequence__Handle_AIS_InteractiveObject",
    (('nanoocp.ChFiDS', 'ChFiDS_SurfData'),): "NCollection_HSequence__Handle_ChFiDS_SurfData",
    (('nanoocp.Geom2d', 'Geom2d_BoundedCurve'),): "NCollection_HSequence__Handle_Geom2d_BoundedCurve",
    (('nanoocp.Geom', 'Geom_BoundedCurve'),): "NCollection_HSequence__Handle_Geom_BoundedCurve",
    (('nanoocp.STEPSelections', 'STEPSelections_AssemblyLink'),): "NCollection_HSequence__Handle_STEPSelections_AssemblyLink",
    (('nanoocp.ShapeAnalysis', 'ShapeAnalysis_FreeBoundData'),): "NCollection_HSequence__Handle_ShapeAnalysis_FreeBoundData",
    (('nanoocp.Standard', 'Standard_Transient'),): "NCollection_HSequence__Handle_Standard_Transient",
    (('nanoocp.StepElement', 'StepElement_CurveElementPurposeMember'),): "NCollection_HSequence__Handle_StepElement_CurveElementPurposeMember",
    (('nanoocp.StepElement', 'StepElement_CurveElementSectionDefinition'),): "NCollection_HSequence__Handle_StepElement_CurveElementSectionDefinition",
    (('nanoocp.StepElement', 'StepElement_ElementMaterial'),): "NCollection_HSequence__Handle_StepElement_ElementMaterial",
    (('nanoocp.StepElement', 'StepElement_SurfaceElementPurposeMember'),): "NCollection_HSequence__Handle_StepElement_SurfaceElementPurposeMember",
    (('nanoocp.StepFEA', 'StepFEA_ElementGeometricRelationship'),): "NCollection_HSequence__Handle_StepFEA_ElementGeometricRelationship",
    (('nanoocp.StepFEA', 'StepFEA_ElementRepresentation'),): "NCollection_HSequence__Handle_StepFEA_ElementRepresentation",
    (('nanoocp.Storage', 'Storage_Root'),): "NCollection_HSequence__Handle_Storage_Root",
    (('nanoocp.TCollection', 'TCollection_HAsciiString'),): "NCollection_HSequence__Handle_TCollection_HAsciiString",
    (('nanoocp.TCollection', 'TCollection_HExtendedString'),): "NCollection_HSequence__Handle_TCollection_HExtendedString",
    (('nanoocp.TransferBRep', 'TransferBRep_TransferResultInfo'),): "NCollection_HSequence__Handle_TransferBRep_TransferResultInfo",
    (('nanoocp.Transfer', 'Transfer_Finder'),): "NCollection_HSequence__Handle_Transfer_Finder",
    (('nanoocp.Units', 'Units_Quantity'),): "NCollection_HSequence__Handle_Units_Quantity",
    (('nanoocp.Units', 'Units_Token'),): "NCollection_HSequence__Handle_Units_Token",
    (('nanoocp.Units', 'Units_Unit'),): "NCollection_HSequence__Handle_Units_Unit",
    (('nanoocp.TCollection', 'TCollection_AsciiString'),): "NCollection_HSequence__TCollection_AsciiString",
    (('nanoocp.TCollection', 'TCollection_ExtendedString'),): "NCollection_HSequence__TCollection_ExtendedString",
    (('nanoocp.TopoDS', 'TopoDS_Shape'),): "NCollection_HSequence__TopoDS_Shape",
    (('builtins', 'float'),): "NCollection_HSequence__double",
    (('nanoocp.gp', 'gp_Pnt'),): "NCollection_HSequence__gp_Pnt",
    (('builtins', 'int'),): "NCollection_HSequence__int",
    (('nanoocp.NCollection', 'NCollection_HSequence__gp_Pnt'),): "NCollection_HSequence__opencascade_handle__NCollection_HSequence__gp_Pnt",
})
NCollection_IndexedDataMap = _Template("NCollection_IndexedDataMap", "nanoocp.NCollection", {
    (('nanoocp.BRepMesh', 'BRepMesh_Edge'), ('nanoocp.BRepMesh', 'BRepMesh_PairOfIndex')): "NCollection_IndexedDataMap__BRepMesh_Edge__BRepMesh_PairOfIndex",
    (('nanoocp.BOPDS', 'BOPDS_PaveBlock'), ('nanoocp.NCollection', 'NCollection_List__Handle_BOPDS_PaveBlock')): "NCollection_IndexedDataMap__Handle_BOPDS_PaveBlock__NCollection_List__Handle_BOPDS_PaveBlock",
    (('nanoocp.BOPDS', 'BOPDS_PaveBlock'), ('nanoocp.NCollection', 'NCollection_List__int')): "NCollection_IndexedDataMap__Handle_BOPDS_PaveBlock__NCollection_List__int",
    (('nanoocp.Standard', 'Standard_Transient'), ('nanoocp.Standard', 'Standard_Transient')): "NCollection_IndexedDataMap__Handle_Standard_Transient__Handle_Standard_Transient",
    (('nanoocp.TCollection', 'TCollection_AsciiString'), ('nanoocp.Aspect', 'Aspect_XRAction')): "NCollection_IndexedDataMap__TCollection_AsciiString__Handle_Aspect_XRAction",
    (('nanoocp.TCollection', 'TCollection_AsciiString'), ('nanoocp.DE', 'DE_ConfigurationNode')): "NCollection_IndexedDataMap__TCollection_AsciiString__Handle_DE_ConfigurationNode",
    (('nanoocp.TCollection', 'TCollection_AsciiString'), ('nanoocp.Standard', 'Standard_Transient')): "NCollection_IndexedDataMap__TCollection_AsciiString__Handle_Standard_Transient",
    (('nanoocp.TCollection', 'TCollection_AsciiString'), ('nanoocp.Standard', 'Standard_DumpValue')): "NCollection_IndexedDataMap__TCollection_AsciiString__Standard_DumpValue",
    (('nanoocp.TCollection', 'TCollection_AsciiString'), ('nanoocp.TCollection', 'TCollection_AsciiString')): "NCollection_IndexedDataMap__TCollection_AsciiString__TCollection_AsciiString",
    (('nanoocp.TCollection', 'TCollection_AsciiString'), ('builtins', 'int')): "NCollection_IndexedDataMap__TCollection_AsciiString__int",
    (('nanoocp.TDF', 'TDF_Label'), ('nanoocp.TopoDS', 'TopoDS_Shape')): "NCollection_IndexedDataMap__TDF_Label__TopoDS_Shape",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.Bnd', 'Bnd_Box')): "NCollection_IndexedDataMap__TopoDS_Shape__Bnd_Box",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.NCollection', 'NCollection_List__TopoDS_Shape'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_IndexedDataMap__TopoDS_Shape__NCollection_List__TopoDS_Shape__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.TopOpeBRepBuild', 'TopOpeBRepBuild_VertexInfo'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_IndexedDataMap__TopoDS_Shape__TopOpeBRepBuild_VertexInfo__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.TopOpeBRepDS', 'TopOpeBRepDS_ShapeData'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_IndexedDataMap__TopoDS_Shape__TopOpeBRepDS_ShapeData__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.TopOpeBRepDS', 'TopOpeBRepDS_ShapeWithState'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_IndexedDataMap__TopoDS_Shape__TopOpeBRepDS_ShapeWithState__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_IndexedDataMap__TopoDS_Shape__TopoDS_Shape__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.XCAFPrs', 'XCAFPrs_Style'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_IndexedDataMap__TopoDS_Shape__XCAFPrs_Style__TopTools_ShapeMapHasher",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('builtins', 'float'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_IndexedDataMap__TopoDS_Shape__double__TopTools_ShapeMapHasher",
})
NCollection_IndexedMap = _Template("NCollection_IndexedMap", "nanoocp.NCollection", {
    (('nanoocp.BOPDS', 'BOPDS_PaveBlock'),): "NCollection_IndexedMap__Handle_BOPDS_PaveBlock",
    (('nanoocp.Select3D', 'Select3D_SensitiveEntity'),): "NCollection_IndexedMap__Handle_Select3D_SensitiveEntity",
    (('nanoocp.SelectMgr', 'SelectMgr_EntityOwner'),): "NCollection_IndexedMap__Handle_SelectMgr_EntityOwner",
    (('nanoocp.SelectMgr', 'SelectMgr_SensitiveEntity'),): "NCollection_IndexedMap__Handle_SelectMgr_SensitiveEntity",
    (('nanoocp.Standard', 'Standard_Transient'),): "NCollection_IndexedMap__Handle_Standard_Transient",
    (('nanoocp.TDF', 'TDF_Attribute'),): "NCollection_IndexedMap__Handle_TDF_Attribute",
    (('nanoocp.Message', 'Message_MetricType'),): "NCollection_IndexedMap__Message_MetricType",
    (('nanoocp.TCollection', 'TCollection_AsciiString'),): "NCollection_IndexedMap__TCollection_AsciiString",
    (('nanoocp.TDF', 'TDF_Label'),): "NCollection_IndexedMap__TDF_Label",
    (('nanoocp.TopoDS', 'TopoDS_Shape'),): "NCollection_IndexedMap__TopoDS_Shape",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_IndexedMap__TopoDS_Shape__TopTools_ShapeMapHasher",
    (('builtins', 'float'),): "NCollection_IndexedMap__double",
})
NCollection_LinearVector = _Template("NCollection_LinearVector", "nanoocp.NCollection", {
    (('nanoocp.BRepGraph', 'BRepGraph.EditorView.BoundaryIssue'),): "NCollection_LinearVector__BRepGraph_EditorView_BoundaryIssue",
    (('nanoocp.BRepGraph', 'BRepGraph_ItemUID'),): "NCollection_LinearVector__BRepGraph_ItemUID",
    (('nanoocp.BRepGraph', 'BRepGraph_NodeId'),): "NCollection_LinearVector__BRepGraph_NodeId",
    (('nanoocp.BRepGraph', 'BRepGraph_CoEdgeId'),): "NCollection_LinearVector__BRepGraph_NodeId_Typed__BRepGraph_NodeId_Kind_CoEdge",
    (('nanoocp.BRepGraph', 'BRepGraph_EdgeId'),): "NCollection_LinearVector__BRepGraph_NodeId_Typed__BRepGraph_NodeId_Kind_Edge",
    (('nanoocp.BRepGraph', 'BRepGraph_FaceId'),): "NCollection_LinearVector__BRepGraph_NodeId_Typed__BRepGraph_NodeId_Kind_Face",
    (('nanoocp.BRepGraph', 'BRepGraph_ProductId'),): "NCollection_LinearVector__BRepGraph_NodeId_Typed__BRepGraph_NodeId_Kind_Product",
    (('nanoocp.BRepGraph', 'BRepGraph_RefId'),): "NCollection_LinearVector__BRepGraph_RefId",
    (('nanoocp.BRepGraph', 'BRepGraph_ChildRefId'),): "NCollection_LinearVector__BRepGraph_RefId_Typed__BRepGraph_RefId_Kind_Child",
    (('nanoocp.BRepGraph', 'BRepGraph_FaceRefId'),): "NCollection_LinearVector__BRepGraph_RefId_Typed__BRepGraph_RefId_Kind_Face",
    (('nanoocp.BRepGraph', 'BRepGraph_OccurrenceRefId'),): "NCollection_LinearVector__BRepGraph_RefId_Typed__BRepGraph_RefId_Kind_Occurrence",
    (('nanoocp.BRepGraph', 'BRepGraph_ShellRefId'),): "NCollection_LinearVector__BRepGraph_RefId_Typed__BRepGraph_RefId_Kind_Shell",
    (('nanoocp.BRepGraph', 'BRepGraph_SolidRefId'),): "NCollection_LinearVector__BRepGraph_RefId_Typed__BRepGraph_RefId_Kind_Solid",
    (('nanoocp.BRepGraph', 'BRepGraph_WireRefId'),): "NCollection_LinearVector__BRepGraph_RefId_Typed__BRepGraph_RefId_Kind_Wire",
    (('nanoocp.BRepGraph', 'BRepGraph_UID'),): "NCollection_LinearVector__BRepGraph_UID",
    (('nanoocp.BRepGraph', 'BRepGraph_Validate.Issue'),): "NCollection_LinearVector__BRepGraph_Validate_Issue",
    (('nanoocp.Poly', 'Poly_PolygonOnTriangulation'),): "NCollection_LinearVector__Handle_Poly_PolygonOnTriangulation",
    (('nanoocp.IntWalk', 'IntWalk_WalkingData'),): "NCollection_LinearVector__IntWalk_WalkingData",
    (('nanoocp.BVH', 'BVH_Vec2d'),): "NCollection_LinearVector__NCollection_Vec2__double",
    (('nanoocp.BVH', 'BVH_Vec2f'),): "NCollection_LinearVector__NCollection_Vec2__float",
    (('nanoocp.BVH', 'BVH_Vec2i'),): "NCollection_LinearVector__NCollection_Vec2__int",
    (('nanoocp.BVH', 'BVH_Vec3d'),): "NCollection_LinearVector__NCollection_Vec3__double",
    (('nanoocp.Quantity', 'NCollection_Vec3__float'),): "NCollection_LinearVector__NCollection_Vec3__float",
    (('nanoocp.BVH', 'BVH_Vec3i'),): "NCollection_LinearVector__NCollection_Vec3__int",
    (('nanoocp.BVH', 'BVH_Vec4d'),): "NCollection_LinearVector__NCollection_Vec4__double",
    (('nanoocp.Quantity', 'NCollection_Vec4__float'),): "NCollection_LinearVector__NCollection_Vec4__float",
    (('nanoocp.BVH', 'BVH_Vec4i'),): "NCollection_LinearVector__NCollection_Vec4__int",
    (('builtins', 'float'),): "NCollection_LinearVector__double",
    (('builtins', 'int'),): "NCollection_LinearVector__int",
})
NCollection_List = _Template("NCollection_List", "nanoocp.NCollection", {
    (('nanoocp.BOPAlgo', 'BOPAlgo_CheckResult'),): "NCollection_List__BOPAlgo_CheckResult",
    (('nanoocp.BOPDS', 'BOPDS_Pave'),): "NCollection_List__BOPDS_Pave",
    (('nanoocp.BOPTools', 'BOPTools_ConnexityBlock'),): "NCollection_List__BOPTools_ConnexityBlock",
    (('nanoocp.BOPTools', 'BOPTools_CoupleOfShape'),): "NCollection_List__BOPTools_CoupleOfShape",
    (('nanoocp.BRepCheck', 'BRepCheck_Status'),): "NCollection_List__BRepCheck_Status",
    (('nanoocp.BRepOffset', 'BRepOffset_Interval'),): "NCollection_List__BRepOffset_Interval",
    (('nanoocp.Bnd', 'Bnd_Range'),): "NCollection_List__Bnd_Range",
    (('nanoocp.ChFiDS', 'ChFiDS_Regul'),): "NCollection_List__ChFiDS_Regul",
    (('nanoocp.DE', 'DE_Provider.ReadStreamNode'),): "NCollection_List__DE_Provider_ReadStreamNode",
    (('nanoocp.DE', 'DE_Provider.WriteStreamNode'),): "NCollection_List__DE_Provider_WriteStreamNode",
    (('nanoocp.HLRAlgo', 'HLRAlgo_BiPoint'),): "NCollection_List__HLRAlgo_BiPoint",
    (('nanoocp.HLRAlgo', 'HLRAlgo_Interference'),): "NCollection_List__HLRAlgo_Interference",
    (('nanoocp.AIS', 'AIS_InteractiveObject'),): "NCollection_List__Handle_AIS_InteractiveObject",
    (('nanoocp.BOPDS', 'BOPDS_PaveBlock'),): "NCollection_List__Handle_BOPDS_PaveBlock",
    (('nanoocp.BRepMesh', 'BRepMesh_DiscretAlgoFactory'),): "NCollection_List__Handle_BRepMesh_DiscretAlgoFactory",
    (('nanoocp.BRep', 'BRep_CurveRepresentation'),): "NCollection_List__Handle_BRep_CurveRepresentation",
    (('nanoocp.BRep', 'BRep_PointRepresentation'),): "NCollection_List__Handle_BRep_PointRepresentation",
    (('nanoocp.ChFiDS', 'ChFiDS_ElSpine'),): "NCollection_List__Handle_ChFiDS_ElSpine",
    (('nanoocp.ChFiDS', 'ChFiDS_Stripe'),): "NCollection_List__Handle_ChFiDS_Stripe",
    (('nanoocp.Font', 'Font_SystemFont'),): "NCollection_List__Handle_Font_SystemFont",
    (('nanoocp.Graphic3d', 'Graphic3d_CLight'),): "NCollection_List__Handle_Graphic3d_CLight",
    (('nanoocp.Graphic3d', 'Graphic3d_GraphicDriverFactory'),): "NCollection_List__Handle_Graphic3d_GraphicDriverFactory",
    (('nanoocp.Graphic3d', 'Graphic3d_Layer'),): "NCollection_List__Handle_Graphic3d_Layer",
    (('nanoocp.IMeshData', 'IMeshData_PCurve'),): "NCollection_List__Handle_IMeshData_PCurve",
    (('nanoocp.Law', 'Law_Function'),): "NCollection_List__Handle_Law_Function",
    (('nanoocp.Message', 'Message_Alert'),): "NCollection_List__Handle_Message_Alert",
    (('nanoocp.Poly', 'Poly_Triangulation'),): "NCollection_List__Handle_Poly_Triangulation",
    (('nanoocp.PrsMgr', 'PrsMgr_PresentableObject'),): "NCollection_List__Handle_PrsMgr_PresentableObject",
    (('nanoocp.SelectMgr', 'SelectMgr_EntityOwner'),): "NCollection_List__Handle_SelectMgr_EntityOwner",
    (('nanoocp.SelectMgr', 'SelectMgr_Filter'),): "NCollection_List__Handle_SelectMgr_Filter",
    (('nanoocp.Standard', 'Standard_Transient'),): "NCollection_List__Handle_Standard_Transient",
    (('nanoocp.TDF', 'TDF_Attribute'),): "NCollection_List__Handle_TDF_Attribute",
    (('nanoocp.TDF', 'TDF_AttributeDelta'),): "NCollection_List__Handle_TDF_AttributeDelta",
    (('nanoocp.TDF', 'TDF_Delta'),): "NCollection_List__Handle_TDF_Delta",
    (('nanoocp.TNaming', 'TNaming_NamedShape'),): "NCollection_List__Handle_TNaming_NamedShape",
    (('nanoocp.TopOpeBRepBuild', 'TopOpeBRepBuild_Loop'),): "NCollection_List__Handle_TopOpeBRepBuild_Loop",
    (('nanoocp.TopOpeBRepBuild', 'TopOpeBRepBuild_Pave'),): "NCollection_List__Handle_TopOpeBRepBuild_Pave",
    (('nanoocp.TopOpeBRepDS', 'TopOpeBRepDS_Interference'),): "NCollection_List__Handle_TopOpeBRepDS_Interference",
    (('nanoocp.V3d', 'V3d_View'),): "NCollection_List__Handle_V3d_View",
    (('nanoocp.IntPolyh', 'IntPolyh_Couple'),): "NCollection_List__IntPolyh_Couple",
    (('nanoocp.IntSurf', 'IntSurf_PntOn2S'),): "NCollection_List__IntSurf_PntOn2S",
    (('nanoocp.IntTools', 'IntTools_CurveRangeSample'),): "NCollection_List__IntTools_CurveRangeSample",
    (('nanoocp.IntTools', 'IntTools_SurfaceRangeSample'),): "NCollection_List__IntTools_SurfaceRangeSample",
    (('nanoocp.Message', 'Message_Msg'),): "NCollection_List__Message_Msg",
    (('nanoocp.NCollection', 'NCollection_List__TopoDS_Shape'),): "NCollection_List__NCollection_List__TopoDS_Shape",
    (('nanoocp.NCollection', 'NCollection_Sequence__int'),): "NCollection_List__NCollection_Sequence__int",
    (('nanoocp.Poly', 'Poly_CoherentTriangulation.TwoIntegers'),): "NCollection_List__Poly_CoherentTriangulation_TwoIntegers",
    (('nanoocp.Poly', 'Poly_MakeLoops.Link'),): "NCollection_List__Poly_MakeLoops_Link",
    (('nanoocp.Poly', 'Poly_Triangle'),): "NCollection_List__Poly_Triangle",
    (('nanoocp.Standard', 'Standard_GUID'),): "NCollection_List__Standard_GUID",
    (('nanoocp.TCollection', 'TCollection_AsciiString'),): "NCollection_List__TCollection_AsciiString",
    (('nanoocp.TCollection', 'TCollection_ExtendedString'),): "NCollection_List__TCollection_ExtendedString",
    (('nanoocp.TDF', 'TDF_Label'),): "NCollection_List__TDF_Label",
    (('nanoocp.TopoDS', 'TopoDS_Shape'),): "NCollection_List__TopoDS_Shape",
    (('builtins', 'float'),): "NCollection_List__double",
    (('nanoocp.gp', 'gp_Pnt'),): "NCollection_List__gp_Pnt",
    (('nanoocp.gp', 'gp_Pnt2d'),): "NCollection_List__gp_Pnt2d",
    (('builtins', 'int'),): "NCollection_List__int",
    (('nanoocp.NCollection', 'NCollection_HSequence__gp_Pnt'),): "NCollection_List__opencascade_handle__NCollection_HSequence__gp_Pnt",
})
NCollection_Map = _Template("NCollection_Map", "nanoocp.NCollection", {
    (('nanoocp.BOPDS', 'BOPDS_Pair'),): "NCollection_Map__BOPDS_Pair",
    (('nanoocp.BRepMesh', 'BRepMesh_OrientedEdge'),): "NCollection_Map__BRepMesh_OrientedEdge",
    (('nanoocp.BOPDS', 'BOPDS_PaveBlock'),): "NCollection_Map__Handle_BOPDS_PaveBlock",
    (('nanoocp.Graphic3d', 'Graphic3d_Structure'),): "NCollection_Map__Handle_Graphic3d_Structure",
    (('nanoocp.TDF', 'TDF_Attribute'),): "NCollection_Map__Handle_TDF_Attribute",
    (('nanoocp.TNaming', 'TNaming_NamedShape'),): "NCollection_Map__Handle_TNaming_NamedShape",
    (('nanoocp.TDF', 'TDF_Label'),): "NCollection_Map__TDF_Label",
    (('nanoocp.TopoDS', 'TopoDS_Shape'), ('nanoocp.TopTools', 'TopTools_ShapeMapHasher')): "NCollection_Map__TopoDS_Shape__TopTools_ShapeMapHasher",
    (('builtins', 'float'),): "NCollection_Map__double",
    (('builtins', 'int'),): "NCollection_Map__int",
})
NCollection_Sequence = _Template("NCollection_Sequence", "nanoocp.NCollection", {
    (('nanoocp.AppParCurves', 'AppParCurves_MultiCurve'),): "NCollection_Sequence__AppParCurves_MultiCurve",
    (('nanoocp.Aspect', 'Aspect_ScrollDelta'),): "NCollection_Sequence__Aspect_ScrollDelta",
    (('nanoocp.BRepExtrema', 'BRepExtrema_SolutionElem'),): "NCollection_Sequence__BRepExtrema_SolutionElem",
    (('nanoocp.Bnd', 'Bnd_B2d'),): "NCollection_Sequence__Bnd_B2__double",
    (('nanoocp.Extrema', 'Extrema_POnCurv'),): "NCollection_Sequence__Extrema_POnCurv",
    (('nanoocp.Extrema', 'Extrema_POnCurv2d'),): "NCollection_Sequence__Extrema_POnCurv2d",
    (('nanoocp.Extrema', 'Extrema_POnSurf'),): "NCollection_Sequence__Extrema_POnSurf",
    (('nanoocp.GeomPlate', 'GeomPlate_Aij'),): "NCollection_Sequence__GeomPlate_Aij",
    (('nanoocp.Graphic3d', 'Graphic3d_ShaderObject.ShaderVariable'),): "NCollection_Sequence__Graphic3d_ShaderObject_ShaderVariable",
    (('nanoocp.HLRBRep', 'HLRBRep_ShapeBounds'),): "NCollection_Sequence__HLRBRep_ShapeBounds",
    (('nanoocp.AIS', 'AIS_Animation'),): "NCollection_Sequence__Handle_AIS_Animation",
    (('nanoocp.AIS', 'AIS_InteractiveObject'),): "NCollection_Sequence__Handle_AIS_InteractiveObject",
    (('nanoocp.AdvApp2Var', 'AdvApp2Var_Iso'),): "NCollection_Sequence__Handle_AdvApp2Var_Iso",
    (('nanoocp.AdvApp2Var', 'AdvApp2Var_Node'),): "NCollection_Sequence__Handle_AdvApp2Var_Node",
    (('nanoocp.AdvApp2Var', 'AdvApp2Var_Patch'),): "NCollection_Sequence__Handle_AdvApp2Var_Patch",
    (('nanoocp.ChFiDS', 'ChFiDS_SurfData'),): "NCollection_Sequence__Handle_ChFiDS_SurfData",
    (('nanoocp.Font', 'Font_SystemFont'),): "NCollection_Sequence__Handle_Font_SystemFont",
    (('nanoocp.Geom2d', 'Geom2d_BoundedCurve'),): "NCollection_Sequence__Handle_Geom2d_BoundedCurve",
    (('nanoocp.Geom2d', 'Geom2d_Curve'),): "NCollection_Sequence__Handle_Geom2d_Curve",
    (('nanoocp.Geom2d', 'Geom2d_Geometry'),): "NCollection_Sequence__Handle_Geom2d_Geometry",
    (('nanoocp.Geom', 'Geom_BoundedCurve'),): "NCollection_Sequence__Handle_Geom_BoundedCurve",
    (('nanoocp.Geom', 'Geom_Curve'),): "NCollection_Sequence__Handle_Geom_Curve",
    (('nanoocp.Graphic3d', 'Graphic3d_CView'),): "NCollection_Sequence__Handle_Graphic3d_CView",
    (('nanoocp.Graphic3d', 'Graphic3d_ClipPlane'),): "NCollection_Sequence__Handle_Graphic3d_ClipPlane",
    (('nanoocp.Graphic3d', 'Graphic3d_Group'),): "NCollection_Sequence__Handle_Graphic3d_Group",
    (('nanoocp.Graphic3d', 'Graphic3d_ShaderAttribute'),): "NCollection_Sequence__Handle_Graphic3d_ShaderAttribute",
    (('nanoocp.Graphic3d', 'Graphic3d_ShaderObject'),): "NCollection_Sequence__Handle_Graphic3d_ShaderObject",
    (('nanoocp.Graphic3d', 'Graphic3d_ShaderVariable'),): "NCollection_Sequence__Handle_Graphic3d_ShaderVariable",
    (('nanoocp.IFSelect', 'IFSelect_Selection'),): "NCollection_Sequence__Handle_IFSelect_Selection",
    (('nanoocp.IntPatch', 'IntPatch_Line'),): "NCollection_Sequence__Handle_IntPatch_Line",
    (('nanoocp.MAT2d', 'MAT2d_Connexion'),): "NCollection_Sequence__Handle_MAT2d_Connexion",
    (('nanoocp.MAT', 'MAT_Arc'),): "NCollection_Sequence__Handle_MAT_Arc",
    (('nanoocp.MAT', 'MAT_BasicElt'),): "NCollection_Sequence__Handle_MAT_BasicElt",
    (('nanoocp.Message', 'Message_Printer'),): "NCollection_Sequence__Handle_Message_Printer",
    (('nanoocp.PCDM', 'PCDM_Document'),): "NCollection_Sequence__Handle_PCDM_Document",
    (('nanoocp.Poly', 'Poly_Triangulation'),): "NCollection_Sequence__Handle_Poly_Triangulation",
    (('nanoocp.PrsMgr', 'PrsMgr_Presentation'),): "NCollection_Sequence__Handle_PrsMgr_Presentation",
    (('nanoocp.STEPSelections', 'STEPSelections_AssemblyLink'),): "NCollection_Sequence__Handle_STEPSelections_AssemblyLink",
    (('nanoocp.Select3D', 'Select3D_SensitiveEntity'),): "NCollection_Sequence__Handle_Select3D_SensitiveEntity",
    (('nanoocp.SelectMgr', 'SelectMgr_EntityOwner'),): "NCollection_Sequence__Handle_SelectMgr_EntityOwner",
    (('nanoocp.SelectMgr', 'SelectMgr_Selection'),): "NCollection_Sequence__Handle_SelectMgr_Selection",
    (('nanoocp.ShapeAnalysis', 'ShapeAnalysis_FreeBoundData'),): "NCollection_Sequence__Handle_ShapeAnalysis_FreeBoundData",
    (('nanoocp.Standard', 'Standard_Transient'),): "NCollection_Sequence__Handle_Standard_Transient",
    (('nanoocp.StepElement', 'StepElement_CurveElementPurposeMember'),): "NCollection_Sequence__Handle_StepElement_CurveElementPurposeMember",
    (('nanoocp.StepElement', 'StepElement_CurveElementSectionDefinition'),): "NCollection_Sequence__Handle_StepElement_CurveElementSectionDefinition",
    (('nanoocp.StepElement', 'StepElement_ElementMaterial'),): "NCollection_Sequence__Handle_StepElement_ElementMaterial",
    (('nanoocp.StepElement', 'StepElement_SurfaceElementPurposeMember'),): "NCollection_Sequence__Handle_StepElement_SurfaceElementPurposeMember",
    (('nanoocp.StepFEA', 'StepFEA_ElementGeometricRelationship'),): "NCollection_Sequence__Handle_StepFEA_ElementGeometricRelationship",
    (('nanoocp.StepFEA', 'StepFEA_ElementRepresentation'),): "NCollection_Sequence__Handle_StepFEA_ElementRepresentation",
    (('nanoocp.Storage', 'Storage_Root'),): "NCollection_Sequence__Handle_Storage_Root",
    (('nanoocp.TCollection', 'TCollection_HAsciiString'),): "NCollection_Sequence__Handle_TCollection_HAsciiString",
    (('nanoocp.TCollection', 'TCollection_HExtendedString'),): "NCollection_Sequence__Handle_TCollection_HExtendedString",
    (('nanoocp.TDF', 'TDF_Attribute'),): "NCollection_Sequence__Handle_TDF_Attribute",
    (('nanoocp.TDocStd', 'TDocStd_ApplicationDelta'),): "NCollection_Sequence__Handle_TDocStd_ApplicationDelta",
    (('nanoocp.TDocStd', 'TDocStd_Document'),): "NCollection_Sequence__Handle_TDocStd_Document",
    (('nanoocp.TransferBRep', 'TransferBRep_TransferResultInfo'),): "NCollection_Sequence__Handle_TransferBRep_TransferResultInfo",
    (('nanoocp.Transfer', 'Transfer_Finder'),): "NCollection_Sequence__Handle_Transfer_Finder",
    (('nanoocp.Units', 'Units_Quantity'),): "NCollection_Sequence__Handle_Units_Quantity",
    (('nanoocp.Units', 'Units_Token'),): "NCollection_Sequence__Handle_Units_Token",
    (('nanoocp.Units', 'Units_Unit'),): "NCollection_Sequence__Handle_Units_Unit",
    (('nanoocp.V3d', 'V3d_View'),): "NCollection_Sequence__Handle_V3d_View",
    (('nanoocp.XCAFDimTolObjects', 'XCAFDimTolObjects_DatumObject'),): "NCollection_Sequence__Handle_XCAFDimTolObjects_DatumObject",
    (('nanoocp.XCAFDimTolObjects', 'XCAFDimTolObjects_DimensionObject'),): "NCollection_Sequence__Handle_XCAFDimTolObjects_DimensionObject",
    (('nanoocp.XCAFDimTolObjects', 'XCAFDimTolObjects_GeomToleranceObject'),): "NCollection_Sequence__Handle_XCAFDimTolObjects_GeomToleranceObject",
    (('nanoocp.IntPatch', 'IntPatch_Point'),): "NCollection_Sequence__IntPatch_Point",
    (('nanoocp.IntRes2d', 'IntRes2d_IntersectionPoint'),): "NCollection_Sequence__IntRes2d_IntersectionPoint",
    (('nanoocp.IntSurf', 'IntSurf_InteriorPoint'),): "NCollection_Sequence__IntSurf_InteriorPoint",
    (('nanoocp.IntSurf', 'IntSurf_PathPoint'),): "NCollection_Sequence__IntSurf_PathPoint",
    (('nanoocp.IntTools', 'IntTools_CommonPrt'),): "NCollection_Sequence__IntTools_CommonPrt",
    (('nanoocp.IntTools', 'IntTools_Curve'),): "NCollection_Sequence__IntTools_Curve",
    (('nanoocp.IntTools', 'IntTools_PntOn2Faces'),): "NCollection_Sequence__IntTools_PntOn2Faces",
    (('nanoocp.IntTools', 'IntTools_Range'),): "NCollection_Sequence__IntTools_Range",
    (('nanoocp.IntTools', 'IntTools_Root'),): "NCollection_Sequence__IntTools_Root",
    (('nanoocp.NCollection', 'NCollection_Sequence__Handle_AdvApp2Var_Iso'),): "NCollection_Sequence__NCollection_Sequence__Handle_AdvApp2Var_Iso",
    (('nanoocp.NCollection', 'NCollection_Sequence__Handle_Geom2d_Geometry'),): "NCollection_Sequence__NCollection_Sequence__Handle_Geom2d_Geometry",
    (('nanoocp.BVH', 'BVH_Vec2i'),): "NCollection_Sequence__NCollection_Vec2__int",
    (('nanoocp.PCDM', 'PCDM_Reference'),): "NCollection_Sequence__PCDM_Reference",
    (('nanoocp.Plate', 'Plate_PinpointConstraint'),): "NCollection_Sequence__Plate_PinpointConstraint",
    (('nanoocp.Quantity', 'Quantity_Color'),): "NCollection_Sequence__Quantity_Color",
    (('nanoocp.ShapeFix', 'ShapeFix_WireSegment'),): "NCollection_Sequence__ShapeFix_WireSegment",
    (('nanoocp.TCollection', 'TCollection_AsciiString'),): "NCollection_Sequence__TCollection_AsciiString",
    (('nanoocp.TCollection', 'TCollection_ExtendedString'),): "NCollection_Sequence__TCollection_ExtendedString",
    (('nanoocp.TDF', 'TDF_Label'),): "NCollection_Sequence__TDF_Label",
    (('nanoocp.TopOpeBRep', 'TopOpeBRep_Point2d'),): "NCollection_Sequence__TopOpeBRep_Point2d",
    (('nanoocp.TopoDS', 'TopoDS_Shape'),): "NCollection_Sequence__TopoDS_Shape",
    (('nanoocp.XCAFDimTolObjects', 'XCAFDimTolObjects_DatumSingleModif'),): "NCollection_Sequence__XCAFDimTolObjects_DatumSingleModif",
    (('nanoocp.XCAFDimTolObjects', 'XCAFDimTolObjects_DimensionModif'),): "NCollection_Sequence__XCAFDimTolObjects_DimensionModif",
    (('nanoocp.XCAFDimTolObjects', 'XCAFDimTolObjects_GeomToleranceModif'),): "NCollection_Sequence__XCAFDimTolObjects_GeomToleranceModif",
    (('builtins', 'bool'),): "NCollection_Sequence__bool",
    (('builtins', 'float'),): "NCollection_Sequence__double",
    (('nanoocp.gp', 'gp_Circ'),): "NCollection_Sequence__gp_Circ",
    (('nanoocp.gp', 'gp_Lin'),): "NCollection_Sequence__gp_Lin",
    (('nanoocp.gp', 'gp_Pnt'),): "NCollection_Sequence__gp_Pnt",
    (('nanoocp.gp', 'gp_Pnt2d'),): "NCollection_Sequence__gp_Pnt2d",
    (('nanoocp.gp', 'gp_Trsf'),): "NCollection_Sequence__gp_Trsf",
    (('nanoocp.gp', 'gp_Vec'),): "NCollection_Sequence__gp_Vec",
    (('nanoocp.gp', 'gp_XY'),): "NCollection_Sequence__gp_XY",
    (('nanoocp.gp', 'gp_XYZ'),): "NCollection_Sequence__gp_XYZ",
    (('builtins', 'int'),): "NCollection_Sequence__int",
    (('nanoocp.NCollection', 'NCollection_HSequence__gp_Pnt'),): "NCollection_Sequence__opencascade_handle__NCollection_HSequence__gp_Pnt",
})
NCollection_Shared = _Template("NCollection_Shared", "nanoocp.NCollection", {
    (('nanoocp.NCollection', 'NCollection_Array1__BRepMesh_Vertex'),): "NCollection_Shared__NCollection_Array1__BRepMesh_Vertex",
    (('nanoocp.NCollection', 'NCollection_Array1__int'),): "NCollection_Shared__NCollection_Array1__int",
    (('nanoocp.NCollection', 'NCollection_DataMap__TopoDS_Shape__int__TopTools_ShapeMapHasher'),): "NCollection_Shared__NCollection_DataMap__TopoDS_Shape__int__TopTools_ShapeMapHasher",
    (('nanoocp.NCollection', 'NCollection_DataMap__int__NCollection_Shared__NCollection_List__int'),): "NCollection_Shared__NCollection_DataMap__int__NCollection_Shared__NCollection_List__int",
    (('nanoocp.NCollection', 'NCollection_DataMap__int__bool'),): "NCollection_Shared__NCollection_DataMap__int__bool",
    (('nanoocp.NCollection', 'NCollection_DynamicArray__BRepMesh_Circle'),): "NCollection_Shared__NCollection_DynamicArray__BRepMesh_Circle",
    (('nanoocp.NCollection', 'NCollection_DynamicArray__BRepMesh_Triangle'),): "NCollection_Shared__NCollection_DynamicArray__BRepMesh_Triangle",
    (('nanoocp.NCollection', 'NCollection_DynamicArray__BRepMesh_Vertex'),): "NCollection_Shared__NCollection_DynamicArray__BRepMesh_Vertex",
    (('nanoocp.NCollection', 'NCollection_DynamicArray__Handle_IMeshData_Edge'),): "NCollection_Shared__NCollection_DynamicArray__Handle_IMeshData_Edge",
    (('nanoocp.NCollection', 'NCollection_DynamicArray__Handle_IMeshData_Face'),): "NCollection_Shared__NCollection_DynamicArray__Handle_IMeshData_Face",
    (('nanoocp.NCollection', 'NCollection_DynamicArray__Handle_IMeshData_PCurve'),): "NCollection_Shared__NCollection_DynamicArray__Handle_IMeshData_PCurve",
    (('nanoocp.NCollection', 'NCollection_DynamicArray__Handle_IMeshData_Wire'),): "NCollection_Shared__NCollection_DynamicArray__Handle_IMeshData_Wire",
    (('nanoocp.NCollection', 'NCollection_DynamicArray__TopAbs_Orientation'),): "NCollection_Shared__NCollection_DynamicArray__TopAbs_Orientation",
    (('nanoocp.NCollection', 'NCollection_DynamicArray__bool'),): "NCollection_Shared__NCollection_DynamicArray__bool",
    (('nanoocp.NCollection', 'NCollection_DynamicArray__int'),): "NCollection_Shared__NCollection_DynamicArray__int",
    (('nanoocp.IMeshData', 'NCollection_EBTree__int__Bnd_Box2d'),): "NCollection_Shared__NCollection_EBTree__int__Bnd_Box2d",
    (('nanoocp.NCollection', 'NCollection_IndexedDataMap__BRepMesh_Edge__BRepMesh_PairOfIndex'),): "NCollection_Shared__NCollection_IndexedDataMap__BRepMesh_Edge__BRepMesh_PairOfIndex",
    (('nanoocp.NCollection', 'NCollection_IndexedMap__Handle_SelectMgr_EntityOwner'),): "NCollection_Shared__NCollection_IndexedMap__Handle_SelectMgr_EntityOwner",
    (('nanoocp.NCollection', 'NCollection_IndexedMap__double'),): "NCollection_Shared__NCollection_IndexedMap__double",
    (('nanoocp.NCollection', 'NCollection_List__Handle_IMeshData_PCurve'),): "NCollection_Shared__NCollection_List__Handle_IMeshData_PCurve",
    (('nanoocp.NCollection', 'NCollection_List__gp_Pnt2d'),): "NCollection_Shared__NCollection_List__gp_Pnt2d",
    (('nanoocp.NCollection', 'NCollection_List__int'),): "NCollection_Shared__NCollection_List__int",
    (('nanoocp.NCollection', 'NCollection_Map__BRepMesh_OrientedEdge'),): "NCollection_Shared__NCollection_Map__BRepMesh_OrientedEdge",
    (('nanoocp.NCollection', 'NCollection_Map__double'),): "NCollection_Shared__NCollection_Map__double",
    (('nanoocp.NCollection', 'NCollection_Map__int'),): "NCollection_Shared__NCollection_Map__int",
    (('nanoocp.TColStd', 'TColStd_PackedMapOfInteger'),): "NCollection_Shared__NCollection_PackedMap__int",
    (('nanoocp.NCollection', 'NCollection_Sequence__Bnd_B2__double'),): "NCollection_Shared__NCollection_Sequence__Bnd_B2__double",
    (('nanoocp.NCollection', 'NCollection_Sequence__double'),): "NCollection_Shared__NCollection_Sequence__double",
    (('nanoocp.NCollection', 'NCollection_Sequence__int'),): "NCollection_Shared__NCollection_Sequence__int",
    (('nanoocp.Standard', 'Standard_Mutex'),): "NCollection_Shared__Standard_Mutex",
})

# deprecated NCollection typedef names -> (home module, bound name)
_ALIASES = {
}


def __getattr__(name):
    target = _ALIASES.get(name)
    if target is not None:
        return getattr(_importlib.import_module(target[0]), target[1])
    return getattr(_ext, name)   # NCollection instantiations bound into this package by other toolkits

# C++ namespaces of the package (Python modules nanoocp.<package>.<namespace>)
import nanoocp.NCollection.NCollection_Primes  # noqa: E402,F401
